import type { VocabItem } from './types';

// German A1 core vocabulary. Categories are deliberately chunky (8+ items
// each) so the exercise generator can always find 3 same-category distractors.

export const A1_VOCAB: VocabItem[] = [
  // ── basics & greetings ────────────────────────────────────────────────
  { id: 'v001', de: 'hallo', en: ['hello'], pos: 'phrase', level: 'A1', category: 'greetings' },
  { id: 'v002', de: 'tschüss', en: ['bye'], pos: 'phrase', level: 'A1', category: 'greetings' },
  { id: 'v003', de: 'guten Morgen', en: ['good morning'], pos: 'phrase', level: 'A1', category: 'greetings' },
  { id: 'v004', de: 'guten Abend', en: ['good evening'], pos: 'phrase', level: 'A1', category: 'greetings' },
  { id: 'v005', de: 'gute Nacht', en: ['good night'], pos: 'phrase', level: 'A1', category: 'greetings' },
  { id: 'v006', de: 'bitte', en: ['please', 'you’re welcome'], pos: 'phrase', level: 'A1', category: 'greetings' },
  { id: 'v007', de: 'danke', en: ['thank you', 'thanks'], pos: 'phrase', level: 'A1', category: 'greetings' },
  { id: 'v008', de: 'Entschuldigung', en: ['excuse me', 'sorry'], pos: 'phrase', level: 'A1', category: 'greetings' },
  { id: 'v009', de: 'ja', en: ['yes'], pos: 'phrase', level: 'A1', category: 'greetings' },
  { id: 'v010', de: 'nein', en: ['no'], pos: 'phrase', level: 'A1', category: 'greetings' },

  // ── people & family ───────────────────────────────────────────────────
  { id: 'v011', de: 'der Mann', en: ['the man'], pos: 'noun', level: 'A1', category: 'people' },
  { id: 'v012', de: 'die Frau', en: ['the woman'], pos: 'noun', level: 'A1', category: 'people' },
  { id: 'v013', de: 'das Kind', en: ['the child'], pos: 'noun', level: 'A1', category: 'people' },
  { id: 'v014', de: 'die Mutter', en: ['the mother'], pos: 'noun', level: 'A1', category: 'people' },
  { id: 'v015', de: 'der Vater', en: ['the father'], pos: 'noun', level: 'A1', category: 'people' },
  { id: 'v016', de: 'die Schwester', en: ['the sister'], pos: 'noun', level: 'A1', category: 'people' },
  { id: 'v017', de: 'der Bruder', en: ['the brother'], pos: 'noun', level: 'A1', category: 'people' },
  { id: 'v018', de: 'der Freund', en: ['the friend (male)', 'the boyfriend'], pos: 'noun', level: 'A1', category: 'people' },
  { id: 'v019', de: 'die Freundin', en: ['the friend (female)', 'the girlfriend'], pos: 'noun', level: 'A1', category: 'people' },
  { id: 'v020', de: 'die Familie', en: ['the family'], pos: 'noun', level: 'A1', category: 'people' },

  // ── food & drink ──────────────────────────────────────────────────────
  { id: 'v021', de: 'das Brot', en: ['the bread'], pos: 'noun', level: 'A1', category: 'food' },
  { id: 'v022', de: 'das Wasser', en: ['the water'], pos: 'noun', level: 'A1', category: 'food' },
  { id: 'v023', de: 'der Kaffee', en: ['the coffee'], pos: 'noun', level: 'A1', category: 'food' },
  { id: 'v024', de: 'der Tee', en: ['the tea'], pos: 'noun', level: 'A1', category: 'food' },
  { id: 'v025', de: 'die Milch', en: ['the milk'], pos: 'noun', level: 'A1', category: 'food' },
  { id: 'v026', de: 'der Apfel', en: ['the apple'], pos: 'noun', level: 'A1', category: 'food' },
  { id: 'v027', de: 'das Ei', en: ['the egg'], pos: 'noun', level: 'A1', category: 'food' },
  { id: 'v028', de: 'der Käse', en: ['the cheese'], pos: 'noun', level: 'A1', category: 'food' },
  { id: 'v029', de: 'das Bier', en: ['the beer'], pos: 'noun', level: 'A1', category: 'food' },
  { id: 'v030', de: 'der Wein', en: ['the wine'], pos: 'noun', level: 'A1', category: 'food' },
  { id: 'v031', de: 'das Frühstück', en: ['the breakfast'], pos: 'noun', level: 'A1', category: 'food' },
  { id: 'v032', de: 'das Restaurant', en: ['the restaurant'], pos: 'noun', level: 'A1', category: 'food' },

  // ── everyday objects ──────────────────────────────────────────────────
  { id: 'v033', de: 'das Haus', en: ['the house'], pos: 'noun', level: 'A1', category: 'objects' },
  { id: 'v034', de: 'die Tür', en: ['the door'], pos: 'noun', level: 'A1', category: 'objects' },
  { id: 'v035', de: 'das Fenster', en: ['the window'], pos: 'noun', level: 'A1', category: 'objects' },
  { id: 'v036', de: 'der Tisch', en: ['the table'], pos: 'noun', level: 'A1', category: 'objects' },
  { id: 'v037', de: 'der Stuhl', en: ['the chair'], pos: 'noun', level: 'A1', category: 'objects' },
  { id: 'v038', de: 'das Bett', en: ['the bed'], pos: 'noun', level: 'A1', category: 'objects' },
  { id: 'v039', de: 'das Buch', en: ['the book'], pos: 'noun', level: 'A1', category: 'objects' },
  { id: 'v040', de: 'das Handy', en: ['the mobile phone', 'the cell phone'], pos: 'noun', level: 'A1', category: 'objects' },
  { id: 'v041', de: 'der Schlüssel', en: ['the key'], pos: 'noun', level: 'A1', category: 'objects' },
  { id: 'v042', de: 'die Tasche', en: ['the bag'], pos: 'noun', level: 'A1', category: 'objects' },
  { id: 'v043', de: 'die Uhr', en: ['the clock', 'the watch'], pos: 'noun', level: 'A1', category: 'objects' },
  { id: 'v044', de: 'das Geld', en: ['the money'], pos: 'noun', level: 'A1', category: 'objects' },

  // ── places & travel ───────────────────────────────────────────────────
  { id: 'v045', de: 'die Stadt', en: ['the city', 'the town'], pos: 'noun', level: 'A1', category: 'places' },
  { id: 'v046', de: 'die Straße', en: ['the street'], pos: 'noun', level: 'A1', category: 'places' },
  { id: 'v047', de: 'der Bahnhof', en: ['the train station'], pos: 'noun', level: 'A1', category: 'places' },
  { id: 'v048', de: 'der Flughafen', en: ['the airport'], pos: 'noun', level: 'A1', category: 'places' },
  { id: 'v049', de: 'der Zug', en: ['the train'], pos: 'noun', level: 'A1', category: 'places' },
  { id: 'v050', de: 'das Auto', en: ['the car'], pos: 'noun', level: 'A1', category: 'places' },
  { id: 'v051', de: 'der Bus', en: ['the bus'], pos: 'noun', level: 'A1', category: 'places' },
  { id: 'v052', de: 'das Hotel', en: ['the hotel'], pos: 'noun', level: 'A1', category: 'places' },
  { id: 'v053', de: 'der Supermarkt', en: ['the supermarket'], pos: 'noun', level: 'A1', category: 'places' },
  { id: 'v054', de: 'die Arbeit', en: ['the work', 'the job'], pos: 'noun', level: 'A1', category: 'places' },
  { id: 'v055', de: 'die Schule', en: ['the school'], pos: 'noun', level: 'A1', category: 'places' },

  // ── time ──────────────────────────────────────────────────────────────
  { id: 'v056', de: 'heute', en: ['today'], pos: 'adv', level: 'A1', category: 'time' },
  { id: 'v057', de: 'morgen', en: ['tomorrow'], pos: 'adv', level: 'A1', category: 'time' },
  { id: 'v058', de: 'gestern', en: ['yesterday'], pos: 'adv', level: 'A1', category: 'time' },
  { id: 'v059', de: 'jetzt', en: ['now'], pos: 'adv', level: 'A1', category: 'time' },
  { id: 'v060', de: 'später', en: ['later'], pos: 'adv', level: 'A1', category: 'time' },
  { id: 'v061', de: 'der Tag', en: ['the day'], pos: 'noun', level: 'A1', category: 'time' },
  { id: 'v062', de: 'die Woche', en: ['the week'], pos: 'noun', level: 'A1', category: 'time' },
  { id: 'v063', de: 'das Jahr', en: ['the year'], pos: 'noun', level: 'A1', category: 'time' },
  { id: 'v064', de: 'die Nacht', en: ['the night'], pos: 'noun', level: 'A1', category: 'time' },
  { id: 'v065', de: 'immer', en: ['always'], pos: 'adv', level: 'A1', category: 'time' },
  { id: 'v066', de: 'nie', en: ['never'], pos: 'adv', level: 'A1', category: 'time' },
  { id: 'v067', de: 'oft', en: ['often'], pos: 'adv', level: 'A1', category: 'time' },

  // ── verbs ─────────────────────────────────────────────────────────────
  { id: 'v068', de: 'sein', en: ['to be'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v069', de: 'haben', en: ['to have'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v070', de: 'gehen', en: ['to go', 'to walk'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v071', de: 'kommen', en: ['to come'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v072', de: 'machen', en: ['to make', 'to do'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v073', de: 'essen', en: ['to eat'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v074', de: 'trinken', en: ['to drink'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v075', de: 'sprechen', en: ['to speak'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v076', de: 'lernen', en: ['to learn'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v077', de: 'arbeiten', en: ['to work'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v078', de: 'schlafen', en: ['to sleep'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v079', de: 'kaufen', en: ['to buy'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v080', de: 'sehen', en: ['to see'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v081', de: 'hören', en: ['to hear', 'to listen'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v082', de: 'lesen', en: ['to read'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v083', de: 'schreiben', en: ['to write'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v084', de: 'fahren', en: ['to drive', 'to ride'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v085', de: 'wohnen', en: ['to live (reside)'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v086', de: 'lieben', en: ['to love'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v087', de: 'brauchen', en: ['to need'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v088', de: 'wissen', en: ['to know (a fact)'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v089', de: 'verstehen', en: ['to understand'], pos: 'verb', level: 'A1', category: 'verbs' },
  { id: 'v090', de: 'helfen', en: ['to help'], pos: 'verb', level: 'A1', category: 'verbs' },

  // ── adjectives ────────────────────────────────────────────────────────
  { id: 'v091', de: 'gut', en: ['good'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v092', de: 'schlecht', en: ['bad'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v093', de: 'groß', en: ['big', 'tall'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v094', de: 'klein', en: ['small', 'little'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v095', de: 'neu', en: ['new'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v096', de: 'alt', en: ['old'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v097', de: 'schön', en: ['beautiful', 'nice'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v098', de: 'schnell', en: ['fast', 'quick'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v099', de: 'langsam', en: ['slow'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v100', de: 'teuer', en: ['expensive'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v101', de: 'billig', en: ['cheap'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v102', de: 'müde', en: ['tired'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v103', de: 'glücklich', en: ['happy'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v104', de: 'kalt', en: ['cold'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v105', de: 'warm', en: ['warm'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v106', de: 'schwer', en: ['heavy', 'difficult'], pos: 'adj', level: 'A1', category: 'adjectives' },
  { id: 'v107', de: 'leicht', en: ['light', 'easy'], pos: 'adj', level: 'A1', category: 'adjectives' },

  // ── numbers ───────────────────────────────────────────────────────────
  { id: 'v108', de: 'eins', en: ['one'], pos: 'number', level: 'A1', category: 'numbers' },
  { id: 'v109', de: 'zwei', en: ['two'], pos: 'number', level: 'A1', category: 'numbers' },
  { id: 'v110', de: 'drei', en: ['three'], pos: 'number', level: 'A1', category: 'numbers' },
  { id: 'v111', de: 'vier', en: ['four'], pos: 'number', level: 'A1', category: 'numbers' },
  { id: 'v112', de: 'fünf', en: ['five'], pos: 'number', level: 'A1', category: 'numbers' },
  { id: 'v113', de: 'sechs', en: ['six'], pos: 'number', level: 'A1', category: 'numbers' },
  { id: 'v114', de: 'sieben', en: ['seven'], pos: 'number', level: 'A1', category: 'numbers' },
  { id: 'v115', de: 'acht', en: ['eight'], pos: 'number', level: 'A1', category: 'numbers' },
  { id: 'v116', de: 'neun', en: ['nine'], pos: 'number', level: 'A1', category: 'numbers' },
  { id: 'v117', de: 'zehn', en: ['ten'], pos: 'number', level: 'A1', category: 'numbers' },
  { id: 'v118', de: 'zwanzig', en: ['twenty'], pos: 'number', level: 'A1', category: 'numbers' },
  { id: 'v119', de: 'hundert', en: ['one hundred'], pos: 'number', level: 'A1', category: 'numbers' },

  // ── question words & connectors ───────────────────────────────────────
  { id: 'v120', de: 'was', en: ['what'], pos: 'question', level: 'A1', category: 'questions' },
  { id: 'v121', de: 'wer', en: ['who'], pos: 'question', level: 'A1', category: 'questions' },
  { id: 'v122', de: 'wo', en: ['where'], pos: 'question', level: 'A1', category: 'questions' },
  { id: 'v123', de: 'wann', en: ['when'], pos: 'question', level: 'A1', category: 'questions' },
  { id: 'v124', de: 'warum', en: ['why'], pos: 'question', level: 'A1', category: 'questions' },
  { id: 'v125', de: 'wie', en: ['how'], pos: 'question', level: 'A1', category: 'questions' },
  { id: 'v126', de: 'wie viel', en: ['how much'], pos: 'question', level: 'A1', category: 'questions' },
  { id: 'v127', de: 'und', en: ['and'], pos: 'conj', level: 'A1', category: 'questions' },
  { id: 'v128', de: 'oder', en: ['or'], pos: 'conj', level: 'A1', category: 'questions' },
  { id: 'v129', de: 'aber', en: ['but'], pos: 'conj', level: 'A1', category: 'questions' },
  { id: 'v130', de: 'weil', en: ['because'], pos: 'conj', level: 'A1', category: 'questions' },

  // ── weather & nature ──────────────────────────────────────────────────
  { id: 'v131', de: 'die Sonne', en: ['the sun'], pos: 'noun', level: 'A1', category: 'nature' },
  { id: 'v132', de: 'der Regen', en: ['the rain'], pos: 'noun', level: 'A1', category: 'nature' },
  { id: 'v133', de: 'der Schnee', en: ['the snow'], pos: 'noun', level: 'A1', category: 'nature' },
  { id: 'v134', de: 'das Wetter', en: ['the weather'], pos: 'noun', level: 'A1', category: 'nature' },
  { id: 'v135', de: 'der Baum', en: ['the tree'], pos: 'noun', level: 'A1', category: 'nature' },
  { id: 'v136', de: 'der Hund', en: ['the dog'], pos: 'noun', level: 'A1', category: 'nature' },
  { id: 'v137', de: 'die Katze', en: ['the cat'], pos: 'noun', level: 'A1', category: 'nature' },
  { id: 'v138', de: 'die Blume', en: ['the flower'], pos: 'noun', level: 'A1', category: 'nature' },

  // ── body & health ─────────────────────────────────────────────────────
  { id: 'v139', de: 'der Kopf', en: ['the head'], pos: 'noun', level: 'A1', category: 'body' },
  { id: 'v140', de: 'die Hand', en: ['the hand'], pos: 'noun', level: 'A1', category: 'body' },
  { id: 'v141', de: 'das Auge', en: ['the eye'], pos: 'noun', level: 'A1', category: 'body' },
  { id: 'v142', de: 'der Fuß', en: ['the foot'], pos: 'noun', level: 'A1', category: 'body' },
  { id: 'v143', de: 'das Herz', en: ['the heart'], pos: 'noun', level: 'A1', category: 'body' },
  { id: 'v144', de: 'der Arzt', en: ['the doctor'], pos: 'noun', level: 'A1', category: 'body' },
  { id: 'v145', de: 'krank', en: ['sick', 'ill'], pos: 'adj', level: 'A1', category: 'body' },
  { id: 'v146', de: 'gesund', en: ['healthy'], pos: 'adj', level: 'A1', category: 'body' },

  // ── useful phrases ────────────────────────────────────────────────────
  { id: 'v147', de: 'Wie geht es dir?', en: ['How are you?'], pos: 'phrase', level: 'A1', category: 'phrases' },
  { id: 'v148', de: 'Ich verstehe nicht.', en: ['I don’t understand.'], pos: 'phrase', level: 'A1', category: 'phrases' },
  { id: 'v149', de: 'Ich heiße …', en: ['My name is …'], pos: 'phrase', level: 'A1', category: 'phrases' },
  { id: 'v150', de: 'Sprechen Sie Englisch?', en: ['Do you speak English?'], pos: 'phrase', level: 'A1', category: 'phrases' },
  { id: 'v151', de: 'Wo ist die Toilette?', en: ['Where is the toilet?'], pos: 'phrase', level: 'A1', category: 'phrases' },
  { id: 'v152', de: 'Das macht nichts.', en: ['That doesn’t matter.', 'No problem.'], pos: 'phrase', level: 'A1', category: 'phrases' },
  { id: 'v153', de: 'Bis später!', en: ['See you later!'], pos: 'phrase', level: 'A1', category: 'phrases' },
  { id: 'v154', de: 'Es tut mir leid.', en: ['I’m sorry.'], pos: 'phrase', level: 'A1', category: 'phrases' },
];
