import type { SentenceItem } from '@/content/german/types';

// English A1 sentences. `de` holds the English text (see content/german/types.ts).
// clozeIndex targets the load-bearing word — never an article — and the three
// clozeDistractors are same-class words that would be grammatical but wrong, so
// the exercise tests meaning rather than word shape.
//
// `en` mirrors `de` for this pack: it is the guaranteed fallback in the type
// contract, but an English-UI user is never offered English to learn, so it is
// not shown. `gloss` carries all five other UI locales — de / es / fr / it / pt.

export const A1_SENTENCES: SentenceItem[] = [
  { id: 'en1s001', de: 'Good morning, how are you?', en: 'Good morning, how are you?', gloss: { de: 'Guten Morgen, wie geht es dir?', es: 'Buenos días, ¿qué tal?', fr: 'Bonjour, comment ça va ?', it: 'Buongiorno, come va?', pt: 'Bom dia, tudo bem?' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['is', 'am', 'do'] },
  { id: 'en1s002', de: 'I want a coffee, please.', en: 'I want a coffee, please.', gloss: { de: 'Ich möchte einen Kaffee, bitte.', es: 'Quiero un café, por favor.', fr: 'Je voudrais un café, s’il vous plaît.', it: 'Vorrei un caffè, per favore.', pt: 'Quero um café, por favor.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['eat', 'speak', 'live'] },
  { id: 'en1s003', de: 'Where is the toilet?', en: 'Where is the toilet?', gloss: { de: 'Wo ist die Toilette?', es: '¿Dónde está el baño?', fr: 'Où sont les toilettes ?', it: 'Dov’è il bagno?', pt: 'Onde fica o banheiro?' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['When', 'How', 'Who'] },
  { id: 'en1s004', de: 'I live in a small house.', en: 'I live in a small house.', gloss: { de: 'Ich wohne in einem kleinen Haus.', es: 'Vivo en una casa pequeña.', fr: 'J’habite dans une petite maison.', it: 'Abito in una casa piccola.', pt: 'Moro numa casa pequena.' }, level: 'A1', clozeIndex: 4, clozeDistractors: ['old', 'new', 'cheap'] },
  { id: 'en1s005', de: 'How much is the beer?', en: 'How much is the beer?', gloss: { de: 'Wie viel kostet das Bier?', es: '¿Cuánto cuesta la cerveza?', fr: 'Combien coûte la bière ?', it: 'Quanto costa la birra?', pt: 'Quanto custa a cerveja?' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['many', 'old', 'good'] },
  { id: 'en1s006', de: 'The food is very good.', en: 'The food is very good.', gloss: { de: 'Das Essen ist sehr gut.', es: 'La comida está muy buena.', fr: 'La nourriture est très bonne.', it: 'Il cibo è molto buono.', pt: 'A comida está muito boa.' }, level: 'A1', clozeIndex: 4, clozeDistractors: ['expensive', 'cold', 'big'] },
  { id: 'en1s007', de: 'I do not speak English very well.', en: 'I do not speak English very well.', gloss: { de: 'Ich spreche nicht sehr gut Englisch.', es: 'No hablo inglés muy bien.', fr: 'Je ne parle pas très bien anglais.', it: 'Non parlo molto bene l’inglese.', pt: 'Não falo inglês muito bem.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['eat', 'buy', 'work'] },
  { id: 'en1s008', de: 'Today I go to work.', en: 'Today I go to work.', gloss: { de: 'Heute gehe ich zur Arbeit.', es: 'Hoy voy al trabajo.', fr: 'Aujourd’hui je vais au travail.', it: 'Oggi vado al lavoro.', pt: 'Hoje eu vou ao trabalho.' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Yesterday', 'Tomorrow', 'Never'] },
  { id: 'en1s009', de: 'She has a little sister.', en: 'She has a little sister.', gloss: { de: 'Sie hat eine kleine Schwester.', es: 'Ella tiene una hermana pequeña.', fr: 'Elle a une petite sœur.', it: 'Lei ha una sorella piccola.', pt: 'Ela tem uma irmã pequena.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['big', 'old', 'new'] },
  { id: 'en1s010', de: 'We like the beach.', en: 'We like the beach.', gloss: { de: 'Wir mögen den Strand.', es: 'Nos gusta la playa.', fr: 'Nous aimons la plage.', it: 'Ci piace la spiaggia.', pt: 'Nós gostamos da praia.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['city', 'school', 'shop'] },
  { id: 'en1s011', de: 'The restaurant is very expensive.', en: 'The restaurant is very expensive.', gloss: { de: 'Das Restaurant ist sehr teuer.', es: 'El restaurante es muy caro.', fr: 'Le restaurant est très cher.', it: 'Il ristorante è molto caro.', pt: 'O restaurante é muito caro.' }, level: 'A1', clozeIndex: 4, clozeDistractors: ['cheap', 'small', 'new'] },
  { id: 'en1s012', de: 'Tomorrow I go to the market.', en: 'Tomorrow I go to the market.', gloss: { de: 'Morgen gehe ich zum Markt.', es: 'Mañana voy al mercado.', fr: 'Demain je vais au marché.', it: 'Domani vado al mercato.', pt: 'Amanhã eu vou ao mercado.' }, level: 'A1', clozeIndex: 5, clozeDistractors: ['station', 'beach', 'school'] },
  { id: 'en1s013', de: 'My mother works in a shop.', en: 'My mother works in a shop.', gloss: { de: 'Meine Mutter arbeitet in einem Laden.', es: 'Mi madre trabaja en una tienda.', fr: 'Ma mère travaille dans un magasin.', it: 'Mia madre lavora in un negozio.', pt: 'Minha mãe trabalha numa loja.' }, level: 'A1', clozeIndex: 2, clozeDistractors: ['lives', 'eats', 'speaks'] },
  { id: 'en1s014', de: 'I do not understand the question.', en: 'I do not understand the question.', gloss: { de: 'Ich verstehe die Frage nicht.', es: 'No entiendo la pregunta.', fr: 'Je ne comprends pas la question.', it: 'Non capisco la domanda.', pt: 'Não entendo a pergunta.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['speak', 'want', 'have'] },
  { id: 'en1s015', de: 'The house is big and new.', en: 'The house is big and new.', gloss: { de: 'Das Haus ist groß und neu.', es: 'La casa es grande y nueva.', fr: 'La maison est grande et neuve.', it: 'La casa è grande e nuova.', pt: 'A casa é grande e nova.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['small', 'old', 'cheap'] },
  { id: 'en1s016', de: 'I have two brothers.', en: 'I have two brothers.', gloss: { de: 'Ich habe zwei Brüder.', es: 'Tengo dos hermanos.', fr: 'J’ai deux frères.', it: 'Ho due fratelli.', pt: 'Tenho dois irmãos.' }, level: 'A1', clozeIndex: 2, clozeDistractors: ['three', 'five', 'ten'] },
  { id: 'en1s017', de: 'The boy drinks milk.', en: 'The boy drinks milk.', gloss: { de: 'Der Junge trinkt Milch.', es: 'El niño bebe leche.', fr: 'Le garçon boit du lait.', it: 'Il bambino beve il latte.', pt: 'O menino bebe leite.' }, level: 'A1', clozeIndex: 2, clozeDistractors: ['eats', 'buys', 'wants'] },
  { id: 'en1s018', de: 'Why are you tired?', en: 'Why are you tired?', gloss: { de: 'Warum bist du müde?', es: '¿Por qué estás cansado?', fr: 'Pourquoi es-tu fatigué ?', it: 'Perché sei stanco?', pt: 'Por que você está cansado?' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Where', 'When', 'How'] },
  { id: 'en1s019', de: 'The bill, please.', en: 'The bill, please.', gloss: { de: 'Die Rechnung, bitte.', es: 'La cuenta, por favor.', fr: 'L’addition, s’il vous plaît.', it: 'Il conto, per favore.', pt: 'A conta, por favor.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['food', 'beer', 'water'] },
  { id: 'en1s020', de: 'I always eat bread in the morning.', en: 'I always eat bread in the morning.', gloss: { de: 'Ich esse morgens immer Brot.', es: 'Siempre como pan por la mañana.', fr: 'Je mange toujours du pain le matin.', it: 'Mangio sempre pane la mattina.', pt: 'Sempre como pão de manhã.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['never', 'today', 'now'] },
  { id: 'en1s021', de: 'Where do you live?', en: 'Where do you live?', gloss: { de: 'Wo wohnst du?', es: '¿Dónde vives?', fr: 'Où habites-tu ?', it: 'Dove abiti?', pt: 'Onde você mora?' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['work', 'eat', 'go'] },
  { id: 'en1s022', de: 'The water is cold.', en: 'The water is cold.', gloss: { de: 'Das Wasser ist kalt.', es: 'El agua está fría.', fr: 'L’eau est froide.', it: 'L’acqua è fredda.', pt: 'A água está fria.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['good', 'cheap', 'small'] },
];
