import type { SentenceItem } from '@/content/german/types';

// English A2 sentences. `de` holds the English text (see content/german/types.ts).
// Where A1 stayed in the present tense, A2 tells small stories: past simple with
// irregular forms (took, bought, forgot, paid, lost), comparatives, and clauses
// joined with because / so / and.
//
// clozeIndex targets the load-bearing word — never an article — and the three
// clozeDistractors are same-class words that would be grammatical but wrong, so
// the exercise tests meaning rather than word shape.
//
// `en` mirrors `de` for this pack: it is the guaranteed fallback in the type
// contract, but an English-UI user is never offered English to learn, so it is
// not shown. `gloss` carries all five other UI locales — de / es / fr / it / pt.

export const A2_SENTENCES: SentenceItem[] = [
  { id: 'en2s001', de: 'I took the bus to work yesterday.', en: 'I took the bus to work yesterday.', gloss: { de: 'Ich bin gestern mit dem Bus zur Arbeit gefahren.', es: 'Ayer tomé el autobús al trabajo.', fr: 'Hier, j’ai pris le bus pour aller au travail.', it: 'Ieri ho preso l’autobus per andare al lavoro.', pt: 'Ontem peguei o ônibus para o trabalho.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['made', 'sent', 'had'] },
  { id: 'en2s002', de: 'We bought the tickets last week.', en: 'We bought the tickets last week.', gloss: { de: 'Wir haben die Fahrkarten letzte Woche gekauft.', es: 'Compramos los billetes la semana pasada.', fr: 'Nous avons acheté les billets la semaine dernière.', it: 'Abbiamo comprato i biglietti la settimana scorsa.', pt: 'Compramos os bilhetes na semana passada.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['sold', 'lost', 'sent'] },
  { id: 'en2s003', de: 'The flight was cheaper than the train.', en: 'The flight was cheaper than the train.', gloss: { de: 'Der Flug war billiger als der Zug.', es: 'El vuelo fue más barato que el tren.', fr: 'Le vol était moins cher que le train.', it: 'Il volo era più economico del treno.', pt: 'O voo foi mais barato que o trem.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['faster', 'better', 'worse'] },
  { id: 'en2s004', de: 'She forgot her keys at the office.', en: 'She forgot her keys at the office.', gloss: { de: 'Sie hat ihre Schlüssel im Büro vergessen.', es: 'Olvidó las llaves en la oficina.', fr: 'Elle a oublié ses clés au bureau.', it: 'Ha dimenticato le chiavi in ufficio.', pt: 'Ela esqueceu as chaves no escritório.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['found', 'brought', 'washed'] },
  { id: 'en2s005', de: 'I woke up early and took a shower.', en: 'I woke up early and took a shower.', gloss: { de: 'Ich bin früh aufgewacht und habe geduscht.', es: 'Me desperté temprano y me duché.', fr: 'Je me suis réveillé tôt et j’ai pris une douche.', it: 'Mi sono svegliato presto e ho fatto la doccia.', pt: 'Acordei cedo e tomei banho.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['late', 'often', 'already'] },
  { id: 'en2s006', de: 'How much did the shoes cost?', en: 'How much did the shoes cost?', gloss: { de: 'Wie viel haben die Schuhe gekostet?', es: '¿Cuánto costaron los zapatos?', fr: 'Combien ont coûté les chaussures ?', it: 'Quanto sono costate le scarpe?', pt: 'Quanto custaram os sapatos?' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['trousers', 'tickets', 'suitcases'] },
  { id: 'en2s007', de: 'He paid with a credit card.', en: 'He paid with a credit card.', gloss: { de: 'Er hat mit Kreditkarte bezahlt.', es: 'Pagó con tarjeta de crédito.', fr: 'Il a payé par carte de crédit.', it: 'Ha pagato con la carta di credito.', pt: 'Ele pagou com cartão de crédito.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['ordered', 'sold', 'sent'] },
  { id: 'en2s008', de: 'The meeting started at nine in the morning.', en: 'The meeting started at nine in the morning.', gloss: { de: 'Die Besprechung hat um neun Uhr morgens angefangen.', es: 'La reunión empezó a las nueve de la mañana.', fr: 'La réunion a commencé à neuf heures du matin.', it: 'La riunione è iniziata alle nove di mattina.', pt: 'A reunião começou às nove da manhã.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['flight', 'exam', 'trip'] },
  { id: 'en2s009', de: 'I studied at the university for three years.', en: 'I studied at the university for three years.', gloss: { de: 'Ich habe drei Jahre an der Universität studiert.', es: 'Estudié en la universidad durante tres años.', fr: 'J’ai étudié à l’université pendant trois ans.', it: 'Ho studiato all’università per tre anni.', pt: 'Estudei na universidade durante três anos.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['worked', 'lived', 'waited'] },
  { id: 'en2s010', de: 'I had a headache, so I went to the pharmacy.', en: 'I had a headache, so I went to the pharmacy.', gloss: { de: 'Ich hatte Kopfschmerzen, also bin ich in die Apotheke gegangen.', es: 'Me dolía la cabeza, así que fui a la farmacia.', fr: 'J’avais mal à la tête, alors je suis allé à la pharmacie.', it: 'Avevo mal di testa, così sono andato in farmacia.', pt: 'Eu estava com dor de cabeça, então fui à farmácia.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['came', 'looked', 'stayed'] },
  { id: 'en2s011', de: 'The doctor gave me some medicine.', en: 'The doctor gave me some medicine.', gloss: { de: 'Der Arzt hat mir ein Medikament gegeben.', es: 'El médico me dio un medicamento.', fr: 'Le médecin m’a donné un médicament.', it: 'Il medico mi ha dato una medicina.', pt: 'O médico me deu um remédio.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['sent', 'brought', 'sold'] },
  { id: 'en2s012', de: 'We were very tired after the trip.', en: 'We were very tired after the trip.', gloss: { de: 'Wir waren nach der Reise sehr müde.', es: 'Estábamos muy cansados después del viaje.', fr: 'Nous étions très fatigués après le voyage.', it: 'Eravamo molto stanchi dopo il viaggio.', pt: 'Estávamos muito cansados depois da viagem.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['happy', 'busy', 'quiet'] },
  { id: 'en2s013', de: 'She was angry because I arrived late.', en: 'She was angry because I arrived late.', gloss: { de: 'Sie war wütend, weil ich zu spät gekommen bin.', es: 'Estaba enfadada porque llegué tarde.', fr: 'Elle était en colère parce que je suis arrivé en retard.', it: 'Era arrabbiata perché sono arrivato in ritardo.', pt: 'Ela ficou brava porque cheguei atrasado.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['sad', 'worried', 'bored'] },
  { id: 'en2s014', de: 'I think this restaurant is the best in the city.', en: 'I think this restaurant is the best in the city.', gloss: { de: 'Ich finde, dieses Restaurant ist das beste in der Stadt.', es: 'Creo que este restaurante es el mejor de la ciudad.', fr: 'Je pense que ce restaurant est le meilleur de la ville.', it: 'Penso che questo ristorante sia il migliore della città.', pt: 'Acho que este restaurante é o melhor da cidade.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['worst', 'cheapest', 'biggest'] },
  { id: 'en2s015', de: 'The flat has a big kitchen and a garden.', en: 'The flat has a big kitchen and a garden.', gloss: { de: 'Die Wohnung hat eine große Küche und einen Garten.', es: 'El apartamento tiene una cocina grande y un jardín.', fr: 'L’appartement a une grande cuisine et un jardin.', it: 'L’appartamento ha una cucina grande e un giardino.', pt: 'O apartamento tem uma cozinha grande e um jardim.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['bedroom', 'bathroom', 'office'] },
  { id: 'en2s016', de: 'We paid the rent last month.', en: 'We paid the rent last month.', gloss: { de: 'Wir haben die Miete letzten Monat bezahlt.', es: 'Pagamos el alquiler el mes pasado.', fr: 'Nous avons payé le loyer le mois dernier.', it: 'Abbiamo pagato l’affitto il mese scorso.', pt: 'Pagamos o aluguel no mês passado.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['bill', 'price', 'salary'] },
  { id: 'en2s017', de: 'He cooked a soup with rice and vegetables.', en: 'He cooked a soup with rice and vegetables.', gloss: { de: 'Er hat eine Suppe mit Reis und Gemüse gekocht.', es: 'Cocinó una sopa con arroz y verduras.', fr: 'Il a préparé une soupe avec du riz et des légumes.', it: 'Ha cucinato una zuppa con riso e verdure.', pt: 'Ele cozinhou uma sopa com arroz e legumes.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['ordered', 'bought', 'brought'] },
  { id: 'en2s018', de: 'We ordered a dessert and two coffees.', en: 'We ordered a dessert and two coffees.', gloss: { de: 'Wir haben einen Nachtisch und zwei Kaffee bestellt.', es: 'Pedimos un postre y dos cafés.', fr: 'Nous avons commandé un dessert et deux cafés.', it: 'Abbiamo ordinato un dolce e due caffè.', pt: 'Pedimos uma sobremesa e dois cafés.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['soup', 'menu', 'chicken'] },
  { id: 'en2s019', de: 'Yesterday the weather was sunny and warm.', en: 'Yesterday the weather was sunny and warm.', gloss: { de: 'Gestern war das Wetter sonnig und warm.', es: 'Ayer el tiempo estuvo soleado y cálido.', fr: 'Hier, le temps était ensoleillé et chaud.', it: 'Ieri il tempo era soleggiato e caldo.', pt: 'Ontem o tempo estava ensolarado e quente.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['cloudy', 'windy', 'cold'] },
  { id: 'en2s020', de: 'I sometimes work from home on Fridays.', en: 'I sometimes work from home on Fridays.', gloss: { de: 'Ich arbeite freitags manchmal von zu Hause.', es: 'A veces trabajo desde casa los viernes.', fr: 'Je travaille parfois à la maison le vendredi.', it: 'A volte lavoro da casa il venerdì.', pt: 'Às vezes trabalho de casa às sextas-feiras.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['often', 'never', 'always'] },
  { id: 'en2s021', de: 'Did you send the email to your boss?', en: 'Did you send the email to your boss?', gloss: { de: 'Hast du die E-Mail an deinen Chef geschickt?', es: '¿Enviaste el correo a tu jefe?', fr: 'As-tu envoyé l’e-mail à ton patron ?', it: 'Hai mandato l’e-mail al tuo capo?', pt: 'Você enviou o e-mail para o seu chefe?' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['bring', 'pay', 'forget'] },
  { id: 'en2s022', de: 'I lost my suitcase at the airport.', en: 'I lost my suitcase at the airport.', gloss: { de: 'Ich habe meinen Koffer am Flughafen verloren.', es: 'Perdí la maleta en el aeropuerto.', fr: 'J’ai perdu ma valise à l’aéroport.', it: 'Ho perso la valigia in aeroporto.', pt: 'Perdi a minha mala no aeroporto.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['found', 'sent', 'bought'] },
];
