import type { SentenceItem } from '@/content/german/types';

// English B1 sentences. `de` holds the English text (see content/german/types.ts).
// Where A1 stayed in the present tense and A2 told small past-tense stories, B1
// argues: subordinate and relative clauses, present perfect with since/never,
// second and third conditionals, and opinion framing carried by connectors
// (although, despite, however, therefore, otherwise, whereas).
//
// clozeIndex targets the load-bearing word — never an article, and never the
// final word of the sentence, since a trailing full stop the distractors lack
// would give the answer away. The three clozeDistractors are same-class words
// that would be grammatical but wrong, so the exercise tests meaning.
//
// `en` mirrors `de` for this pack: it is the guaranteed fallback in the type
// contract, but an English-UI user is never offered English to learn, so it is
// not shown. `gloss` carries all five other UI locales — de / es / fr / it / pt.

export const B1_SENTENCES: SentenceItem[] = [
  { id: 'en3s001', de: 'Although the salary is lower, I prefer this job.', en: 'Although the salary is lower, I prefer this job.', gloss: { de: 'Obwohl das Gehalt niedriger ist, ziehe ich diese Stelle vor.', es: 'Aunque el sueldo es más bajo, prefiero este trabajo.', fr: 'Bien que le salaire soit plus bas, je préfère ce travail.', it: 'Anche se lo stipendio è più basso, preferisco questo lavoro.', pt: 'Embora o salário seja mais baixo, prefiro este trabalho.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Despite', 'However', 'Therefore'] },
  { id: 'en3s002', de: 'In my opinion, the government should protect the environment.', en: 'In my opinion, the government should protect the environment.', gloss: { de: 'Meiner Meinung nach sollte die Regierung die Umwelt schützen.', es: 'En mi opinión, el gobierno debería proteger el medio ambiente.', fr: 'À mon avis, le gouvernement devrait protéger l’environnement.', it: 'Secondo me, il governo dovrebbe proteggere l’ambiente.', pt: 'Na minha opinião, o governo deveria proteger o meio ambiente.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['pollute', 'publish', 'consume'] },
  { id: 'en3s003', de: 'I have never regretted the choice that I made.', en: 'I have never regretted the choice that I made.', gloss: { de: 'Ich habe die Entscheidung, die ich getroffen habe, nie bereut.', es: 'Nunca me he arrepentido de la elección que hice.', fr: 'Je n’ai jamais regretté le choix que j’ai fait.', it: 'Non ho mai rimpianto la scelta che ho fatto.', pt: 'Nunca me arrependi da escolha que fiz.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['admitted', 'achieved', 'shared'] },
  { id: 'en3s004', de: 'If the deadline were realistic, we would finish on time.', en: 'If the deadline were realistic, we would finish on time.', gloss: { de: 'Wenn die Frist realistisch wäre, würden wir rechtzeitig fertig werden.', es: 'Si el plazo fuera realista, terminaríamos a tiempo.', fr: 'Si le délai était réaliste, nous finirions à temps.', it: 'Se la scadenza fosse realistica, finiremmo in tempo.', pt: 'Se o prazo fosse realista, terminaríamos a tempo.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['promotion', 'application', 'interview'] },
  { id: 'en3s005', de: 'The journalist who wrote the article checked every source.', en: 'The journalist who wrote the article checked every source.', gloss: { de: 'Der Journalist, der den Artikel geschrieben hat, hat jede Quelle geprüft.', es: 'El periodista que escribió el artículo comprobó todas las fuentes.', fr: 'Le journaliste qui a écrit l’article a vérifié chaque source.', it: 'Il giornalista che ha scritto l’articolo ha verificato ogni fonte.', pt: 'O jornalista que escreveu o artigo verificou todas as fontes.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['citizen', 'audience', 'colleague'] },
  { id: 'en3s006', de: 'Despite the risk, she decided to apply for the job.', en: 'Despite the risk, she decided to apply for the job.', gloss: { de: 'Trotz des Risikos hat sie sich entschieden, sich auf die Stelle zu bewerben.', es: 'A pesar del riesgo, decidió solicitar el puesto.', fr: 'Malgré le risque, elle a décidé de postuler pour ce poste.', it: 'Nonostante il rischio, ha deciso di candidarsi per il posto.', pt: 'Apesar do risco, ela decidiu se candidatar à vaga.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Although', 'However', 'Moreover'] },
  { id: 'en3s007', de: 'The company has hired ten people since the new manager arrived.', en: 'The company has hired ten people since the new manager arrived.', gloss: { de: 'Die Firma hat zehn Leute eingestellt, seit der neue Chef angefangen hat.', es: 'La empresa ha contratado a diez personas desde que llegó el nuevo jefe.', fr: 'L’entreprise a embauché dix personnes depuis l’arrivée du nouveau directeur.', it: 'L’azienda ha assunto dieci persone da quando è arrivato il nuovo capo.', pt: 'A empresa contratou dez pessoas desde que o novo gerente chegou.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['trusted', 'managed', 'published'] },
  { id: 'en3s008', de: 'However, I still think that the plan is too expensive.', en: 'However, I still think that the plan is too expensive.', gloss: { de: 'Ich finde jedoch immer noch, dass der Plan zu teuer ist.', es: 'Sin embargo, sigo pensando que el plan es demasiado caro.', fr: 'Cependant, je pense toujours que le plan est trop cher.', it: 'Tuttavia, penso ancora che il piano sia troppo caro.', pt: 'No entanto, ainda acho que o plano é caro demais.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['result', 'effort', 'deadline'] },
  { id: 'en3s009', de: 'Therefore, we should reduce the waste that we produce at home.', en: 'Therefore, we should reduce the waste that we produce at home.', gloss: { de: 'Deshalb sollten wir den Müll reduzieren, den wir zu Hause produzieren.', es: 'Por lo tanto, deberíamos reducir los residuos que producimos en casa.', fr: 'Par conséquent, nous devrions réduire les déchets que nous produisons à la maison.', it: 'Quindi dovremmo ridurre i rifiuti che produciamo in casa.', pt: 'Portanto, deveríamos reduzir o lixo que produzimos em casa.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['energy', 'pollution', 'poverty'] },
  { id: 'en3s010', de: 'If I were you, I would complain to the manager.', en: 'If I were you, I would complain to the manager.', gloss: { de: 'An deiner Stelle würde ich mich beim Chef beschweren.', es: 'Yo que tú, me quejaría al jefe.', fr: 'À ta place, je me plaindrais au responsable.', it: 'Se fossi in te, mi lamenterei con il responsabile.', pt: 'Se eu fosse você, reclamaria com o gerente.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['apply', 'vote', 'resign'] },
  { id: 'en3s011', de: 'She was disappointed because nobody had read her essay.', en: 'She was disappointed because nobody had read her essay.', gloss: { de: 'Sie war enttäuscht, weil niemand ihren Aufsatz gelesen hatte.', es: 'Estaba decepcionada porque nadie había leído su redacción.', fr: 'Elle était déçue parce que personne n’avait lu sa dissertation.', it: 'Era delusa perché nessuno aveva letto il suo tema.', pt: 'Ela ficou decepcionada porque ninguém tinha lido a sua redação.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['relieved', 'proud', 'confident'] },
  { id: 'en3s012', de: 'The report that they published last week influenced the whole debate.', en: 'The report that they published last week influenced the whole debate.', gloss: { de: 'Der Bericht, den sie letzte Woche veröffentlicht haben, hat die ganze Debatte beeinflusst.', es: 'El informe que publicaron la semana pasada influyó en todo el debate.', fr: 'Le rapport qu’ils ont publié la semaine dernière a influencé tout le débat.', it: 'Il rapporto che hanno pubblicato la settimana scorsa ha influenzato tutto il dibattito.', pt: 'O relatório que publicaram na semana passada influenciou todo o debate.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['broadcast', 'shared', 'protected'] },
  { id: 'en3s013', de: 'Moreover, the new law will affect thousands of citizens.', en: 'Moreover, the new law will affect thousands of citizens.', gloss: { de: 'Außerdem wird das neue Gesetz Tausende von Bürgern betreffen.', es: 'Además, la nueva ley afectará a miles de ciudadanos.', fr: 'De plus, la nouvelle loi touchera des milliers de citoyens.', it: 'Inoltre, la nuova legge riguarderà migliaia di cittadini.', pt: 'Além disso, a nova lei vai afetar milhares de cidadãos.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['tax', 'crime', 'source'] },
  { id: 'en3s014', de: 'He has been working here since he finished his degree.', en: 'He has been working here since he finished his degree.', gloss: { de: 'Er arbeitet hier, seit er seinen Abschluss gemacht hat.', es: 'Trabaja aquí desde que terminó la carrera.', fr: 'Il travaille ici depuis qu’il a terminé ses études.', it: 'Lavora qui da quando si è laureato.', pt: 'Ele trabalha aqui desde que terminou o curso.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['although', 'despite', 'whereas'] },
  { id: 'en3s015', de: 'As far as I am concerned, the argument is not convincing.', en: 'As far as I am concerned, the argument is not convincing.', gloss: { de: 'Was mich betrifft, ist das Argument nicht überzeugend.', es: 'En lo que a mí respecta, el argumento no es convincente.', fr: 'En ce qui me concerne, l’argument n’est pas convaincant.', it: 'Per quanto mi riguarda, l’argomento non è convincente.', pt: 'No que me diz respeito, o argumento não é convincente.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['headline', 'purpose', 'effort'] },
  { id: 'en3s016', de: 'We must recycle more, otherwise the situation will get worse.', en: 'We must recycle more, otherwise the situation will get worse.', gloss: { de: 'Wir müssen mehr recyceln, sonst wird die Lage schlimmer.', es: 'Tenemos que reciclar más, si no la situación empeorará.', fr: 'Nous devons recycler davantage, sinon la situation va empirer.', it: 'Dobbiamo riciclare di più, altrimenti la situazione peggiorerà.', pt: 'Temos que reciclar mais, caso contrário a situação vai piorar.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['moreover', 'however', 'therefore'] },
  { id: 'en3s017', de: 'I would like to know why she resigned so suddenly.', en: 'I would like to know why she resigned so suddenly.', gloss: { de: 'Ich wüsste gern, warum sie so plötzlich gekündigt hat.', es: 'Me gustaría saber por qué dimitió tan de repente.', fr: 'J’aimerais savoir pourquoi elle a démissionné si soudainement.', it: 'Vorrei sapere perché si è dimessa così all’improvviso.', pt: 'Gostaria de saber por que ela se demitiu tão de repente.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['complained', 'protested', 'improved'] },
  { id: 'en3s018', de: 'Everyone is aware of the problem, whereas nobody wants to pay for it.', en: 'Everyone is aware of the problem, whereas nobody wants to pay for it.', gloss: { de: 'Alle sind sich des Problems bewusst, während niemand dafür zahlen will.', es: 'Todos son conscientes del problema, mientras que nadie quiere pagarlo.', fr: 'Tout le monde est conscient du problème, alors que personne ne veut payer.', it: 'Tutti sono consapevoli del problema, mentre nessuno vuole pagarlo.', pt: 'Todos estão conscientes do problema, enquanto ninguém quer pagar por isso.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['because', 'otherwise', 'therefore'] },
  { id: 'en3s019', de: 'The freedom to say what you think is worth protecting.', en: 'The freedom to say what you think is worth protecting.', gloss: { de: 'Die Freiheit, zu sagen, was man denkt, verdient es, geschützt zu werden.', es: 'La libertad de decir lo que uno piensa merece ser protegida.', fr: 'La liberté de dire ce que l’on pense mérite d’être protégée.', it: 'La libertà di dire ciò che si pensa merita di essere protetta.', pt: 'A liberdade de dizer o que se pensa merece ser protegida.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['effort', 'result', 'influence'] },
  { id: 'en3s020', de: 'If we had voted, the result would have been different.', en: 'If we had voted, the result would have been different.', gloss: { de: 'Wenn wir gewählt hätten, wäre das Ergebnis anders gewesen.', es: 'Si hubiéramos votado, el resultado habría sido diferente.', fr: 'Si nous avions voté, le résultat aurait été différent.', it: 'Se avessimo votato, il risultato sarebbe stato diverso.', pt: 'Se tivéssemos votado, o resultado teria sido diferente.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['reason', 'purpose', 'choice'] },
];
