"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.B2_VOCAB = void 0;
// Italian (it-IT) B2 vocabulary. The `de` field holds the Italian text (see the
// note in content/german/types.ts). Nouns ship with the article, chosen by the
// SOUND that follows: il (most consonants), lo (s+consonant, z, gn, ps, y),
// l' (any vowel), la (feminine + consonant) — lo stereotipo, l’obiezione,
// l’indagine, la trattativa.
//
// Level discipline: A1 owns greetings/people/food/places/core verbs/numbers,
// A2 owns daily routine, travel, shopping, health, weather, house, B1 owns the
// first register of argument. B2 is the register of NUANCE — hypothesis and
// concession, cause traced to consequence, hedged claims, diplomatic
// disagreement, and the specialised vocabularies (law, economics, criticism,
// the ethics of technology) a B1 speaker reads but cannot yet produce.
//
// `gloss` carries the other UI locales. English lives in `en` and is the
// guaranteed fallback; Italian itself is never glossed, so each item covers
// de / es / fr / pt.
exports.B2_VOCAB = [
    // ── argument & hedging ────────────────────────────────────────────────
    { id: 'it4v001', de: 'la sfumatura', en: ['the nuance', 'the shade'], gloss: { de: ['die Nuance'], es: ['el matiz'], fr: ['la nuance'], pt: ['a nuance'] }, pos: 'noun', level: 'B2', category: 'argument' },
    { id: 'it4v002', de: 'la congettura', en: ['the conjecture'], gloss: { de: ['die Mutmaßung'], es: ['la conjetura'], fr: ['la conjecture'], pt: ['a conjectura'] }, pos: 'noun', level: 'B2', category: 'argument' },
    { id: 'it4v003', de: 'la premessa', en: ['the premise'], gloss: { de: ['die Prämisse'], es: ['la premisa'], fr: ['la prémisse'], pt: ['a premissa'] }, pos: 'noun', level: 'B2', category: 'argument' },
    { id: 'it4v004', de: 'l’obiezione', en: ['the objection'], gloss: { de: ['der Einwand'], es: ['la objeción'], fr: ['l’objection'], pt: ['a objeção'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'argument' },
    { id: 'it4v005', de: 'il presupposto', en: ['the assumption'], gloss: { de: ['die Voraussetzung'], es: ['el supuesto'], fr: ['le présupposé'], pt: ['o pressuposto'] }, pos: 'noun', level: 'B2', category: 'argument' },
    { id: 'it4v006', de: 'il fraintendimento', en: ['the misunderstanding'], gloss: { de: ['das Missverständnis'], es: ['el malentendido'], fr: ['le malentendu'], pt: ['o mal-entendido'] }, pos: 'noun', level: 'B2', category: 'argument' },
    { id: 'it4v007', de: 'ribadire', en: ['to reiterate', 'to restate'], gloss: { de: ['bekräftigen'], es: ['reiterar'], fr: ['réitérer'], pt: ['reiterar'] }, pos: 'verb', level: 'B2', category: 'argument' },
    { id: 'it4v008', de: 'contestare', en: ['to dispute', 'to challenge'], gloss: { de: ['bestreiten'], es: ['impugnar'], fr: ['contester'], pt: ['contestar'] }, pos: 'verb', level: 'B2', category: 'argument' },
    { id: 'it4v009', de: 'ammettere', en: ['to admit', 'to concede'], gloss: { de: ['zugeben'], es: ['admitir'], fr: ['admettre'], pt: ['admitir'] }, pos: 'verb', level: 'B2', category: 'argument' },
    { id: 'it4v010', de: 'supporre', en: ['to suppose', 'to assume'], gloss: { de: ['vermuten'], es: ['suponer'], fr: ['supposer'], pt: ['supor'] }, pos: 'verb', level: 'B2', category: 'argument' },
    { id: 'it4v011', de: 'attenuare', en: ['to tone down', 'to mitigate'], gloss: { de: ['abschwächen'], es: ['atenuar'], fr: ['atténuer'], pt: ['atenuar'] }, pos: 'verb', level: 'B2', category: 'argument' },
    { id: 'it4v012', de: 'per quanto ne so', en: ['as far as I know'], gloss: { de: ['soweit ich weiß'], es: ['que yo sepa'], fr: ['autant que je sache'], pt: ['que eu saiba'] }, pos: 'phrase', level: 'B2', category: 'argument' },
    { id: 'it4v013', de: 'mi permetto di dissentire', en: ['I beg to differ'], gloss: { de: ['ich erlaube mir zu widersprechen'], es: ['me permito discrepar'], fr: ['je me permets de ne pas être d’accord'], pt: ['permito-me discordar'] }, pos: 'phrase', level: 'B2', category: 'argument' },
    // ── work & negotiation ────────────────────────────────────────────────
    { id: 'it4v014', de: 'la trattativa', en: ['the negotiation'], gloss: { de: ['die Verhandlung'], es: ['la negociación'], fr: ['la négociation'], pt: ['a negociação'] }, pos: 'noun', level: 'B2', category: 'negotiation' },
    { id: 'it4v015', de: 'la controproposta', en: ['the counter-proposal'], gloss: { de: ['der Gegenvorschlag'], es: ['la contrapropuesta'], fr: ['la contre-proposition'], pt: ['a contraproposta'] }, pos: 'noun', level: 'B2', category: 'negotiation' },
    { id: 'it4v016', de: 'la scadenza', en: ['the deadline'], gloss: { de: ['die Frist'], es: ['el plazo'], fr: ['l’échéance'], pt: ['o prazo'] }, pos: 'noun', level: 'B2', category: 'negotiation' },
    { id: 'it4v017', de: 'il preavviso', en: ['the advance notice'], gloss: { de: ['die Vorankündigung'], es: ['el preaviso'], fr: ['le préavis'], pt: ['o aviso prévio'] }, pos: 'noun', level: 'B2', category: 'negotiation' },
    { id: 'it4v018', de: 'la clausola', en: ['the clause'], gloss: { de: ['die Klausel'], es: ['la cláusula'], fr: ['la clause'], pt: ['a cláusula'] }, pos: 'noun', level: 'B2', category: 'negotiation' },
    { id: 'it4v019', de: 'il fornitore', en: ['the supplier'], gloss: { de: ['der Lieferant'], es: ['el proveedor'], fr: ['le fournisseur'], pt: ['o fornecedor'] }, pos: 'noun', level: 'B2', category: 'negotiation' },
    { id: 'it4v020', de: 'il tirocinio', en: ['the internship'], gloss: { de: ['das Praktikum'], es: ['las prácticas'], fr: ['le stage'], pt: ['o estágio'] }, pos: 'noun', level: 'B2', category: 'negotiation' },
    { id: 'it4v021', de: 'lo straordinario', en: ['the overtime'], gloss: { de: ['die Überstunde'], es: ['la hora extra'], fr: ['l’heure supplémentaire'], pt: ['a hora extra'] }, pos: 'noun', level: 'B2', category: 'negotiation' },
    { id: 'it4v022', de: 'il sindacato', en: ['the trade union'], gloss: { de: ['die Gewerkschaft'], es: ['el sindicato'], fr: ['le syndicat'], pt: ['o sindicato'] }, pos: 'noun', level: 'B2', category: 'negotiation' },
    { id: 'it4v023', de: 'la mansione', en: ['the duty', 'the job task'], gloss: { de: ['die Arbeitsaufgabe'], es: ['la tarea'], fr: ['la tâche'], pt: ['a atribuição'] }, pos: 'noun', level: 'B2', category: 'negotiation' },
    { id: 'it4v024', de: 'negoziare', en: ['to negotiate'], gloss: { de: ['verhandeln'], es: ['negociar'], fr: ['négocier'], pt: ['negociar'] }, pos: 'verb', level: 'B2', category: 'negotiation' },
    { id: 'it4v025', de: 'delegare', en: ['to delegate'], gloss: { de: ['delegieren'], es: ['delegar'], fr: ['déléguer'], pt: ['delegar'] }, pos: 'verb', level: 'B2', category: 'negotiation' },
    { id: 'it4v026', de: 'dimettersi', en: ['to resign'], gloss: { de: ['zurücktreten'], es: ['dimitir'], fr: ['démissionner'], pt: ['demitir-se'] }, pos: 'verb', level: 'B2', category: 'negotiation' },
    // ── media & information ───────────────────────────────────────────────
    { id: 'it4v027', de: 'la fonte', en: ['the source'], gloss: { de: ['die Quelle'], es: ['la fuente'], fr: ['la source'], pt: ['a fonte'] }, pos: 'noun', level: 'B2', category: 'information' },
    { id: 'it4v028', de: 'l’inchiesta', en: ['the investigative report'], gloss: { de: ['die Recherche'], es: ['la investigación periodística'], fr: ['l’enquête'], pt: ['a reportagem investigativa'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'information' },
    { id: 'it4v029', de: 'il titolo', en: ['the headline', 'the title'], gloss: { de: ['die Schlagzeile'], es: ['el titular'], fr: ['le titre'], pt: ['a manchete'] }, pos: 'noun', level: 'B2', category: 'information' },
    { id: 'it4v030', de: 'la testata', en: ['the news outlet'], gloss: { de: ['das Presseorgan'], es: ['la cabecera'], fr: ['le titre de presse'], pt: ['o veículo de imprensa'] }, pos: 'noun', level: 'B2', category: 'information' },
    { id: 'it4v031', de: 'la censura', en: ['the censorship'], gloss: { de: ['die Zensur'], es: ['la censura'], fr: ['la censure'], pt: ['a censura'] }, pos: 'noun', level: 'B2', category: 'information' },
    { id: 'it4v032', de: 'l’emittente', en: ['the broadcaster'], gloss: { de: ['der Sender'], es: ['la emisora'], fr: ['la chaîne'], pt: ['a emissora'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'information' },
    { id: 'it4v033', de: 'la disinformazione', en: ['the disinformation'], gloss: { de: ['die Desinformation'], es: ['la desinformación'], fr: ['la désinformation'], pt: ['a desinformação'] }, pos: 'noun', level: 'B2', category: 'information' },
    { id: 'it4v034', de: 'il portavoce', en: ['the spokesperson'], gloss: { de: ['der Sprecher'], es: ['el portavoz'], fr: ['le porte-parole'], pt: ['o porta-voz'] }, pos: 'noun', level: 'B2', category: 'information' },
    { id: 'it4v035', de: 'parziale', en: ['biased', 'partial'], gloss: { de: ['parteiisch'], es: ['parcial'], fr: ['partial'], pt: ['parcial'] }, pos: 'adj', level: 'B2', category: 'information' },
    { id: 'it4v036', de: 'attendibile', en: ['credible', 'trustworthy'], gloss: { de: ['glaubwürdig'], es: ['fidedigno'], fr: ['digne de foi'], pt: ['fidedigno'] }, pos: 'adj', level: 'B2', category: 'information' },
    { id: 'it4v037', de: 'divulgare', en: ['to disclose', 'to make public'], gloss: { de: ['bekannt machen'], es: ['divulgar'], fr: ['divulguer'], pt: ['divulgar'] }, pos: 'verb', level: 'B2', category: 'information' },
    { id: 'it4v038', de: 'smentire', en: ['to deny', 'to refute'], gloss: { de: ['dementieren'], es: ['desmentir'], fr: ['démentir'], pt: ['desmentir'] }, pos: 'verb', level: 'B2', category: 'information' },
    // ── science & environment ─────────────────────────────────────────────
    { id: 'it4v039', de: 'il riscaldamento globale', en: ['the global warming'], gloss: { de: ['die globale Erwärmung'], es: ['el calentamiento global'], fr: ['le réchauffement climatique'], pt: ['o aquecimento global'] }, pos: 'noun', level: 'B2', category: 'science' },
    { id: 'it4v040', de: 'la biodiversità', en: ['the biodiversity'], gloss: { de: ['die Artenvielfalt'], es: ['la biodiversidad'], fr: ['la biodiversité'], pt: ['a biodiversidade'] }, pos: 'noun', level: 'B2', category: 'science' },
    { id: 'it4v041', de: 'l’esperimento', en: ['the experiment'], gloss: { de: ['das Experiment'], es: ['el experimento'], fr: ['l’expérience'], pt: ['o experimento'] }, pos: 'noun', gender: 'm', level: 'B2', category: 'science' },
    { id: 'it4v042', de: 'il campione', en: ['the sample'], gloss: { de: ['die Stichprobe'], es: ['la muestra'], fr: ['l’échantillon'], pt: ['a amostra'] }, pos: 'noun', level: 'B2', category: 'science' },
    { id: 'it4v043', de: 'la siccità', en: ['the drought'], gloss: { de: ['die Dürre'], es: ['la sequía'], fr: ['la sécheresse'], pt: ['a seca'] }, pos: 'noun', level: 'B2', category: 'science' },
    { id: 'it4v044', de: 'le emissioni', en: ['the emissions'], gloss: { de: ['die Emissionen'], es: ['las emisiones'], fr: ['les émissions'], pt: ['as emissões'] }, pos: 'noun', level: 'B2', category: 'science' },
    { id: 'it4v045', de: 'la specie', en: ['the species'], gloss: { de: ['die Art'], es: ['la especie'], fr: ['l’espèce'], pt: ['a espécie'] }, pos: 'noun', level: 'B2', category: 'science' },
    { id: 'it4v046', de: 'la scoperta', en: ['the discovery'], gloss: { de: ['die Entdeckung'], es: ['el descubrimiento'], fr: ['la découverte'], pt: ['a descoberta'] }, pos: 'noun', level: 'B2', category: 'science' },
    { id: 'it4v047', de: 'il vincolo', en: ['the constraint', 'the restriction'], gloss: { de: ['die Auflage'], es: ['la restricción'], fr: ['la contrainte'], pt: ['a restrição'] }, pos: 'noun', level: 'B2', category: 'science' },
    { id: 'it4v048', de: 'smaltire', en: ['to dispose of'], gloss: { de: ['entsorgen'], es: ['eliminar'], fr: ['éliminer'], pt: ['descartar'] }, pos: 'verb', level: 'B2', category: 'science' },
    { id: 'it4v049', de: 'rilevare', en: ['to detect', 'to record'], gloss: { de: ['erfassen'], es: ['detectar'], fr: ['relever'], pt: ['detectar'] }, pos: 'verb', level: 'B2', category: 'science' },
    { id: 'it4v050', de: 'presumibilmente', en: ['presumably'], gloss: { de: ['vermutlich'], es: ['presumiblemente'], fr: ['vraisemblablement'], pt: ['presumivelmente'] }, pos: 'adv', level: 'B2', category: 'science' },
    // ── culture & identity ────────────────────────────────────────────────
    { id: 'it4v051', de: 'l’appartenenza', en: ['the belonging'], gloss: { de: ['die Zugehörigkeit'], es: ['la pertenencia'], fr: ['l’appartenance'], pt: ['o pertencimento'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'identity' },
    { id: 'it4v052', de: 'il pregiudizio', en: ['the prejudice'], gloss: { de: ['das Vorurteil'], es: ['el prejuicio'], fr: ['le préjugé'], pt: ['o preconceito'] }, pos: 'noun', level: 'B2', category: 'identity' },
    { id: 'it4v053', de: 'lo stereotipo', en: ['the stereotype'], gloss: { de: ['das Klischee'], es: ['el estereotipo'], fr: ['le stéréotype'], pt: ['o estereótipo'] }, pos: 'noun', level: 'B2', category: 'identity' },
    { id: 'it4v054', de: 'l’usanza', en: ['the custom'], gloss: { de: ['der Brauch'], es: ['la costumbre'], fr: ['la coutume'], pt: ['o costume'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'identity' },
    { id: 'it4v055', de: 'il patrimonio', en: ['the heritage'], gloss: { de: ['das Erbe'], es: ['el patrimonio'], fr: ['le patrimoine'], pt: ['o patrimônio'] }, pos: 'noun', level: 'B2', category: 'identity' },
    { id: 'it4v056', de: 'l’integrazione', en: ['the integration'], gloss: { de: ['die Integration'], es: ['la integración'], fr: ['l’intégration'], pt: ['a integração'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'identity' },
    { id: 'it4v057', de: 'il divario', en: ['the gap', 'the divide'], gloss: { de: ['die Kluft'], es: ['la brecha'], fr: ['l’écart'], pt: ['a disparidade'] }, pos: 'noun', level: 'B2', category: 'identity' },
    { id: 'it4v058', de: 'il dialetto', en: ['the dialect'], gloss: { de: ['der Dialekt'], es: ['el dialecto'], fr: ['le dialecte'], pt: ['o dialeto'] }, pos: 'noun', level: 'B2', category: 'identity' },
    { id: 'it4v059', de: 'radicato', en: ['deep-rooted'], gloss: { de: ['tief verwurzelt'], es: ['arraigado'], fr: ['enraciné'], pt: ['enraizado'] }, pos: 'adj', level: 'B2', category: 'identity' },
    { id: 'it4v060', de: 'estraneo', en: ['alien', 'unconnected'], gloss: { de: ['fremd'], es: ['ajeno'], fr: ['étranger'], pt: ['alheio'] }, pos: 'adj', level: 'B2', category: 'identity' },
    { id: 'it4v061', de: 'tramandare', en: ['to hand down', 'to pass on'], gloss: { de: ['überliefern'], es: ['transmitir'], fr: ['transmettre'], pt: ['transmitir'] }, pos: 'verb', level: 'B2', category: 'identity' },
    { id: 'it4v062', de: 'convivere', en: ['to coexist', 'to live together'], gloss: { de: ['zusammenleben'], es: ['convivir'], fr: ['cohabiter'], pt: ['conviver'] }, pos: 'verb', level: 'B2', category: 'identity' },
    // ── law & rights ──────────────────────────────────────────────────────
    { id: 'it4v063', de: 'la sentenza', en: ['the ruling', 'the verdict'], gloss: { de: ['das Urteil'], es: ['la sentencia'], fr: ['le jugement'], pt: ['a sentença'] }, pos: 'noun', level: 'B2', category: 'law' },
    { id: 'it4v064', de: 'la magistratura', en: ['the judiciary'], gloss: { de: ['die Justiz'], es: ['la magistratura'], fr: ['la magistrature'], pt: ['a magistratura'] }, pos: 'noun', level: 'B2', category: 'law' },
    { id: 'it4v065', de: 'l’imputato', en: ['the defendant'], gloss: { de: ['der Angeklagte'], es: ['el acusado'], fr: ['l’accusé'], pt: ['o réu'] }, pos: 'noun', gender: 'm', level: 'B2', category: 'law' },
    { id: 'it4v066', de: 'la testimonianza', en: ['the testimony'], gloss: { de: ['die Zeugenaussage'], es: ['el testimonio'], fr: ['le témoignage'], pt: ['o testemunho'] }, pos: 'noun', level: 'B2', category: 'law' },
    { id: 'it4v067', de: 'la pena', en: ['the penalty', 'the sentence'], gloss: { de: ['die Strafe'], es: ['la pena'], fr: ['la peine'], pt: ['a pena'] }, pos: 'noun', level: 'B2', category: 'law' },
    { id: 'it4v068', de: 'l’indagine', en: ['the inquiry', 'the investigation'], gloss: { de: ['die Ermittlung'], es: ['la indagación'], fr: ['l’enquête judiciaire'], pt: ['a apuração'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'law' },
    { id: 'it4v069', de: 'il ricorso', en: ['the appeal'], gloss: { de: ['die Berufung'], es: ['el recurso'], fr: ['le recours'], pt: ['o recurso'] }, pos: 'noun', level: 'B2', category: 'law' },
    { id: 'it4v070', de: 'la normativa', en: ['the regulations'], gloss: { de: ['die Vorschriften'], es: ['la normativa'], fr: ['la réglementation'], pt: ['a regulamentação'] }, pos: 'noun', level: 'B2', category: 'law' },
    { id: 'it4v071', de: 'l’ordinamento', en: ['the legal system'], gloss: { de: ['die Rechtsordnung'], es: ['el ordenamiento jurídico'], fr: ['l’ordre juridique'], pt: ['o ordenamento jurídico'] }, pos: 'noun', gender: 'm', level: 'B2', category: 'law' },
    { id: 'it4v072', de: 'risarcire', en: ['to compensate', 'to pay damages to'], gloss: { de: ['entschädigen'], es: ['indemnizar'], fr: ['indemniser'], pt: ['indenizar'] }, pos: 'verb', level: 'B2', category: 'law' },
    { id: 'it4v073', de: 'tutelare', en: ['to protect', 'to safeguard'], gloss: { de: ['schützen'], es: ['tutelar'], fr: ['protéger'], pt: ['tutelar'] }, pos: 'verb', level: 'B2', category: 'law' },
    { id: 'it4v074', de: 'lecito', en: ['lawful', 'permissible'], gloss: { de: ['zulässig'], es: ['lícito'], fr: ['licite'], pt: ['lícito'] }, pos: 'adj', level: 'B2', category: 'law' },
    // ── economics ─────────────────────────────────────────────────────────
    { id: 'it4v075', de: 'l’inflazione', en: ['the inflation'], gloss: { de: ['die Inflation'], es: ['la inflación'], fr: ['l’inflation'], pt: ['a inflação'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'economics' },
    { id: 'it4v076', de: 'il mutuo', en: ['the mortgage'], gloss: { de: ['die Hypothek'], es: ['la hipoteca'], fr: ['le prêt immobilier'], pt: ['o crédito imobiliário'] }, pos: 'noun', level: 'B2', category: 'economics' },
    { id: 'it4v077', de: 'il rendimento', en: ['the return', 'the yield'], gloss: { de: ['die Rendite'], es: ['el rendimiento'], fr: ['le rendement'], pt: ['o rendimento'] }, pos: 'noun', level: 'B2', category: 'economics' },
    { id: 'it4v078', de: 'l’indebitamento', en: ['the indebtedness'], gloss: { de: ['die Verschuldung'], es: ['el endeudamiento'], fr: ['l’endettement'], pt: ['o endividamento'] }, pos: 'noun', gender: 'm', level: 'B2', category: 'economics' },
    { id: 'it4v079', de: 'l’aliquota', en: ['the tax rate'], gloss: { de: ['der Steuersatz'], es: ['el tipo impositivo'], fr: ['le taux d’imposition'], pt: ['a alíquota'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'economics' },
    { id: 'it4v080', de: 'il rincaro', en: ['the price rise'], gloss: { de: ['die Verteuerung'], es: ['la subida de precios'], fr: ['la hausse des prix'], pt: ['o aumento de preços'] }, pos: 'noun', level: 'B2', category: 'economics' },
    { id: 'it4v081', de: 'il potere d’acquisto', en: ['the purchasing power'], gloss: { de: ['die Kaufkraft'], es: ['el poder adquisitivo'], fr: ['le pouvoir d’achat'], pt: ['o poder de compra'] }, pos: 'noun', level: 'B2', category: 'economics' },
    { id: 'it4v082', de: 'la recessione', en: ['the recession'], gloss: { de: ['die Rezession'], es: ['la recesión'], fr: ['la récession'], pt: ['a recessão'] }, pos: 'noun', level: 'B2', category: 'economics' },
    { id: 'it4v083', de: 'il consumo', en: ['the consumption'], gloss: { de: ['der Verbrauch'], es: ['el consumo'], fr: ['la consommation'], pt: ['o consumo'] }, pos: 'noun', level: 'B2', category: 'economics' },
    { id: 'it4v084', de: 'risparmiare', en: ['to save money'], gloss: { de: ['sparen'], es: ['ahorrar'], fr: ['économiser'], pt: ['poupar'] }, pos: 'verb', level: 'B2', category: 'economics' },
    { id: 'it4v085', de: 'investire', en: ['to invest'], gloss: { de: ['investieren'], es: ['invertir'], fr: ['investir'], pt: ['investir'] }, pos: 'verb', level: 'B2', category: 'economics' },
    { id: 'it4v086', de: 'redditizio', en: ['profitable'], gloss: { de: ['rentabel'], es: ['rentable'], fr: ['rentable'], pt: ['rentável'] }, pos: 'adj', level: 'B2', category: 'economics' },
    // ── psychology ────────────────────────────────────────────────────────
    { id: 'it4v087', de: 'il comportamento', en: ['the behaviour'], gloss: { de: ['das Verhalten'], es: ['el comportamiento'], fr: ['le comportement'], pt: ['o comportamento'] }, pos: 'noun', level: 'B2', category: 'psychology' },
    { id: 'it4v088', de: 'l’abitudine', en: ['the habit'], gloss: { de: ['die Gewohnheit'], es: ['el hábito'], fr: ['l’habitude'], pt: ['o hábito'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'psychology' },
    { id: 'it4v089', de: 'la consapevolezza', en: ['the awareness'], gloss: { de: ['das Bewusstsein'], es: ['la conciencia'], fr: ['la conscience'], pt: ['a consciência'] }, pos: 'noun', level: 'B2', category: 'psychology' },
    { id: 'it4v090', de: 'l’autostima', en: ['the self-esteem'], gloss: { de: ['das Selbstwertgefühl'], es: ['la autoestima'], fr: ['l’estime de soi'], pt: ['a autoestima'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'psychology' },
    { id: 'it4v091', de: 'il disagio', en: ['the unease', 'the discomfort'], gloss: { de: ['das Unbehagen'], es: ['el malestar'], fr: ['le malaise'], pt: ['o mal-estar'] }, pos: 'noun', level: 'B2', category: 'psychology' },
    { id: 'it4v092', de: 'la resilienza', en: ['the resilience'], gloss: { de: ['die Resilienz'], es: ['la resiliencia'], fr: ['la résilience'], pt: ['a resiliência'] }, pos: 'noun', level: 'B2', category: 'psychology' },
    { id: 'it4v093', de: 'il rimpianto', en: ['the regret'], gloss: { de: ['das Bedauern'], es: ['el arrepentimiento'], fr: ['le regret'], pt: ['o arrependimento'] }, pos: 'noun', level: 'B2', category: 'psychology' },
    { id: 'it4v094', de: 'l’inconscio', en: ['the unconscious'], gloss: { de: ['das Unbewusste'], es: ['el inconsciente'], fr: ['l’inconscient'], pt: ['o inconsciente'] }, pos: 'noun', gender: 'm', level: 'B2', category: 'psychology' },
    { id: 'it4v095', de: 'rimuginare', en: ['to brood', 'to dwell on'], gloss: { de: ['grübeln'], es: ['darle vueltas'], fr: ['ruminer'], pt: ['remoer'] }, pos: 'verb', level: 'B2', category: 'psychology' },
    { id: 'it4v096', de: 'reprimere', en: ['to repress', 'to suppress'], gloss: { de: ['unterdrücken'], es: ['reprimir'], fr: ['réprimer'], pt: ['reprimir'] }, pos: 'verb', level: 'B2', category: 'psychology' },
    { id: 'it4v097', de: 'suscitare', en: ['to arouse', 'to provoke'], gloss: { de: ['hervorrufen'], es: ['suscitar'], fr: ['susciter'], pt: ['suscitar'] }, pos: 'verb', level: 'B2', category: 'psychology' },
    { id: 'it4v098', de: 'restio', en: ['reluctant'], gloss: { de: ['widerwillig'], es: ['reacio'], fr: ['réticent'], pt: ['relutante'] }, pos: 'adj', level: 'B2', category: 'psychology' },
    // ── technology & ethics ───────────────────────────────────────────────
    { id: 'it4v099', de: 'l’algoritmo', en: ['the algorithm'], gloss: { de: ['der Algorithmus'], es: ['el algoritmo'], fr: ['l’algorithme'], pt: ['o algoritmo'] }, pos: 'noun', gender: 'm', level: 'B2', category: 'technology' },
    { id: 'it4v100', de: 'la riservatezza', en: ['the confidentiality', 'the privacy'], gloss: { de: ['die Vertraulichkeit'], es: ['la confidencialidad'], fr: ['la confidentialité'], pt: ['a confidencialidade'] }, pos: 'noun', level: 'B2', category: 'technology' },
    { id: 'it4v101', de: 'il consenso', en: ['the consent', 'the consensus'], gloss: { de: ['die Zustimmung'], es: ['el consentimiento'], fr: ['le consentement'], pt: ['o consentimento'] }, pos: 'noun', level: 'B2', category: 'technology' },
    { id: 'it4v102', de: 'la sorveglianza', en: ['the surveillance'], gloss: { de: ['die Überwachung'], es: ['la vigilancia'], fr: ['la surveillance'], pt: ['a vigilância'] }, pos: 'noun', level: 'B2', category: 'technology' },
    { id: 'it4v103', de: 'l’utente', en: ['the user'], gloss: { de: ['der Nutzer'], es: ['el usuario'], fr: ['l’utilisateur'], pt: ['o usuário'] }, pos: 'noun', gender: 'm', level: 'B2', category: 'technology' },
    { id: 'it4v104', de: 'la truffa', en: ['the scam', 'the fraud'], gloss: { de: ['der Betrug'], es: ['la estafa'], fr: ['l’arnaque'], pt: ['a fraude'] }, pos: 'noun', level: 'B2', category: 'technology' },
    { id: 'it4v105', de: 'l’aggiornamento', en: ['the update'], gloss: { de: ['die Aktualisierung'], es: ['la actualización'], fr: ['la mise à jour'], pt: ['a atualização'] }, pos: 'noun', gender: 'm', level: 'B2', category: 'technology' },
    { id: 'it4v106', de: 'l’anonimato', en: ['the anonymity'], gloss: { de: ['die Anonymität'], es: ['el anonimato'], fr: ['l’anonymat'], pt: ['o anonimato'] }, pos: 'noun', gender: 'm', level: 'B2', category: 'technology' },
    { id: 'it4v107', de: 'la dipendenza', en: ['the addiction', 'the dependence'], gloss: { de: ['die Abhängigkeit'], es: ['la dependencia'], fr: ['la dépendance'], pt: ['a dependência'] }, pos: 'noun', level: 'B2', category: 'technology' },
    { id: 'it4v108', de: 'tracciare', en: ['to track'], gloss: { de: ['nachverfolgen'], es: ['rastrear'], fr: ['tracer'], pt: ['rastrear'] }, pos: 'verb', level: 'B2', category: 'technology' },
    { id: 'it4v109', de: 'archiviare', en: ['to archive', 'to file away'], gloss: { de: ['archivieren'], es: ['archivar'], fr: ['archiver'], pt: ['arquivar'] }, pos: 'verb', level: 'B2', category: 'technology' },
    { id: 'it4v110', de: 'invasivo', en: ['intrusive'], gloss: { de: ['aufdringlich'], es: ['invasivo'], fr: ['intrusif'], pt: ['invasivo'] }, pos: 'adj', level: 'B2', category: 'technology' },
    // ── urban life ────────────────────────────────────────────────────────
    { id: 'it4v111', de: 'il quartiere', en: ['the neighbourhood'], gloss: { de: ['das Viertel'], es: ['el barrio'], fr: ['le quartier'], pt: ['o bairro'] }, pos: 'noun', level: 'B2', category: 'urban' },
    { id: 'it4v112', de: 'il traffico', en: ['the traffic'], gloss: { de: ['der Verkehr'], es: ['el tráfico'], fr: ['la circulation'], pt: ['o trânsito'] }, pos: 'noun', level: 'B2', category: 'urban' },
    { id: 'it4v113', de: 'l’affitto', en: ['the rent'], gloss: { de: ['die Miete'], es: ['el alquiler'], fr: ['le loyer'], pt: ['o aluguel'] }, pos: 'noun', gender: 'm', level: 'B2', category: 'urban' },
    { id: 'it4v114', de: 'il canone', en: ['the recurring fee'], gloss: { de: ['die Gebühr'], es: ['la cuota'], fr: ['la redevance'], pt: ['a taxa'] }, pos: 'noun', level: 'B2', category: 'urban' },
    { id: 'it4v115', de: 'la periferia', en: ['the outskirts'], gloss: { de: ['der Stadtrand'], es: ['las afueras'], fr: ['la banlieue'], pt: ['a periferia'] }, pos: 'noun', level: 'B2', category: 'urban' },
    { id: 'it4v116', de: 'il cantiere', en: ['the building site'], gloss: { de: ['die Baustelle'], es: ['la obra'], fr: ['le chantier'], pt: ['o canteiro de obras'] }, pos: 'noun', level: 'B2', category: 'urban' },
    { id: 'it4v117', de: 'il sovraffollamento', en: ['the overcrowding'], gloss: { de: ['die Überfüllung'], es: ['la masificación'], fr: ['la surpopulation'], pt: ['a superlotação'] }, pos: 'noun', level: 'B2', category: 'urban' },
    { id: 'it4v118', de: 'la sosta', en: ['the parking', 'the stopping'], gloss: { de: ['das Parken'], es: ['el estacionamiento'], fr: ['le stationnement'], pt: ['o estacionamento'] }, pos: 'noun', level: 'B2', category: 'urban' },
    { id: 'it4v119', de: 'il degrado', en: ['the decay', 'the deterioration'], gloss: { de: ['der Verfall'], es: ['el deterioro'], fr: ['la dégradation'], pt: ['a degradação'] }, pos: 'noun', level: 'B2', category: 'urban' },
    { id: 'it4v120', de: 'la riqualificazione', en: ['the redevelopment'], gloss: { de: ['die Sanierung'], es: ['la rehabilitación'], fr: ['la requalification'], pt: ['a requalificação'] }, pos: 'noun', level: 'B2', category: 'urban' },
    { id: 'it4v121', de: 'abitabile', en: ['habitable', 'livable'], gloss: { de: ['bewohnbar'], es: ['habitable'], fr: ['habitable'], pt: ['habitável'] }, pos: 'adj', level: 'B2', category: 'urban' },
    { id: 'it4v122', de: 'sorgere', en: ['to spring up', 'to arise'], gloss: { de: ['entstehen'], es: ['surgir'], fr: ['surgir'], pt: ['surgir'] }, pos: 'verb', level: 'B2', category: 'urban' },
    // ── arts & criticism ──────────────────────────────────────────────────
    { id: 'it4v123', de: 'il capolavoro', en: ['the masterpiece'], gloss: { de: ['das Meisterwerk'], es: ['la obra maestra'], fr: ['le chef-d’œuvre'], pt: ['a obra-prima'] }, pos: 'noun', level: 'B2', category: 'arts' },
    { id: 'it4v124', de: 'la sceneggiatura', en: ['the screenplay'], gloss: { de: ['das Drehbuch'], es: ['el guión'], fr: ['le scénario'], pt: ['o roteiro'] }, pos: 'noun', level: 'B2', category: 'arts' },
    { id: 'it4v125', de: 'la regia', en: ['the directing'], gloss: { de: ['die Regie'], es: ['la dirección'], fr: ['la mise en scène'], pt: ['a direção'] }, pos: 'noun', level: 'B2', category: 'arts' },
    { id: 'it4v126', de: 'l’interpretazione', en: ['the performance', 'the interpretation'], gloss: { de: ['die Darstellung'], es: ['la interpretación'], fr: ['l’interprétation'], pt: ['a interpretação'] }, pos: 'noun', gender: 'f', level: 'B2', category: 'arts' },
    { id: 'it4v127', de: 'la recensione', en: ['the review'], gloss: { de: ['die Rezension'], es: ['la reseña'], fr: ['la critique'], pt: ['a resenha'] }, pos: 'noun', level: 'B2', category: 'arts' },
    { id: 'it4v128', de: 'lo spettatore', en: ['the viewer', 'the spectator'], gloss: { de: ['der Zuschauer'], es: ['el espectador'], fr: ['le spectateur'], pt: ['o espectador'] }, pos: 'noun', level: 'B2', category: 'arts' },
    { id: 'it4v129', de: 'il tono', en: ['the tone'], gloss: { de: ['der Ton'], es: ['el tono'], fr: ['le ton'], pt: ['o tom'] }, pos: 'noun', level: 'B2', category: 'arts' },
    { id: 'it4v130', de: 'il ritmo', en: ['the pace', 'the rhythm'], gloss: { de: ['das Tempo'], es: ['el ritmo'], fr: ['le rythme'], pt: ['o ritmo'] }, pos: 'noun', level: 'B2', category: 'arts' },
    { id: 'it4v131', de: 'avvincente', en: ['gripping', 'compelling'], gloss: { de: ['fesselnd'], es: ['apasionante'], fr: ['captivant'], pt: ['envolvente'] }, pos: 'adj', level: 'B2', category: 'arts' },
    { id: 'it4v132', de: 'banale', en: ['trite', 'banal'], gloss: { de: ['banal'], es: ['banal'], fr: ['banal'], pt: ['banal'] }, pos: 'adj', level: 'B2', category: 'arts' },
    { id: 'it4v133', de: 'impegnativo', en: ['demanding', 'challenging'], gloss: { de: ['anspruchsvoll'], es: ['exigente'], fr: ['exigeant'], pt: ['exigente'] }, pos: 'adj', level: 'B2', category: 'arts' },
    { id: 'it4v134', de: 'suggestivo', en: ['evocative', 'atmospheric'], gloss: { de: ['stimmungsvoll'], es: ['evocador'], fr: ['évocateur'], pt: ['evocativo'] }, pos: 'adj', level: 'B2', category: 'arts' },
    // ── advanced connectors ───────────────────────────────────────────────
    { id: 'it4v135', de: 'nondimeno', en: ['nonetheless'], gloss: { de: ['nichtsdestoweniger'], es: ['no obstante'], fr: ['néanmoins'], pt: ['não obstante'] }, pos: 'conj', level: 'B2', category: 'connectors' },
    { id: 'it4v136', de: 'purché', en: ['provided that'], gloss: { de: ['vorausgesetzt, dass'], es: ['siempre que'], fr: ['pourvu que'], pt: ['contanto que'] }, pos: 'conj', level: 'B2', category: 'connectors' },
    { id: 'it4v137', de: 'qualora', en: ['should it be that', 'in the event that'], gloss: { de: ['falls'], es: ['en caso de que'], fr: ['au cas où'], pt: ['caso'] }, pos: 'conj', level: 'B2', category: 'connectors' },
    { id: 'it4v138', de: 'dato che', en: ['given that'], gloss: { de: ['da'], es: ['dado que'], fr: ['étant donné que'], pt: ['dado que'] }, pos: 'conj', level: 'B2', category: 'connectors' },
    { id: 'it4v139', de: 'anziché', en: ['rather than'], gloss: { de: ['anstatt'], es: ['en lugar de'], fr: ['plutôt que'], pt: ['em vez de'] }, pos: 'conj', level: 'B2', category: 'connectors' },
    { id: 'it4v140', de: 'pertanto', en: ['therefore', 'consequently'], gloss: { de: ['daher'], es: ['por consiguiente'], fr: ['par conséquent'], pt: ['por conseguinte'] }, pos: 'conj', level: 'B2', category: 'connectors' },
    { id: 'it4v141', de: 'eppure', en: ['and yet'], gloss: { de: ['und doch'], es: ['y sin embargo'], fr: ['et pourtant'], pt: ['e no entanto'] }, pos: 'conj', level: 'B2', category: 'connectors' },
    { id: 'it4v142', de: 'malgrado', en: ['despite', 'in spite of'], gloss: { de: ['trotz'], es: ['a pesar de'], fr: ['malgré'], pt: ['apesar de'] }, pos: 'prep', level: 'B2', category: 'connectors' },
    { id: 'it4v143', de: 'seppure', en: ['even if', 'albeit'], gloss: { de: ['wenn auch'], es: ['aunque'], fr: ['même si'], pt: ['ainda que'] }, pos: 'conj', level: 'B2', category: 'connectors' },
    { id: 'it4v144', de: 'ossia', en: ['that is to say'], gloss: { de: ['das heißt'], es: ['o sea'], fr: ['c’est-à-dire'], pt: ['ou seja'] }, pos: 'conj', level: 'B2', category: 'connectors' },
    { id: 'it4v145', de: 'viceversa', en: ['vice versa', 'conversely'], gloss: { de: ['umgekehrt'], es: ['viceversa'], fr: ['inversement'], pt: ['vice-versa'] }, pos: 'adv', level: 'B2', category: 'connectors' },
    { id: 'it4v146', de: 'per giunta', en: ['on top of that'], gloss: { de: ['obendrein'], es: ['por añadidura'], fr: ['de surcroît'], pt: ['ainda por cima'] }, pos: 'phrase', level: 'B2', category: 'connectors' },
    { id: 'it4v147', de: 'infatti', en: ['indeed', 'in fact'], gloss: { de: ['tatsächlich'], es: ['de hecho'], fr: ['en effet'], pt: ['de fato'] }, pos: 'adv', level: 'B2', category: 'connectors' },
    { id: 'it4v148', de: 'a patto che', en: ['on condition that'], gloss: { de: ['unter der Bedingung, dass'], es: ['a condición de que'], fr: ['à condition que'], pt: ['com a condição de que'] }, pos: 'conj', level: 'B2', category: 'connectors' },
    // ── idioms & collocations ─────────────────────────────────────────────
    { id: 'it4v149', de: 'dare per scontato', en: ['to take for granted'], gloss: { de: ['als selbstverständlich ansehen'], es: ['dar por sentado'], fr: ['tenir pour acquis'], pt: ['dar por certo'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
    { id: 'it4v150', de: 'mettere in discussione', en: ['to call into question'], gloss: { de: ['infrage stellen'], es: ['poner en tela de juicio'], fr: ['remettre en question'], pt: ['pôr em causa'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
    { id: 'it4v151', de: 'prendere le distanze', en: ['to distance oneself'], gloss: { de: ['sich distanzieren'], es: ['distanciarse'], fr: ['prendre ses distances'], pt: ['distanciar-se'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
    { id: 'it4v152', de: 'trovare un punto d’incontro', en: ['to find common ground'], gloss: { de: ['eine gemeinsame Basis finden'], es: ['encontrar un punto en común'], fr: ['trouver un terrain d’entente'], pt: ['encontrar um ponto em comum'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
    { id: 'it4v153', de: 'a lungo andare', en: ['in the long run'], gloss: { de: ['auf Dauer'], es: ['a la larga'], fr: ['à la longue'], pt: ['a longo prazo'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
    { id: 'it4v154', de: 'in linea di massima', en: ['broadly speaking'], gloss: { de: ['im Großen und Ganzen'], es: ['en líneas generales'], fr: ['dans les grandes lignes'], pt: ['em linhas gerais'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
    { id: 'it4v155', de: 'a maggior ragione', en: ['all the more so'], gloss: { de: ['erst recht'], es: ['con mayor razón'], fr: ['à plus forte raison'], pt: ['com mais razão'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
    { id: 'it4v156', de: 'tenere conto di', en: ['to take into account'], gloss: { de: ['berücksichtigen'], es: ['tener en cuenta'], fr: ['tenir compte de'], pt: ['levar em conta'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
    { id: 'it4v157', de: 'saltare agli occhi', en: ['to be glaringly obvious'], gloss: { de: ['ins Auge springen'], es: ['saltar a la vista'], fr: ['sauter aux yeux'], pt: ['saltar aos olhos'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
    { id: 'it4v158', de: 'in fin dei conti', en: ['after all', 'at the end of the day'], gloss: { de: ['letzten Endes'], es: ['al fin y al cabo'], fr: ['en fin de compte'], pt: ['no fim das contas'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
    { id: 'it4v159', de: 'a quanto pare', en: ['apparently'], gloss: { de: ['anscheinend'], es: ['por lo visto'], fr: ['apparemment'], pt: ['pelo visto'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
    { id: 'it4v160', de: 'dare adito a', en: ['to give rise to'], gloss: { de: ['Anlass geben zu'], es: ['dar lugar a'], fr: ['donner lieu à'], pt: ['dar azo a'] }, pos: 'phrase', level: 'B2', category: 'idioms' },
];
