export const metadata = {
  title: 'Terms of Use',
  description: 'LangPass terms: a general wellness companion, not a medical device. Subscriptions, acceptable use, and your responsibilities.',
  alternates: { canonical: '/terms' },
};

// LangPass terms of use — wellness positioning, medical disclaimer, AI limitations,
// subscriptions, acceptable use.
const C = { ink: '#14110E', soft: '#6B6258', paper: '#F6F3EE', line: '#E7E1D8', accent: '#C8553D' };

const S = {
  h2: { fontFamily: 'Georgia, serif', fontSize: 24, margin: '36px 0 12px', color: C.ink } as const,
  p: { lineHeight: 1.65, color: C.soft, margin: '0 0 12px' } as const,
  li: { lineHeight: 1.65, color: C.soft, marginBottom: 8 } as const,
};

export default function TermsOfUsePage() {
  return (
    <main style={{ minHeight: '100vh', background: C.paper, padding: '64px 24px', fontFamily: 'ui-sans-serif, system-ui' }}>
      <div style={{ maxWidth: 760, margin: '0 auto' }}>
        <div style={{ fontSize: 12, letterSpacing: 2, textTransform: 'uppercase', color: C.accent, fontWeight: 700 }}>LangPass</div>
        <h1 style={{ fontFamily: 'Georgia, serif', fontSize: 40, margin: '4px 0 8px', color: C.ink }}>Terms of Use</h1>
        <p style={{ ...S.p, fontSize: 14 }}>Last updated: June 16, 2026</p>

        <h2 style={S.h2}>1. What LangPass is — and is not</h2>
        <p style={S.p}>
          LangPass is a general wellness companion that helps you build healthy recovery habits: tracking
          how you feel, suggesting gentle exercise routines, and encouraging consistency. LangPass is
          <strong style={{ color: C.ink }}> not a medical device</strong> and does not provide medical
          advice. It does not diagnose, treat, cure, or prevent any disease or condition, and it is not
          a substitute for the care of a physician, physiotherapist, or other qualified professional.
        </p>
        <ul style={{ paddingLeft: 22 }}>
          <li style={S.li}>Always consult a healthcare professional about an injury, and follow their guidance over anything the app suggests.</li>
          <li style={S.li}>Stop any activity that causes sharp or worsening pain.</li>
          <li style={S.li}>Seek prompt medical attention for serious symptoms (severe pain, spreading numbness or tingling, significant swelling, fever, chest pain, or injuries from major trauma). In an emergency, call your local emergency number.</li>
        </ul>

        <h2 style={S.h2}>2. AI-generated content</h2>
        <p style={S.p}>
          Conversations, plans, and illustrations in LangPass are generated by artificial intelligence
          based on the information you provide. AI output can be incomplete, imprecise, or wrong for
          your specific situation. You are responsible for using your own judgment — and your
          clinician’s advice — when deciding what physical activity is appropriate for you.
        </p>

        <h2 style={S.h2}>3. Assumption of risk</h2>
        <p style={S.p}>
          Physical exercise carries inherent risk of injury. By using LangPass you confirm you are
          voluntarily choosing to perform any suggested activity at your own risk, and that you have had
          the opportunity to consult a professional about your condition. To the maximum extent
          permitted by law, LangPass and its creators are not liable for injuries or damages arising from
          your use of the app’s suggestions.
        </p>

        <h2 style={S.h2}>4. Subscriptions &amp; auto-renewal</h2>
        <p style={S.p}>
          LangPass offers an optional auto-renewing subscription, <strong style={{ color: C.ink }}>LangPass+</strong>,
          available as a monthly or yearly plan. The free tier includes a daily conversation limit and one
          tracked injury; new users also get a one-week introductory period of full access. The exact
          title, length, and price of each plan — in your local currency — are shown in the app before you
          purchase.
        </p>
        <p style={S.p}>
          Payment will be charged to your Apple ID account at confirmation of purchase. The subscription
          automatically renews unless auto-renew is turned off at least 24 hours before the end of the
          current period. Your account will be charged for renewal — at the price of the plan you
          selected — within 24 hours before the end of the current period. You can manage your
          subscription and turn off auto-renewal in your App Store account settings at any time after
          purchase, and you can restore a previous purchase from the in-app paywall. Any unused portion of
          a free trial period, if offered, is forfeited when you purchase a subscription to that product,
          where applicable. Subscriptions are sold by Apple and managed for us by RevenueCat.
        </p>

        <h2 style={S.h2}>5. Acceptable use</h2>
        <p style={S.p}>
          The recovery companion is provided solely for recovery support. Attempting to misuse it for
          unrelated purposes, to extract harmful content, or to disrupt the service may result in
          limits or termination of access to AI features.
        </p>

        <h2 style={S.h2}>6. Your data</h2>
        <p style={S.p}>
          Your recovery data lives on your device and is yours. See the{' '}
          <a href="/privacy" style={{ color: C.accent }}>Privacy Policy</a> for exactly what is and
          isn’t processed by our systems. You are responsible for backups of your device; deleting the
          app deletes your data.
        </p>

        <h2 style={S.h2}>7. Intellectual property</h2>
        <p style={S.p}>
          The app, its design, and generated illustrations are provided for your personal,
          non-commercial use within the app experience.
        </p>

        <h2 style={S.h2}>8. Changes, termination & governing law</h2>
        <p style={S.p}>
          We may update these terms; material changes will be shown in the app before they take effect.
          Continued use after changes means acceptance. These terms are governed by the laws of Germany,
          without prejudice to any mandatory consumer-protection rights you have where you live. If any
          provision is found unenforceable, the remainder stays in effect. LangPass is operated from
          Germany. Contact: legal@langpass.app.
        </p>

        <div style={{ borderTop: `1px solid ${C.line}`, marginTop: 40, paddingTop: 16, fontSize: 13, color: C.soft }}>
          Be kind to your body. LangPass · <a href="/privacy" style={{ color: C.accent }}>Privacy Policy</a>
        </div>
      </div>
    </main>
  );
}
