import type { SentenceItem } from './types';

// A1 sentences for cloze exercises. clozeIndex points at the word worth testing
// (verb conjugation, article, preposition) — never a boring filler word.

export const A1_SENTENCES: SentenceItem[] = [
  { id: 's001', de: 'Ich trinke jeden Morgen Kaffee.', en: 'I drink coffee every morning.', level: 'A1', clozeIndex: 1, clozeDistractors: ['trinkst', 'trinkt', 'trinken'] },
  { id: 's002', de: 'Wir wohnen in Berlin.', en: 'We live in Berlin.', level: 'A1', clozeIndex: 1, clozeDistractors: ['wohne', 'wohnt', 'wohnst'] },
  { id: 's003', de: 'Er hat einen Hund.', en: 'He has a dog.', level: 'A1', clozeIndex: 1, clozeDistractors: ['habe', 'hast', 'haben'] },
  { id: 's004', de: 'Das Wetter ist heute schön.', en: 'The weather is nice today.', level: 'A1', clozeIndex: 2, clozeDistractors: ['sind', 'bist', 'seid'] },
  { id: 's005', de: 'Ich gehe morgen zur Arbeit.', en: 'I am going to work tomorrow.', level: 'A1', clozeIndex: 3, clozeDistractors: ['zum', 'nach', 'bei'] },
  { id: 's006', de: 'Sie isst gern Brot mit Käse.', en: 'She likes eating bread with cheese.', level: 'A1', clozeIndex: 1, clozeDistractors: ['esse', 'essen', 'esst'] },
  { id: 's007', de: 'Wie viel kostet das Buch?', en: 'How much does the book cost?', level: 'A1', clozeIndex: 3, clozeDistractors: ['der', 'die', 'den'] },
  { id: 's008', de: 'Der Zug kommt um acht Uhr.', en: 'The train arrives at eight o’clock.', level: 'A1', clozeIndex: 3, clozeDistractors: ['am', 'im', 'auf'] },
  { id: 's009', de: 'Ich habe zwei Schwestern.', en: 'I have two sisters.', level: 'A1', clozeIndex: 1, clozeDistractors: ['bin', 'hat', 'haben'] },
  { id: 's010', de: 'Kannst du mir helfen?', en: 'Can you help me?', level: 'A1', clozeIndex: 2, clozeDistractors: ['mich', 'dir', 'ich'] },
  { id: 's011', de: 'Wir fahren am Wochenende nach München.', en: 'We are driving to Munich on the weekend.', level: 'A1', clozeIndex: 4, clozeDistractors: ['zu', 'in', 'bei'] },
  { id: 's012', de: 'Das Kind spielt im Garten.', en: 'The child is playing in the garden.', level: 'A1', clozeIndex: 3, clozeDistractors: ['am', 'um', 'ins'] },
  { id: 's013', de: 'Ich möchte einen Tee, bitte.', en: 'I would like a tea, please.', level: 'A1', clozeIndex: 2, clozeDistractors: ['ein', 'eine', 'einem'] },
  { id: 's014', de: 'Mein Vater arbeitet in einem Büro.', en: 'My father works in an office.', level: 'A1', clozeIndex: 2, clozeDistractors: ['arbeite', 'arbeitest', 'arbeiten'] },
  { id: 's015', de: 'Sprichst du Deutsch?', en: 'Do you speak German?', level: 'A1', clozeIndex: 0, clozeDistractors: ['Spreche', 'Spricht', 'Sprechen'] },
  { id: 's016', de: 'Die Katze schläft auf dem Bett.', en: 'The cat is sleeping on the bed.', level: 'A1', clozeIndex: 4, clozeDistractors: ['das', 'der', 'den'] },
  { id: 's017', de: 'Ich verstehe die Frage nicht.', en: 'I don’t understand the question.', level: 'A1', clozeIndex: 4, clozeDistractors: ['kein', 'nichts', 'nein'] },
  { id: 's018', de: 'Wo ist der Bahnhof?', en: 'Where is the train station?', level: 'A1', clozeIndex: 0, clozeDistractors: ['Was', 'Wer', 'Wann'] },
  { id: 's019', de: 'Wir lernen zusammen Deutsch.', en: 'We are learning German together.', level: 'A1', clozeIndex: 1, clozeDistractors: ['lerne', 'lernt', 'lernst'] },
  { id: 's020', de: 'Sie kauft Milch im Supermarkt.', en: 'She buys milk at the supermarket.', level: 'A1', clozeIndex: 1, clozeDistractors: ['kaufe', 'kaufen', 'kaufst'] },
  { id: 's021', de: 'Heute ist das Wetter kalt.', en: 'Today the weather is cold.', level: 'A1', clozeIndex: 4, clozeDistractors: ['kalte', 'kalter', 'kaltes'] },
  { id: 's022', de: 'Ich lese gern Bücher.', en: 'I like reading books.', level: 'A1', clozeIndex: 2, clozeDistractors: ['gut', 'viel', 'schnell'] },
  { id: 's023', de: 'Er fährt mit dem Bus zur Schule.', en: 'He takes the bus to school.', level: 'A1', clozeIndex: 1, clozeDistractors: ['fahre', 'fährst', 'fahren'] },
  { id: 's024', de: 'Wir haben heute keine Zeit.', en: 'We have no time today.', level: 'A1', clozeIndex: 3, clozeDistractors: ['nicht', 'kein', 'nein'] },
  { id: 's025', de: 'Das Essen schmeckt sehr gut.', en: 'The food tastes very good.', level: 'A1', clozeIndex: 2, clozeDistractors: ['schmecke', 'schmeckst', 'schmecken'] },
  { id: 's026', de: 'Ich stehe um sieben Uhr auf.', en: 'I get up at seven o’clock.', level: 'A1', clozeIndex: 5, clozeDistractors: ['an', 'aus', 'ab'] },
  { id: 's027', de: 'Meine Mutter kocht das Abendessen.', en: 'My mother is cooking dinner.', level: 'A1', clozeIndex: 0, clozeDistractors: ['Mein', 'Meiner', 'Meinem'] },
  { id: 's028', de: 'Der Kaffee ist zu heiß.', en: 'The coffee is too hot.', level: 'A1', clozeIndex: 3, clozeDistractors: ['sehr', 'so', 'mehr'] },
  { id: 's029', de: 'Ich brauche einen neuen Schlüssel.', en: 'I need a new key.', level: 'A1', clozeIndex: 1, clozeDistractors: ['brauchst', 'braucht', 'brauchen'] },
  { id: 's030', de: 'Am Montag gehe ich zum Arzt.', en: 'On Monday I am going to the doctor.', level: 'A1', clozeIndex: 4, clozeDistractors: ['zur', 'nach', 'im'] },
  { id: 's031', de: 'Das ist mein bester Freund.', en: 'That is my best friend.', level: 'A1', clozeIndex: 2, clozeDistractors: ['meine', 'meinen', 'meinem'] },
  { id: 's032', de: 'Wir sehen heute Abend einen Film.', en: 'We are watching a movie tonight.', level: 'A1', clozeIndex: 1, clozeDistractors: ['sehe', 'sieht', 'siehst'] },
  { id: 's033', de: 'Sie schreibt eine E-Mail an ihre Freundin.', en: 'She is writing an email to her friend.', level: 'A1', clozeIndex: 1, clozeDistractors: ['schreibe', 'schreiben', 'schreibst'] },
  { id: 's034', de: 'Ich bin sehr müde.', en: 'I am very tired.', level: 'A1', clozeIndex: 1, clozeDistractors: ['bist', 'ist', 'sind'] },
  { id: 's035', de: 'Das Hotel ist neben dem Bahnhof.', en: 'The hotel is next to the train station.', level: 'A1', clozeIndex: 3, clozeDistractors: ['zwischen', 'hinter', 'für'] },
  { id: 's036', de: 'Ich spreche ein bisschen Deutsch.', en: 'I speak a little German.', level: 'A1', clozeIndex: 1, clozeDistractors: ['sprichst', 'spricht', 'sprechen'] },
  { id: 's037', de: 'Der Apfel liegt auf dem Tisch.', en: 'The apple is (lying) on the table.', level: 'A1', clozeIndex: 3, clozeDistractors: ['unter', 'über', 'im'] },
  { id: 's038', de: 'Wann beginnt der Kurs?', en: 'When does the course begin?', level: 'A1', clozeIndex: 0, clozeDistractors: ['Wo', 'Wie', 'Wer'] },
  { id: 's039', de: 'Es regnet den ganzen Tag.', en: 'It is raining all day.', level: 'A1', clozeIndex: 1, clozeDistractors: ['regnen', 'regnest', 'geregnet'] },
  { id: 's040', de: 'Ich helfe meiner Schwester.', en: 'I am helping my sister.', level: 'A1', clozeIndex: 2, clozeDistractors: ['meine', 'meinem', 'mein'] },
];
