import type { SentenceItem } from './types';

// A2 sentences: past tense creeps in, subordinate clauses appear, real
// situations (travel, health, work). clozeIndex picks the load-bearing word.

export const A2_SENTENCES: SentenceItem[] = [
  { id: 'a2s001', de: 'Ich bin heute um sieben Uhr aufgestanden.', en: 'I got up at seven o’clock today.', gloss: { es: 'Hoy me levanté a las siete.', fr: 'Aujourd’hui je me suis levé à sept heures.', it: 'Oggi mi sono alzato alle sette.', pt: 'Hoje eu levantei às sete horas.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['eingeschlafen', 'angekommen', 'ausgegangen'] },
  { id: 'a2s002', de: 'Der Zug hat zwanzig Minuten Verspätung.', en: 'The train is twenty minutes late.', gloss: { es: 'El tren lleva veinte minutos de retraso.', fr: 'Le train a vingt minutes de retard.', it: 'Il treno ha venti minuti di ritardo.', pt: 'O trem está vinte minutos atrasado.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['Gepäck', 'Gleis', 'Pause'] },
  { id: 'a2s003', de: 'Wir müssen in Köln umsteigen.', en: 'We have to change trains in Cologne.', gloss: { es: 'Tenemos que hacer transbordo en Colonia.', fr: 'Nous devons changer de train à Cologne.', it: 'Dobbiamo cambiare treno a Colonia.', pt: 'Temos que trocar de trem em Colônia.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['einkaufen', 'aufstehen', 'anrufen'] },
  { id: 'a2s004', de: 'Ich habe starke Schmerzen im Rücken.', en: 'I have bad pain in my back.', gloss: { es: 'Tengo mucho dolor de espalda.', fr: 'J’ai de fortes douleurs au dos.', it: 'Ho forti dolori alla schiena.', pt: 'Estou com muita dor nas costas.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['Wolken', 'Aufgaben', 'Angebote'] },
  { id: 'a2s005', de: 'Kann ich einen Termin für morgen bekommen?', en: 'Can I get an appointment for tomorrow?', gloss: { es: '¿Puedo conseguir una cita para mañana?', fr: 'Puis-je avoir un rendez-vous pour demain ?', it: 'Posso avere un appuntamento per domani?', pt: 'Posso conseguir um horário para amanhã?' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['Schlüssel', 'Mantel', 'Kunden'] },
  { id: 'a2s006', de: 'Morgen soll es den ganzen Tag regnen.', en: 'It is supposed to rain all day tomorrow.', gloss: { es: 'Mañana va a llover todo el día.', fr: 'Demain il doit pleuvoir toute la journée.', it: 'Domani dovrebbe piovere tutto il giorno.', pt: 'Amanhã deve chover o dia todo.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['schneien', 'arbeiten', 'kochen'] },
  { id: 'a2s007', de: 'Gehen Sie geradeaus und dann links.', en: 'Go straight ahead and then left.', gloss: { es: 'Siga todo recto y luego a la izquierda.', fr: 'Allez tout droit puis à gauche.', it: 'Vada dritto e poi a sinistra.', pt: 'Siga em frente e depois à esquerda.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['plötzlich', 'meistens', 'zufrieden'] },
  { id: 'a2s008', de: 'Die Besprechung beginnt um zehn Uhr.', en: 'The meeting starts at ten o’clock.', gloss: { es: 'La reunión empieza a las diez.', fr: 'La réunion commence à dix heures.', it: 'La riunione comincia alle dieci.', pt: 'A reunião começa às dez horas.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['Erkältung', 'Wohnung', 'Fahrkarte'] },
  { id: 'a2s009', de: 'Nach der Arbeit habe ich endlich Feierabend.', en: 'After work I finally have my evening off.', gloss: { es: 'Después del trabajo por fin tengo la tarde libre.', fr: 'Après le travail, j’ai enfin ma soirée libre.', it: 'Dopo il lavoro finalmente ho la serata libera.', pt: 'Depois do trabalho finalmente tenho a noite livre.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['Fieber', 'Gewitter', 'Gepäck'] },
  { id: 'a2s010', de: 'Kann ich diese Jacke bitte anprobieren?', en: 'Can I try on this jacket, please?', gloss: { es: '¿Puedo probarme esta chaqueta, por favor?', fr: 'Puis-je essayer cette veste, s’il vous plaît ?', it: 'Posso provare questa giacca, per favore?', pt: 'Posso experimentar esta jaqueta, por favor?' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['umtauschen', 'verdienen', 'verpassen'] },
  { id: 'a2s011', de: 'Die Wohnung ist schön, aber die Miete ist zu hoch.', en: 'The apartment is nice, but the rent is too high.', gloss: { es: 'El piso es bonito, pero el alquiler es demasiado alto.', fr: 'L’appartement est joli, mais le loyer est trop élevé.', it: 'L’appartamento è bello, ma l’affitto è troppo alto.', pt: 'O apartamento é bonito, mas o aluguel é caro demais.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['Größe', 'Ampel', 'Pause'] },
  { id: 'a2s012', de: 'Ich habe gestern meinen Schlüssel verloren.', en: 'I lost my key yesterday.', gloss: { es: 'Ayer perdí mi llave.', fr: 'Hier j’ai perdu ma clé.', it: 'Ieri ho perso la mia chiave.', pt: 'Ontem eu perdi minha chave.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['Nachbarn', 'Kaffee', 'Regen'] },
  { id: 'a2s013', de: 'Er ist enttäuscht, weil das Spiel verloren ging.', en: 'He is disappointed because the game was lost.', gloss: { es: 'Está decepcionado porque perdieron el partido.', fr: 'Il est déçu parce que le match a été perdu.', it: 'È deluso perché la partita è stata persa.', pt: 'Ele está decepcionado porque o jogo foi perdido.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['stolz', 'gelangweilt', 'überrascht'] },
  { id: 'a2s014', de: 'Ich freue mich auf das Wochenende.', en: 'I am looking forward to the weekend.', gloss: { es: 'Tengo ganas de que llegue el fin de semana.', fr: 'J’ai hâte du week-end.', it: 'Non vedo l’ora del fine settimana.', pt: 'Estou ansioso pelo fim de semana.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['ärgere', 'erinnere', 'kümmere'] },
  { id: 'a2s015', de: 'Wir sind letztes Jahr nach Spanien gereist.', en: 'We travelled to Spain last year.', gloss: { es: 'El año pasado viajamos a España.', fr: 'L’année dernière, nous avons voyagé en Espagne.', it: 'L’anno scorso abbiamo viaggiato in Spagna.', pt: 'No ano passado nós viajamos para a Espanha.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['gearbeitet', 'gekocht', 'geblieben'] },
  { id: 'a2s016', de: 'Meistens frühstücke ich nur einen Kaffee.', en: 'Usually I just have a coffee for breakfast.', gloss: { es: 'Normalmente solo desayuno un café.', fr: 'D’habitude je ne prends qu’un café au petit-déjeuner.', it: 'Di solito faccio colazione solo con un caffè.', pt: 'Geralmente eu só tomo um café no café da manhã.' }, level: 'A2', clozeIndex: 0, clozeDistractors: ['Selten', 'Sofort', 'Übermorgen'] },
  { id: 'a2s017', de: 'Der Kühlschrank ist schon wieder leer.', en: 'The fridge is empty again already.', gloss: { es: 'La nevera está otra vez vacía.', fr: 'Le frigo est de nouveau vide.', it: 'Il frigo è di nuovo vuoto.', pt: 'A geladeira está vazia de novo.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['Stadtplan', 'Feierabend', 'Bahnhof'] },
  { id: 'a2s018', de: 'Sie hat sich um die neue Stelle beworben.', en: 'She applied for the new position.', gloss: { es: 'Solicitó el nuevo puesto.', fr: 'Elle a postulé pour le nouveau poste.', it: 'Si è candidata per il nuovo posto.', pt: 'Ela se candidatou à nova vaga.' }, level: 'A2', clozeIndex: 7, clozeDistractors: ['gekümmert', 'gefreut', 'erinnert'] },
  { id: 'a2s019', de: 'Ohne Rezept bekommen Sie dieses Medikament nicht.', en: 'You won’t get this medicine without a prescription.', gloss: { es: 'Sin receta no puede conseguir este medicamento.', fr: 'Sans ordonnance, vous n’obtiendrez pas ce médicament.', it: 'Senza ricetta non può avere questo medicinale.', pt: 'Sem receita você não consegue este medicamento.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['Gehalt', 'Angebot', 'Gewitter'] },
  { id: 'a2s020', de: 'Plötzlich hat es angefangen zu schneien.', en: 'Suddenly it started to snow.', gloss: { es: 'De repente empezó a nevar.', fr: 'Soudain, il a commencé à neiger.', it: 'All’improvviso ha cominciato a nevicare.', pt: 'De repente começou a nevar.' }, level: 'A2', clozeIndex: 0, clozeDistractors: ['Geradeaus', 'Zufrieden', 'Meistens'] },
  { id: 'a2s021', de: 'Wir ziehen nächsten Monat in eine größere Wohnung um.', en: 'We are moving to a bigger apartment next month.', gloss: { es: 'El mes que viene nos mudamos a un piso más grande.', fr: 'Le mois prochain, nous déménageons dans un appartement plus grand.', it: 'Il mese prossimo ci trasferiamo in un appartamento più grande.', pt: 'No mês que vem vamos nos mudar para um apartamento maior.' }, level: 'A2', clozeIndex: 8, clozeDistractors: ['an', 'aus', 'auf'] },
  { id: 'a2s022', de: 'An der Kasse war eine lange Schlange.', en: 'There was a long queue at the checkout.', gloss: { es: 'En la caja había una cola larga.', fr: 'Il y avait une longue file à la caisse.', it: 'Alla cassa c’era una lunga fila.', pt: 'Havia uma fila longa no caixa.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['Ampel', 'Brücke', 'Heizung'] },
];
