import type { SentenceItem } from './types';

// B1 sentences: subordinate clauses, Konjunktiv creeping in, opinions and
// real argumentation. clozeIndex targets connectors and load-bearing verbs.

export const B1_SENTENCES: SentenceItem[] = [
  { id: 'b1s001', de: 'Obwohl es regnete, sind wir wandern gegangen.', en: 'Although it was raining, we went hiking.', gloss: { es: 'Aunque llovía, fuimos de excursión.', fr: 'Même s’il pleuvait, nous sommes allés faire une randonnée.', it: 'Anche se pioveva, siamo andati a fare un’escursione.', pt: 'Embora estivesse chovendo, fomos fazer uma trilha.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Trotzdem', 'Deshalb', 'Außerdem'] },
  { id: 'b1s002', de: 'Meiner Meinung nach ist das keine gute Idee.', en: 'In my opinion, that is not a good idea.', gloss: { es: 'En mi opinión, no es una buena idea.', fr: 'À mon avis, ce n’est pas une bonne idée.', it: 'Secondo me, non è una buona idea.', pt: 'Na minha opinião, isso não é uma boa ideia.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['Erfahrung', 'Regierung', 'Beziehung'] },
  { id: 'b1s003', de: 'Er hat mich überzeugt, obwohl ich skeptisch war.', en: 'He convinced me, although I was sceptical.', gloss: { es: 'Me convenció, aunque yo era escéptico.', fr: 'Il m’a convaincu, même si j’étais sceptique.', it: 'Mi ha convinto, anche se ero scettico.', pt: 'Ele me convenceu, embora eu estivesse cético.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['entlassen', 'verglichen', 'vermisst'] },
  { id: 'b1s004', de: 'Die Regierung hat ein neues Gesetz beschlossen.', en: 'The government passed a new law.', gloss: { es: 'El gobierno ha aprobado una nueva ley.', fr: 'Le gouvernement a adopté une nouvelle loi.', it: 'Il governo ha approvato una nuova legge.', pt: 'O governo aprovou uma nova lei.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['Vertrauen', 'Angebot', 'Verhalten'] },
  { id: 'b1s005', de: 'Wir sollten mehr auf die Umwelt achten.', en: 'We should pay more attention to the environment.', gloss: { es: 'Deberíamos cuidar más el medio ambiente.', fr: 'Nous devrions faire plus attention à l’environnement.', it: 'Dovremmo fare più attenzione all’ambiente.', pt: 'Deveríamos cuidar mais do meio ambiente.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['Wahl', 'Miete', 'Meinung'] },
  { id: 'b1s006', de: 'Je mehr du übst, desto besser wirst du.', en: 'The more you practice, the better you get.', gloss: { es: 'Cuanto más practicas, mejor lo haces.', fr: 'Plus tu t’entraînes, meilleur tu deviens.', it: 'Più ti eserciti, più migliori.', pt: 'Quanto mais você pratica, melhor você fica.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['trotzdem', 'obwohl', 'sondern'] },
  { id: 'b1s007', de: 'Ich habe die Nase voll von diesen Ausreden.', en: 'I am fed up with these excuses.', gloss: { es: 'Estoy harto de estas excusas.', fr: 'J’en ai marre de ces excuses.', it: 'Ne ho abbastanza di queste scuse.', pt: 'Estou de saco cheio dessas desculpas.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['Hand', 'Stirn', 'Zunge'] },
  { id: 'b1s008', de: 'Sie hat sich endlich entschieden, zu kündigen.', en: 'She finally decided to quit.', gloss: { es: 'Por fin ha decidido dejar el trabajo.', fr: 'Elle a enfin décidé de démissionner.', it: 'Alla fine ha deciso di licenziarsi.', pt: 'Ela finalmente decidiu pedir demissão.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['gewöhnt', 'versöhnt', 'verlassen'] },
  { id: 'b1s009', de: 'Es lohnt sich, jeden Tag ein bisschen zu lernen.', en: 'It is worth learning a little every day.', gloss: { es: 'Merece la pena estudiar un poco cada día.', fr: 'Ça vaut la peine d’apprendre un peu chaque jour.', it: 'Vale la pena studiare un po’ ogni giorno.', pt: 'Vale a pena estudar um pouco todo dia.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['trennt', 'erinnert', 'ärgert'] },
  { id: 'b1s010', de: 'Trotzdem hat er sich bei mir entschuldigt.', en: 'Nevertheless, he apologised to me.', gloss: { es: 'Aun así, se disculpó conmigo.', fr: 'Il s’est quand même excusé auprès de moi.', it: 'Nonostante tutto, si è scusato con me.', pt: 'Mesmo assim, ele se desculpou comigo.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Obwohl', 'Deshalb', 'Falls'] },
  { id: 'b1s011', de: 'Man kann sich immer auf sie verlassen.', en: 'You can always rely on her.', gloss: { es: 'Siempre se puede contar con ella.', fr: 'On peut toujours compter sur elle.', it: 'Si può sempre contare su di lei.', pt: 'Sempre se pode contar com ela.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['versöhnen', 'gewöhnen', 'freuen'] },
  { id: 'b1s012', de: 'Nach dem Streit haben sie sich wieder versöhnt.', en: 'After the argument, they made up again.', gloss: { es: 'Después de la discusión, han hecho las paces.', fr: 'Après la dispute, ils se sont réconciliés.', it: 'Dopo il litigio, si sono riconciliati.', pt: 'Depois da briga, eles fizeram as pazes.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['Vorschlag', 'Vorteil', 'Lebenslauf'] },
  { id: 'b1s013', de: 'Im Vorstellungsgespräch war sie sehr überzeugend.', en: 'She was very convincing in the job interview.', gloss: { es: 'En la entrevista de trabajo estuvo muy convincente.', fr: 'Lors de l’entretien d’embauche, elle a été très convaincante.', it: 'Al colloquio di lavoro è stata molto convincente.', pt: 'Na entrevista de emprego, ela foi muito convincente.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['Klimawandel', 'Kühlschrank', 'Feierabend'] },
  { id: 'b1s014', de: 'Wir müssen unnötigen Müll unbedingt vermeiden.', en: 'We absolutely have to avoid unnecessary waste.', gloss: { es: 'Tenemos que evitar sin falta la basura innecesaria.', fr: 'Nous devons absolument éviter les déchets inutiles.', it: 'Dobbiamo assolutamente evitare i rifiuti inutili.', pt: 'Precisamos evitar a todo custo o lixo desnecessário.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['verbrauchen', 'vergleichen', 'verzeihen'] },
  { id: 'b1s015', de: 'Falls du Hilfe brauchst, ruf mich einfach an.', en: 'In case you need help, just call me.', gloss: { es: 'Si necesitas ayuda, llámame sin más.', fr: 'Au cas où tu aurais besoin d’aide, appelle-moi.', it: 'Se hai bisogno di aiuto, chiamami pure.', pt: 'Caso você precise de ajuda, é só me ligar.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Obwohl', 'Deshalb', 'Außerdem'] },
  { id: 'b1s016', de: 'Ich drücke dir für die Prüfung die Daumen.', en: 'I’ll keep my fingers crossed for your exam.', gloss: { es: 'Cruzo los dedos por ti para el examen.', fr: 'Je croise les doigts pour ton examen.', it: 'Incrocio le dita per il tuo esame.', pt: 'Vou torcer por você na prova.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['Hände', 'Finger', 'Ohren'] },
  { id: 'b1s017', de: 'Die Firma hat letzten Monat zwanzig Leute eingestellt.', en: 'The company hired twenty people last month.', gloss: { es: 'La empresa contrató a veinte personas el mes pasado.', fr: 'L’entreprise a embauché vingt personnes le mois dernier.', it: 'L’azienda ha assunto venti persone il mese scorso.', pt: 'A empresa contratou vinte pessoas no mês passado.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['entlassen', 'befördert', 'verglichen'] },
  { id: 'b1s018', de: 'Deshalb verzichte ich dieses Jahr auf Flugreisen.', en: 'That is why I am giving up air travel this year.', gloss: { es: 'Por eso este año renuncio a viajar en avión.', fr: 'C’est pourquoi je renonce aux voyages en avion cette année.', it: 'Perciò quest’anno rinuncio ai viaggi in aereo.', pt: 'Por isso, este ano abro mão de viagens de avião.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['vergesse', 'verbessere', 'vergleiche'] },
  { id: 'b1s019', de: 'Können wir das bitte unter vier Augen besprechen?', en: 'Can we please discuss this in private?', gloss: { es: '¿Podemos hablar de esto a solas, por favor?', fr: 'Pouvons-nous en parler en tête-à-tête, s’il te plaît ?', it: 'Possiamo parlarne a quattr’occhi, per favore?', pt: 'Podemos conversar sobre isso a sós, por favor?' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['Ohren', 'Händen', 'Wänden'] },
  { id: 'b1s020', de: 'Sowohl der Chef als auch die Kollegen waren begeistert.', en: 'Both the boss and the colleagues were thrilled.', gloss: { es: 'Tanto el jefe como los compañeros estaban entusiasmados.', fr: 'Aussi bien le chef que les collègues étaient enthousiastes.', it: 'Sia il capo sia i colleghi erano entusiasti.', pt: 'Tanto o chefe quanto os colegas ficaram entusiasmados.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Weder', 'Entweder', 'Obwohl'] },
];
