import type { SentenceItem } from '@/content/german/types';

// Spanish A1 sentences. `de` holds the Spanish text. clozeIndex targets the
// load-bearing word (never the article), and clozeDistractors are same-class
// words that would be grammatical but wrong — so the exercise tests meaning,
// not pattern-matching on word shape.
//
// `gloss` carries the non-English UI locales; see a1-vocab.ts for the rule.

export const A1_SENTENCES: SentenceItem[] = [
  { id: 'ss001', de: 'Buenos días, ¿qué tal?', en: 'Good morning, how’s it going?', gloss: { de: 'Guten Morgen, wie geht’s?', fr: 'Bonjour, ça va ?', it: 'Buongiorno, come va?', pt: 'Bom dia, tudo bem?' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Buenas', 'Gracias', 'Adiós'] },
  { id: 'ss002', de: 'Quiero un café, por favor.', en: 'I want a coffee, please.', gloss: { de: 'Ich möchte einen Kaffee, bitte.', fr: 'Je veux un café, s’il vous plaît.', it: 'Voglio un caffè, per favore.', pt: 'Quero um café, por favor.' }, level: 'A1', clozeIndex: 2, clozeDistractors: ['pan', 'vino', 'huevo'] },
  { id: 'ss003', de: '¿Dónde está el baño?', en: 'Where is the bathroom?', gloss: { de: 'Wo ist die Toilette?', fr: 'Où sont les toilettes ?', it: 'Dov’è il bagno?', pt: 'Onde fica o banheiro?' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Cuándo', 'Cómo', 'Quién'] },
  { id: 'ss004', de: 'Vivo en Madrid.', en: 'I live in Madrid.', gloss: { de: 'Ich wohne in Madrid.', fr: 'J’habite à Madrid.', it: 'Vivo a Madrid.', pt: 'Moro em Madri.' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Hablo', 'Como', 'Quiero'] },
  { id: 'ss005', de: '¿Cuánto cuesta la cerveza?', en: 'How much does the beer cost?', gloss: { de: 'Wie viel kostet das Bier?', fr: 'Combien coûte la bière ?', it: 'Quanto costa la birra?', pt: 'Quanto custa a cerveja?' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Dónde', 'Quién', 'Cómo'] },
  { id: 'ss006', de: 'La comida está muy buena.', en: 'The food is very good.', gloss: { de: 'Das Essen ist sehr gut.', fr: 'La nourriture est très bonne.', it: 'Il cibo è molto buono.', pt: 'A comida está muito boa.' }, level: 'A1', clozeIndex: 4, clozeDistractors: ['cara', 'fría', 'grande'] },
  { id: 'ss007', de: 'No hablo español muy bien.', en: 'I don’t speak Spanish very well.', gloss: { de: 'Ich spreche nicht sehr gut Spanisch.', fr: 'Je ne parle pas très bien espagnol.', it: 'Non parlo molto bene lo spagnolo.', pt: 'Não falo espanhol muito bem.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['como', 'quiero', 'vivo'] },
  { id: 'ss008', de: 'Hoy voy a trabajar.', en: 'Today I am going to work.', gloss: { de: 'Heute gehe ich arbeiten.', fr: 'Aujourd’hui je vais travailler.', it: 'Oggi vado a lavorare.', pt: 'Hoje eu vou trabalhar.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['comer', 'hablar', 'comprar'] },
  { id: 'ss009', de: 'Ella tiene una hermana pequeña.', en: 'She has a little sister.', gloss: { de: 'Sie hat eine kleine Schwester.', fr: 'Elle a une petite sœur.', it: 'Lei ha una sorella piccola.', pt: 'Ela tem uma irmã pequena.' }, level: 'A1', clozeIndex: 4, clozeDistractors: ['grande', 'bonita', 'cansada'] },
  { id: 'ss010', de: 'Nos gusta la playa.', en: 'We like the beach.', gloss: { de: 'Wir mögen den Strand.', fr: 'Nous aimons la plage.', it: 'Ci piace la spiaggia.', pt: 'Nós gostamos da praia.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['ciudad', 'escuela', 'tienda'] },
  { id: 'ss011', de: 'El restaurante es muy caro.', en: 'The restaurant is very expensive.', gloss: { de: 'Das Restaurant ist sehr teuer.', fr: 'Le restaurant est très cher.', it: 'Il ristorante è molto caro.', pt: 'O restaurante é muito caro.' }, level: 'A1', clozeIndex: 4, clozeDistractors: ['barato', 'pequeño', 'nuevo'] },
  { id: 'ss012', de: 'Mañana voy al mercado.', en: 'Tomorrow I am going to the market.', gloss: { de: 'Morgen gehe ich zum Markt.', fr: 'Demain je vais au marché.', it: 'Domani vado al mercato.', pt: 'Amanhã eu vou ao mercado.' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Ayer', 'Ahora', 'Siempre'] },
  { id: 'ss013', de: 'Mi madre trabaja en una tienda.', en: 'My mother works in a shop.', gloss: { de: 'Meine Mutter arbeitet in einem Laden.', fr: 'Ma mère travaille dans un magasin.', it: 'Mia madre lavora in un negozio.', pt: 'Minha mãe trabalha numa loja.' }, level: 'A1', clozeIndex: 2, clozeDistractors: ['vive', 'come', 'habla'] },
  { id: 'ss014', de: 'No entiendo la pregunta.', en: 'I don’t understand the question.', gloss: { de: 'Ich verstehe die Frage nicht.', fr: 'Je ne comprends pas la question.', it: 'Non capisco la domanda.', pt: 'Não entendo a pergunta.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['hablo', 'quiero', 'tengo'] },
  { id: 'ss015', de: 'La casa es grande y nueva.', en: 'The house is big and new.', gloss: { de: 'Das Haus ist groß und neu.', fr: 'La maison est grande et neuve.', it: 'La casa è grande e nuova.', pt: 'A casa é grande e nova.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['pequeña', 'vieja', 'cara'] },
  { id: 'ss016', de: 'Tengo dos hermanos.', en: 'I have two brothers.', gloss: { de: 'Ich habe zwei Brüder.', fr: 'J’ai deux frères.', it: 'Ho due fratelli.', pt: 'Tenho dois irmãos.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['tres', 'cinco', 'diez'] },
  { id: 'ss017', de: 'El niño bebe leche.', en: 'The boy drinks milk.', gloss: { de: 'Der Junge trinkt Milch.', fr: 'Le garçon boit du lait.', it: 'Il bambino beve il latte.', pt: 'O menino bebe leite.' }, level: 'A1', clozeIndex: 2, clozeDistractors: ['come', 'compra', 'quiere'] },
  { id: 'ss018', de: '¿Por qué estás cansado?', en: 'Why are you tired?', gloss: { de: 'Warum bist du müde?', fr: 'Pourquoi es-tu fatigué ?', it: 'Perché sei stanco?', pt: 'Por que você está cansado?' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['contento', 'nuevo', 'pequeño'] },
  { id: 'ss019', de: 'La cuenta, por favor.', en: 'The bill, please.', gloss: { de: 'Die Rechnung, bitte.', fr: 'L’addition, s’il vous plaît.', it: 'Il conto, per favore.', pt: 'A conta, por favor.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['comida', 'cerveza', 'tienda'] },
  { id: 'ss020', de: 'Siempre como pan por la mañana.', en: 'I always eat bread in the morning.', gloss: { de: 'Ich esse morgens immer Brot.', fr: 'Je mange toujours du pain le matin.', it: 'Mangio sempre pane la mattina.', pt: 'Sempre como pão de manhã.' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Nunca', 'Hoy', 'Ayer'] },
];
