import type { SentenceItem } from '@/content/german/types';

// Spanish A2 sentences. `de` holds the Spanish text. Where A1 stays in the
// present tense with short clauses, A2 tells small stories: preterite for
// completed events, imperfect for background and habits, plus comparatives and
// subordinate clauses ("porque…", "antes de…", "cuando era niño…").
//
// clozeIndex is a 0-based index into de.split(' ') and always targets the
// load-bearing word, never an article. clozeDistractors are same-class words
// that would be grammatical in the slot but wrong in meaning, so the exercise
// tests comprehension rather than word-shape matching.
//
// `gloss` carries the non-English UI locales; see a2-vocab.ts for the rule.

export const A2_SENTENCES: SentenceItem[] = [
  { id: 'es2s001', de: 'Ayer me levanté muy temprano.', en: 'Yesterday I got up very early.', gloss: { de: 'Gestern bin ich sehr früh aufgestanden.', fr: 'Hier je me suis levé très tôt.', it: 'Ieri mi sono alzato molto presto.', pt: 'Ontem eu me levantei muito cedo.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['acosté', 'duché', 'vestí'] },
  { id: 'es2s002', de: 'El tren llegó con media hora de retraso.', en: 'The train arrived half an hour late.', gloss: { de: 'Der Zug kam mit einer halben Stunde Verspätung an.', fr: 'Le train est arrivé avec une demi-heure de retard.', it: 'Il treno è arrivato con mezz’ora di ritardo.', pt: 'O trem chegou com meia hora de atraso.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['salió', 'volvió', 'terminó'] },
  { id: 'es2s003', de: 'Perdí el pasaporte en el aeropuerto.', en: 'I lost my passport at the airport.', gloss: { de: 'Ich habe meinen Reisepass am Flughafen verloren.', fr: 'J’ai perdu mon passeport à l’aéroport.', it: 'Ho perso il passaporto in aeroporto.', pt: 'Perdi o passaporte no aeroporto.' }, level: 'A2', clozeIndex: 0, clozeDistractors: ['Encontré', 'Compré', 'Guardé'] },
  { id: 'es2s004', de: 'Cuando era niño, vivía en el campo.', en: 'When I was a child, I lived in the countryside.', gloss: { de: 'Als ich ein Kind war, wohnte ich auf dem Land.', fr: 'Quand j’étais enfant, j’habitais à la campagne.', it: 'Quando ero bambino, vivevo in campagna.', pt: 'Quando eu era criança, morava no campo.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['trabajaba', 'estudiaba', 'jugaba'] },
  { id: 'es2s005', de: 'Anoche cené con mis compañeros de trabajo.', en: 'Last night I had dinner with my colleagues.', gloss: { de: 'Gestern Abend habe ich mit meinen Arbeitskollegen zu Abend gegessen.', fr: 'Hier soir j’ai dîné avec mes collègues de travail.', it: 'Ieri sera ho cenato con i miei colleghi di lavoro.', pt: 'Ontem à noite jantei com meus colegas de trabalho.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['desayuné', 'trabajé', 'hablé'] },
  { id: 'es2s006', de: 'Este hotel es más barato que el otro.', en: 'This hotel is cheaper than the other one.', gloss: { de: 'Dieses Hotel ist billiger als das andere.', fr: 'Cet hôtel est moins cher que l’autre.', it: 'Questo hotel è più economico dell’altro.', pt: 'Este hotel é mais barato que o outro.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['caro', 'limpio', 'tranquilo'] },
  { id: 'es2s007', de: 'Me duele mucho la cabeza.', en: 'My head hurts a lot.', gloss: { de: 'Mein Kopf tut sehr weh.', fr: 'J’ai très mal à la tête.', it: 'Mi fa molto male la testa.', pt: 'Minha cabeça dói muito.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['espalda', 'mano', 'garganta'] },
  { id: 'es2s008', de: 'Tengo que ir al médico esta tarde.', en: 'I have to go to the doctor this afternoon.', gloss: { de: 'Ich muss heute Nachmittag zum Arzt gehen.', fr: 'Je dois aller chez le médecin cet après-midi.', it: 'Devo andare dal medico questo pomeriggio.', pt: 'Tenho que ir ao médico esta tarde.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['hospital', 'supermercado', 'aeropuerto'] },
  { id: 'es2s009', de: '¿Cuánto costó tu billete de avión?', en: 'How much did your plane ticket cost?', gloss: { de: 'Wie viel hat dein Flugticket gekostet?', fr: 'Combien a coûté ton billet d’avion ?', it: 'Quanto è costato il tuo biglietto aereo?', pt: 'Quanto custou a sua passagem de avião?' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['pagó', 'ganó', 'cambió'] },
  { id: 'es2s010', de: 'Pagué con tarjeta porque no llevaba efectivo.', en: 'I paid by card because I wasn’t carrying any cash.', gloss: { de: 'Ich habe mit Karte bezahlt, weil ich kein Bargeld dabeihatte.', fr: 'J’ai payé par carte parce que je n’avais pas d’espèces.', it: 'Ho pagato con la carta perché non avevo contanti.', pt: 'Paguei com cartão porque não tinha dinheiro em espécie.' }, level: 'A2', clozeIndex: 0, clozeDistractors: ['Compré', 'Gasté', 'Cambié'] },
  { id: 'es2s011', de: 'La reunión empezó a las nueve de la mañana.', en: 'The meeting started at nine in the morning.', gloss: { de: 'Die Besprechung begann um neun Uhr morgens.', fr: 'La réunion a commencé à neuf heures du matin.', it: 'La riunione è cominciata alle nove di mattina.', pt: 'A reunião começou às nove da manhã.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['terminó', 'llegó', 'volvió'] },
  { id: 'es2s012', de: 'Mi jefe me pidió un informe para el viernes.', en: 'My boss asked me for a report by Friday.', gloss: { de: 'Mein Chef hat mich um einen Bericht bis Freitag gebeten.', fr: 'Mon patron m’a demandé un rapport pour vendredi.', it: 'Il mio capo mi ha chiesto una relazione per venerdì.', pt: 'Meu chefe me pediu um relatório para sexta-feira.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['mandó', 'escribió', 'explicó'] },
  { id: 'es2s013', de: 'Estudié en la universidad durante cuatro años.', en: 'I studied at university for four years.', gloss: { de: 'Ich habe vier Jahre lang an der Universität studiert.', fr: 'J’ai étudié à l’université pendant quatre ans.', it: 'Ho studiato all’università per quattro anni.', pt: 'Estudei na universidade durante quatro anos.' }, level: 'A2', clozeIndex: 0, clozeDistractors: ['Trabajé', 'Viví', 'Enseñé'] },
  { id: 'es2s014', de: 'Ayer hacía mucho frío y llovía sin parar.', en: 'Yesterday it was very cold and it rained non-stop.', gloss: { de: 'Gestern war es sehr kalt und es regnete ununterbrochen.', fr: 'Hier il faisait très froid et il pleuvait sans arrêt.', it: 'Ieri faceva molto freddo e pioveva senza sosta.', pt: 'Ontem fazia muito frio e chovia sem parar.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['calor', 'viento', 'sol'] },
  { id: 'es2s015', de: 'El fin de semana pasado fuimos a la playa.', en: 'Last weekend we went to the beach.', gloss: { de: 'Letztes Wochenende sind wir an den Strand gefahren.', fr: 'Le week-end dernier, nous sommes allés à la plage.', it: 'Lo scorso fine settimana siamo andati al mare.', pt: 'No fim de semana passado fomos à praia.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['volvimos', 'salimos', 'llamamos'] },
  { id: 'es2s016', de: 'Me sentía nervioso antes de la entrevista.', en: 'I felt nervous before the interview.', gloss: { de: 'Vor dem Vorstellungsgespräch war ich nervös.', fr: 'Je me sentais nerveux avant l’entretien.', it: 'Mi sentivo nervoso prima del colloquio.', pt: 'Eu me sentia nervoso antes da entrevista.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['tranquilo', 'aburrido', 'ocupado'] },
  { id: 'es2s017', de: 'No encontré las llaves del coche.', en: 'I couldn’t find the car keys.', gloss: { de: 'Ich habe die Autoschlüssel nicht gefunden.', fr: 'Je n’ai pas trouvé les clés de la voiture.', it: 'Non ho trovato le chiavi della macchina.', pt: 'Não encontrei as chaves do carro.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['olvidé', 'guardé', 'compré'] },
  { id: 'es2s018', de: 'La cocina de mi apartamento es muy pequeña.', en: 'The kitchen in my apartment is very small.', gloss: { de: 'Die Küche in meiner Wohnung ist sehr klein.', fr: 'La cuisine de mon appartement est très petite.', it: 'La cucina del mio appartamento è molto piccola.', pt: 'A cozinha do meu apartamento é muito pequena.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['sala', 'ventana', 'puerta'] },
  { id: 'es2s019', de: 'Antes salía con mis amigos todos los sábados.', en: 'I used to go out with my friends every Saturday.', gloss: { de: 'Früher ging ich jeden Samstag mit meinen Freunden aus.', fr: 'Avant, je sortais avec mes amis tous les samedis.', it: 'Prima uscivo con i miei amici tutti i sabati.', pt: 'Antes eu saía com meus amigos todos os sábados.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['cenaba', 'hablaba', 'viajaba'] },
  { id: 'es2s020', de: '¿Tienen esta camisa en otra talla?', en: 'Do you have this shirt in another size?', gloss: { de: 'Haben Sie dieses Hemd in einer anderen Größe?', fr: 'Avez-vous cette chemise dans une autre taille ?', it: 'Avete questa camicia in un’altra taglia?', pt: 'Vocês têm esta camisa em outro tamanho?' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['chaqueta', 'falda', 'blusa'] },
  { id: 'es2s021', de: 'Me olvidé de comprar el pan esta mañana.', en: 'I forgot to buy bread this morning.', gloss: { de: 'Ich habe heute Morgen vergessen, Brot zu kaufen.', fr: 'J’ai oublié d’acheter du pain ce matin.', it: 'Ho dimenticato di comprare il pane stamattina.', pt: 'Esqueci de comprar pão esta manhã.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['acordé', 'encargué', 'cansé'] },
  { id: 'es2s022', de: 'Después de cenar, mi hermana lavó los platos.', en: 'After dinner, my sister washed the dishes.', gloss: { de: 'Nach dem Abendessen hat meine Schwester das Geschirr gespült.', fr: 'Après le dîner, ma sœur a fait la vaisselle.', it: 'Dopo cena, mia sorella ha lavato i piatti.', pt: 'Depois do jantar, minha irmã lavou a louça.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['rompió', 'guardó', 'secó'] },
  { id: 'es2s023', de: 'El autobús pasa cada veinte minutos por esta parada.', en: 'The bus comes every twenty minutes at this stop.', gloss: { de: 'Der Bus fährt alle zwanzig Minuten an dieser Haltestelle.', fr: 'Le bus passe toutes les vingt minutes à cet arrêt.', it: 'L’autobus passa ogni venti minuti a questa fermata.', pt: 'O ônibus passa a cada vinte minutos nesta parada.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['metro', 'tren', 'avión'] },
  { id: 'es2s024', de: 'Ayer olvidé la contraseña del ordenador.', en: 'Yesterday I forgot my computer password.', gloss: { de: 'Gestern habe ich das Passwort des Computers vergessen.', fr: 'Hier j’ai oublié le mot de passe de l’ordinateur.', it: 'Ieri ho dimenticato la password del computer.', pt: 'Ontem esqueci a senha do computador.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['pantalla', 'aplicación', 'llamada'] },
  { id: 'es2s025', de: 'Te envié un mensaje esta mañana.', en: 'I sent you a message this morning.', gloss: { de: 'Ich habe dir heute Morgen eine Nachricht geschickt.', fr: 'Je t’ai envoyé un message ce matin.', it: 'Ti ho inviato un messaggio stamattina.', pt: 'Te enviei uma mensagem esta manhã.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['escribí', 'dejé', 'llevé'] },
  { id: 'es2s026', de: 'Vamos a cambiar de piso el mes que viene.', en: 'We are going to move flat next month.', gloss: { de: 'Wir ziehen nächsten Monat in eine andere Wohnung.', fr: 'Nous allons déménager le mois prochain.', it: 'Cambieremo appartamento il mese prossimo.', pt: 'Vamos mudar de apartamento no mês que vem.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['año', 'viernes', 'sábado'] },
  { id: 'es2s027', de: 'Cuando llegué a la estación, el tren ya no estaba.', en: 'When I got to the station, the train was no longer there.', gloss: { de: 'Als ich am Bahnhof ankam, war der Zug nicht mehr da.', fr: 'Quand je suis arrivé à la gare, le train n’était plus là.', it: 'Quando sono arrivato in stazione, il treno non c’era più.', pt: 'Quando cheguei à estação, o trem já não estava.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['volví', 'salí', 'entré'] },
  { id: 'es2s028', de: 'El sábado nadé en la piscina del gimnasio.', en: 'On Saturday I swam in the gym pool.', gloss: { de: 'Am Samstag bin ich im Schwimmbad des Fitnessstudios geschwommen.', fr: 'Samedi, j’ai nagé dans la piscine de la salle de sport.', it: 'Sabato ho nuotato nella piscina della palestra.', pt: 'No sábado nadei na piscina da academia.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['corrí', 'cené', 'trabajé'] },
  { id: 'es2s029', de: 'Mi vecino me prestó su coche para ir al aeropuerto.', en: 'My neighbour lent me his car to go to the airport.', gloss: { de: 'Mein Nachbar hat mir sein Auto geliehen, um zum Flughafen zu fahren.', fr: 'Mon voisin m’a prêté sa voiture pour aller à l’aéroport.', it: 'Il mio vicino mi ha prestato la sua macchina per andare all’aeroporto.', pt: 'Meu vizinho me emprestou o carro dele para ir ao aeroporto.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['pidió', 'vendió', 'enseñó'] },
  { id: 'es2s030', de: 'Compré un regalo para el cumpleaños de mi madre.', en: 'I bought a present for my mother’s birthday.', gloss: { de: 'Ich habe ein Geschenk zum Geburtstag meiner Mutter gekauft.', fr: 'J’ai acheté un cadeau pour l’anniversaire de ma mère.', it: 'Ho comprato un regalo per il compleanno di mia madre.', pt: 'Comprei um presente para o aniversário da minha mãe.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['billete', 'postre', 'mensaje'] },
  { id: 'es2s031', de: 'La boda fue en un pueblo de la montaña.', en: 'The wedding was in a village in the mountains.', gloss: { de: 'Die Hochzeit war in einem Dorf in den Bergen.', fr: 'Le mariage a eu lieu dans un village de montagne.', it: 'Il matrimonio è stato in un paese di montagna.', pt: 'O casamento foi em um vilarejo na montanha.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['cena', 'reunión', 'entrevista'] },
  { id: 'es2s032', de: 'Ayer llovió toda la tarde y no salimos de casa.', en: 'Yesterday it rained all afternoon and we didn’t leave the house.', gloss: { de: 'Gestern hat es den ganzen Nachmittag geregnet und wir sind nicht aus dem Haus gegangen.', fr: 'Hier il a plu tout l’après-midi et nous ne sommes pas sortis de la maison.', it: 'Ieri ha piovuto tutto il pomeriggio e non siamo usciti di casa.', pt: 'Ontem choveu a tarde toda e não saímos de casa.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['mañana', 'noche', 'semana'] },
  { id: 'es2s033', de: 'En invierno hay mucha nieve en las montañas del norte.', en: 'In winter there is a lot of snow in the northern mountains.', gloss: { de: 'Im Winter liegt viel Schnee in den Bergen im Norden.', fr: 'En hiver il y a beaucoup de neige dans les montagnes du nord.', it: 'In inverno c’è molta neve sulle montagne del nord.', pt: 'No inverno há muita neve nas montanhas do norte.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['lluvia', 'niebla', 'gente'] },
  { id: 'es2s034', de: 'Vi una película muy triste el domingo.', en: 'I watched a very sad film on Sunday.', gloss: { de: 'Am Sonntag habe ich einen sehr traurigen Film gesehen.', fr: 'Dimanche j’ai vu un film très triste.', it: 'Domenica ho visto un film molto triste.', pt: 'Vi um filme muito triste no domingo.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['larga', 'divertida', 'aburrida'] },
  { id: 'es2s035', de: 'No pude comprar entradas para el concierto.', en: 'I couldn’t buy tickets for the concert.', gloss: { de: 'Ich konnte keine Karten für das Konzert kaufen.', fr: 'Je n’ai pas pu acheter de billets pour le concert.', it: 'Non ho potuto comprare i biglietti per il concerto.', pt: 'Não consegui comprar ingressos para o show.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['billetes', 'maletas', 'tarjetas'] },
  { id: 'es2s036', de: 'Mi equipo ganó el partido por dos goles.', en: 'My team won the match by two goals.', gloss: { de: 'Meine Mannschaft hat das Spiel mit zwei Toren gewonnen.', fr: 'Mon équipe a gagné le match par deux buts.', it: 'La mia squadra ha vinto la partita per due gol.', pt: 'Meu time ganhou a partida por dois gols.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['perdió', 'empezó', 'terminó'] },
  { id: 'es2s037', de: 'Antes corría todas las mañanas en el parque.', en: 'I used to run every morning in the park.', gloss: { de: 'Früher bin ich jeden Morgen im Park gelaufen.', fr: 'Avant, je courais tous les matins dans le parc.', it: 'Prima correvo tutte le mattine al parco.', pt: 'Antes eu corria todas as manhãs no parque.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['nadaba', 'cocinaba', 'estudiaba'] },
  { id: 'es2s038', de: 'Deja las llaves encima de la mesa, por favor.', en: 'Leave the keys on the table, please.', gloss: { de: 'Leg die Schlüssel bitte auf den Tisch.', fr: 'Laisse les clés sur la table, s’il te plaît.', it: 'Lascia le chiavi sul tavolo, per favore.', pt: 'Deixe as chaves em cima da mesa, por favor.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['maletas', 'tarjetas', 'zapatos'] },
  { id: 'es2s039', de: 'Tengo que recoger a mi hija del colegio a las cinco.', en: 'I have to pick my daughter up from school at five.', gloss: { de: 'Ich muss meine Tochter um fünf von der Schule abholen.', fr: 'Je dois récupérer ma fille à l’école à cinq heures.', it: 'Devo andare a prendere mia figlia a scuola alle cinque.', pt: 'Tenho que buscar minha filha na escola às cinco.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['llevar', 'esperar', 'ayudar'] },
  { id: 'es2s040', de: 'El semáforo estaba en rojo y el coche no paró.', en: 'The traffic light was red and the car didn’t stop.', gloss: { de: 'Die Ampel war rot und das Auto hielt nicht an.', fr: 'Le feu était rouge et la voiture ne s’est pas arrêtée.', it: 'Il semaforo era rosso e la macchina non si è fermata.', pt: 'O semáforo estava vermelho e o carro não parou.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['puente', 'barrio', 'metro'] },
  { id: 'es2s041', de: 'Quedamos en la esquina de mi calle a las ocho.', en: 'We’re meeting on the corner of my street at eight.', gloss: { de: 'Wir treffen uns um acht an der Ecke meiner Straße.', fr: 'On se retrouve au coin de ma rue à huit heures.', it: 'Ci vediamo all’angolo della mia via alle otto.', pt: 'A gente se encontra na esquina da minha rua às oito.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['parada', 'entrada', 'puerta'] },
  { id: 'es2s042', de: 'Aparqué el coche en el aparcamiento del supermercado.', en: 'I parked the car in the supermarket car park.', gloss: { de: 'Ich habe das Auto auf dem Parkplatz des Supermarkts geparkt.', fr: 'J’ai garé la voiture dans le parking du supermarché.', it: 'Ho parcheggiato la macchina nel parcheggio del supermercato.', pt: 'Estacionei o carro no estacionamento do supermercado.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['barrio', 'puente', 'metro'] },
  { id: 'es2s043', de: 'La aplicación no funciona bien en mi móvil.', en: 'The app doesn’t work properly on my phone.', gloss: { de: 'Die App funktioniert auf meinem Handy nicht gut.', fr: 'L’application ne marche pas bien sur mon portable.', it: 'L’applicazione non funziona bene sul mio cellulare.', pt: 'O aplicativo não funciona bem no meu celular.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['pantalla', 'contraseña', 'llamada'] },
  { id: 'es2s044', de: 'Descargué el archivo pero no pude abrirlo.', en: 'I downloaded the file but I couldn’t open it.', gloss: { de: 'Ich habe die Datei heruntergeladen, konnte sie aber nicht öffnen.', fr: 'J’ai téléchargé le fichier mais je n’ai pas pu l’ouvrir.', it: 'Ho scaricato il file ma non sono riuscito ad aprirlo.', pt: 'Baixei o arquivo mas não consegui abri-lo.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['mensaje', 'teclado', 'precio'] },
  { id: 'es2s045', de: 'Mi jefe cambió la fecha de la reunión.', en: 'My boss changed the date of the meeting.', gloss: { de: 'Mein Chef hat den Termin der Besprechung geändert.', fr: 'Mon patron a changé la date de la réunion.', it: 'Il mio capo ha cambiato la data della riunione.', pt: 'Meu chefe mudou a data da reunião.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['olvidó', 'confirmó', 'envió'] },
  { id: 'es2s046', de: 'Decidimos ir al campo en vez de a la playa.', en: 'We decided to go to the countryside instead of the beach.', gloss: { de: 'Wir haben beschlossen, aufs Land statt an den Strand zu fahren.', fr: 'Nous avons décidé d’aller à la campagne au lieu de la plage.', it: 'Abbiamo deciso di andare in campagna invece che al mare.', pt: 'Decidimos ir ao campo em vez de ir à praia.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['río', 'museo', 'gimnasio'] },
  { id: 'es2s047', de: 'Este verano voy a viajar por el sur del país.', en: 'This summer I’m going to travel around the south of the country.', gloss: { de: 'Diesen Sommer werde ich durch den Süden des Landes reisen.', fr: 'Cet été je vais voyager dans le sud du pays.', it: 'Quest’estate viaggerò per il sud del paese.', pt: 'Neste verão vou viajar pelo sul do país.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['trabajar', 'estudiar', 'conducir'] },
  { id: 'es2s048', de: 'Mi pareja y yo vamos a mudarnos a otro barrio.', en: 'My partner and I are going to move to another neighbourhood.', gloss: { de: 'Mein Partner und ich ziehen in ein anderes Viertel.', fr: 'Mon partenaire et moi allons déménager dans un autre quartier.', it: 'Io e il mio partner ci trasferiremo in un altro quartiere.', pt: 'Meu parceiro e eu vamos nos mudar para outro bairro.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['vecina', 'jefa', 'compañera'] },
  { id: 'es2s049', de: 'El médico me dijo que tenía que descansar una semana.', en: 'The doctor told me I had to rest for a week.', gloss: { de: 'Der Arzt sagte mir, ich müsse eine Woche lang ausruhen.', fr: 'Le médecin m’a dit que je devais me reposer une semaine.', it: 'Il medico mi ha detto che dovevo riposare una settimana.', pt: 'O médico me disse que eu tinha que descansar uma semana.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['pidió', 'explicó', 'preguntó'] },
  { id: 'es2s050', de: 'Me puse el abrigo porque hacía mucho viento.', en: 'I put on my coat because it was very windy.', gloss: { de: 'Ich habe den Mantel angezogen, weil es sehr windig war.', fr: 'J’ai mis mon manteau parce qu’il y avait beaucoup de vent.', it: 'Mi sono messo il cappotto perché c’era molto vento.', pt: 'Coloquei o casaco porque estava ventando muito.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['sombrero', 'jersey', 'pantalón'] },
  { id: 'es2s051', de: 'Mi vecina es muy amable con todo el mundo.', en: 'My neighbour is very kind to everyone.', gloss: { de: 'Meine Nachbarin ist zu allen sehr freundlich.', fr: 'Ma voisine est très aimable avec tout le monde.', it: 'La mia vicina è molto gentile con tutti.', pt: 'Minha vizinha é muito gentil com todo mundo.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['tímida', 'seria', 'callada'] },
  { id: 'es2s052', de: 'De pequeño era muy tímido y hablaba poco.', en: 'As a child I was very shy and didn’t talk much.', gloss: { de: 'Als Kind war ich sehr schüchtern und habe wenig geredet.', fr: 'Enfant, j’étais très timide et je parlais peu.', it: 'Da piccolo ero molto timido e parlavo poco.', pt: 'Quando pequeno eu era muito tímido e falava pouco.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['nervioso', 'tranquilo', 'ocupado'] },
  { id: 'es2s053', de: 'Nuestra amistad empezó en la universidad.', en: 'Our friendship began at university.', gloss: { de: 'Unsere Freundschaft begann an der Universität.', fr: 'Notre amitié a commencé à l’université.', it: 'La nostra amicizia è iniziata all’università.', pt: 'Nossa amizade começou na universidade.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['carrera', 'rutina', 'cita'] },
  { id: 'es2s054', de: 'Tengo una cita con el dentista el jueves.', en: 'I have an appointment with the dentist on Thursday.', gloss: { de: 'Ich habe am Donnerstag einen Termin beim Zahnarzt.', fr: 'J’ai un rendez-vous chez le dentiste jeudi.', it: 'Ho un appuntamento dal dentista giovedì.', pt: 'Tenho uma consulta com o dentista na quinta-feira.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['reunión', 'entrevista', 'llamada'] },
  { id: 'es2s055', de: 'Intenté llamarte dos veces, pero no contestaste.', en: 'I tried to call you twice, but you didn’t answer.', gloss: { de: 'Ich habe zweimal versucht, dich anzurufen, aber du bist nicht rangegangen.', fr: 'J’ai essayé de t’appeler deux fois, mais tu n’as pas répondu.', it: 'Ho provato a chiamarti due volte, ma non hai risposto.', pt: 'Tentei te ligar duas vezes, mas você não atendeu.' }, level: 'A2', clozeIndex: 0, clozeDistractors: ['Conseguí', 'Olvidé', 'Esperé'] },
  { id: 'es2s056', de: 'No recuerdo dónde dejé el paraguas.', en: 'I don’t remember where I left the umbrella.', gloss: { de: 'Ich weiß nicht mehr, wo ich den Schirm gelassen habe.', fr: 'Je ne me souviens pas où j’ai laissé le parapluie.', it: 'Non ricordo dove ho lasciato l’ombrello.', pt: 'Não lembro onde deixei o guarda-chuva.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['entiendo', 'pregunto', 'olvido'] },
  { id: 'es2s057', de: 'El río pasa justo detrás de nuestra casa.', en: 'The river runs right behind our house.', gloss: { de: 'Der Fluss verläuft direkt hinter unserem Haus.', fr: 'La rivière passe juste derrière notre maison.', it: 'Il fiume passa proprio dietro casa nostra.', pt: 'O rio passa bem atrás da nossa casa.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['puente', 'árbol', 'camino'] },
  { id: 'es2s058', de: 'Ese árbol es más alto que el edificio.', en: 'That tree is taller than the building.', gloss: { de: 'Dieser Baum ist höher als das Gebäude.', fr: 'Cet arbre est plus haut que l’immeuble.', it: 'Quell’albero è più alto dell’edificio.', pt: 'Aquela árvore é mais alta que o prédio.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['viejo', 'ancho', 'estrecho'] },
  { id: 'es2s059', de: 'Ayer el sol salió a las siete y media.', en: 'Yesterday the sun rose at half past seven.', gloss: { de: 'Gestern ging die Sonne um halb acht auf.', fr: 'Hier le soleil s’est levé à sept heures et demie.', it: 'Ieri il sole è sorto alle sette e mezza.', pt: 'Ontem o sol nasceu às sete e meia.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['tren', 'autobús', 'avión'] },
  { id: 'es2s060', de: 'Siguió trabajando porque tenía mucha prisa.', en: 'He carried on working because he was in a big hurry.', gloss: { de: 'Er hat weitergearbeitet, weil er es sehr eilig hatte.', fr: 'Il a continué à travailler parce qu’il était très pressé.', it: 'Ha continuato a lavorare perché aveva molta fretta.', pt: 'Ele continuou trabalhando porque estava com muita pressa.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['estudiando', 'corriendo', 'cocinando'] },
  { id: 'es2s061', de: 'Llevé la maleta hasta la parada del metro.', en: 'I carried the suitcase to the underground stop.', gloss: { de: 'Ich habe den Koffer bis zur U-Bahn-Haltestelle getragen.', fr: 'J’ai porté la valise jusqu’à l’arrêt de métro.', it: 'Ho portato la valigia fino alla fermata della metropolitana.', pt: 'Levei a mala até a parada do metrô.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['tarjeta', 'llave', 'entrada'] },
  { id: 'es2s062', de: 'El ayuntamiento abrió un centro deportivo en mi barrio.', en: 'The town hall opened a sports centre in my neighbourhood.', gloss: { de: 'Die Stadtverwaltung hat ein Sportzentrum in meinem Viertel eröffnet.', fr: 'La mairie a ouvert un centre sportif dans mon quartier.', it: 'Il municipio ha aperto un centro sportivo nel mio quartiere.', pt: 'A prefeitura abriu um centro esportivo no meu bairro.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['hospital', 'instituto', 'museo'] },
];
