import type { SentenceItem } from '@/content/german/types';

// Spanish A2 sentences. `de` holds the Spanish text. Where A1 stays in the
// present tense with short clauses, A2 tells small stories: preterite for
// completed events, imperfect for background and habits, plus comparatives and
// subordinate clauses ("porque…", "antes de…", "cuando era niño…").
//
// clozeIndex is a 0-based index into de.split(' ') and always targets the
// load-bearing word, never an article. clozeDistractors are same-class words
// that would be grammatical in the slot but wrong in meaning, so the exercise
// tests comprehension rather than word-shape matching.
//
// `gloss` carries the non-English UI locales; see a2-vocab.ts for the rule.

export const A2_SENTENCES: SentenceItem[] = [
  { id: 'es2s001', de: 'Ayer me levanté muy temprano.', en: 'Yesterday I got up very early.', gloss: { de: 'Gestern bin ich sehr früh aufgestanden.', fr: 'Hier je me suis levé très tôt.', it: 'Ieri mi sono alzato molto presto.', pt: 'Ontem eu me levantei muito cedo.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['acosté', 'duché', 'vestí'] },
  { id: 'es2s002', de: 'El tren llegó con media hora de retraso.', en: 'The train arrived half an hour late.', gloss: { de: 'Der Zug kam mit einer halben Stunde Verspätung an.', fr: 'Le train est arrivé avec une demi-heure de retard.', it: 'Il treno è arrivato con mezz’ora di ritardo.', pt: 'O trem chegou com meia hora de atraso.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['salió', 'volvió', 'terminó'] },
  { id: 'es2s003', de: 'Perdí el pasaporte en el aeropuerto.', en: 'I lost my passport at the airport.', gloss: { de: 'Ich habe meinen Reisepass am Flughafen verloren.', fr: 'J’ai perdu mon passeport à l’aéroport.', it: 'Ho perso il passaporto in aeroporto.', pt: 'Perdi o passaporte no aeroporto.' }, level: 'A2', clozeIndex: 0, clozeDistractors: ['Encontré', 'Compré', 'Guardé'] },
  { id: 'es2s004', de: 'Cuando era niño, vivía en el campo.', en: 'When I was a child, I lived in the countryside.', gloss: { de: 'Als ich ein Kind war, wohnte ich auf dem Land.', fr: 'Quand j’étais enfant, j’habitais à la campagne.', it: 'Quando ero bambino, vivevo in campagna.', pt: 'Quando eu era criança, morava no campo.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['trabajaba', 'estudiaba', 'jugaba'] },
  { id: 'es2s005', de: 'Anoche cené con mis compañeros de trabajo.', en: 'Last night I had dinner with my colleagues.', gloss: { de: 'Gestern Abend habe ich mit meinen Arbeitskollegen zu Abend gegessen.', fr: 'Hier soir j’ai dîné avec mes collègues de travail.', it: 'Ieri sera ho cenato con i miei colleghi di lavoro.', pt: 'Ontem à noite jantei com meus colegas de trabalho.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['desayuné', 'trabajé', 'hablé'] },
  { id: 'es2s006', de: 'Este hotel es más barato que el otro.', en: 'This hotel is cheaper than the other one.', gloss: { de: 'Dieses Hotel ist billiger als das andere.', fr: 'Cet hôtel est moins cher que l’autre.', it: 'Questo hotel è più economico dell’altro.', pt: 'Este hotel é mais barato que o outro.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['caro', 'limpio', 'tranquilo'] },
  { id: 'es2s007', de: 'Me duele mucho la cabeza.', en: 'My head hurts a lot.', gloss: { de: 'Mein Kopf tut sehr weh.', fr: 'J’ai très mal à la tête.', it: 'Mi fa molto male la testa.', pt: 'Minha cabeça dói muito.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['espalda', 'mano', 'garganta'] },
  { id: 'es2s008', de: 'Tengo que ir al médico esta tarde.', en: 'I have to go to the doctor this afternoon.', gloss: { de: 'Ich muss heute Nachmittag zum Arzt gehen.', fr: 'Je dois aller chez le médecin cet après-midi.', it: 'Devo andare dal medico questo pomeriggio.', pt: 'Tenho que ir ao médico esta tarde.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['hospital', 'supermercado', 'aeropuerto'] },
  { id: 'es2s009', de: '¿Cuánto costó tu billete de avión?', en: 'How much did your plane ticket cost?', gloss: { de: 'Wie viel hat dein Flugticket gekostet?', fr: 'Combien a coûté ton billet d’avion ?', it: 'Quanto è costato il tuo biglietto aereo?', pt: 'Quanto custou a sua passagem de avião?' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['pagó', 'ganó', 'cambió'] },
  { id: 'es2s010', de: 'Pagué con tarjeta porque no llevaba efectivo.', en: 'I paid by card because I wasn’t carrying any cash.', gloss: { de: 'Ich habe mit Karte bezahlt, weil ich kein Bargeld dabeihatte.', fr: 'J’ai payé par carte parce que je n’avais pas d’espèces.', it: 'Ho pagato con la carta perché non avevo contanti.', pt: 'Paguei com cartão porque não tinha dinheiro em espécie.' }, level: 'A2', clozeIndex: 0, clozeDistractors: ['Compré', 'Gasté', 'Cambié'] },
  { id: 'es2s011', de: 'La reunión empezó a las nueve de la mañana.', en: 'The meeting started at nine in the morning.', gloss: { de: 'Die Besprechung begann um neun Uhr morgens.', fr: 'La réunion a commencé à neuf heures du matin.', it: 'La riunione è cominciata alle nove di mattina.', pt: 'A reunião começou às nove da manhã.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['terminó', 'llegó', 'volvió'] },
  { id: 'es2s012', de: 'Mi jefe me pidió un informe para el viernes.', en: 'My boss asked me for a report by Friday.', gloss: { de: 'Mein Chef hat mich um einen Bericht bis Freitag gebeten.', fr: 'Mon patron m’a demandé un rapport pour vendredi.', it: 'Il mio capo mi ha chiesto una relazione per venerdì.', pt: 'Meu chefe me pediu um relatório para sexta-feira.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['mandó', 'escribió', 'explicó'] },
  { id: 'es2s013', de: 'Estudié en la universidad durante cuatro años.', en: 'I studied at university for four years.', gloss: { de: 'Ich habe vier Jahre lang an der Universität studiert.', fr: 'J’ai étudié à l’université pendant quatre ans.', it: 'Ho studiato all’università per quattro anni.', pt: 'Estudei na universidade durante quatro anos.' }, level: 'A2', clozeIndex: 0, clozeDistractors: ['Trabajé', 'Viví', 'Enseñé'] },
  { id: 'es2s014', de: 'Ayer hacía mucho frío y llovía sin parar.', en: 'Yesterday it was very cold and it rained non-stop.', gloss: { de: 'Gestern war es sehr kalt und es regnete ununterbrochen.', fr: 'Hier il faisait très froid et il pleuvait sans arrêt.', it: 'Ieri faceva molto freddo e pioveva senza sosta.', pt: 'Ontem fazia muito frio e chovia sem parar.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['calor', 'viento', 'sol'] },
  { id: 'es2s015', de: 'El fin de semana pasado fuimos a la playa.', en: 'Last weekend we went to the beach.', gloss: { de: 'Letztes Wochenende sind wir an den Strand gefahren.', fr: 'Le week-end dernier, nous sommes allés à la plage.', it: 'Lo scorso fine settimana siamo andati al mare.', pt: 'No fim de semana passado fomos à praia.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['volvimos', 'salimos', 'llamamos'] },
  { id: 'es2s016', de: 'Me sentía nervioso antes de la entrevista.', en: 'I felt nervous before the interview.', gloss: { de: 'Vor dem Vorstellungsgespräch war ich nervös.', fr: 'Je me sentais nerveux avant l’entretien.', it: 'Mi sentivo nervoso prima del colloquio.', pt: 'Eu me sentia nervoso antes da entrevista.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['tranquilo', 'aburrido', 'ocupado'] },
  { id: 'es2s017', de: 'No encontré las llaves del coche.', en: 'I couldn’t find the car keys.', gloss: { de: 'Ich habe die Autoschlüssel nicht gefunden.', fr: 'Je n’ai pas trouvé les clés de la voiture.', it: 'Non ho trovato le chiavi della macchina.', pt: 'Não encontrei as chaves do carro.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['olvidé', 'guardé', 'compré'] },
  { id: 'es2s018', de: 'La cocina de mi apartamento es muy pequeña.', en: 'The kitchen in my apartment is very small.', gloss: { de: 'Die Küche in meiner Wohnung ist sehr klein.', fr: 'La cuisine de mon appartement est très petite.', it: 'La cucina del mio appartamento è molto piccola.', pt: 'A cozinha do meu apartamento é muito pequena.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['sala', 'ventana', 'puerta'] },
  { id: 'es2s019', de: 'Antes salía con mis amigos todos los sábados.', en: 'I used to go out with my friends every Saturday.', gloss: { de: 'Früher ging ich jeden Samstag mit meinen Freunden aus.', fr: 'Avant, je sortais avec mes amis tous les samedis.', it: 'Prima uscivo con i miei amici tutti i sabati.', pt: 'Antes eu saía com meus amigos todos os sábados.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['cenaba', 'hablaba', 'viajaba'] },
  { id: 'es2s020', de: '¿Tienen esta camisa en otra talla?', en: 'Do you have this shirt in another size?', gloss: { de: 'Haben Sie dieses Hemd in einer anderen Größe?', fr: 'Avez-vous cette chemise dans une autre taille ?', it: 'Avete questa camicia in un’altra taglia?', pt: 'Vocês têm esta camisa em outro tamanho?' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['chaqueta', 'falda', 'blusa'] },
  { id: 'es2s021', de: 'Me olvidé de comprar el pan esta mañana.', en: 'I forgot to buy bread this morning.', gloss: { de: 'Ich habe heute Morgen vergessen, Brot zu kaufen.', fr: 'J’ai oublié d’acheter du pain ce matin.', it: 'Ho dimenticato di comprare il pane stamattina.', pt: 'Esqueci de comprar pão esta manhã.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['acordé', 'encargué', 'cansé'] },
  { id: 'es2s022', de: 'Después de cenar, mi hermana lavó los platos.', en: 'After dinner, my sister washed the dishes.', gloss: { de: 'Nach dem Abendessen hat meine Schwester das Geschirr gespült.', fr: 'Après le dîner, ma sœur a fait la vaisselle.', it: 'Dopo cena, mia sorella ha lavato i piatti.', pt: 'Depois do jantar, minha irmã lavou a louça.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['rompió', 'guardó', 'secó'] },
];
