import type { SentenceItem } from '@/content/german/types';

// Spanish B1 sentences. `de` holds the Spanish text. These are deliberately not
// simple SVO: subordinate clauses, the subjunctive after doubt / emotion /
// purpose / unrealised time, si-clauses, and opinion framing — the shapes a B1
// learner has to produce, not just recognise.
//
// clozeIndex targets the load-bearing word (never an article), and where the
// answer is a subjunctive form the distractors are the indicative/other tenses
// of the same verb, so the exercise tests mood rather than vocabulary.
//
// `gloss` carries the non-English UI locales; see b1-vocab.ts for the rule.

export const B1_SENTENCES: SentenceItem[] = [
  { id: 'es3s001', de: 'No creo que sea una buena idea.', en: 'I don’t think that’s a good idea.', gloss: { de: 'Ich glaube nicht, dass das eine gute Idee ist.', fr: 'Je ne pense pas que ce soit une bonne idée.', it: 'Non credo che sia una buona idea.', pt: 'Não acho que seja uma boa ideia.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['es', 'fue', 'sería'] },
  { id: 'es3s002', de: 'Aunque el sueldo sea bajo, el trabajo me interesa.', en: 'Even if the salary is low, the job interests me.', gloss: { de: 'Auch wenn das Gehalt niedrig ist, interessiert mich die Stelle.', fr: 'Même si le salaire est bas, le poste m’intéresse.', it: 'Anche se lo stipendio è basso, il lavoro mi interessa.', pt: 'Embora o salário seja baixo, o trabalho me interessa.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Porque', 'Cuando', 'Mientras'] },
  { id: 'es3s003', de: 'Sin embargo, muchos ciudadanos no confían en el gobierno.', en: 'However, many citizens do not trust the government.', gloss: { de: 'Viele Bürger vertrauen der Regierung jedoch nicht.', fr: 'Cependant, beaucoup de citoyens ne font pas confiance au gouvernement.', it: 'Tuttavia, molti cittadini non si fidano del governo.', pt: 'No entanto, muitos cidadãos não confiam no governo.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['periódico', 'desempleo', 'reciclaje'] },
  { id: 'es3s004', de: 'Es imprescindible que reduzcamos la contaminación.', en: 'It is essential that we reduce pollution.', gloss: { de: 'Es ist unerlässlich, dass wir die Verschmutzung verringern.', fr: 'Il est indispensable que nous réduisions la pollution.', it: 'È indispensabile che riduciamo l’inquinamento.', pt: 'É imprescindível que reduzamos a poluição.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['reducimos', 'reducíamos', 'reduciremos'] },
  { id: 'es3s005', de: 'A pesar de los riesgos, decidió montar su propia empresa.', en: 'Despite the risks, she decided to start her own company.', gloss: { de: 'Trotz der Risiken beschloss sie, ihr eigenes Unternehmen zu gründen.', fr: 'Malgré les risques, elle a décidé de créer sa propre entreprise.', it: 'Nonostante i rischi, ha deciso di aprire una propria azienda.', pt: 'Apesar dos riscos, ela decidiu abrir a própria empresa.' }, level: 'B1', clozeIndex: 9, clozeDistractors: ['carrera', 'reunión', 'beca'] },
  { id: 'es3s006', de: 'Los medios difunden rumores sin comprobar las fuentes.', en: 'The media spread rumours without checking the sources.', gloss: { de: 'Die Medien verbreiten Gerüchte, ohne die Quellen zu prüfen.', fr: 'Les médias diffusent des rumeurs sans vérifier les sources.', it: 'I media diffondono dicerie senza verificare le fonti.', pt: 'Os meios de comunicação divulgam boatos sem verificar as fontes.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['informan', 'debaten', 'reconocen'] },
  { id: 'es3s007', de: 'Por lo tanto, deberíamos apostar por las energías renovables.', en: 'Therefore, we should bet on renewable energy.', gloss: { de: 'Deshalb sollten wir auf erneuerbare Energien setzen.', fr: 'Par conséquent, nous devrions miser sur les énergies renouvelables.', it: 'Pertanto, dovremmo puntare sulle energie rinnovabili.', pt: 'Portanto, deveríamos apostar nas energias renováveis.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['escasas', 'cotidianas', 'exigentes'] },
  { id: 'es3s008', de: 'Cuando termine la carrera, buscaré trabajo en el extranjero.', en: 'When I finish my degree, I will look for a job abroad.', gloss: { de: 'Wenn ich mein Studium beendet habe, werde ich im Ausland eine Stelle suchen.', fr: 'Quand j’aurai fini mes études, je chercherai un emploi à l’étranger.', it: 'Quando avrò finito gli studi, cercherò lavoro all’estero.', pt: 'Quando terminar o curso, vou procurar trabalho no exterior.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['termino', 'terminé', 'terminaré'] },
  { id: 'es3s009', de: 'Me sorprende que tanta gente siga sin votar.', en: 'It surprises me that so many people still don’t vote.', gloss: { de: 'Es überrascht mich, dass so viele Menschen immer noch nicht wählen.', fr: 'Ça m’étonne que tant de gens ne votent toujours pas.', it: 'Mi sorprende che tanta gente continui a non votare.', pt: 'Me surpreende que tanta gente continue sem votar.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['sigue', 'seguía', 'seguirá'] },
  { id: 'es3s010', de: 'Aunque no estoy de acuerdo, reconozco que tiene razón.', en: 'Although I don’t agree, I admit that he is right.', gloss: { de: 'Obwohl ich nicht einverstanden bin, gebe ich zu, dass er recht hat.', fr: 'Bien que je ne sois pas d’accord, je reconnais qu’il a raison.', it: 'Anche se non sono d’accordo, riconosco che ha ragione.', pt: 'Embora eu não concorde, reconheço que ele tem razão.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['dudo', 'niego', 'olvido'] },
  { id: 'es3s011', de: 'Si tuviera más tiempo, me matricularía en un curso de formación.', en: 'If I had more time, I would enrol in a training course.', gloss: { de: 'Wenn ich mehr Zeit hätte, würde ich mich für einen Weiterbildungskurs einschreiben.', fr: 'Si j’avais plus de temps, je m’inscrirais à une formation.', it: 'Se avessi più tempo, mi iscriverei a un corso di formazione.', pt: 'Se eu tivesse mais tempo, me matricularia num curso de formação.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['tengo', 'tenía', 'tendría'] },
  { id: 'es3s012', de: 'La empresa lo despidió sin darle ninguna explicación.', en: 'The company fired him without giving him any explanation.', gloss: { de: 'Die Firma entließ ihn, ohne ihm eine Erklärung zu geben.', fr: 'L’entreprise l’a licencié sans lui donner aucune explication.', it: 'L’azienda lo ha licenziato senza dargli alcuna spiegazione.', pt: 'A empresa o demitiu sem lhe dar nenhuma explicação.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['contrató', 'convenció', 'entrevistó'] },
  { id: 'es3s013', de: 'Es injusto que el desempleo afecte sobre todo a los jóvenes.', en: 'It is unfair that unemployment mainly affects young people.', gloss: { de: 'Es ist ungerecht, dass die Arbeitslosigkeit vor allem junge Menschen trifft.', fr: 'Il est injuste que le chômage touche surtout les jeunes.', it: 'È ingiusto che la disoccupazione colpisca soprattutto i giovani.', pt: 'É injusto que o desemprego afete sobretudo os jovens.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['capaz', 'escaso', 'cotidiano'] },
  { id: 'es3s014', de: 'Te lo explico otra vez para que lo entiendas bien.', en: 'I’ll explain it to you again so that you understand it properly.', gloss: { de: 'Ich erkläre es dir noch einmal, damit du es gut verstehst.', fr: 'Je te l’explique encore une fois pour que tu le comprennes bien.', it: 'Te lo spiego di nuovo affinché tu lo capisca bene.', pt: 'Explico de novo para que você entenda bem.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['entiendes', 'entendías', 'entenderás'] },
  { id: 'es3s015', de: 'Mientras que unos defienden la libertad total, otros piden más control.', en: 'Whereas some defend total freedom, others ask for more control.', gloss: { de: 'Während die einen völlige Freiheit verteidigen, fordern die anderen mehr Kontrolle.', fr: 'Alors que certains défendent la liberté totale, d’autres réclament plus de contrôle.', it: 'Mentre alcuni difendono la libertà totale, altri chiedono più controllo.', pt: 'Enquanto uns defendem a liberdade total, outros pedem mais controle.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['pobreza', 'sequía', 'publicidad'] },
  { id: 'es3s016', de: 'No creo que las redes sociales tengan toda la culpa.', en: 'I don’t think social media is entirely to blame.', gloss: { de: 'Ich glaube nicht, dass die sozialen Netzwerke allein schuld sind.', fr: 'Je ne crois pas que les réseaux sociaux soient les seuls responsables.', it: 'Non credo che i social network abbiano tutta la colpa.', pt: 'Não acho que as redes sociais tenham toda a culpa.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['tienen', 'tenían', 'tendrán'] },
  { id: 'es3s017', de: 'Ojalá el gobierno invierta más en educación pública.', en: 'I hope the government invests more in public education.', gloss: { de: 'Hoffentlich investiert die Regierung mehr in die öffentliche Bildung.', fr: 'J’espère que le gouvernement investira davantage dans l’éducation publique.', it: 'Speriamo che il governo investa di più nell’istruzione pubblica.', pt: 'Tomara que o governo invista mais na educação pública.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['invierte', 'invirtió', 'invertirá'] },
  { id: 'es3s018', de: 'A pesar de la sequía, muchos siguen sin ahorrar agua.', en: 'Despite the drought, many still don’t save water.', gloss: { de: 'Trotz der Dürre sparen viele immer noch kein Wasser.', fr: 'Malgré la sécheresse, beaucoup ne font toujours pas d’économies d’eau.', it: 'Nonostante la siccità, molti continuano a non risparmiare acqua.', pt: 'Apesar da seca, muitos continuam sem economizar água.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['contaminar', 'reciclar', 'debatir'] },
  { id: 'es3s019', de: 'Estoy dispuesto a asumir más responsabilidad si me suben el sueldo.', en: 'I’m willing to take on more responsibility if they raise my salary.', gloss: { de: 'Ich bin bereit, mehr Verantwortung zu übernehmen, wenn man mein Gehalt erhöht.', fr: 'Je suis prêt à assumer plus de responsabilités si on augmente mon salaire.', it: 'Sono disposto ad assumermi più responsabilità se mi aumentano lo stipendio.', pt: 'Estou disposto a assumir mais responsabilidade se aumentarem o meu salário.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['capaz', 'exigente', 'arriesgado'] },
  { id: 'es3s020', de: 'Es decir, el esfuerzo vale la pena aunque los resultados tarden.', en: 'That is to say, the effort is worth it even if the results take time.', gloss: { de: 'Das heißt, die Mühe lohnt sich, auch wenn die Ergebnisse auf sich warten lassen.', fr: 'C’est-à-dire que l’effort en vaut la peine même si les résultats tardent.', it: 'Cioè, ne vale la pena anche se i risultati tardano.', pt: 'Ou seja, o esforço vale a pena mesmo que os resultados demorem.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['porque', 'cuando', 'mientras'] },
];
