import type { SentenceItem } from '@/content/german/types';

// Spanish B1 sentences. `de` holds the Spanish text. These are deliberately not
// simple SVO: subordinate clauses, the subjunctive after doubt / emotion /
// purpose / unrealised time, si-clauses, and opinion framing — the shapes a B1
// learner has to produce, not just recognise.
//
// clozeIndex targets the load-bearing word (never an article), and where the
// answer is a subjunctive form the distractors are the indicative/other tenses
// of the same verb, so the exercise tests mood rather than vocabulary.
//
// `gloss` carries the non-English UI locales; see b1-vocab.ts for the rule.

export const B1_SENTENCES: SentenceItem[] = [
  { id: 'es3s001', de: 'No creo que sea una buena idea.', en: 'I don’t think that’s a good idea.', gloss: { de: 'Ich glaube nicht, dass das eine gute Idee ist.', fr: 'Je ne pense pas que ce soit une bonne idée.', it: 'Non credo che sia una buona idea.', pt: 'Não acho que seja uma boa ideia.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['es', 'fue', 'sería'] },
  { id: 'es3s002', de: 'Aunque el sueldo sea bajo, el trabajo me interesa.', en: 'Even if the salary is low, the job interests me.', gloss: { de: 'Auch wenn das Gehalt niedrig ist, interessiert mich die Stelle.', fr: 'Même si le salaire est bas, le poste m’intéresse.', it: 'Anche se lo stipendio è basso, il lavoro mi interessa.', pt: 'Embora o salário seja baixo, o trabalho me interessa.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Porque', 'Cuando', 'Mientras'] },
  { id: 'es3s003', de: 'Sin embargo, muchos ciudadanos no confían en el gobierno.', en: 'However, many citizens do not trust the government.', gloss: { de: 'Viele Bürger vertrauen der Regierung jedoch nicht.', fr: 'Cependant, beaucoup de citoyens ne font pas confiance au gouvernement.', it: 'Tuttavia, molti cittadini non si fidano del governo.', pt: 'No entanto, muitos cidadãos não confiam no governo.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['periódico', 'desempleo', 'reciclaje'] },
  { id: 'es3s004', de: 'Es imprescindible que reduzcamos la contaminación.', en: 'It is essential that we reduce pollution.', gloss: { de: 'Es ist unerlässlich, dass wir die Verschmutzung verringern.', fr: 'Il est indispensable que nous réduisions la pollution.', it: 'È indispensabile che riduciamo l’inquinamento.', pt: 'É imprescindível que reduzamos a poluição.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['reducimos', 'reducíamos', 'reduciremos'] },
  { id: 'es3s005', de: 'A pesar de los riesgos, decidió montar su propia empresa.', en: 'Despite the risks, she decided to start her own company.', gloss: { de: 'Trotz der Risiken beschloss sie, ihr eigenes Unternehmen zu gründen.', fr: 'Malgré les risques, elle a décidé de créer sa propre entreprise.', it: 'Nonostante i rischi, ha deciso di aprire una propria azienda.', pt: 'Apesar dos riscos, ela decidiu abrir a própria empresa.' }, level: 'B1', clozeIndex: 9, clozeDistractors: ['carrera', 'reunión', 'beca'] },
  { id: 'es3s006', de: 'Los medios difunden rumores sin comprobar las fuentes.', en: 'The media spread rumours without checking the sources.', gloss: { de: 'Die Medien verbreiten Gerüchte, ohne die Quellen zu prüfen.', fr: 'Les médias diffusent des rumeurs sans vérifier les sources.', it: 'I media diffondono dicerie senza verificare le fonti.', pt: 'Os meios de comunicação divulgam boatos sem verificar as fontes.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['informan', 'debaten', 'reconocen'] },
  { id: 'es3s007', de: 'Por lo tanto, deberíamos apostar por las energías renovables.', en: 'Therefore, we should bet on renewable energy.', gloss: { de: 'Deshalb sollten wir auf erneuerbare Energien setzen.', fr: 'Par conséquent, nous devrions miser sur les énergies renouvelables.', it: 'Pertanto, dovremmo puntare sulle energie rinnovabili.', pt: 'Portanto, deveríamos apostar nas energias renováveis.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['escasas', 'cotidianas', 'exigentes'] },
  { id: 'es3s008', de: 'Cuando termine la carrera, buscaré trabajo en el extranjero.', en: 'When I finish my degree, I will look for a job abroad.', gloss: { de: 'Wenn ich mein Studium beendet habe, werde ich im Ausland eine Stelle suchen.', fr: 'Quand j’aurai fini mes études, je chercherai un emploi à l’étranger.', it: 'Quando avrò finito gli studi, cercherò lavoro all’estero.', pt: 'Quando terminar o curso, vou procurar trabalho no exterior.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['termino', 'terminé', 'terminaré'] },
  { id: 'es3s009', de: 'Me sorprende que tanta gente siga sin votar.', en: 'It surprises me that so many people still don’t vote.', gloss: { de: 'Es überrascht mich, dass so viele Menschen immer noch nicht wählen.', fr: 'Ça m’étonne que tant de gens ne votent toujours pas.', it: 'Mi sorprende che tanta gente continui a non votare.', pt: 'Me surpreende que tanta gente continue sem votar.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['sigue', 'seguía', 'seguirá'] },
  { id: 'es3s010', de: 'Aunque no estoy de acuerdo, reconozco que tiene razón.', en: 'Although I don’t agree, I admit that he is right.', gloss: { de: 'Obwohl ich nicht einverstanden bin, gebe ich zu, dass er recht hat.', fr: 'Bien que je ne sois pas d’accord, je reconnais qu’il a raison.', it: 'Anche se non sono d’accordo, riconosco che ha ragione.', pt: 'Embora eu não concorde, reconheço que ele tem razão.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['dudo', 'niego', 'olvido'] },
  { id: 'es3s011', de: 'Si tuviera más tiempo, me matricularía en un curso de formación.', en: 'If I had more time, I would enrol in a training course.', gloss: { de: 'Wenn ich mehr Zeit hätte, würde ich mich für einen Weiterbildungskurs einschreiben.', fr: 'Si j’avais plus de temps, je m’inscrirais à une formation.', it: 'Se avessi più tempo, mi iscriverei a un corso di formazione.', pt: 'Se eu tivesse mais tempo, me matricularia num curso de formação.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['tengo', 'tenía', 'tendría'] },
  { id: 'es3s012', de: 'La empresa lo despidió sin darle ninguna explicación.', en: 'The company fired him without giving him any explanation.', gloss: { de: 'Die Firma entließ ihn, ohne ihm eine Erklärung zu geben.', fr: 'L’entreprise l’a licencié sans lui donner aucune explication.', it: 'L’azienda lo ha licenziato senza dargli alcuna spiegazione.', pt: 'A empresa o demitiu sem lhe dar nenhuma explicação.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['contrató', 'convenció', 'entrevistó'] },
  { id: 'es3s013', de: 'Es injusto que el desempleo afecte sobre todo a los jóvenes.', en: 'It is unfair that unemployment mainly affects young people.', gloss: { de: 'Es ist ungerecht, dass die Arbeitslosigkeit vor allem junge Menschen trifft.', fr: 'Il est injuste que le chômage touche surtout les jeunes.', it: 'È ingiusto che la disoccupazione colpisca soprattutto i giovani.', pt: 'É injusto que o desemprego afete sobretudo os jovens.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['capaz', 'escaso', 'cotidiano'] },
  { id: 'es3s014', de: 'Te lo explico otra vez para que lo entiendas bien.', en: 'I’ll explain it to you again so that you understand it properly.', gloss: { de: 'Ich erkläre es dir noch einmal, damit du es gut verstehst.', fr: 'Je te l’explique encore une fois pour que tu le comprennes bien.', it: 'Te lo spiego di nuovo affinché tu lo capisca bene.', pt: 'Explico de novo para que você entenda bem.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['entiendes', 'entendías', 'entenderás'] },
  { id: 'es3s015', de: 'Mientras que unos defienden la libertad total, otros piden más control.', en: 'Whereas some defend total freedom, others ask for more control.', gloss: { de: 'Während die einen völlige Freiheit verteidigen, fordern die anderen mehr Kontrolle.', fr: 'Alors que certains défendent la liberté totale, d’autres réclament plus de contrôle.', it: 'Mentre alcuni difendono la libertà totale, altri chiedono più controllo.', pt: 'Enquanto uns defendem a liberdade total, outros pedem mais controle.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['pobreza', 'sequía', 'publicidad'] },
  { id: 'es3s016', de: 'No creo que las redes sociales tengan toda la culpa.', en: 'I don’t think social media is entirely to blame.', gloss: { de: 'Ich glaube nicht, dass die sozialen Netzwerke allein schuld sind.', fr: 'Je ne crois pas que les réseaux sociaux soient les seuls responsables.', it: 'Non credo che i social network abbiano tutta la colpa.', pt: 'Não acho que as redes sociais tenham toda a culpa.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['tienen', 'tenían', 'tendrán'] },
  { id: 'es3s017', de: 'Ojalá el gobierno invierta más en educación pública.', en: 'I hope the government invests more in public education.', gloss: { de: 'Hoffentlich investiert die Regierung mehr in die öffentliche Bildung.', fr: 'J’espère que le gouvernement investira davantage dans l’éducation publique.', it: 'Speriamo che il governo investa di più nell’istruzione pubblica.', pt: 'Tomara que o governo invista mais na educação pública.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['invierte', 'invirtió', 'invertirá'] },
  { id: 'es3s018', de: 'A pesar de la sequía, muchos siguen sin ahorrar agua.', en: 'Despite the drought, many still don’t save water.', gloss: { de: 'Trotz der Dürre sparen viele immer noch kein Wasser.', fr: 'Malgré la sécheresse, beaucoup ne font toujours pas d’économies d’eau.', it: 'Nonostante la siccità, molti continuano a non risparmiare acqua.', pt: 'Apesar da seca, muitos continuam sem economizar água.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['contaminar', 'reciclar', 'debatir'] },
  { id: 'es3s019', de: 'Estoy dispuesto a asumir más responsabilidad si me suben el sueldo.', en: 'I’m willing to take on more responsibility if they raise my salary.', gloss: { de: 'Ich bin bereit, mehr Verantwortung zu übernehmen, wenn man mein Gehalt erhöht.', fr: 'Je suis prêt à assumer plus de responsabilités si on augmente mon salaire.', it: 'Sono disposto ad assumermi più responsabilità se mi aumentano lo stipendio.', pt: 'Estou disposto a assumir mais responsabilidade se aumentarem o meu salário.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['capaz', 'exigente', 'arriesgado'] },
  { id: 'es3s020', de: 'Es decir, el esfuerzo vale la pena aunque los resultados tarden.', en: 'That is to say, the effort is worth it even if the results take time.', gloss: { de: 'Das heißt, die Mühe lohnt sich, auch wenn die Ergebnisse auf sich warten lassen.', fr: 'C’est-à-dire que l’effort en vaut la peine même si les résultats tardent.', it: 'Cioè, ne vale la pena anche se i risultati tardano.', pt: 'Ou seja, o esforço vale a pena mesmo que os resultados demorem.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['porque', 'cuando', 'mientras'] },
  { id: 'es3s021', de: 'Es probable que la crisis dure varios años.', en: 'The crisis is likely to last several years.', gloss: { de: 'Wahrscheinlich wird die Krise mehrere Jahre dauern.', fr: 'Il est probable que la crise dure plusieurs années.', it: 'È probabile che la crisi duri diversi anni.', pt: 'É provável que a crise dure vários anos.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['dura', 'duraba', 'durará'] },
  { id: 'es3s022', de: 'No creo que subir los impuestos resuelva el problema.', en: 'I don’t think raising taxes will solve the problem.', gloss: { de: 'Ich glaube nicht, dass Steuererhöhungen das Problem lösen.', fr: 'Je ne crois pas qu’augmenter les impôts résolve le problème.', it: 'Non credo che aumentare le tasse risolva il problema.', pt: 'Não acho que aumentar os impostos resolva o problema.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['resuelve', 'resolvía', 'resolverá'] },
  { id: 'es3s023', de: 'El alquiler ha subido tanto que muchos jóvenes no pueden independizarse.', en: 'Rent has risen so much that many young people cannot move out on their own.', gloss: { de: 'Die Mieten sind so stark gestiegen, dass viele junge Leute nicht ausziehen können.', fr: 'Les loyers ont tellement augmenté que beaucoup de jeunes ne peuvent pas prendre leur indépendance.', it: 'Gli affitti sono aumentati così tanto che molti giovani non riescono a rendersi indipendenti.', pt: 'O aluguel subiu tanto que muitos jovens não conseguem sair da casa dos pais.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['préstamo', 'consumo', 'patrimonio'] },
  { id: 'es3s024', de: 'Puesto que el sueldo no compensa, ha rechazado la oferta.', en: 'Since the salary isn’t worth it, she has turned down the offer.', gloss: { de: 'Da das Gehalt sich nicht lohnt, hat sie das Angebot abgelehnt.', fr: 'Puisque le salaire n’en vaut pas la peine, elle a refusé l’offre.', it: 'Poiché lo stipendio non è conveniente, ha rifiutato l’offerta.', pt: 'Uma vez que o salário não compensa, ela recusou a oferta.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['aceptado', 'firmado', 'buscado'] },
  { id: 'es3s025', de: 'A menos que ahorremos más, no podremos invertir este año.', en: 'Unless we save more, we won’t be able to invest this year.', gloss: { de: 'Wenn wir nicht mehr sparen, können wir dieses Jahr nicht investieren.', fr: 'À moins que nous n’économisions plus, nous ne pourrons pas investir cette année.', it: 'A meno che non risparmiamo di più, quest’anno non potremo investire.', pt: 'A menos que economizemos mais, não poderemos investir este ano.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['ahorramos', 'ahorrábamos', 'ahorraremos'] },
  { id: 'es3s026', de: 'En cuanto tenga los datos, te mando el informe.', en: 'As soon as I have the data, I’ll send you the report.', gloss: { de: 'Sobald ich die Daten habe, schicke ich dir den Bericht.', fr: 'Dès que j’aurai les données, je t’envoie le rapport.', it: 'Non appena avrò i dati, ti mando la relazione.', pt: 'Assim que eu tiver os dados, te mando o relatório.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['tengo', 'tenía', 'tendré'] },
  { id: 'es3s027', de: 'Me preocupa que las empresas vendan nuestros datos sin permiso.', en: 'It worries me that companies sell our data without permission.', gloss: { de: 'Es beunruhigt mich, dass Firmen unsere Daten ohne Erlaubnis verkaufen.', fr: 'Ça m’inquiète que les entreprises vendent nos données sans autorisation.', it: 'Mi preoccupa che le aziende vendano i nostri dati senza permesso.', pt: 'Me preocupa que as empresas vendam nossos dados sem permissão.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['venden', 'vendían', 'venderán'] },
  { id: 'es3s028', de: 'La inteligencia artificial no sustituirá a los buenos profesores.', en: 'Artificial intelligence will not replace good teachers.', gloss: { de: 'Künstliche Intelligenz wird gute Lehrer nicht ersetzen.', fr: 'L’intelligence artificielle ne remplacera pas les bons professeurs.', it: 'L’intelligenza artificiale non sostituirà i bravi insegnanti.', pt: 'A inteligência artificial não substituirá os bons professores.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['apoyará', 'formará', 'contratará'] },
  { id: 'es3s029', de: 'De hecho, muchos usuarios ni siquiera leen las condiciones.', en: 'In fact, many users don’t even read the terms.', gloss: { de: 'Tatsächlich lesen viele Nutzer nicht einmal die Bedingungen.', fr: 'En fait, beaucoup d’utilisateurs ne lisent même pas les conditions.', it: 'In effetti, molti utenti non leggono nemmeno le condizioni.', pt: 'De fato, muitos usuários nem sequer leem as condições.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['ciudadanos', 'periodistas', 'escritores'] },
  { id: 'es3s030', de: 'Es una herramienta útil siempre que se use con cabeza.', en: 'It is a useful tool as long as it is used sensibly.', gloss: { de: 'Es ist ein nützliches Werkzeug, sofern man es mit Verstand benutzt.', fr: 'C’est un outil utile à condition qu’on l’utilise intelligemment.', it: 'È uno strumento utile purché venga usato con criterio.', pt: 'É uma ferramenta útil desde que seja usada com bom senso.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['usa', 'usaba', 'usará'] },
  { id: 'es3s031', de: 'Si durmiera mejor, rendiría más en el trabajo.', en: 'If I slept better, I would perform better at work.', gloss: { de: 'Wenn ich besser schlafen würde, wäre ich bei der Arbeit leistungsfähiger.', fr: 'Si je dormais mieux, je serais plus performant au travail.', it: 'Se dormissi meglio, renderei di più al lavoro.', pt: 'Se eu dormisse melhor, renderia mais no trabalho.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['duermo', 'dormía', 'dormiré'] },
  { id: 'es3s032', de: 'El médico insistió en que cambiara mi alimentación.', en: 'The doctor insisted that I change my diet.', gloss: { de: 'Der Arzt bestand darauf, dass ich meine Ernährung umstelle.', fr: 'Le médecin a insisté pour que je change mon alimentation.', it: 'Il medico ha insistito perché cambiassi alimentazione.', pt: 'O médico insistiu que eu mudasse minha alimentação.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['cambio', 'cambié', 'cambiaré'] },
  { id: 'es3s033', de: 'El estrés continuo puede provocar enfermedades graves.', en: 'Continuous stress can cause serious illnesses.', gloss: { de: 'Dauerstress kann schwere Krankheiten verursachen.', fr: 'Le stress continu peut provoquer des maladies graves.', it: 'Lo stress continuo può provocare malattie gravi.', pt: 'O estresse contínuo pode provocar doenças graves.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['bienestar', 'patrimonio', 'consumo'] },
  { id: 'es3s034', de: 'Conviene prevenir antes de que el problema se agrave.', en: 'It is best to take precautions before the problem gets worse.', gloss: { de: 'Man sollte vorbeugen, bevor sich das Problem verschlimmert.', fr: 'Il vaut mieux prévenir avant que le problème ne s’aggrave.', it: 'Conviene prevenire prima che il problema peggiori.', pt: 'Convém prevenir antes que o problema se agrave.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['padecer', 'rechazar', 'gastar'] },
  { id: 'es3s035', de: 'Al fin y al cabo, la salud importa más que el dinero.', en: 'After all, health matters more than money.', gloss: { de: 'Letzten Endes ist Gesundheit wichtiger als Geld.', fr: 'Après tout, la santé compte plus que l’argent.', it: 'In fin dei conti, la salute conta più del denaro.', pt: 'Afinal de contas, a saúde importa mais que o dinheiro.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['deuda', 'crítica', 'obra'] },
  { id: 'es3s036', de: 'Aunque la crítica fue dura, la obra sigue llenando el teatro.', en: 'Although the review was harsh, the play still fills the theatre.', gloss: { de: 'Obwohl die Kritik hart war, füllt das Stück weiterhin das Theater.', fr: 'Bien que la critique ait été dure, la pièce remplit toujours le théâtre.', it: 'Anche se la critica è stata dura, l’opera continua a riempire il teatro.', pt: 'Embora a crítica tenha sido dura, a peça continua lotando o teatro.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['novela', 'exposición', 'carrera'] },
  { id: 'es3s037', de: 'La exposición se inaugurará en cuanto termine la reforma del museo.', en: 'The exhibition will open as soon as the museum refurbishment is finished.', gloss: { de: 'Die Ausstellung wird eröffnet, sobald der Umbau des Museums fertig ist.', fr: 'L’exposition ouvrira dès que la rénovation du musée sera terminée.', it: 'La mostra sarà inaugurata non appena finiranno i lavori del museo.', pt: 'A exposição será aberta assim que terminar a reforma do museu.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['termina', 'terminaba', 'terminará'] },
  { id: 'es3s038', de: 'Ese escritor logró que su novela se tradujera a diez idiomas.', en: 'That writer managed to get his novel translated into ten languages.', gloss: { de: 'Dieser Schriftsteller erreichte, dass sein Roman in zehn Sprachen übersetzt wurde.', fr: 'Cet écrivain a réussi à faire traduire son roman en dix langues.', it: 'Quello scrittore è riuscito a far tradurre il suo romanzo in dieci lingue.', pt: 'Aquele escritor conseguiu que seu romance fosse traduzido para dez idiomas.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['impidió', 'supuso', 'rechazó'] },
  { id: 'es3s039', de: 'El público aplaudió de pie durante varios minutos.', en: 'The audience applauded standing for several minutes.', gloss: { de: 'Das Publikum applaudierte mehrere Minuten im Stehen.', fr: 'Le public a applaudi debout pendant plusieurs minutes.', it: 'Il pubblico ha applaudito in piedi per diversi minuti.', pt: 'O público aplaudiu de pé durante vários minutos.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['guion', 'patrimonio', 'usuario'] },
  { id: 'es3s040', de: 'Por supuesto que apoyo la propuesta, pero exijo más detalles.', en: 'Of course I support the proposal, but I demand more details.', gloss: { de: 'Natürlich unterstütze ich den Vorschlag, aber ich verlange mehr Einzelheiten.', fr: 'Bien sûr que je soutiens la proposition, mais j’exige plus de détails.', it: 'Certo che sostengo la proposta, ma esigo più dettagli.', pt: 'Com certeza apoio a proposta, mas exijo mais detalhes.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['rechazo', 'impido', 'supongo'] },
  { id: 'es3s041', de: 'Nadie planteó la cuestión hasta que surgió el conflicto.', en: 'Nobody raised the issue until the conflict arose.', gloss: { de: 'Niemand warf die Frage auf, bis der Konflikt entstand.', fr: 'Personne n’a soulevé la question avant que le conflit ne surgisse.', it: 'Nessuno ha posto la questione finché non è sorto il conflitto.', pt: 'Ninguém levantou a questão até que surgiu o conflito.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['reconoció', 'difundió', 'convenció'] },
  { id: 'es3s042', de: 'En realidad, el problema no es técnico sino político.', en: 'Actually, the problem is not technical but political.', gloss: { de: 'Eigentlich ist das Problem nicht technisch, sondern politisch.', fr: 'En réalité, le problème n’est pas technique mais politique.', it: 'In realtà, il problema non è tecnico ma politico.', pt: 'Na verdade, o problema não é técnico, mas político.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['económico', 'cultural', 'legal'] },
  { id: 'es3s043', de: 'Las autoridades deberían fomentar el transporte público.', en: 'The authorities should promote public transport.', gloss: { de: 'Die Behörden sollten den öffentlichen Verkehr fördern.', fr: 'Les autorités devraient encourager les transports publics.', it: 'Le autorità dovrebbero promuovere il trasporto pubblico.', pt: 'As autoridades deveriam fomentar o transporte público.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['impedir', 'sustituir', 'padecer'] },
  { id: 'es3s044', de: 'Nada impide que la ciudad invierta en carriles bici.', en: 'Nothing prevents the city from investing in bike lanes.', gloss: { de: 'Nichts hindert die Stadt daran, in Radwege zu investieren.', fr: 'Rien n’empêche la ville d’investir dans des pistes cyclables.', it: 'Niente impedisce alla città di investire in piste ciclabili.', pt: 'Nada impede que a cidade invista em ciclovias.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['invierte', 'invertía', 'invertirá'] },
  { id: 'es3s045', de: 'De todos modos, habrá que revisar el contrato antes de firmarlo.', en: 'Anyway, the contract will have to be reviewed before signing it.', gloss: { de: 'Jedenfalls muss der Vertrag vor der Unterschrift geprüft werden.', fr: 'De toute façon, il faudra revoir le contrat avant de le signer.', it: 'Comunque, bisognerà rivedere il contratto prima di firmarlo.', pt: 'De qualquer forma, será preciso revisar o contrato antes de assiná-lo.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['plazo', 'ascenso', 'puesto'] },
  { id: 'es3s046', de: 'Supongo que el aumento del consumo explica parte del problema.', en: 'I suppose the rise in consumption explains part of the problem.', gloss: { de: 'Ich nehme an, dass der gestiegene Konsum einen Teil des Problems erklärt.', fr: 'Je suppose que la hausse de la consommation explique une partie du problème.', it: 'Suppongo che l’aumento dei consumi spieghi parte del problema.', pt: 'Suponho que o aumento do consumo explique parte do problema.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['desempleo', 'reciclaje', 'bienestar'] },
  { id: 'es3s047', de: 'Por cierto, el banco me ha concedido el préstamo.', en: 'By the way, the bank has granted me the loan.', gloss: { de: 'Übrigens, die Bank hat mir den Kredit bewilligt.', fr: 'Au fait, la banque m’a accordé le prêt.', it: 'A proposito, la banca mi ha concesso il prestito.', pt: 'A propósito, o banco me concedeu o empréstimo.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['gobierno', 'ministerio', 'comité'] },
  { id: 'es3s048', de: 'Es una pena que tanta gente padezca soledad en las ciudades.', en: 'It is a shame that so many people suffer loneliness in cities.', gloss: { de: 'Es ist schade, dass so viele Menschen in den Städten unter Einsamkeit leiden.', fr: 'C’est dommage que tant de gens souffrent de solitude dans les villes.', it: 'È un peccato che tanta gente soffra di solitudine nelle città.', pt: 'É uma pena que tanta gente sofra de solidão nas cidades.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['padece', 'padecía', 'padecerá'] },
  { id: 'es3s049', de: 'Dudo que este dispositivo funcione sin conexión.', en: 'I doubt that this device works offline.', gloss: { de: 'Ich bezweifle, dass dieses Gerät ohne Verbindung funktioniert.', fr: 'Je doute que cet appareil fonctionne hors connexion.', it: 'Dubito che questo dispositivo funzioni senza connessione.', pt: 'Duvido que este dispositivo funcione sem conexão.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['funciona', 'funcionaba', 'funcionará'] },
  { id: 'es3s050', de: 'La investigación demuestra que dormir poco afecta al rendimiento.', en: 'Research shows that sleeping little affects performance.', gloss: { de: 'Die Forschung zeigt, dass wenig Schlaf die Leistung beeinträchtigt.', fr: 'La recherche montre que dormir peu affecte les performances.', it: 'La ricerca dimostra che dormire poco influisce sul rendimento.', pt: 'A pesquisa mostra que dormir pouco afeta o desempenho.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['publicidad', 'costumbre', 'vergüenza'] },
  { id: 'es3s051', de: 'Este avance permitirá desarrollar tratamientos más eficaces.', en: 'This breakthrough will make it possible to develop more effective treatments.', gloss: { de: 'Dieser Fortschritt wird es ermöglichen, wirksamere Behandlungen zu entwickeln.', fr: 'Cette avancée permettra de développer des traitements plus efficaces.', it: 'Questo progresso permetterà di sviluppare trattamenti più efficaci.', pt: 'Este avanço permitirá desenvolver tratamentos mais eficazes.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['riesgo', 'rumor', 'enfado'] },
  { id: 'es3s052', de: 'Si el gobierno bajara los impuestos, aumentaría la inversión privada.', en: 'If the government lowered taxes, private investment would rise.', gloss: { de: 'Wenn die Regierung die Steuern senken würde, würden die privaten Investitionen steigen.', fr: 'Si le gouvernement baissait les impôts, l’investissement privé augmenterait.', it: 'Se il governo abbassasse le tasse, aumenterebbero gli investimenti privati.', pt: 'Se o governo baixasse os impostos, aumentaria o investimento privado.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['baja', 'bajaba', 'bajará'] },
  { id: 'es3s053', de: 'Muchas familias siguen pagando deudas de la crisis anterior.', en: 'Many families are still paying off debts from the previous crisis.', gloss: { de: 'Viele Familien zahlen noch Schulden aus der letzten Krise ab.', fr: 'Beaucoup de familles remboursent encore des dettes de la crise précédente.', it: 'Molte famiglie stanno ancora pagando i debiti della crisi precedente.', pt: 'Muitas famílias ainda estão pagando dívidas da crise anterior.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['facturas', 'multas', 'ayudas'] },
  { id: 'es3s054', de: 'Destaca sobre todo la calidad del guion.', en: 'What stands out above all is the quality of the screenplay.', gloss: { de: 'Hervor sticht vor allem die Qualität des Drehbuchs.', fr: 'Ce qui ressort surtout, c’est la qualité du scénario.', it: 'Spicca soprattutto la qualità della sceneggiatura.', pt: 'Destaca-se sobretudo a qualidade do roteiro.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Sorprende', 'Preocupa', 'Convence'] },
  { id: 'es3s055', de: 'Interpretar ese papel exige mucha preparación.', en: 'Playing that role demands a lot of preparation.', gloss: { de: 'Diese Rolle zu spielen erfordert viel Vorbereitung.', fr: 'Interpréter ce rôle exige beaucoup de préparation.', it: 'Interpretare quel ruolo richiede molta preparazione.', pt: 'Interpretar esse papel exige muita preparação.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['impide', 'sustituye', 'rechaza'] },
  { id: 'es3s056', de: 'El patrimonio histórico se pierde cuando nadie lo protege.', en: 'Historic heritage is lost when nobody protects it.', gloss: { de: 'Das historische Erbe geht verloren, wenn niemand es schützt.', fr: 'Le patrimoine historique se perd quand personne ne le protège.', it: 'Il patrimonio storico si perde quando nessuno lo protegge.', pt: 'O patrimônio histórico se perde quando ninguém o protege.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['aprendizaje', 'desempleo', 'rendimiento'] },
  { id: 'es3s057', de: 'Ni siquiera los expertos se ponen de acuerdo sobre las causas.', en: 'Not even the experts agree on the causes.', gloss: { de: 'Nicht einmal die Fachleute sind sich über die Ursachen einig.', fr: 'Même les experts ne s’accordent pas sur les causes.', it: 'Nemmeno gli esperti sono d’accordo sulle cause.', pt: 'Nem sequer os especialistas concordam sobre as causas.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['periodistas', 'ciudadanos', 'escritores'] },
  { id: 'es3s058', de: 'Le pedí que me apoyara delante del comité.', en: 'I asked him to back me up in front of the committee.', gloss: { de: 'Ich bat ihn, mich vor dem Ausschuss zu unterstützen.', fr: 'Je lui ai demandé de me soutenir devant le comité.', it: 'Gli ho chiesto di sostenermi davanti al comitato.', pt: 'Pedi a ele que me apoiasse diante do comitê.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['apoya', 'apoyaba', 'apoyará'] },
  { id: 'es3s059', de: 'Una alimentación sana previene muchas enfermedades.', en: 'A healthy diet prevents many illnesses.', gloss: { de: 'Eine gesunde Ernährung beugt vielen Krankheiten vor.', fr: 'Une alimentation saine prévient beaucoup de maladies.', it: 'Un’alimentazione sana previene molte malattie.', pt: 'Uma alimentação saudável previne muitas doenças.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['provoca', 'padece', 'sustituye'] },
  { id: 'es3s060', de: 'Es evidente que la privacidad se ha convertido en un lujo.', en: 'It is clear that privacy has become a luxury.', gloss: { de: 'Es ist offensichtlich, dass Privatsphäre zu einem Luxus geworden ist.', fr: 'Il est évident que la vie privée est devenue un luxe.', it: 'È evidente che la riservatezza è diventata un lusso.', pt: 'É evidente que a privacidade se tornou um luxo.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['igualdad', 'libertad', 'confianza'] },
];
