import type { SentenceItem } from '@/content/german/types';

// Italian A1 sentences. `de` holds the Italian text. clozeIndex targets the
// load-bearing word (never the article), and clozeDistractors are same-class
// words that would be grammatical but wrong — so the exercise tests meaning,
// not pattern-matching on word shape.
//
// `gloss` carries the non-English UI locales; see a1-vocab.ts for the rule.

export const A1_SENTENCES: SentenceItem[] = [
  { id: 'it1s001', de: 'Buongiorno, come va?', en: 'Good morning, how’s it going?', gloss: { de: 'Guten Morgen, wie geht’s?', es: 'Buenos días, ¿qué tal?', fr: 'Bonjour, ça va ?', pt: 'Bom dia, tudo bem?' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['chi', 'dove', 'quanto'] },
  { id: 'it1s002', de: 'Voglio un caffè, per favore.', en: 'I want a coffee, please.', gloss: { de: 'Ich möchte einen Kaffee, bitte.', es: 'Quiero un café, por favor.', fr: 'Je veux un café, s’il vous plaît.', pt: 'Quero um café, por favor.' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Mangio', 'Parlo', 'Compro'] },
  { id: 'it1s003', de: 'Dov’è il bagno?', en: 'Where is the bathroom?', gloss: { de: 'Wo ist die Toilette?', es: '¿Dónde está el baño?', fr: 'Où sont les toilettes ?', pt: 'Onde fica o banheiro?' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Cos’è', 'Quant’è', 'Perché'] },
  { id: 'it1s004', de: 'Vivo a Roma.', en: 'I live in Rome.', gloss: { de: 'Ich wohne in Rom.', es: 'Vivo en Roma.', fr: 'J’habite à Rome.', pt: 'Moro em Roma.' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Lavoro', 'Mangio', 'Parlo'] },
  { id: 'it1s005', de: 'Quanto costa la birra?', en: 'How much does the beer cost?', gloss: { de: 'Wie viel kostet das Bier?', es: '¿Cuánto cuesta la cerveza?', fr: 'Combien coûte la bière ?', pt: 'Quanto custa a cerveja?' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Dove', 'Chi', 'Come'] },
  { id: 'it1s006', de: 'Il cibo è molto buono.', en: 'The food is very good.', gloss: { de: 'Das Essen ist sehr gut.', es: 'La comida está muy buena.', fr: 'La nourriture est très bonne.', pt: 'A comida está muito boa.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['vino', 'pane', 'pesce'] },
  { id: 'it1s007', de: 'Non parlo bene l’italiano.', en: 'I don’t speak Italian well.', gloss: { de: 'Ich spreche nicht gut Italienisch.', es: 'No hablo bien italiano.', fr: 'Je ne parle pas bien italien.', pt: 'Não falo bem italiano.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['mangio', 'lavoro', 'capisco'] },
  { id: 'it1s008', de: 'Oggi vado a lavorare.', en: 'Today I am going to work.', gloss: { de: 'Heute gehe ich arbeiten.', es: 'Hoy voy a trabajar.', fr: 'Aujourd’hui je vais travailler.', pt: 'Hoje eu vou trabalhar.' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Ieri', 'Domani', 'Adesso'] },
  { id: 'it1s009', de: 'Lei ha una sorella piccola.', en: 'She has a little sister.', gloss: { de: 'Sie hat eine kleine Schwester.', es: 'Ella tiene una hermana pequeña.', fr: 'Elle a une petite sœur.', pt: 'Ela tem uma irmã pequena.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['figlia', 'amica', 'zia'] },
  { id: 'it1s010', de: 'La spiaggia è molto bella.', en: 'The beach is very beautiful.', gloss: { de: 'Der Strand ist sehr schön.', es: 'La playa es muy bonita.', fr: 'La plage est très belle.', pt: 'A praia é muito bonita.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['città', 'scuola', 'strada'] },
  { id: 'it1s011', de: 'Il ristorante è molto caro.', en: 'The restaurant is very expensive.', gloss: { de: 'Das Restaurant ist sehr teuer.', es: 'El restaurante es muy caro.', fr: 'Le restaurant est très cher.', pt: 'O restaurante é muito caro.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['negozio', 'mercato', 'bagno'] },
  { id: 'it1s012', de: 'Domani vado al mercato.', en: 'Tomorrow I am going to the market.', gloss: { de: 'Morgen gehe ich zum Markt.', es: 'Mañana voy al mercado.', fr: 'Demain je vais au marché.', pt: 'Amanhã eu vou ao mercado.' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Ieri', 'Adesso', 'Sempre'] },
  { id: 'it1s013', de: 'Mia madre lavora in un negozio.', en: 'My mother works in a shop.', gloss: { de: 'Meine Mutter arbeitet in einem Laden.', es: 'Mi madre trabaja en una tienda.', fr: 'Ma mère travaille dans un magasin.', pt: 'Minha mãe trabalha numa loja.' }, level: 'A1', clozeIndex: 2, clozeDistractors: ['vive', 'mangia', 'parla'] },
  { id: 'it1s014', de: 'Non capisco la domanda.', en: 'I don’t understand the question.', gloss: { de: 'Ich verstehe die Frage nicht.', es: 'No entiendo la pregunta.', fr: 'Je ne comprends pas la question.', pt: 'Não entendo a pergunta.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['parlo', 'voglio', 'mangio'] },
  { id: 'it1s015', de: 'La casa è grande e nuova.', en: 'The house is big and new.', gloss: { de: 'Das Haus ist groß und neu.', es: 'La casa es grande y nueva.', fr: 'La maison est grande et neuve.', pt: 'A casa é grande e nova.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['piccola', 'vecchia', 'cara'] },
  { id: 'it1s016', de: 'Ho due fratelli.', en: 'I have two brothers.', gloss: { de: 'Ich habe zwei Brüder.', es: 'Tengo dos hermanos.', fr: 'J’ai deux frères.', pt: 'Tenho dois irmãos.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['tre', 'cinque', 'dieci'] },
  { id: 'it1s017', de: 'Il bambino beve il latte.', en: 'The child drinks the milk.', gloss: { de: 'Das Kind trinkt die Milch.', es: 'El niño bebe la leche.', fr: 'L’enfant boit le lait.', pt: 'A criança bebe o leite.' }, level: 'A1', clozeIndex: 2, clozeDistractors: ['mangia', 'compra', 'vuole'] },
  { id: 'it1s018', de: 'Perché sei stanco?', en: 'Why are you tired?', gloss: { de: 'Warum bist du müde?', es: '¿Por qué estás cansado?', fr: 'Pourquoi es-tu fatigué ?', pt: 'Por que você está cansado?' }, level: 'A1', clozeIndex: 0, clozeDistractors: ['Quando', 'Dove', 'Come'] },
  { id: 'it1s019', de: 'Il conto, per favore.', en: 'The bill, please.', gloss: { de: 'Die Rechnung, bitte.', es: 'La cuenta, por favor.', fr: 'L’addition, s’il vous plaît.', pt: 'A conta, por favor.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['pane', 'caffè', 'vino'] },
  { id: 'it1s020', de: 'Mangio sempre il pane la mattina.', en: 'I always eat bread in the morning.', gloss: { de: 'Ich esse morgens immer Brot.', es: 'Siempre como pan por la mañana.', fr: 'Je mange toujours du pain le matin.', pt: 'Sempre como pão de manhã.' }, level: 'A1', clozeIndex: 1, clozeDistractors: ['mai', 'oggi', 'domani'] },
  { id: 'it1s021', de: 'Lo studente parla italiano.', en: 'The student speaks Italian.', gloss: { de: 'Der Student spricht Italienisch.', es: 'El estudiante habla italiano.', fr: 'L’étudiant parle italien.', pt: 'O estudante fala italiano.' }, level: 'A1', clozeIndex: 2, clozeDistractors: ['mangia', 'compra', 'capisce'] },
  { id: 'it1s022', de: 'Ho fame e voglio mangiare.', en: 'I am hungry and I want to eat.', gloss: { de: 'Ich habe Hunger und will essen.', es: 'Tengo hambre y quiero comer.', fr: 'J’ai faim et je veux manger.', pt: 'Estou com fome e quero comer.' }, level: 'A1', clozeIndex: 3, clozeDistractors: ['posso', 'devo', 'preferisco'] },
];
