import type { SentenceItem } from '@/content/german/types';

// Italian A2 sentences. `de` holds the Italian text. Where A1 stayed in the
// present tense, A2 leans on the passato prossimo — including the essere/avere
// split and the participle agreement that comes with it (è arrivato, è finita,
// mi sono lavato) — plus reflexives, modals and comparatives.
//
// clozeIndex is a 0-based index into de.split(' ') and always lands on the
// load-bearing word, never an article. clozeDistractors are same-class words
// that would parse but mean something else, so the exercise tests meaning.
//
// `gloss` carries the non-English UI locales; see a2-vocab.ts for the rule.

export const A2_SENTENCES: SentenceItem[] = [
  { id: 'it2s001', de: 'Ieri ho preso il treno per Milano.', en: 'Yesterday I took the train to Milan.', gloss: { de: 'Gestern habe ich den Zug nach Mailand genommen.', es: 'Ayer tomé el tren a Milán.', fr: 'Hier j’ai pris le train pour Milan.', pt: 'Ontem peguei o trem para Milão.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['perso', 'comprato', 'venduto'] },
  { id: 'it2s002', de: 'Stamattina mi sono svegliato alle sette.', en: 'This morning I woke up at seven.', gloss: { de: 'Heute Morgen bin ich um sieben aufgewacht.', es: 'Esta mañana me desperté a las siete.', fr: 'Ce matin je me suis réveillé à sept heures.', pt: 'Hoje de manhã acordei às sete.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['addormentato', 'seduto', 'arrabbiato'] },
  { id: 'it2s003', de: 'Sabato scorso abbiamo mangiato al ristorante.', en: 'Last Saturday we ate at the restaurant.', gloss: { de: 'Letzten Samstag haben wir im Restaurant gegessen.', es: 'El sábado pasado comimos en el restaurante.', fr: 'Samedi dernier nous avons mangé au restaurant.', pt: 'No sábado passado comemos no restaurante.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['dormito', 'lavorato', 'pagato'] },
  { id: 'it2s004', de: 'Ho dimenticato le chiavi a casa.', en: 'I forgot the keys at home.', gloss: { de: 'Ich habe die Schlüssel zu Hause vergessen.', es: 'Olvidé las llaves en casa.', fr: 'J’ai oublié les clés à la maison.', pt: 'Esqueci as chaves em casa.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['trovato', 'comprato', 'pulito'] },
  { id: 'it2s005', de: 'L’aereo è arrivato in ritardo.', en: 'The plane arrived late.', gloss: { de: 'Das Flugzeug ist mit Verspätung angekommen.', es: 'El avión llegó tarde.', fr: 'L’avion est arrivé en retard.', pt: 'O avião chegou atrasado.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['partito', 'uscito', 'tornato'] },
  { id: 'it2s006', de: 'Quanto hai pagato questi pantaloni?', en: 'How much did you pay for these trousers?', gloss: { de: 'Wie viel hast du für diese Hose bezahlt?', es: '¿Cuánto pagaste por estos pantalones?', fr: 'Combien as-tu payé ce pantalon ?', pt: 'Quanto você pagou por essas calças?' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['venduto', 'portato', 'cercato'] },
  { id: 'it2s007', de: 'Ieri ha piovuto tutto il giorno.', en: 'Yesterday it rained all day.', gloss: { de: 'Gestern hat es den ganzen Tag geregnet.', es: 'Ayer llovió todo el día.', fr: 'Hier il a plu toute la journée.', pt: 'Ontem choveu o dia todo.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['nevicato', 'dormito', 'lavorato'] },
  { id: 'it2s008', de: 'Non posso uscire, devo studiare.', en: 'I can’t go out, I have to study.', gloss: { de: 'Ich kann nicht ausgehen, ich muss lernen.', es: 'No puedo salir, tengo que estudiar.', fr: 'Je ne peux pas sortir, je dois étudier.', pt: 'Não posso sair, tenho que estudar.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['riesco', 'spero', 'penso'] },
  { id: 'it2s009', de: 'Mi fa male la testa e ho la febbre.', en: 'My head hurts and I have a fever.', gloss: { de: 'Mir tut der Kopf weh und ich habe Fieber.', es: 'Me duele la cabeza y tengo fiebre.', fr: 'J’ai mal à la tête et j’ai de la fièvre.', pt: 'Estou com dor de cabeça e com febre.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['mano', 'gamba', 'schiena'] },
  { id: 'it2s010', de: 'Sono andato dal medico ieri mattina.', en: 'I went to the doctor yesterday morning.', gloss: { de: 'Ich bin gestern Morgen zum Arzt gegangen.', es: 'Fui al médico ayer por la mañana.', fr: 'Je suis allé chez le médecin hier matin.', pt: 'Fui ao médico ontem de manhã.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['dentista', 'capo', 'cameriere'] },
  { id: 'it2s011', de: 'Ho comprato un biglietto per l’aereo.', en: 'I bought a plane ticket.', gloss: { de: 'Ich habe eine Flugkarte gekauft.', es: 'Compré un billete de avión.', fr: 'J’ai acheté un billet d’avion.', pt: 'Comprei uma passagem de avião.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['passaporto', 'ombrello', 'bicchiere'] },
  { id: 'it2s012', de: 'Sono preoccupato per l’esame di domani.', en: 'I am worried about tomorrow’s exam.', gloss: { de: 'Ich bin wegen der Prüfung morgen besorgt.', es: 'Estoy preocupado por el examen de mañana.', fr: 'Je suis inquiet pour l’examen de demain.', pt: 'Estou preocupado com o exame de amanhã.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['arrabbiato', 'contento', 'tranquillo'] },
  { id: 'it2s013', de: 'Il treno è più veloce dell’autobus.', en: 'The train is faster than the bus.', gloss: { de: 'Der Zug ist schneller als der Bus.', es: 'El tren es más rápido que el autobús.', fr: 'Le train est plus rapide que le bus.', pt: 'O trem é mais rápido que o ônibus.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['lento', 'pulito', 'pieno'] },
  { id: 'it2s014', de: 'Ieri sera sono tornato a casa tardi.', en: 'Last night I came home late.', gloss: { de: 'Gestern Abend bin ich spät nach Hause gekommen.', es: 'Anoche volví a casa tarde.', fr: 'Hier soir je suis rentré tard à la maison.', pt: 'Ontem à noite voltei para casa tarde.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['uscito', 'caduto', 'salito'] },
  { id: 'it2s015', de: 'Di solito faccio colazione alle otto.', en: 'I usually have breakfast at eight.', gloss: { de: 'Normalerweise frühstücke ich um acht.', es: 'Normalmente desayuno a las ocho.', fr: 'D’habitude je prends le petit-déjeuner à huit heures.', pt: 'Normalmente tomo o café da manhã às oito.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['mangio', 'bevo', 'porto'] },
  { id: 'it2s016', de: 'Ho perso il passaporto in aeroporto.', en: 'I lost my passport at the airport.', gloss: { de: 'Ich habe meinen Reisepass am Flughafen verloren.', es: 'Perdí el pasaporte en el aeropuerto.', fr: 'J’ai perdu mon passeport à l’aéroport.', pt: 'Perdi o passaporte no aeroporto.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['trovato', 'pagato', 'aperto'] },
  { id: 'it2s017', de: 'Che tempo fa oggi?', en: 'What’s the weather like today?', gloss: { de: 'Wie ist das Wetter heute?', es: '¿Qué tiempo hace hoy?', fr: 'Quel temps fait-il aujourd’hui ?', pt: 'Como está o tempo hoje?' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['giorno', 'mese', 'anno'] },
  { id: 'it2s018', de: 'Sono stanco perché ho dormito poco.', en: 'I am tired because I slept little.', gloss: { de: 'Ich bin müde, weil ich wenig geschlafen habe.', es: 'Estoy cansado porque dormí poco.', fr: 'Je suis fatigué parce que j’ai peu dormi.', pt: 'Estou cansado porque dormi pouco.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['mangiato', 'lavorato', 'letto'] },
  { id: 'it2s019', de: 'Mi sono lavato le mani prima di cena.', en: 'I washed my hands before dinner.', gloss: { de: 'Ich habe mir vor dem Abendessen die Hände gewaschen.', es: 'Me lavé las manos antes de la cena.', fr: 'Je me suis lavé les mains avant le dîner.', pt: 'Lavei as mãos antes do jantar.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['vestito', 'pettinato', 'alzato'] },
  { id: 'it2s020', de: 'La riunione è finita alle sei.', en: 'The meeting ended at six.', gloss: { de: 'Die Besprechung ist um sechs zu Ende gegangen.', es: 'La reunión terminó a las seis.', fr: 'La réunion s’est terminée à six heures.', pt: 'A reunião terminou às seis.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['lezione', 'cena', 'partita'] },
  { id: 'it2s021', de: 'Ho scritto un messaggio al mio capo.', en: 'I wrote a message to my boss.', gloss: { de: 'Ich habe meinem Chef eine Nachricht geschrieben.', es: 'Le escribí un mensaje a mi jefe.', fr: 'J’ai écrit un message à mon chef.', pt: 'Escrevi uma mensagem para o meu chefe.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['letto', 'aperto', 'chiesto'] },
  { id: 'it2s022', de: 'Non ho mai visto la neve in vita mia.', en: 'I have never seen snow in my life.', gloss: { de: 'Ich habe in meinem Leben noch nie Schnee gesehen.', es: 'Nunca he visto la nieve en mi vida.', fr: 'Je n’ai jamais vu la neige de ma vie.', pt: 'Nunca vi neve na minha vida.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['pioggia', 'nuvola', 'montagna'] },
];
