import type { SentenceItem } from '@/content/german/types';

// Italian B1 sentences. `de` holds the Italian text. These are deliberately not
// simple SVO: subordinate clauses, the congiuntivo after verbs of opinion and
// after benché / sebbene / affinché, and opinion framing.
//
// clozeIndex targets the load-bearing word (never an article), and
// clozeDistractors are same-class words — congiuntivo forms against congiuntivo
// forms, connectors against connectors — so the exercise tests meaning rather
// than word shape.
//
// `gloss` carries the non-English UI locales; see b1-vocab.ts for the rule.

export const B1_SENTENCES: SentenceItem[] = [
  { id: 'it3s001', de: 'Penso che sia una decisione sbagliata.', en: 'I think it is a wrong decision.', gloss: { de: 'Ich finde, das ist eine falsche Entscheidung.', es: 'Creo que es una decisión equivocada.', fr: 'Je pense que c’est une mauvaise décision.', pt: 'Acho que é uma decisão errada.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['abbia', 'faccia', 'possa'] },
  { id: 'it3s002', de: 'Benché sia difficile, vale la pena provare.', en: 'Although it is difficult, it is worth trying.', gloss: { de: 'Obwohl es schwierig ist, lohnt es sich, es zu versuchen.', es: 'Aunque sea difícil, vale la pena intentarlo.', fr: 'Bien que ce soit difficile, ça vaut la peine d’essayer.', pt: 'Embora seja difícil, vale a pena tentar.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Perciò', 'Tuttavia', 'Inoltre'] },
  { id: 'it3s003', de: 'Secondo me il governo dovrebbe agire subito.', en: 'In my opinion the government should act immediately.', gloss: { de: 'Meiner Meinung nach sollte die Regierung sofort handeln.', es: 'En mi opinión el gobierno debería actuar de inmediato.', fr: 'À mon avis le gouvernement devrait agir tout de suite.', pt: 'Na minha opinião o governo deveria agir imediatamente.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['giornale', 'dibattito', 'stipendio'] },
  { id: 'it3s004', de: 'Non credo che l’azienda voglia assumere altri dipendenti.', en: 'I don’t think the company wants to hire more employees.', gloss: { de: 'Ich glaube nicht, dass die Firma weitere Mitarbeiter einstellen will.', es: 'No creo que la empresa quiera contratar a más empleados.', fr: 'Je ne crois pas que l’entreprise veuille embaucher d’autres employés.', pt: 'Não acho que a empresa queira contratar mais funcionários.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['possa', 'debba', 'sappia'] },
  { id: 'it3s005', de: 'L’inquinamento è aumentato nonostante le nuove leggi.', en: 'Pollution has increased despite the new laws.', gloss: { de: 'Die Verschmutzung ist trotz der neuen Gesetze gestiegen.', es: 'La contaminación ha aumentado a pesar de las nuevas leyes.', fr: 'La pollution a augmenté malgré les nouvelles lois.', pt: 'A poluição aumentou apesar das novas leis.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['secondo', 'durante', 'oltre'] },
  { id: 'it3s006', de: 'Bisogna ridurre i rifiuti, altrimenti il problema peggiorerà.', en: 'We have to reduce waste, otherwise the problem will get worse.', gloss: { de: 'Man muss den Müll reduzieren, sonst wird das Problem schlimmer.', es: 'Hay que reducir los residuos, si no el problema empeorará.', fr: 'Il faut réduire les déchets, sinon le problème va empirer.', pt: 'É preciso reduzir o lixo, senão o problema vai piorar.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['inoltre', 'tuttavia', 'quindi'] },
  { id: 'it3s007', de: 'Tuttavia non sono del tutto d’accordo con te.', en: 'However, I do not entirely agree with you.', gloss: { de: 'Ich bin jedoch nicht ganz deiner Meinung.', es: 'Sin embargo, no estoy del todo de acuerdo com você.', fr: 'Cependant, je ne suis pas entièrement d’accord avec toi.', pt: 'No entanto, não concordo totalmente com você.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Inoltre', 'Perciò', 'Quindi'] },
  { id: 'it3s008', de: 'Spero che il colloquio vada bene.', en: 'I hope the job interview goes well.', gloss: { de: 'Ich hoffe, dass das Vorstellungsgespräch gut läuft.', es: 'Espero que la entrevista vaya bien.', fr: 'J’espère que l’entretien se passera bien.', pt: 'Espero que a entrevista corra bem.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['finisca', 'sembri', 'riesca'] },
  { id: 'it3s009', de: 'È importante che i cittadini abbiano fiducia nelle istituzioni.', en: 'It is important that citizens have trust in institutions.', gloss: { de: 'Es ist wichtig, dass die Bürger Vertrauen in die Institutionen haben.', es: 'Es importante que los ciudadanos tengan confianza en las instituciones.', fr: 'Il est important que les citoyens aient confiance dans les institutions.', pt: 'É importante que os cidadãos tenham confiança nas instituições.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['possano', 'sappiano', 'vogliano'] },
  { id: 'it3s010', de: 'Il giornale ha pubblicato un sondaggio molto discutibile.', en: 'The newspaper published a very questionable poll.', gloss: { de: 'Die Zeitung hat eine sehr fragwürdige Umfrage veröffentlicht.', es: 'El periódico publicó una encuesta muy discutible.', fr: 'Le journal a publié un sondage très discutable.', pt: 'O jornal publicou uma pesquisa muito discutível.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['articolo', 'dibattito', 'parere'] },
  { id: 'it3s011', de: 'Sebbene sia giovane, ha molta esperienza.', en: 'Although he is young, he has a lot of experience.', gloss: { de: 'Obwohl er jung ist, hat er viel Erfahrung.', es: 'Aunque es joven, tiene mucha experiencia.', fr: 'Bien qu’il soit jeune, il a beaucoup d’expérience.', pt: 'Embora seja jovem, tem muita experiência.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Perciò', 'Inoltre', 'Quindi'] },
  { id: 'it3s012', de: 'Se avessi più tempo, approfondirei l’argomento.', en: 'If I had more time, I would study the topic in depth.', gloss: { de: 'Wenn ich mehr Zeit hätte, würde ich das Thema vertiefen.', es: 'Si tuviera más tiempo, profundizaría en el tema.', fr: 'Si j’avais plus de temps, j’approfondirais le sujet.', pt: 'Se eu tivesse mais tempo, aprofundaria o assunto.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['potessi', 'sapessi', 'trovassi'] },
  { id: 'it3s013', de: 'Mi rendo conto che la situazione è più complessa di quanto pensassi.', en: 'I realize that the situation is more complex than I thought.', gloss: { de: 'Mir ist klar, dass die Lage komplexer ist, als ich dachte.', es: 'Me doy cuenta de que la situación es más compleja de lo que pensaba.', fr: 'Je me rends compte que la situation est plus complexe que je ne pensais.', pt: 'Me dou conta de que a situação é mais complexa do que eu pensava.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['inevitabile', 'superficiale', 'urgente'] },
  { id: 'it3s014', de: 'Molti giovani rinunciano a un lavoro stabile per viaggiare.', en: 'Many young people give up a stable job in order to travel.', gloss: { de: 'Viele junge Leute verzichten auf einen festen Job, um zu reisen.', es: 'Muchos jóvenes renuncian a un trabajo estable para viajar.', fr: 'Beaucoup de jeunes renoncent à un emploi stable pour voyager.', pt: 'Muitos jovens renunciam a um emprego estável para viajar.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['cercano', 'evitano', 'accettano'] },
  { id: 'it3s015', de: 'Quindi è meglio affrontare il problema adesso.', en: 'So it is better to face the problem now.', gloss: { de: 'Also ist es besser, das Problem jetzt anzugehen.', es: 'Por lo tanto es mejor afrontar el problema ahora.', fr: 'Donc il vaut mieux affronter le problème maintenant.', pt: 'Portanto é melhor enfrentar o problema agora.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['evitare', 'proporre', 'impedire'] },
  { id: 'it3s016', de: 'Nonostante gli sforzi, la povertà continua crescendoe.', en: 'Despite the efforts, poverty keeps growing.', gloss: { de: 'Trotz der Bemühungen wächst die Armut weiter.', es: 'A pesar de los esfuerzos, la pobreza sigue creciendo.', fr: 'Malgré les efforts, la pauvreté continue d’augmenter.', pt: 'Apesar dos esforços, a pobreza continua crescendo.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['disoccupazione', 'pubblicità', 'libertà'] },
  { id: 'it3s017', de: 'Bisogna che tutti facciano la propria parte.', en: 'Everyone needs to do their part.', gloss: { de: 'Es ist nötig, dass alle ihren Teil beitragen.', es: 'Hace falta que todos hagan su parte.', fr: 'Il faut que chacun fasse sa part.', pt: 'É preciso que todos façam a sua parte.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['diano', 'sappiano', 'vogliano'] },
  { id: 'it3s018', de: 'L’energia rinnovabile è una scelta sostenibile per il futuro.', en: 'Renewable energy is a sustainable choice for the future.', gloss: { de: 'Erneuerbare Energie ist eine nachhaltige Entscheidung für die Zukunft.', es: 'La energía renovable es una opción sostenible para el futuro.', fr: 'L’énergie renouvelable est un choix durable pour l’avenir.', pt: 'A energia renovável é uma escolha sustentável para o futuro.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['efficace', 'urgente', 'affidabile'] },
  { id: 'it3s019', de: 'Ho l’impressione che nessuno voglia prendersi la responsabilità.', en: 'I have the impression that nobody wants to take responsibility.', gloss: { de: 'Ich habe den Eindruck, dass niemand die Verantwortung übernehmen will.', es: 'Tengo la impresión de que nadie quiere asumir la responsabilidad.', fr: 'J’ai l’impression que personne ne veut prendre la responsabilité.', pt: 'Tenho a impressão de que ninguém quer assumir a responsabilidade.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['qualcuno', 'ognuno', 'chiunque'] },
  { id: 'it3s020', de: 'Affinché il progetto riesca, serve l’impegno di tutti.', en: 'For the project to succeed, everyone’s commitment is needed.', gloss: { de: 'Damit das Projekt gelingt, braucht es das Engagement aller.', es: 'Para que el proyecto tenga éxito, hace falta el compromiso de todos.', fr: 'Pour que le projet réussisse, il faut l’engagement de tous.', pt: 'Para que o projeto tenha sucesso, é preciso o empenho de todos.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['funzioni', 'cresca', 'duri'] },
];
