import type { SentenceItem } from '@/content/german/types';

// Italian B2 sentences. `de` holds the Italian text. Where B1 defended an
// opinion, B2 qualifies one: congiuntivo across all four tenses, the three
// periodi ipotetici, the venire/andare passives (andare carrying obligation,
// not just voice), gerundio and forma impersonale, and the register shift
// between "non sono d'accordo" and "mi permetto di dissentire".
//
// clozeIndex targets the load-bearing word (never an article, never the last
// word of the sentence), and clozeDistractors are same-class words —
// congiuntivo against congiuntivo, connector against connector — so the
// exercise tests meaning rather than word shape.
//
// `gloss` carries the non-English UI locales; see b2-vocab.ts for the rule.

export const B2_SENTENCES: SentenceItem[] = [
  // ── congiuntivo across tenses ─────────────────────────────────────────
  { id: 'it4s001', de: 'Non credo che il governo abbia valutato tutte le conseguenze.', en: 'I don’t believe the government has weighed all the consequences.', gloss: { de: 'Ich glaube nicht, dass die Regierung alle Folgen abgewogen hat.', es: 'No creo que el gobierno haya sopesado todas las consecuencias.', fr: 'Je ne crois pas que le gouvernement ait pesé toutes les conséquences.', pt: 'Não acredito que o governo tenha ponderado todas as consequências.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['possa', 'debba', 'voglia'] },
  { id: 'it4s002', de: 'Temevo che la trattativa si interrompesse prima dell’accordo.', en: 'I feared the negotiation would break off before the agreement.', gloss: { de: 'Ich fürchtete, dass die Verhandlung vor der Einigung abbrechen würde.', es: 'Temía que la negociación se interrumpiera antes del acuerdo.', fr: 'Je craignais que la négociation ne s’interrompe avant l’accord.', pt: 'Temia que a negociação se interrompesse antes do acordo.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['concludesse', 'riprendesse', 'proseguisse'] },
  { id: 'it4s003', de: 'Sembrava che nessuno avesse letto la clausola sulla riservatezza.', en: 'It seemed nobody had read the confidentiality clause.', gloss: { de: 'Es schien, als hätte niemand die Vertraulichkeitsklausel gelesen.', es: 'Parecía que nadie había leído la cláusula de confidencialidad.', fr: 'Il semblait que personne n’avait lu la clause de confidentialité.', pt: 'Parecia que ninguém tinha lido a cláusula de confidencialidade.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['volesse', 'potesse', 'dovesse'] },
  { id: 'it4s004', de: 'Che la fonte sia attendibile resta tutto da dimostrare.', en: 'Whether the source is trustworthy remains to be proven.', gloss: { de: 'Ob die Quelle glaubwürdig ist, muss erst bewiesen werden.', es: 'Que la fuente sea fidedigna está todavía por demostrar.', fr: 'Que la source soit digne de foi reste à démontrer.', pt: 'Que a fonte seja fidedigna ainda está por provar.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['parziale', 'invasiva', 'banale'] },
  { id: 'it4s005', de: 'Mi auguro che la sentenza venga motivata con chiarezza.', en: 'I hope the ruling is given clear reasoning.', gloss: { de: 'Ich hoffe, dass das Urteil klar begründet wird.', es: 'Espero que la sentencia sea motivada con claridad.', fr: 'J’espère que le jugement sera clairement motivé.', pt: 'Espero que a sentença seja fundamentada com clareza.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['normativa', 'testimonianza', 'premessa'] },
  { id: 'it4s006', de: 'Benché avessimo previsto il rincaro, il bilancio è saltato.', en: 'Although we had foreseen the price rise, the budget collapsed.', gloss: { de: 'Obwohl wir die Verteuerung vorhergesehen hatten, ist der Haushalt geplatzt.', es: 'Aunque habíamos previsto la subida de precios, el presupuesto se vino abajo.', fr: 'Bien que nous ayons prévu la hausse des prix, le budget a explosé.', pt: 'Embora tivéssemos previsto o aumento de preços, o orçamento estourou.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['potessimo', 'dovessimo', 'volessimo'] },
  { id: 'it4s007', de: 'È probabile che l’inflazione rallenti nei prossimi mesi.', en: 'It is likely that inflation will slow in the coming months.', gloss: { de: 'Es ist wahrscheinlich, dass die Inflation in den nächsten Monaten nachlässt.', es: 'Es probable que la inflación se desacelere en los próximos meses.', fr: 'Il est probable que l’inflation ralentisse dans les prochains mois.', pt: 'É provável que a inflação desacelere nos próximos meses.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['aumenti', 'peggiori', 'raddoppi'] },
  { id: 'it4s008', de: 'Dubito che l’azienda voglia ammettere il proprio errore.', en: 'I doubt the company wants to admit its own mistake.', gloss: { de: 'Ich bezweifle, dass die Firma ihren eigenen Fehler zugeben will.', es: 'Dudo que la empresa quiera admitir su propio error.', fr: 'Je doute que l’entreprise veuille admettre sa propre erreur.', pt: 'Duvido que a empresa queira admitir o próprio erro.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['contestare', 'ribadire', 'attenuare'] },
  { id: 'it4s009', de: 'Che si tratti di un capolavoro, francamente, mi pare esagerato.', en: 'That it is a masterpiece, frankly, strikes me as an overstatement.', gloss: { de: 'Dass es ein Meisterwerk sei, halte ich ehrlich gesagt für übertrieben.', es: 'Que se trate de una obra maestra, francamente, me parece exagerado.', fr: 'Que ce soit un chef-d’œuvre, franchement, me paraît exagéré.', pt: 'Que se trate de uma obra-prima, francamente, me parece exagerado.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['fraintendimento', 'compromesso', 'pregiudizio'] },
  { id: 'it4s010', de: 'Bisognava che qualcuno si assumesse la responsabilità del degrado.', en: 'Someone needed to take responsibility for the decay.', gloss: { de: 'Es war nötig, dass jemand die Verantwortung für den Verfall übernahm.', es: 'Hacía falta que alguien asumiera la responsabilidad del deterioro.', fr: 'Il fallait que quelqu’un assume la responsabilité de la dégradation.', pt: 'Era preciso que alguém assumisse a responsabilidade pela degradação.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['negasse', 'evitasse', 'chiedesse'] },
  { id: 'it4s011', de: 'Per quanto il progetto sia ambizioso, i fondi restano insufficienti.', en: 'However ambitious the project may be, the funds remain insufficient.', gloss: { de: 'So ehrgeizig das Projekt auch sein mag, die Mittel bleiben unzureichend.', es: 'Por ambicioso que sea el proyecto, los fondos siguen siendo insuficientes.', fr: 'Si ambitieux que soit le projet, les fonds restent insuffisants.', pt: 'Por mais ambicioso que seja o projeto, os fundos continuam insuficientes.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['redditizio', 'impegnativo', 'lecito'] },
  { id: 'it4s012', de: 'Non vorrei che questo suonasse come un rimprovero.', en: 'I wouldn’t want this to sound like a reproach.', gloss: { de: 'Ich möchte nicht, dass das wie ein Vorwurf klingt.', es: 'No quisiera que esto sonara como un reproche.', fr: 'Je ne voudrais pas que cela sonne comme un reproche.', pt: 'Eu não gostaria que isso soasse como uma repreensão.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['sembrasse', 'apparisse', 'risultasse'] },

  // ── periodo ipotetico ─────────────────────────────────────────────────
  { id: 'it4s013', de: 'Se il canone aumenta ancora, molti lasceranno il quartiere.', en: 'If the rent goes up again, many will leave the neighbourhood.', gloss: { de: 'Wenn die Gebühr weiter steigt, werden viele das Viertel verlassen.', es: 'Si la cuota sube otra vez, muchos dejarán el barrio.', fr: 'Si la redevance augmente encore, beaucoup quitteront le quartier.', pt: 'Se a taxa subir de novo, muitos deixarão o bairro.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['scende', 'resta', 'cambia'] },
  { id: 'it4s014', de: 'Se avessimo tenuto conto dei dati, non avremmo firmato.', en: 'If we had taken the data into account, we would not have signed.', gloss: { de: 'Hätten wir die Daten berücksichtigt, hätten wir nicht unterschrieben.', es: 'Si hubiéramos tenido en cuenta los datos, no habríamos firmado.', fr: 'Si nous avions tenu compte des données, nous n’aurions pas signé.', pt: 'Se tivéssemos levado em conta os dados, não teríamos assinado.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['perso', 'chiesto', 'trovato'] },
  { id: 'it4s015', de: 'Se fossi in te, chiederei un preavviso più lungo.', en: 'If I were you, I would ask for a longer notice period.', gloss: { de: 'An deiner Stelle würde ich eine längere Vorankündigung verlangen.', es: 'Yo que tú, pediría un preaviso más largo.', fr: 'À ta place, je demanderais un préavis plus long.', pt: 'Se eu fosse você, pediria um aviso prévio mais longo.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['accetterei', 'firmerei', 'proporrei'] },
  { id: 'it4s016', de: 'Qualora la scadenza slittasse, avviseremmo subito il fornitore.', en: 'Should the deadline slip, we would notify the supplier at once.', gloss: { de: 'Sollte sich die Frist verschieben, würden wir den Lieferanten sofort benachrichtigen.', es: 'En caso de que el plazo se retrasara, avisaríamos enseguida al proveedor.', fr: 'Au cas où l’échéance serait repoussée, nous préviendrions aussitôt le fournisseur.', pt: 'Caso o prazo escorregasse, avisaríamos imediatamente o fornecedor.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Sebbene', 'Nondimeno', 'Pertanto'] },
  { id: 'it4s017', de: 'Se la ricerca fosse stata pubblicata prima, il dibattito sarebbe diverso.', en: 'If the research had been published earlier, the debate would be different.', gloss: { de: 'Wäre die Studie früher veröffentlicht worden, wäre die Debatte eine andere.', es: 'Si la investigación se hubiera publicado antes, el debate sería distinto.', fr: 'Si la recherche avait été publiée plus tôt, le débat serait différent.', pt: 'Se a pesquisa tivesse sido publicada antes, o debate seria diferente.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['contestata', 'finanziata', 'ripetuta'] },
  { id: 'it4s018', de: 'Accetterei l’incarico purché mi lascino delegare qualche mansione.', en: 'I would accept the post provided they let me delegate some duties.', gloss: { de: 'Ich würde die Aufgabe annehmen, sofern man mich einige Tätigkeiten delegieren lässt.', es: 'Aceptaría el encargo siempre que me dejen delegar algunas tareas.', fr: 'J’accepterais la mission pourvu qu’on me laisse déléguer certaines tâches.', pt: 'Aceitaria a incumbência contanto que me deixem delegar algumas atribuições.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['sebbene', 'benché', 'affinché'] },
  { id: 'it4s019', de: 'A patto che i dati restino anonimi, l’esperimento è lecito.', en: 'On condition that the data stay anonymous, the experiment is lawful.', gloss: { de: 'Unter der Bedingung, dass die Daten anonym bleiben, ist das Experiment zulässig.', es: 'A condición de que los datos sigan siendo anónimos, el experimento es lícito.', fr: 'À condition que les données restent anonymes, l’expérience est licite.', pt: 'Com a condição de que os dados permaneçam anônimos, o experimento é lícito.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['pubblici', 'parziali', 'completi'] },
  { id: 'it4s020', de: 'Se non avessi rimuginato tanto, avrei dormito meglio.', en: 'If I hadn’t brooded so much, I would have slept better.', gloss: { de: 'Hätte ich nicht so viel gegrübelt, hätte ich besser geschlafen.', es: 'Si no le hubiera dado tantas vueltas, habría dormido mejor.', fr: 'Si je n’avais pas autant ruminé, j’aurais mieux dormi.', pt: 'Se eu não tivesse remoído tanto, teria dormido melhor.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['discusso', 'lavorato', 'letto'] },

  // ── passive with venire / andare ──────────────────────────────────────
  { id: 'it4s021', de: 'Se venisse approvata la normativa, molte emissioni sarebbero ridotte.', en: 'If the regulations were approved, many emissions would be cut.', gloss: { de: 'Würde die Vorschrift verabschiedet, würden viele Emissionen gesenkt.', es: 'Si se aprobara la normativa, muchas emisiones se reducirían.', fr: 'Si la réglementation était approuvée, de nombreuses émissions seraient réduites.', pt: 'Se a regulamentação fosse aprovada, muitas emissões seriam reduzidas.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['respinta', 'rinviata', 'riscritta'] },
  { id: 'it4s022', de: 'Il ricorso viene esaminato dal tribunale entro trenta giorni.', en: 'The appeal is examined by the court within thirty days.', gloss: { de: 'Die Berufung wird binnen dreißig Tagen vom Gericht geprüft.', es: 'El recurso es examinado por el tribunal en treinta días.', fr: 'Le recours est examiné par le tribunal sous trente jours.', pt: 'O recurso é examinado pelo tribunal em trinta dias.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['respinto', 'trascritto', 'firmato'] },
  { id: 'it4s023', de: 'I rifiuti pericolosi vanno smaltiti secondo regole precise.', en: 'Hazardous waste must be disposed of according to strict rules.', gloss: { de: 'Gefährlicher Abfall muss nach genauen Regeln entsorgt werden.', es: 'Los residuos peligrosos deben eliminarse según reglas precisas.', fr: 'Les déchets dangereux doivent être éliminés selon des règles précises.', pt: 'Os resíduos perigosos devem ser descartados segundo regras precisas.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['trasportati', 'registrati', 'venduti'] },
  { id: 'it4s024', de: 'La testimonianza venne registrata senza il consenso dell’imputato.', en: 'The testimony was recorded without the defendant’s consent.', gloss: { de: 'Die Zeugenaussage wurde ohne Zustimmung des Angeklagten aufgezeichnet.', es: 'El testimonio fue grabado sin el consentimiento del acusado.', fr: 'Le témoignage fut enregistré sans le consentement de l’accusé.', pt: 'O testemunho foi gravado sem o consentimento do acusado.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['smentita', 'ripetuta', 'tradotta'] },
  { id: 'it4s025', de: 'Questo dato va interpretato con una certa cautela.', en: 'This figure should be interpreted with a certain caution.', gloss: { de: 'Diese Zahl ist mit einer gewissen Vorsicht zu deuten.', es: 'Este dato debe interpretarse con cierta cautela.', fr: 'Cette donnée doit être interprétée avec une certaine prudence.', pt: 'Este dado deve ser interpretado com certa cautela.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['confrontato', 'aggiornato', 'presentato'] },
  { id: 'it4s026', de: 'Le fonti anonime vengono tutelate dalla legge sulla stampa.', en: 'Anonymous sources are protected by the press law.', gloss: { de: 'Anonyme Quellen werden vom Pressegesetz geschützt.', es: 'Las fuentes anónimas están protegidas por la ley de prensa.', fr: 'Les sources anonymes sont protégées par la loi sur la presse.', pt: 'As fontes anônimas são protegidas pela lei de imprensa.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['citate', 'contattate', 'pagate'] },
  { id: 'it4s027', de: 'Il cantiere andrebbe completato prima dell’inverno.', en: 'The building site ought to be completed before winter.', gloss: { de: 'Die Baustelle sollte vor dem Winter fertiggestellt werden.', es: 'La obra debería completarse antes del invierno.', fr: 'Le chantier devrait être achevé avant l’hiver.', pt: 'A obra deveria ser concluída antes do inverno.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['ampliato', 'ispezionato', 'chiuso'] },
  { id: 'it4s028', de: 'Ogni aggiornamento viene testato prima della distribuzione.', en: 'Every update is tested before release.', gloss: { de: 'Jede Aktualisierung wird vor der Verteilung getestet.', es: 'Cada actualización se prueba antes de su distribución.', fr: 'Chaque mise à jour est testée avant la diffusion.', pt: 'Cada atualização é testada antes da distribuição.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['tradotto', 'annunciato', 'sospeso'] },

  // ── gerundio & forma impersonale ──────────────────────────────────────
  { id: 'it4s029', de: 'La recensione venne accolta con una certa freddezza.', en: 'The review was received with a certain coolness.', gloss: { de: 'Die Rezension wurde mit einer gewissen Kühle aufgenommen.', es: 'La reseña fue acogida con cierta frialdad.', fr: 'La critique fut accueillie avec une certaine froideur.', pt: 'A resenha foi recebida com certa frieza.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['scritta', 'letta', 'citata'] },
  { id: 'it4s030', de: 'Pur riconoscendo il tuo impegno, non condivido la conclusione.', en: 'While acknowledging your effort, I do not share the conclusion.', gloss: { de: 'Bei aller Anerkennung deines Einsatzes teile ich die Schlussfolgerung nicht.', es: 'Aun reconociendo tu esfuerzo, no comparto la conclusión.', fr: 'Tout en reconnaissant ton effort, je ne partage pas la conclusion.', pt: 'Embora reconhecendo o teu empenho, não partilho a conclusão.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['apprezzando', 'valutando', 'ricordando'] },
  { id: 'it4s031', de: 'Leggendo il titolo, si capisce già l’orientamento della testata.', en: 'Reading the headline, you already grasp the outlet’s leaning.', gloss: { de: 'Schon beim Lesen der Schlagzeile erkennt man die Ausrichtung des Blattes.', es: 'Leyendo el titular, ya se entiende la orientación del medio.', fr: 'En lisant le titre, on comprend déjà l’orientation du journal.', pt: 'Lendo a manchete, já se entende a orientação do veículo.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Ascoltando', 'Scrivendo', 'Guardando'] },
  { id: 'it4s032', de: 'Si tende a dare per scontato che i dati siano corretti.', en: 'People tend to take for granted that the data are correct.', gloss: { de: 'Man neigt dazu, als selbstverständlich anzunehmen, dass die Daten stimmen.', es: 'Se tiende a dar por sentado que los datos son correctos.', fr: 'On a tendance à tenir pour acquis que les données sont correctes.', pt: 'Tende-se a dar por certo que os dados estão corretos.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['rischia', 'continua', 'rinuncia'] },
  { id: 'it4s033', de: 'Insistendo troppo, si rischia di irrigidire la trattativa.', en: 'By pushing too hard, one risks hardening the negotiation.', gloss: { de: 'Wenn man zu sehr insistiert, riskiert man, die Verhandlung zu verhärten.', es: 'Insistiendo demasiado, se corre el riesgo de endurecer la negociación.', fr: 'En insistant trop, on risque de durcir la négociation.', pt: 'Insistindo demais, corre-se o risco de endurecer a negociação.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Rinviando', 'Cedendo', 'Tacendo'] },
  { id: 'it4s034', de: 'In Italia si discute molto di riqualificazione delle periferie.', en: 'In Italy there is much discussion of redeveloping the outskirts.', gloss: { de: 'In Italien wird viel über die Sanierung der Vorstädte diskutiert.', es: 'En Italia se discute mucho sobre la rehabilitación de las afueras.', fr: 'En Italie, on discute beaucoup de la requalification des banlieues.', pt: 'Na Itália discute-se muito sobre a requalificação das periferias.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['scrive', 'protesta', 'dubita'] },
  { id: 'it4s035', de: 'Pur essendo redditizio, quell’investimento comporta rischi notevoli.', en: 'Though profitable, that investment carries considerable risks.', gloss: { de: 'Obwohl rentabel, birgt diese Investition erhebliche Risiken.', es: 'Aun siendo rentable, esa inversión conlleva riesgos notables.', fr: 'Bien que rentable, cet investissement comporte des risques notables.', pt: 'Embora rentável, esse investimento acarreta riscos consideráveis.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['prudente', 'legittimo', 'trasparente'] },
  { id: 'it4s036', de: 'Non si può pretendere che tutti condividano lo stesso parere.', en: 'One cannot expect everybody to share the same view.', gloss: { de: 'Man kann nicht erwarten, dass alle dieselbe Ansicht teilen.', es: 'No se puede pretender que todos compartan la misma opinión.', fr: 'On ne peut pas exiger que tous partagent le même avis.', pt: 'Não se pode exigir que todos partilhem a mesma opinião.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['sperare', 'immaginare', 'promettere'] },

  // ── connectors of argument ────────────────────────────────────────────
  { id: 'it4s037', de: 'Avendo letto l’inchiesta, molti hanno cambiato idea.', en: 'Having read the investigative report, many changed their minds.', gloss: { de: 'Nachdem sie die Recherche gelesen hatten, änderten viele ihre Meinung.', es: 'Habiendo leído la investigación, muchos cambiaron de opinión.', fr: 'Ayant lu l’enquête, beaucoup ont changé d’avis.', pt: 'Tendo lido a reportagem, muitos mudaram de ideia.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Volendo', 'Dovendo', 'Sapendo'] },
  { id: 'it4s038', de: 'La proposta è interessante; nondimeno, i costi restano proibitivi.', en: 'The proposal is interesting; nonetheless, the costs remain prohibitive.', gloss: { de: 'Der Vorschlag ist interessant; nichtsdestoweniger bleiben die Kosten untragbar.', es: 'La propuesta es interesante; no obstante, los costes siguen siendo prohibitivos.', fr: 'La proposition est intéressante ; néanmoins, les coûts restent prohibitifs.', pt: 'A proposta é interessante; não obstante, os custos continuam proibitivos.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['pertanto', 'infatti', 'ossia'] },
  { id: 'it4s039', de: 'Dato che le fonti concordano, la notizia appare verosimile.', en: 'Given that the sources agree, the story looks plausible.', gloss: { de: 'Da die Quellen übereinstimmen, erscheint die Nachricht glaubhaft.', es: 'Dado que las fuentes coinciden, la noticia parece verosímil.', fr: 'Étant donné que les sources concordent, l’information paraît vraisemblable.', pt: 'Dado que as fontes coincidem, a notícia parece verossímil.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['tacciono', 'smentiscono', 'esagerano'] },
  { id: 'it4s040', de: 'Preferisco ascoltare anziché rispondere d’istinto.', en: 'I prefer to listen rather than answer on instinct.', gloss: { de: 'Ich höre lieber zu, anstatt aus dem Bauch heraus zu antworten.', es: 'Prefiero escuchar en lugar de responder por instinto.', fr: 'Je préfère écouter plutôt que de répondre d’instinct.', pt: 'Prefiro escutar em vez de responder por instinto.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['piuttosto', 'invece', 'ossia'] },
  { id: 'it4s041', de: 'I dati sono chiari; pertanto, la conclusione si impone da sé.', en: 'The data are clear; therefore, the conclusion imposes itself.', gloss: { de: 'Die Daten sind eindeutig; daher drängt sich der Schluss auf.', es: 'Los datos son claros; por consiguiente, la conclusión se impone sola.', fr: 'Les données sont claires ; par conséquent, la conclusion s’impose d’elle-même.', pt: 'Os dados são claros; por conseguinte, a conclusão se impõe sozinha.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['nondimeno', 'seppure', 'viceversa'] },
  { id: 'it4s042', de: 'Eppure nessuno ha voluto mettere in discussione quel presupposto.', en: 'And yet nobody wanted to call that assumption into question.', gloss: { de: 'Und doch wollte niemand diese Voraussetzung infrage stellen.', es: 'Y sin embargo nadie quiso poner en tela de juicio ese supuesto.', fr: 'Et pourtant personne n’a voulu remettre en question ce présupposé.', pt: 'E no entanto ninguém quis pôr em causa aquele pressuposto.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Pertanto', 'Infatti', 'Ossia'] },
  { id: 'it4s043', de: 'Malgrado le critiche, la regia mi è sembrata coraggiosa.', en: 'Despite the criticism, the directing struck me as brave.', gloss: { de: 'Trotz der Kritik erschien mir die Regie mutig.', es: 'A pesar de las críticas, la dirección me pareció valiente.', fr: 'Malgré les critiques, la mise en scène m’a semblé courageuse.', pt: 'Apesar das críticas, a direção me pareceu corajosa.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Sebbene', 'Purché', 'Qualora'] },
  { id: 'it4s044', de: 'Il divario tra le due periferie è, ossia, anche culturale.', en: 'The gap between the two outskirts is, that is to say, cultural too.', gloss: { de: 'Die Kluft zwischen den beiden Vororten ist, das heißt, auch kulturell.', es: 'La brecha entre las dos afueras es, o sea, también cultural.', fr: 'L’écart entre les deux banlieues est, c’est-à-dire, aussi culturel.', pt: 'A disparidade entre as duas periferias é, ou seja, também cultural.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['pregiudizio', 'patrimonio', 'consenso'] },
  { id: 'it4s045', de: 'Seppure a malincuore, il portavoce ha smentito la notizia.', en: 'Albeit reluctantly, the spokesperson denied the story.', gloss: { de: 'Wenn auch widerwillig, hat der Sprecher die Nachricht dementiert.', es: 'Aunque a regañadientes, el portavoz desmintió la noticia.', fr: 'Même à contrecœur, le porte-parole a démenti l’information.', pt: 'Ainda que a contragosto, o porta-voz desmentiu a notícia.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['confermato', 'diffuso', 'commentato'] },
  { id: 'it4s046', de: 'Infatti nessuna emittente ha voluto trasmettere quell’inchiesta.', en: 'Indeed no broadcaster wanted to air that investigation.', gloss: { de: 'Tatsächlich wollte kein Sender diese Recherche ausstrahlen.', es: 'De hecho ninguna emisora quiso emitir esa investigación.', fr: 'En effet aucune chaîne n’a voulu diffuser cette enquête.', pt: 'De fato nenhuma emissora quis transmitir aquela reportagem.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Tuttavia', 'Eppure', 'Nondimeno'] },
  { id: 'it4s047', de: 'Per giunta, il canone è aumentato senza alcun preavviso.', en: 'On top of that, the fee went up without any notice.', gloss: { de: 'Obendrein ist die Gebühr ohne jede Vorankündigung gestiegen.', es: 'Por añadidura, la cuota subió sin ningún preaviso.', fr: 'De surcroît, la redevance a augmenté sans aucun préavis.', pt: 'Ainda por cima, a taxa subiu sem aviso prévio algum.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['diminuito', 'cambiato', 'sparito'] },
  { id: 'it4s048', de: 'Chi lavora poco guadagna meno; viceversa, non sempre vale il contrario.', en: 'Those who work little earn less; conversely, the opposite is not always true.', gloss: { de: 'Wer wenig arbeitet, verdient weniger; umgekehrt gilt das Gegenteil nicht immer.', es: 'Quien trabaja poco gana menos; a la inversa, lo contrario no siempre vale.', fr: 'Qui travaille peu gagne moins ; inversement, l’inverse n’est pas toujours vrai.', pt: 'Quem trabalha pouco ganha menos; inversamente, o contrário nem sempre vale.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['pertanto', 'infatti', 'nondimeno'] },

  // ── register, hedging, diplomatic disagreement ────────────────────────
  { id: 'it4s049', de: 'A lungo andare, il consumo di suolo rende la città meno abitabile.', en: 'In the long run, land consumption makes the city less livable.', gloss: { de: 'Auf Dauer macht der Flächenverbrauch die Stadt weniger bewohnbar.', es: 'A la larga, el consumo de suelo hace la ciudad menos habitable.', fr: 'À la longue, la consommation de sol rend la ville moins habitable.', pt: 'A longo prazo, o consumo de solo torna a cidade menos habitável.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['degrado', 'traffico', 'patrimonio'] },
  { id: 'it4s050', de: 'Mi permetto di dissentire, seppure con grande rispetto.', en: 'I beg to differ, albeit with great respect.', gloss: { de: 'Ich erlaube mir zu widersprechen, wenn auch mit großem Respekt.', es: 'Me permito discrepar, aunque con gran respeto.', fr: 'Je me permets de ne pas être d’accord, quoique avec grand respect.', pt: 'Permito-me discordar, ainda que com grande respeito.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['insistere', 'replicare', 'intervenire'] },
  { id: 'it4s051', de: 'A quanto pare, la decisione era già stata presa altrove.', en: 'Apparently, the decision had already been made elsewhere.', gloss: { de: 'Anscheinend war die Entscheidung anderswo bereits gefallen.', es: 'Por lo visto, la decisión ya se había tomado en otro sitio.', fr: 'Apparemment, la décision avait déjà été prise ailleurs.', pt: 'Pelo visto, a decisão já tinha sido tomada em outro lugar.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['obiezione', 'clausola', 'premessa'] },
  { id: 'it4s052', de: 'Per quanto ne so, nessuna testata ha verificato quel dato.', en: 'As far as I know, no outlet has verified that figure.', gloss: { de: 'Soweit ich weiß, hat kein Presseorgan diese Zahl geprüft.', es: 'Que yo sepa, ningún medio ha verificado ese dato.', fr: 'Autant que je sache, aucun titre de presse n’a vérifié cette donnée.', pt: 'Que eu saiba, nenhum veículo verificou aquele dado.' }, level: 'B2', clozeIndex: 7, clozeDistractors: ['smentito', 'divulgato', 'archiviato'] },
  { id: 'it4s053', de: 'In linea di massima condivido, ma vorrei attenuare il tono.', en: 'Broadly speaking I agree, but I would like to tone it down.', gloss: { de: 'Im Großen und Ganzen stimme ich zu, möchte aber den Ton abschwächen.', es: 'En líneas generales estoy de acuerdo, pero quisiera atenuar el tono.', fr: 'Dans les grandes lignes je suis d’accord, mais je voudrais atténuer le ton.', pt: 'Em linhas gerais concordo, mas gostaria de atenuar o tom.' }, level: 'B2', clozeIndex: 7, clozeDistractors: ['ribadire', 'contestare', 'ripetere'] },
  { id: 'it4s054', de: 'La Sua osservazione è pertinente, ma andrebbe contestualizzata.', en: 'Your remark is pertinent, but it would need to be put in context.', gloss: { de: 'Ihre Bemerkung ist zutreffend, müsste aber eingeordnet werden.', es: 'Su observación es pertinente, pero habría que contextualizarla.', fr: 'Votre remarque est pertinente, mais elle mériterait d’être contextualisée.', pt: 'A sua observação é pertinente, mas deveria ser contextualizada.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['banale', 'invasiva', 'parziale'] },
  { id: 'it4s055', de: 'Preferirei non dare per scontata la buona fede di nessuno.', en: 'I would rather not take anyone’s good faith for granted.', gloss: { de: 'Ich möchte niemandes guten Glauben als selbstverständlich voraussetzen.', es: 'Preferiría no dar por sentada la buena fe de nadie.', fr: 'Je préférerais ne présumer la bonne foi de personne.', pt: 'Preferiria não dar por certa a boa-fé de ninguém.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Vorrei', 'Potrei', 'Dovrei'] },
  { id: 'it4s056', de: 'Detto tra noi, quella controproposta non conviene a nessuno.', en: 'Between us, that counter-proposal suits nobody.', gloss: { de: 'Unter uns gesagt, dieser Gegenvorschlag nützt niemandem.', es: 'Entre nosotros, esa contrapropuesta no le conviene a nadie.', fr: 'Entre nous, cette contre-proposition n’arrange personne.', pt: 'Cá entre nós, essa contraproposta não convém a ninguém.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['clausola', 'mansione', 'scadenza'] },
  { id: 'it4s057', de: 'Sarei propenso a rinviare la firma, se me lo consentisse.', en: 'I would be inclined to postpone the signing, if you would allow me.', gloss: { de: 'Ich wäre geneigt, die Unterschrift zu verschieben, wenn Sie es erlauben.', es: 'Me inclinaría a aplazar la firma, si usted me lo permitiera.', fr: 'Je serais enclin à repousser la signature, si vous me le permettiez.', pt: 'Estaria inclinado a adiar a assinatura, se o senhor permitisse.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['anticipare', 'annullare', 'accelerare'] },
  { id: 'it4s058', de: 'Non intendevo offenderla; temo di essermi espresso male.', en: 'I did not mean to offend you; I fear I expressed myself badly.', gloss: { de: 'Ich wollte Sie nicht kränken; ich fürchte, ich habe mich schlecht ausgedrückt.', es: 'No pretendía ofenderle; temo haberme expresado mal.', fr: 'Je ne voulais pas vous offenser ; je crains de m’être mal exprimé.', pt: 'Não pretendia ofendê-lo; temo ter-me expressado mal.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['contraddirla', 'interromperla', 'correggerla'] },

  // ── idiom, collocation & topic ───────────────────────────────────────
  { id: 'it4s059', de: 'Ci sarebbe da chiedersi se il consenso sia stato davvero informato.', en: 'One might ask whether the consent was really informed.', gloss: { de: 'Man müsste sich fragen, ob die Zustimmung wirklich informiert war.', es: 'Cabría preguntarse si el consentimiento fue realmente informado.', fr: 'On pourrait se demander si le consentement a été vraiment éclairé.', pt: 'Caberia perguntar se o consentimento foi realmente informado.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['anonimato', 'algoritmo', 'aggiornamento'] },
  { id: 'it4s060', de: 'La contraddizione salta agli occhi già nella premessa.', en: 'The contradiction is glaringly obvious right in the premise.', gloss: { de: 'Der Widerspruch springt schon in der Prämisse ins Auge.', es: 'La contradicción salta a la vista ya en la premisa.', fr: 'La contradiction saute aux yeux dès la prémisse.', pt: 'A contradição salta aos olhos já na premissa.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['appare', 'resta', 'nasce'] },
  { id: 'it4s061', de: 'In fin dei conti, nessuno voleva prendere le distanze pubblicamente.', en: 'At the end of the day, nobody wanted to distance themselves publicly.', gloss: { de: 'Letzten Endes wollte sich niemand öffentlich distanzieren.', es: 'Al fin y al cabo, nadie quería distanciarse públicamente.', fr: 'En fin de compte, personne ne voulait prendre ses distances publiquement.', pt: 'No fim das contas, ninguém queria distanciar-se publicamente.' }, level: 'B2', clozeIndex: 8, clozeDistractors: ['difese', 'critiche', 'misure'] },
  { id: 'it4s062', de: 'Le due parti hanno finito per trovare un punto d’incontro.', en: 'The two sides ended up finding common ground.', gloss: { de: 'Die beiden Seiten fanden schließlich eine gemeinsame Basis.', es: 'Las dos partes acabaron encontrando un punto en común.', fr: 'Les deux parties ont fini par trouver un terrain d’entente.', pt: 'As duas partes acabaram encontrando um ponto em comum.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['cercare', 'perdere', 'imporre'] },
  { id: 'it4s063', de: 'Quell’articolo ha dato adito a numerose obiezioni.', en: 'That article gave rise to numerous objections.', gloss: { de: 'Jener Artikel gab Anlass zu zahlreichen Einwänden.', es: 'Aquel artículo dio lugar a numerosas objeciones.', fr: 'Cet article a donné lieu à de nombreuses objections.', pt: 'Aquele artigo deu azo a numerosas objeções.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['seguito', 'inizio', 'peso'] },
  { id: 'it4s064', de: 'A maggior ragione bisogna tutelare le fonti più fragili.', en: 'All the more reason to protect the most fragile sources.', gloss: { de: 'Erst recht muss man die anfälligsten Quellen schützen.', es: 'Con mayor razón hay que proteger las fuentes más frágiles.', fr: 'À plus forte raison faut-il protéger les sources les plus fragiles.', pt: 'Com mais razão é preciso proteger as fontes mais frágeis.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['citare', 'formare', 'pagare'] },
  { id: 'it4s065', de: 'Molti utenti ignorano quanto a lungo vengano tracciati i loro dati.', en: 'Many users are unaware how long their data are tracked.', gloss: { de: 'Viele Nutzer wissen nicht, wie lange ihre Daten verfolgt werden.', es: 'Muchos usuarios ignoran cuánto tiempo se rastrean sus datos.', fr: 'Beaucoup d’utilisateurs ignorent combien de temps leurs données sont tracées.', pt: 'Muitos usuários ignoram por quanto tempo os seus dados são rastreados.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['scoprono', 'accettano', 'discutono'] },
  { id: 'it4s066', de: 'La sorveglianza continua produce un disagio difficile da descrivere.', en: 'Constant surveillance produces an unease that is hard to describe.', gloss: { de: 'Ständige Überwachung erzeugt ein schwer zu beschreibendes Unbehagen.', es: 'La vigilancia continua produce un malestar difícil de describir.', fr: 'La surveillance continue produit un malaise difficile à décrire.', pt: 'A vigilância contínua produz um mal-estar difícil de descrever.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['rimpianto', 'pregiudizio', 'anonimato'] },
  { id: 'it4s067', de: 'Un algoritmo mal progettato può rafforzare vecchi stereotipi.', en: 'A badly designed algorithm can reinforce old stereotypes.', gloss: { de: 'Ein schlecht entworfener Algorithmus kann alte Klischees verstärken.', es: 'Un algoritmo mal diseñado puede reforzar viejos estereotipos.', fr: 'Un algorithme mal conçu peut renforcer de vieux stéréotypes.', pt: 'Um algoritmo mal projetado pode reforçar velhos estereótipos.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['smentire', 'attenuare', 'ereditare'] },
  { id: 'it4s068', de: 'L’aumento del potere d’acquisto non ha ridotto il divario sociale.', en: 'The rise in purchasing power has not narrowed the social gap.', gloss: { de: 'Der Anstieg der Kaufkraft hat die soziale Kluft nicht verringert.', es: 'El aumento del poder adquisitivo no ha reducido la brecha social.', fr: 'La hausse du pouvoir d’achat n’a pas réduit l’écart social.', pt: 'O aumento do poder de compra não reduziu a disparidade social.' }, level: 'B2', clozeIndex: 8, clozeDistractors: ['pregiudizio', 'patrimonio', 'consenso'] },
  { id: 'it4s069', de: 'Il dialetto locale viene ancora tramandato dalle famiglie più anziane.', en: 'The local dialect is still handed down by the older families.', gloss: { de: 'Der örtliche Dialekt wird von den älteren Familien noch überliefert.', es: 'El dialecto local todavía se transmite en las familias mayores.', fr: 'Le dialecte local est encore transmis par les familles les plus âgées.', pt: 'O dialeto local ainda é transmitido pelas famílias mais velhas.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['insegnato', 'studiato', 'raccolto'] },
  { id: 'it4s070', de: 'Il ritmo del film è lento, eppure l’interpretazione resta avvincente.', en: 'The pace of the film is slow, and yet the performance stays gripping.', gloss: { de: 'Das Tempo des Films ist langsam, und doch bleibt die Darstellung fesselnd.', es: 'El ritmo de la película es lento, y sin embargo la interpretación sigue siendo apasionante.', fr: 'Le rythme du film est lent, et pourtant l’interprétation reste captivante.', pt: 'O ritmo do filme é lento, e no entanto a interpretação continua envolvente.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['banale', 'rapido', 'confuso'] },
  { id: 'it4s071', de: 'Molti spettatori hanno trovato il finale francamente banale.', en: 'Many viewers found the ending frankly banal.', gloss: { de: 'Viele Zuschauer fanden das Ende ehrlich gesagt banal.', es: 'Muchos espectadores encontraron el final francamente banal.', fr: 'Beaucoup de spectateurs ont trouvé la fin franchement banale.', pt: 'Muitos espectadores acharam o final francamente banal.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['giornalisti', 'studenti', 'lettori'] },
  { id: 'it4s072', de: 'Il sovraffollamento del centro rende il traffico quasi ingestibile.', en: 'The overcrowding of the centre makes traffic almost unmanageable.', gloss: { de: 'Die Überfüllung des Zentrums macht den Verkehr fast unbeherrschbar.', es: 'La masificación del centro hace el tráfico casi ingobernable.', fr: 'La surpopulation du centre rend la circulation presque ingérable.', pt: 'A superlotação do centro torna o trânsito quase ingerenciável.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['degrado', 'patrimonio', 'canone'] },
  { id: 'it4s073', de: 'Il sindacato ha chiesto che gli straordinari vengano retribuiti meglio.', en: 'The union asked for overtime to be paid better.', gloss: { de: 'Die Gewerkschaft forderte, dass Überstunden besser vergütet werden.', es: 'El sindicato pidió que las horas extra se paguen mejor.', fr: 'Le syndicat a demandé que les heures supplémentaires soient mieux payées.', pt: 'O sindicato pediu que as horas extras sejam mais bem pagas.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['tribunale', 'fornitore', 'quartiere'] },
  { id: 'it4s074', de: 'Nessuna riqualificazione funziona se il quartiere non viene ascoltato.', en: 'No redevelopment works if the neighbourhood is not listened to.', gloss: { de: 'Keine Sanierung funktioniert, wenn das Viertel nicht gehört wird.', es: 'Ninguna rehabilitación funciona si no se escucha al barrio.', fr: 'Aucune requalification ne marche si le quartier n’est pas écouté.', pt: 'Nenhuma requalificação funciona se o bairro não for ouvido.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['sorveglianza', 'resilienza', 'testimonianza'] },
  { id: 'it4s075', de: 'Un pregiudizio radicato non si smonta con un solo esperimento.', en: 'A deep-rooted prejudice is not dismantled by a single experiment.', gloss: { de: 'Ein tief verwurzeltes Vorurteil lässt sich nicht mit einem Experiment abbauen.', es: 'Un prejuicio arraigado no se desmonta con un solo experimento.', fr: 'Un préjugé enraciné ne se démonte pas avec une seule expérience.', pt: 'Um preconceito enraizado não se desmonta com um único experimento.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['recente', 'diffuso', 'evidente'] },
];
