import type { SentenceItem } from '@/content/german/types';

// English A2 sentences. `de` holds the English text (see content/german/types.ts).
// Where A1 stayed in the present tense, A2 tells small stories: past simple with
// irregular forms (took, bought, forgot, paid, lost), comparatives, and clauses
// joined with because / so / and.
//
// clozeIndex targets the load-bearing word — never an article — and the three
// clozeDistractors are same-class words that would be grammatical but wrong, so
// the exercise tests meaning rather than word shape.
//
// `en` mirrors `de` for this pack: it is the guaranteed fallback in the type
// contract, but an English-UI user is never offered English to learn, so it is
// not shown. `gloss` carries all five other UI locales — de / es / fr / it / pt.

export const A2_SENTENCES: SentenceItem[] = [
  { id: 'en2s001', de: 'I took the bus to work yesterday.', en: 'I took the bus to work yesterday.', gloss: { de: 'Ich bin gestern mit dem Bus zur Arbeit gefahren.', es: 'Ayer tomé el autobús al trabajo.', fr: 'Hier, j’ai pris le bus pour aller au travail.', it: 'Ieri ho preso l’autobus per andare al lavoro.', pt: 'Ontem peguei o ônibus para o trabalho.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['made', 'sent', 'had'] },
  { id: 'en2s002', de: 'We bought the tickets last week.', en: 'We bought the tickets last week.', gloss: { de: 'Wir haben die Fahrkarten letzte Woche gekauft.', es: 'Compramos los billetes la semana pasada.', fr: 'Nous avons acheté les billets la semaine dernière.', it: 'Abbiamo comprato i biglietti la settimana scorsa.', pt: 'Compramos os bilhetes na semana passada.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['sold', 'lost', 'sent'] },
  { id: 'en2s003', de: 'The flight was cheaper than the train.', en: 'The flight was cheaper than the train.', gloss: { de: 'Der Flug war billiger als der Zug.', es: 'El vuelo fue más barato que el tren.', fr: 'Le vol était moins cher que le train.', it: 'Il volo era più economico del treno.', pt: 'O voo foi mais barato que o trem.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['faster', 'better', 'worse'] },
  { id: 'en2s004', de: 'She forgot her keys at the office.', en: 'She forgot her keys at the office.', gloss: { de: 'Sie hat ihre Schlüssel im Büro vergessen.', es: 'Olvidó las llaves en la oficina.', fr: 'Elle a oublié ses clés au bureau.', it: 'Ha dimenticato le chiavi in ufficio.', pt: 'Ela esqueceu as chaves no escritório.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['found', 'brought', 'washed'] },
  { id: 'en2s005', de: 'I woke up early and took a shower.', en: 'I woke up early and took a shower.', gloss: { de: 'Ich bin früh aufgewacht und habe geduscht.', es: 'Me desperté temprano y me duché.', fr: 'Je me suis réveillé tôt et j’ai pris une douche.', it: 'Mi sono svegliato presto e ho fatto la doccia.', pt: 'Acordei cedo e tomei banho.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['late', 'often', 'already'] },
  { id: 'en2s006', de: 'How much did the shoes cost?', en: 'How much did the shoes cost?', gloss: { de: 'Wie viel haben die Schuhe gekostet?', es: '¿Cuánto costaron los zapatos?', fr: 'Combien ont coûté les chaussures ?', it: 'Quanto sono costate le scarpe?', pt: 'Quanto custaram os sapatos?' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['trousers', 'tickets', 'suitcases'] },
  { id: 'en2s007', de: 'He paid with a credit card.', en: 'He paid with a credit card.', gloss: { de: 'Er hat mit Kreditkarte bezahlt.', es: 'Pagó con tarjeta de crédito.', fr: 'Il a payé par carte de crédit.', it: 'Ha pagato con la carta di credito.', pt: 'Ele pagou com cartão de crédito.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['ordered', 'sold', 'sent'] },
  { id: 'en2s008', de: 'The meeting started at nine in the morning.', en: 'The meeting started at nine in the morning.', gloss: { de: 'Die Besprechung hat um neun Uhr morgens angefangen.', es: 'La reunión empezó a las nueve de la mañana.', fr: 'La réunion a commencé à neuf heures du matin.', it: 'La riunione è iniziata alle nove di mattina.', pt: 'A reunião começou às nove da manhã.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['flight', 'exam', 'trip'] },
  { id: 'en2s009', de: 'I studied at the university for three years.', en: 'I studied at the university for three years.', gloss: { de: 'Ich habe drei Jahre an der Universität studiert.', es: 'Estudié en la universidad durante tres años.', fr: 'J’ai étudié à l’université pendant trois ans.', it: 'Ho studiato all’università per tre anni.', pt: 'Estudei na universidade durante três anos.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['worked', 'lived', 'waited'] },
  { id: 'en2s010', de: 'I had a headache, so I went to the pharmacy.', en: 'I had a headache, so I went to the pharmacy.', gloss: { de: 'Ich hatte Kopfschmerzen, also bin ich in die Apotheke gegangen.', es: 'Me dolía la cabeza, así que fui a la farmacia.', fr: 'J’avais mal à la tête, alors je suis allé à la pharmacie.', it: 'Avevo mal di testa, così sono andato in farmacia.', pt: 'Eu estava com dor de cabeça, então fui à farmácia.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['came', 'looked', 'stayed'] },
  { id: 'en2s011', de: 'The doctor gave me some medicine.', en: 'The doctor gave me some medicine.', gloss: { de: 'Der Arzt hat mir ein Medikament gegeben.', es: 'El médico me dio un medicamento.', fr: 'Le médecin m’a donné un médicament.', it: 'Il medico mi ha dato una medicina.', pt: 'O médico me deu um remédio.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['sent', 'brought', 'sold'] },
  { id: 'en2s012', de: 'We were very tired after the trip.', en: 'We were very tired after the trip.', gloss: { de: 'Wir waren nach der Reise sehr müde.', es: 'Estábamos muy cansados después del viaje.', fr: 'Nous étions très fatigués après le voyage.', it: 'Eravamo molto stanchi dopo il viaggio.', pt: 'Estávamos muito cansados depois da viagem.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['happy', 'busy', 'quiet'] },
  { id: 'en2s013', de: 'She was angry because I arrived late.', en: 'She was angry because I arrived late.', gloss: { de: 'Sie war wütend, weil ich zu spät gekommen bin.', es: 'Estaba enfadada porque llegué tarde.', fr: 'Elle était en colère parce que je suis arrivé en retard.', it: 'Era arrabbiata perché sono arrivato in ritardo.', pt: 'Ela ficou brava porque cheguei atrasado.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['sad', 'worried', 'bored'] },
  { id: 'en2s014', de: 'I think this restaurant is the best in the city.', en: 'I think this restaurant is the best in the city.', gloss: { de: 'Ich finde, dieses Restaurant ist das beste in der Stadt.', es: 'Creo que este restaurante es el mejor de la ciudad.', fr: 'Je pense que ce restaurant est le meilleur de la ville.', it: 'Penso che questo ristorante sia il migliore della città.', pt: 'Acho que este restaurante é o melhor da cidade.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['worst', 'cheapest', 'biggest'] },
  { id: 'en2s015', de: 'The flat has a big kitchen and a garden.', en: 'The flat has a big kitchen and a garden.', gloss: { de: 'Die Wohnung hat eine große Küche und einen Garten.', es: 'El apartamento tiene una cocina grande y un jardín.', fr: 'L’appartement a une grande cuisine et un jardin.', it: 'L’appartamento ha una cucina grande e un giardino.', pt: 'O apartamento tem uma cozinha grande e um jardim.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['bedroom', 'bathroom', 'office'] },
  { id: 'en2s016', de: 'We paid the rent last month.', en: 'We paid the rent last month.', gloss: { de: 'Wir haben die Miete letzten Monat bezahlt.', es: 'Pagamos el alquiler el mes pasado.', fr: 'Nous avons payé le loyer le mois dernier.', it: 'Abbiamo pagato l’affitto il mese scorso.', pt: 'Pagamos o aluguel no mês passado.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['bill', 'price', 'salary'] },
  { id: 'en2s017', de: 'He cooked a soup with rice and vegetables.', en: 'He cooked a soup with rice and vegetables.', gloss: { de: 'Er hat eine Suppe mit Reis und Gemüse gekocht.', es: 'Cocinó una sopa con arroz y verduras.', fr: 'Il a préparé une soupe avec du riz et des légumes.', it: 'Ha cucinato una zuppa con riso e verdure.', pt: 'Ele cozinhou uma sopa com arroz e legumes.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['ordered', 'bought', 'brought'] },
  { id: 'en2s018', de: 'We ordered a dessert and two coffees.', en: 'We ordered a dessert and two coffees.', gloss: { de: 'Wir haben einen Nachtisch und zwei Kaffee bestellt.', es: 'Pedimos un postre y dos cafés.', fr: 'Nous avons commandé un dessert et deux cafés.', it: 'Abbiamo ordinato un dolce e due caffè.', pt: 'Pedimos uma sobremesa e dois cafés.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['soup', 'menu', 'chicken'] },
  { id: 'en2s019', de: 'Yesterday the weather was sunny and warm.', en: 'Yesterday the weather was sunny and warm.', gloss: { de: 'Gestern war das Wetter sonnig und warm.', es: 'Ayer el tiempo estuvo soleado y cálido.', fr: 'Hier, le temps était ensoleillé et chaud.', it: 'Ieri il tempo era soleggiato e caldo.', pt: 'Ontem o tempo estava ensolarado e quente.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['cloudy', 'windy', 'cold'] },
  { id: 'en2s020', de: 'I sometimes work from home on Fridays.', en: 'I sometimes work from home on Fridays.', gloss: { de: 'Ich arbeite freitags manchmal von zu Hause.', es: 'A veces trabajo desde casa los viernes.', fr: 'Je travaille parfois à la maison le vendredi.', it: 'A volte lavoro da casa il venerdì.', pt: 'Às vezes trabalho de casa às sextas-feiras.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['often', 'never', 'always'] },
  { id: 'en2s021', de: 'Did you send the email to your boss?', en: 'Did you send the email to your boss?', gloss: { de: 'Hast du die E-Mail an deinen Chef geschickt?', es: '¿Enviaste el correo a tu jefe?', fr: 'As-tu envoyé l’e-mail à ton patron ?', it: 'Hai mandato l’e-mail al tuo capo?', pt: 'Você enviou o e-mail para o seu chefe?' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['bring', 'pay', 'forget'] },
  { id: 'en2s022', de: 'I lost my suitcase at the airport.', en: 'I lost my suitcase at the airport.', gloss: { de: 'Ich habe meinen Koffer am Flughafen verloren.', es: 'Perdí la maleta en el aeropuerto.', fr: 'J’ai perdu ma valise à l’aéroport.', it: 'Ho perso la valigia in aeroporto.', pt: 'Perdi a minha mala no aeroporto.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['found', 'sent', 'bought'] },
  { id: 'en2s023', de: 'She sent me a message about the meeting.', en: 'She sent me a message about the meeting.', gloss: { de: 'Sie hat mir eine Nachricht wegen der Besprechung geschickt.', es: 'Me envió un mensaje sobre la reunión.', fr: 'Elle m’a envoyé un message au sujet de la réunion.', it: 'Mi ha mandato un messaggio riguardo alla riunione.', pt: 'Ela me enviou uma mensagem sobre a reunião.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['paid', 'cooked', 'washed'] },
  { id: 'en2s024', de: 'We are going to visit my grandparents next month.', en: 'We are going to visit my grandparents next month.', gloss: { de: 'Wir werden nächsten Monat meine Großeltern besuchen.', es: 'Vamos a visitar a mis abuelos el mes que viene.', fr: 'Nous allons rendre visite à mes grands-parents le mois prochain.', it: 'Il mese prossimo andremo a trovare i miei nonni.', pt: 'Vamos visitar meus avós no mês que vem.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['call', 'invite', 'help'] },
  { id: 'en2s025', de: 'The shop was closed when we arrived.', en: 'The shop was closed when we arrived.', gloss: { de: 'Der Laden war geschlossen, als wir ankamen.', es: 'La tienda estaba cerrada cuando llegamos.', fr: 'Le magasin était fermé quand nous sommes arrivés.', it: 'Il negozio era chiuso quando siamo arrivati.', pt: 'A loja estava fechada quando chegamos.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['empty', 'crowded', 'quiet'] },
  { id: 'en2s026', de: 'I am going to book a table for two.', en: 'I am going to book a table for two.', gloss: { de: 'Ich werde einen Tisch für zwei Personen reservieren.', es: 'Voy a reservar una mesa para dos.', fr: 'Je vais réserver une table pour deux.', it: 'Prenoterò un tavolo per due.', pt: 'Vou reservar uma mesa para dois.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['clean', 'pay', 'order'] },
  { id: 'en2s027', de: 'He waited at the bus stop for twenty minutes.', en: 'He waited at the bus stop for twenty minutes.', gloss: { de: 'Er hat zwanzig Minuten an der Bushaltestelle gewartet.', es: 'Esperó veinte minutos en la parada del autobús.', fr: 'Il a attendu vingt minutes à l’arrêt de bus.', it: 'Ha aspettato venti minuti alla fermata dell’autobus.', pt: 'Ele esperou vinte minutos no ponto de ônibus.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['arrived', 'worked', 'stayed'] },
  { id: 'en2s028', de: 'My flat is smaller than yours, but it is cheaper.', en: 'My flat is smaller than yours, but it is cheaper.', gloss: { de: 'Meine Wohnung ist kleiner als deine, aber sie ist billiger.', es: 'Mi apartamento es más pequeño que el tuyo, pero es más barato.', fr: 'Mon appartement est plus petit que le tien, mais il est moins cher.', it: 'Il mio appartamento è più piccolo del tuo, ma è più economico.', pt: 'Meu apartamento é menor que o seu, mas é mais barato.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['bigger', 'older', 'newer'] },
  { id: 'en2s029', de: 'We did not have enough money for the tickets.', en: 'We did not have enough money for the tickets.', gloss: { de: 'Wir hatten nicht genug Geld für die Fahrkarten.', es: 'No teníamos suficiente dinero para los billetes.', fr: 'Nous n’avions pas assez d’argent pour les billets.', it: 'Non avevamo abbastanza soldi per i biglietti.', pt: 'Não tínhamos dinheiro suficiente para as passagens.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['time', 'space', 'room'] },
  { id: 'en2s030', de: 'She has lived in Manchester for five years.', en: 'She has lived in Manchester for five years.', gloss: { de: 'Sie wohnt seit fünf Jahren in Manchester.', es: 'Vive en Mánchester desde hace cinco años.', fr: 'Elle habite à Manchester depuis cinq ans.', it: 'Vive a Manchester da cinque anni.', pt: 'Ela mora em Manchester há cinco anos.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['worked', 'studied', 'stayed'] },
  { id: 'en2s031', de: 'I washed the dishes after dinner.', en: 'I washed the dishes after dinner.', gloss: { de: 'Ich habe nach dem Abendessen abgewaschen.', es: 'Lavé los platos después de la cena.', fr: 'J’ai fait la vaisselle après le dîner.', it: 'Ho lavato i piatti dopo cena.', pt: 'Lavei a louça depois do jantar.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['cooked', 'ordered', 'bought'] },
  { id: 'en2s032', de: 'The underground was very crowded this morning.', en: 'The underground was very crowded this morning.', gloss: { de: 'Die U-Bahn war heute Morgen sehr voll.', es: 'El metro estaba muy lleno esta mañana.', fr: 'Le métro était très bondé ce matin.', it: 'La metropolitana era molto affollata stamattina.', pt: 'O metrô estava muito cheio esta manhã.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['quiet', 'empty', 'clean'] },
  { id: 'en2s033', de: 'Could you tell me where the lift is?', en: 'Could you tell me where the lift is?', gloss: { de: 'Könnten Sie mir sagen, wo der Aufzug ist?', es: '¿Podría decirme dónde está el ascensor?', fr: 'Pourriez-vous me dire où est l’ascenseur ?', it: 'Potrebbe dirmi dov’è l’ascensore?', pt: 'Você poderia me dizer onde fica o elevador?' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['kitchen', 'entrance', 'station'] },
  { id: 'en2s034', de: 'They moved to a bigger flat last autumn.', en: 'They moved to a bigger flat last autumn.', gloss: { de: 'Sie sind letzten Herbst in eine größere Wohnung gezogen.', es: 'Se mudaron a un apartamento más grande el otoño pasado.', fr: 'Ils ont déménagé dans un appartement plus grand l’automne dernier.', it: 'L’autunno scorso si sono trasferiti in un appartamento più grande.', pt: 'Eles se mudaram para um apartamento maior no outono passado.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['walked', 'travelled', 'returned'] },
  { id: 'en2s035', de: 'I have to finish this report before Friday.', en: 'I have to finish this report before Friday.', gloss: { de: 'Ich muss diesen Bericht vor Freitag fertig machen.', es: 'Tengo que terminar este informe antes del viernes.', fr: 'Je dois finir ce rapport avant vendredi.', it: 'Devo finire questa relazione prima di venerdì.', pt: 'Tenho que terminar este relatório antes de sexta-feira.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['send', 'print', 'check'] },
  { id: 'en2s036', de: 'She was wearing a blue coat and black boots.', en: 'She was wearing a blue coat and black boots.', gloss: { de: 'Sie trug einen blauen Mantel und schwarze Stiefel.', es: 'Llevaba un abrigo azul y botas negras.', fr: 'Elle portait un manteau bleu et des bottes noires.', it: 'Indossava un cappotto blu e stivali neri.', pt: 'Ela estava usando um casaco azul e botas pretas.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['buying', 'washing', 'carrying'] },
  { id: 'en2s037', de: 'We watched a film and then went to bed.', en: 'We watched a film and then went to bed.', gloss: { de: 'Wir haben einen Film gesehen und sind dann ins Bett gegangen.', es: 'Vimos una película y luego nos acostamos.', fr: 'Nous avons regardé un film puis nous sommes allés nous coucher.', it: 'Abbiamo visto un film e poi siamo andati a letto.', pt: 'Assistimos a um filme e depois fomos para a cama.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['booked', 'cooked', 'cleaned'] },
  { id: 'en2s038', de: 'The queue at the post office was very long.', en: 'The queue at the post office was very long.', gloss: { de: 'Die Schlange auf der Post war sehr lang.', es: 'La cola en la oficina de correos era muy larga.', fr: 'La file d’attente à la poste était très longue.', it: 'La fila alla posta era molto lunga.', pt: 'A fila no correio estava muito longa.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['meeting', 'journey', 'holiday'] },
  { id: 'en2s039', de: 'I usually walk to work when the weather is good.', en: 'I usually walk to work when the weather is good.', gloss: { de: 'Ich gehe normalerweise zu Fuß zur Arbeit, wenn das Wetter gut ist.', es: 'Normalmente voy andando al trabajo cuando hace buen tiempo.', fr: 'Je vais généralement au travail à pied quand il fait beau.', it: 'Di solito vado al lavoro a piedi quando il tempo è bello.', pt: 'Normalmente vou a pé para o trabalho quando o tempo está bom.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['drive', 'cycle', 'run'] },
  { id: 'en2s040', de: 'He borrowed a book from the library yesterday.', en: 'He borrowed a book from the library yesterday.', gloss: { de: 'Er hat gestern ein Buch aus der Bibliothek ausgeliehen.', es: 'Ayer sacó un libro de la biblioteca.', fr: 'Il a emprunté un livre à la bibliothèque hier.', it: 'Ieri ha preso in prestito un libro dalla biblioteca.', pt: 'Ontem ele pegou um livro emprestado na biblioteca.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['returned', 'ordered', 'carried'] },
  { id: 'en2s041', de: 'Next summer we are going to travel around Scotland.', en: 'Next summer we are going to travel around Scotland.', gloss: { de: 'Nächsten Sommer werden wir durch Schottland reisen.', es: 'El próximo verano vamos a viajar por Escocia.', fr: 'L’été prochain, nous allons voyager en Écosse.', it: 'La prossima estate viaggeremo per la Scozia.', pt: 'No próximo verão vamos viajar pela Escócia.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['drive', 'walk', 'cycle'] },
  { id: 'en2s042', de: 'I forgot to switch off the lights.', en: 'I forgot to switch off the lights.', gloss: { de: 'Ich habe vergessen, das Licht auszuschalten.', es: 'Olvidé apagar las luces.', fr: 'J’ai oublié d’éteindre les lumières.', it: 'Ho dimenticato di spegnere le luci.', pt: 'Esqueci de apagar as luzes.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['agreed', 'decided', 'promised'] },
  { id: 'en2s043', de: 'The bill was higher than we expected.', en: 'The bill was higher than we expected.', gloss: { de: 'Die Rechnung war höher, als wir erwartet hatten.', es: 'La cuenta fue más alta de lo que esperábamos.', fr: 'L’addition était plus élevée que prévu.', it: 'Il conto era più alto di quanto ci aspettassimo.', pt: 'A conta foi mais alta do que esperávamos.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['cheaper', 'lower', 'smaller'] },
  { id: 'en2s044', de: 'She cleaned the kitchen while I did the shopping.', en: 'She cleaned the kitchen while I did the shopping.', gloss: { de: 'Sie hat die Küche geputzt, während ich eingekauft habe.', es: 'Ella limpió la cocina mientras yo hacía la compra.', fr: 'Elle a nettoyé la cuisine pendant que je faisais les courses.', it: 'Ha pulito la cucina mentre io facevo la spesa.', pt: 'Ela limpou a cozinha enquanto eu fazia as compras.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['painted', 'booked', 'opened'] },
  { id: 'en2s045', de: 'Are you going to the party on Saturday evening?', en: 'Are you going to the party on Saturday evening?', gloss: { de: 'Gehst du am Samstagabend auf die Party?', es: '¿Vas a la fiesta el sábado por la noche?', fr: 'Est-ce que tu vas à la fête samedi soir ?', it: 'Vai alla festa sabato sera?', pt: 'Você vai à festa no sábado à noite?' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['beach', 'meeting', 'airport'] },
  { id: 'en2s046', de: 'I have already booked a room in a small hotel.', en: 'I have already booked a room in a small hotel.', gloss: { de: 'Ich habe schon ein Zimmer in einem kleinen Hotel gebucht.', es: 'Ya he reservado una habitación en un hotel pequeño.', fr: 'J’ai déjà réservé une chambre dans un petit hôtel.', it: 'Ho già prenotato una camera in un piccolo hotel.', pt: 'Já reservei um quarto em um hotel pequeno.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['painted', 'cleaned', 'sold'] },
  { id: 'en2s047', de: 'The film was boring, so we left early.', en: 'The film was boring, so we left early.', gloss: { de: 'Der Film war langweilig, also sind wir früh gegangen.', es: 'La película era aburrida, así que nos fuimos temprano.', fr: 'Le film était ennuyeux, alors nous sommes partis tôt.', it: 'Il film era noioso, così ce ne siamo andati presto.', pt: 'O filme era chato, então saímos cedo.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['funny', 'expensive', 'crowded'] },
  { id: 'en2s048', de: 'My neighbour helped me carry the suitcases upstairs.', en: 'My neighbour helped me carry the suitcases upstairs.', gloss: { de: 'Mein Nachbar hat mir geholfen, die Koffer nach oben zu tragen.', es: 'Mi vecino me ayudó a subir las maletas.', fr: 'Mon voisin m’a aidé à monter les valises.', it: 'Il mio vicino mi ha aiutato a portare su le valigie.', pt: 'Meu vizinho me ajudou a levar as malas para cima.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['watched', 'asked', 'taught'] },
  { id: 'en2s049', de: 'It rained all weekend, so we stayed at home.', en: 'It rained all weekend, so we stayed at home.', gloss: { de: 'Es hat das ganze Wochenende geregnet, also sind wir zu Hause geblieben.', es: 'Llovió todo el fin de semana, así que nos quedamos en casa.', fr: 'Il a plu tout le week-end, alors nous sommes restés à la maison.', it: 'Ha piovuto tutto il fine settimana, così siamo rimasti a casa.', pt: 'Choveu o fim de semana inteiro, então ficamos em casa.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['snowed', 'worked', 'waited'] },
  { id: 'en2s050', de: 'I need to change some money before the trip.', en: 'I need to change some money before the trip.', gloss: { de: 'Ich muss vor der Reise Geld wechseln.', es: 'Necesito cambiar dinero antes del viaje.', fr: 'Je dois changer de l’argent avant le voyage.', it: 'Devo cambiare dei soldi prima del viaggio.', pt: 'Preciso trocar dinheiro antes da viagem.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['spend', 'count', 'earn'] },
  { id: 'en2s051', de: 'The train to Edinburgh leaves from platform four.', en: 'The train to Edinburgh leaves from platform four.', gloss: { de: 'Der Zug nach Edinburgh fährt von Gleis vier ab.', es: 'El tren a Edimburgo sale del andén cuatro.', fr: 'Le train pour Édimbourg part du quai quatre.', it: 'Il treno per Edimburgo parte dal binario quattro.', pt: 'O trem para Edimburgo sai da plataforma quatro.' }, level: 'A2', clozeIndex: 6, clozeDistractors: ['station', 'ticket', 'journey'] },
  { id: 'en2s052', de: 'She told me that she was looking for a new job.', en: 'She told me that she was looking for a new job.', gloss: { de: 'Sie hat mir gesagt, dass sie eine neue Stelle sucht.', es: 'Me dijo que estaba buscando un trabajo nuevo.', fr: 'Elle m’a dit qu’elle cherchait un nouveau travail.', it: 'Mi ha detto che cercava un nuovo lavoro.', pt: 'Ela me disse que estava procurando um novo emprego.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['asked', 'showed', 'sent'] },
  { id: 'en2s053', de: 'We had dinner in a quiet restaurant near the river.', en: 'We had dinner in a quiet restaurant near the river.', gloss: { de: 'Wir haben in einem ruhigen Restaurant am Fluss zu Abend gegessen.', es: 'Cenamos en un restaurante tranquilo cerca del río.', fr: 'Nous avons dîné dans un restaurant tranquille près de la rivière.', it: 'Abbiamo cenato in un ristorante tranquillo vicino al fiume.', pt: 'Jantamos em um restaurante tranquilo perto do rio.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['crowded', 'expensive', 'modern'] },
  { id: 'en2s054', de: 'I am learning to drive, but it is quite difficult.', en: 'I am learning to drive, but it is quite difficult.', gloss: { de: 'Ich lerne gerade Auto fahren, aber es ist ziemlich schwierig.', es: 'Estoy aprendiendo a conducir, pero es bastante difícil.', fr: 'J’apprends à conduire, mais c’est assez difficile.', it: 'Sto imparando a guidare, ma è piuttosto difficile.', pt: 'Estou aprendendo a dirigir, mas é bem difícil.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['starting', 'waiting', 'hoping'] },
  { id: 'en2s055', de: 'He left his umbrella on the train again.', en: 'He left his umbrella on the train again.', gloss: { de: 'Er hat seinen Regenschirm schon wieder im Zug liegen lassen.', es: 'Se dejó el paraguas en el tren otra vez.', fr: 'Il a encore oublié son parapluie dans le train.', it: 'Ha lasciato di nuovo l’ombrello sul treno.', pt: 'Ele deixou o guarda-chuva no trem de novo.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['jacket', 'suitcase', 'ticket'] },
  { id: 'en2s056', de: 'The chemist on the corner opens at eight.', en: 'The chemist on the corner opens at eight.', gloss: { de: 'Die Apotheke an der Ecke öffnet um acht.', es: 'La farmacia de la esquina abre a las ocho.', fr: 'La pharmacie du coin ouvre à huit heures.', it: 'La farmacia all’angolo apre alle otto.', pt: 'A farmácia da esquina abre às oito.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['closes', 'arrives', 'starts'] },
  { id: 'en2s057', de: 'Do you want to come with us to the cinema?', en: 'Do you want to come with us to the cinema?', gloss: { de: 'Willst du mit uns ins Kino kommen?', es: '¿Quieres venir con nosotros al cine?', fr: 'Tu veux venir avec nous au cinéma ?', it: 'Vuoi venire con noi al cinema?', pt: 'Você quer vir com a gente ao cinema?' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['walk', 'drive', 'travel'] },
  { id: 'en2s058', de: 'Last night I could not sleep because of the noise.', en: 'Last night I could not sleep because of the noise.', gloss: { de: 'Letzte Nacht konnte ich wegen des Lärms nicht schlafen.', es: 'Anoche no pude dormir por el ruido.', fr: 'Hier soir, je n’ai pas pu dormir à cause du bruit.', it: 'Ieri notte non sono riuscito a dormire per il rumore.', pt: 'Ontem à noite não consegui dormir por causa do barulho.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['work', 'read', 'study'] },
  { id: 'en2s059', de: 'The exam was easier than I expected.', en: 'The exam was easier than I expected.', gloss: { de: 'Die Prüfung war leichter, als ich erwartet hatte.', es: 'El examen fue más fácil de lo que esperaba.', fr: 'L’examen était plus facile que je ne le pensais.', it: 'L’esame è stato più facile di quanto pensassi.', pt: 'A prova foi mais fácil do que eu esperava.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['harder', 'longer', 'shorter'] },
  { id: 'en2s060', de: 'She is going to start a new course in September.', en: 'She is going to start a new course in September.', gloss: { de: 'Sie wird im September einen neuen Kurs anfangen.', es: 'Va a empezar un curso nuevo en septiembre.', fr: 'Elle va commencer un nouveau cours en septembre.', it: 'A settembre inizierà un nuovo corso.', pt: 'Ela vai começar um novo curso em setembro.' }, level: 'A2', clozeIndex: 7, clozeDistractors: ['job', 'flat', 'holiday'] },
  { id: 'en2s061', de: 'I paid for the shopping with my debit card.', en: 'I paid for the shopping with my debit card.', gloss: { de: 'Ich habe den Einkauf mit meiner Bankkarte bezahlt.', es: 'Pagué la compra con mi tarjeta de débito.', fr: 'J’ai payé les courses avec ma carte bancaire.', it: 'Ho pagato la spesa con la mia carta di debito.', pt: 'Paguei as compras com meu cartão de débito.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['tickets', 'flight', 'holiday'] },
  { id: 'en2s062', de: 'We booked our holiday online three weeks ago.', en: 'We booked our holiday online three weeks ago.', gloss: { de: 'Wir haben unseren Urlaub vor drei Wochen online gebucht.', es: 'Reservamos nuestras vacaciones por internet hace tres semanas.', fr: 'Nous avons réservé nos vacances en ligne il y a trois semaines.', it: 'Abbiamo prenotato la vacanza online tre settimane fa.', pt: 'Reservamos nossas férias pela internet há três semanas.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['flight', 'journey', 'ticket'] },
];
