import type { SentenceItem } from '@/content/german/types';

// English B2 sentences. `de` holds the English text (see content/german/types.ts).
// Where B1 argues in plain subordination, B2 argues in structure: third and mixed
// conditionals, inversion after negative adverbials (rarely, not until, little
// did, so/such), cleft sentences (it was X that…, what surprised me was…),
// passive reporting (is said to have…, is alleged to have been…), modal perfects
// (must have been, would have had to, might well have been), and the connectors
// of concession and condition (albeit, notwithstanding, insofar as, provided
// that, hence, conversely).
//
// BRITISH English throughout, matching b2-vocab.ts: spelling (colour, realise,
// centre, summarised, apologise) and vocabulary (the lift, the underground, the
// queue, rubbish, a fortnight, the council, a flat, a mobile, autumn).
//
// clozeIndex targets the load-bearing word — never an article, and never the
// final word of the sentence, since a trailing full stop the distractors lack
// would give the answer away. The three clozeDistractors are same-class words
// that would be grammatical but wrong, so the exercise tests meaning rather
// than grammar alone.
//
// `en` mirrors `de` for this pack: it is the guaranteed fallback in the type
// contract, but an English-UI user is never offered English to learn, so it is
// not shown. `gloss` carries all five other UI locales — de / es / fr / it / pt.

export const B2_SENTENCES: SentenceItem[] = [
  { id: 'en4s001', de: 'Had we known about the risks, we would have postponed the launch.', en: 'Had we known about the risks, we would have postponed the launch.', gloss: { de: 'Hätten wir von den Risiken gewusst, hätten wir den Start verschoben.', es: 'Si hubiéramos conocido los riesgos, habríamos aplazado el lanzamiento.', fr: 'Si nous avions connu les risques, nous aurions reporté le lancement.', it: 'Se avessimo conosciuto i rischi, avremmo rinviato il lancio.', pt: 'Se soubéssemos dos riscos, teríamos adiado o lançamento.' }, level: 'B2', clozeIndex: 9, clozeDistractors: ['cancelled', 'announced', 'approved'] },
  { id: 'en4s002', de: 'The report must have been leaked before the meeting began.', en: 'The report must have been leaked before the meeting began.', gloss: { de: 'Der Bericht muss vor Beginn der Sitzung durchgesickert sein.', es: 'El informe debió de filtrarse antes de que empezara la reunión.', fr: 'Le rapport a dû fuiter avant le début de la réunion.', it: 'Il rapporto dev’essere trapelato prima che iniziasse la riunione.', pt: 'O relatório deve ter vazado antes de a reunião começar.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['drafted', 'filed', 'edited'] },
  { id: 'en4s003', de: 'It was the tone, rather than the content, that offended the committee.', en: 'It was the tone, rather than the content, that offended the committee.', gloss: { de: 'Es war der Ton und nicht der Inhalt, der den Ausschuss verärgert hat.', es: 'Fue el tono, más que el contenido, lo que ofendió al comité.', fr: 'C’est le ton, plutôt que le contenu, qui a offensé le comité.', it: 'È stato il tono, più che il contenuto, a offendere la commissione.', pt: 'Foi o tom, e não o conteúdo, que ofendeu a comissão.' }, level: 'B2', clozeIndex: 9, clozeDistractors: ['impressed', 'concerned', 'alarmed'] },
  { id: 'en4s004', de: 'Not only did the scheme fail, but it also damaged public trust.', en: 'Not only did the scheme fail, but it also damaged public trust.', gloss: { de: 'Das Programm ist nicht nur gescheitert, es hat auch das Vertrauen der Öffentlichkeit beschädigt.', es: 'El plan no solo fracasó, sino que además dañó la confianza pública.', fr: 'Non seulement le dispositif a échoué, mais il a aussi nui à la confiance du public.', it: 'Non solo il piano è fallito, ma ha anche danneggiato la fiducia pubblica.', pt: 'O programa não só fracassou, como também prejudicou a confiança pública.' }, level: 'B2', clozeIndex: 9, clozeDistractors: ['restored', 'shaped', 'reflected'] },
  { id: 'en4s005', de: 'Were the evidence stronger, the case would already have gone to trial.', en: 'Were the evidence stronger, the case would already have gone to trial.', gloss: { de: 'Wären die Beweise stärker, wäre der Fall längst vor Gericht gegangen.', es: 'Si las pruebas fueran más sólidas, el caso ya habría llegado a juicio.', fr: 'Si les preuves étaient plus solides, l’affaire serait déjà passée en procès.', it: 'Se le prove fossero più solide, il caso sarebbe già andato a processo.', pt: 'Se as provas fossem mais sólidas, o caso já teria ido a julgamento.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['testimony', 'motive', 'defence'] },
  { id: 'en4s006', de: 'What surprised me most was how readily the tenants accepted the rise.', en: 'What surprised me most was how readily the tenants accepted the rise.', gloss: { de: 'Was mich am meisten überrascht hat, war, wie bereitwillig die Mieter die Erhöhung akzeptiert haben.', es: 'Lo que más me sorprendió fue con qué facilidad los inquilinos aceptaron la subida.', fr: 'Ce qui m’a le plus surpris, c’est la facilité avec laquelle les locataires ont accepté la hausse.', it: 'Ciò che più mi ha sorpreso è stata la prontezza con cui gli inquilini hanno accettato l’aumento.', pt: 'O que mais me surpreendeu foi a facilidade com que os inquilinos aceitaram o aumento.' }, level: 'B2', clozeIndex: 8, clozeDistractors: ['landlords', 'commuters', 'residents'] },
  { id: 'en4s007', de: 'The council is said to have approved the plan without proper consultation.', en: 'The council is said to have approved the plan without proper consultation.', gloss: { de: 'Die Stadtverwaltung soll den Plan ohne ordentliche Anhörung genehmigt haben.', es: 'Se dice que el ayuntamiento aprobó el plan sin una consulta adecuada.', fr: 'La mairie aurait approuvé le projet sans véritable consultation.', it: 'Si dice che il comune abbia approvato il piano senza una vera consultazione.', pt: 'Diz-se que a câmara municipal aprovou o plano sem consulta adequada.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['rejected', 'drafted', 'delayed'] },
  { id: 'en4s008', de: 'Had she taken the job, she would be living in Manchester now.', en: 'Had she taken the job, she would be living in Manchester now.', gloss: { de: 'Hätte sie die Stelle angenommen, würde sie jetzt in Manchester wohnen.', es: 'Si hubiera aceptado el puesto, ahora estaría viviendo en Mánchester.', fr: 'Si elle avait accepté le poste, elle vivrait aujourd’hui à Manchester.', it: 'Se avesse accettato il posto, ora vivrebbe a Manchester.', pt: 'Se ela tivesse aceitado o emprego, estaria a viver em Manchester agora.' }, level: 'B2', clozeIndex: 8, clozeDistractors: ['working', 'studying', 'staying'] },
  { id: 'en4s009', de: 'Nevertheless, the argument gains traction insofar as the data support it.', en: 'Nevertheless, the argument gains traction insofar as the data support it.', gloss: { de: 'Dennoch gewinnt das Argument an Zugkraft, insofern die Daten es stützen.', es: 'Aun así, el argumento gana terreno en la medida en que los datos lo respaldan.', fr: 'Néanmoins, l’argument gagne du terrain dans la mesure où les données le confirment.', it: 'Tuttavia, l’argomento prende piede nella misura in cui i dati lo sostengono.', pt: 'Mesmo assim, o argumento ganha terreno na medida em que os dados o sustentam.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['ground', 'momentum', 'credibility'] },
  { id: 'en4s010', de: 'Provided that the funding continues, the research will run for another decade.', en: 'Provided that the funding continues, the research will run for another decade.', gloss: { de: 'Vorausgesetzt, dass die Finanzierung weiterläuft, wird die Forschung noch ein Jahrzehnt fortgesetzt.', es: 'Siempre que continúe la financiación, la investigación durará otra década.', fr: 'À condition que le financement se poursuive, la recherche durera encore une décennie.', it: 'A condizione che i finanziamenti continuino, la ricerca proseguirà per un altro decennio.', pt: 'Desde que o financiamento continue, a pesquisa vai durar mais uma década.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['staffing', 'interest', 'demand'] },
  { id: 'en4s011', de: 'The minister would have had to resign had the story been published.', en: 'The minister would have had to resign had the story been published.', gloss: { de: 'Der Minister hätte zurücktreten müssen, wäre die Geschichte veröffentlicht worden.', es: 'El ministro habría tenido que dimitir si la historia se hubiera publicado.', fr: 'Le ministre aurait dû démissionner si l’affaire avait été publiée.', it: 'Il ministro avrebbe dovuto dimettersi se la storia fosse stata pubblicata.', pt: 'O ministro teria tido de se demitir se a história tivesse sido publicada.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['apologise', 'withdraw', 'explain'] },
  { id: 'en4s012', de: 'Albeit expensive, the scheme has measurably reduced congestion in the centre.', en: 'Albeit expensive, the scheme has measurably reduced congestion in the centre.', gloss: { de: 'Wenn auch teuer, hat das Programm den Verkehr im Zentrum messbar verringert.', es: 'Aunque caro, el plan ha reducido de forma medible la congestión en el centro.', fr: 'Bien que coûteux, le dispositif a réduit de façon mesurable les embouteillages dans le centre.', it: 'Sebbene costoso, il piano ha ridotto in modo misurabile la congestione in centro.', pt: 'Embora caro, o programa reduziu de forma mensurável o congestionamento no centro.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['worsened', 'monitored', 'tolerated'] },
  { id: 'en4s013', de: 'It is widely believed that the algorithm favours certain suppliers.', en: 'It is widely believed that the algorithm favours certain suppliers.', gloss: { de: 'Es wird allgemein angenommen, dass der Algorithmus bestimmte Lieferanten bevorzugt.', es: 'Se cree en general que el algoritmo favorece a ciertos proveedores.', fr: 'On pense généralement que l’algorithme favorise certains fournisseurs.', it: 'Si ritiene in genere che l’algoritmo favorisca certi fornitori.', pt: 'Acredita-se em geral que o algoritmo favorece certos fornecedores.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['committee', 'regulator', 'contract'] },
  { id: 'en4s014', de: 'Rarely have I read a review so unfair to the author.', en: 'Rarely have I read a review so unfair to the author.', gloss: { de: 'Selten habe ich eine Rezension gelesen, die dem Autor gegenüber so unfair war.', es: 'Pocas veces he leído una crítica tan injusta con el autor.', fr: 'J’ai rarement lu une critique aussi injuste envers l’auteur.', it: 'Raramente ho letto una recensione così ingiusta verso l’autore.', pt: 'Raramente li uma crítica tão injusta com o autor.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['account', 'critique', 'summary'] },
  { id: 'en4s015', de: 'Only after the trial did the full extent of the negligence emerge.', en: 'Only after the trial did the full extent of the negligence emerge.', gloss: { de: 'Erst nach dem Prozess kam das ganze Ausmaß der Fahrlässigkeit ans Licht.', es: 'Solo después del juicio salió a la luz el alcance completo de la negligencia.', fr: 'Ce n’est qu’après le procès que toute l’ampleur de la négligence est apparue.', it: 'Solo dopo il processo è emersa l’intera portata della negligenza.', pt: 'Só depois do julgamento é que veio à luz toda a extensão da negligência.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['inquiry', 'hearing', 'investigation'] },
  { id: 'en4s016', de: 'The company claims to have offset all of its emissions since 2020.', en: 'The company claims to have offset all of its emissions since 2020.', gloss: { de: 'Das Unternehmen behauptet, seit 2020 alle seine Emissionen ausgeglichen zu haben.', es: 'La empresa afirma haber compensado todas sus emisiones desde 2020.', fr: 'L’entreprise affirme avoir compensé toutes ses émissions depuis 2020.', it: 'L’azienda sostiene di aver compensato tutte le sue emissioni dal 2020.', pt: 'A empresa afirma ter compensado todas as suas emissões desde 2020.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['measured', 'reported', 'reduced'] },
  { id: 'en4s017', de: 'Whereas the north has prospered, the coastal towns have been left behind.', en: 'Whereas the north has prospered, the coastal towns have been left behind.', gloss: { de: 'Während der Norden aufgeblüht ist, sind die Küstenstädte zurückgeblieben.', es: 'Mientras que el norte ha prosperado, los pueblos costeros se han quedado atrás.', fr: 'Alors que le nord a prospéré, les villes côtières ont été laissées de côté.', it: 'Mentre il nord ha prosperato, le città costiere sono rimaste indietro.', pt: 'Enquanto o norte prosperou, as cidades costeiras ficaram para trás.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['declined', 'stagnated', 'suffered'] },
  { id: 'en4s018', de: 'She might well have been misled by an unreliable source.', en: 'She might well have been misled by an unreliable source.', gloss: { de: 'Sie könnte durchaus von einer unzuverlässigen Quelle in die Irre geführt worden sein.', es: 'Es muy posible que la haya engañado una fuente poco fiable.', fr: 'Elle a très bien pu être induite en erreur par une source peu fiable.', it: 'Potrebbe benissimo essere stata fuorviata da una fonte poco affidabile.', pt: 'É bem possível que ela tenha sido induzida em erro por uma fonte pouco fiável.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['informed', 'contacted', 'advised'] },
  { id: 'en4s019', de: 'Notwithstanding the delays, the project came in under budget.', en: 'Notwithstanding the delays, the project came in under budget.', gloss: { de: 'Ungeachtet der Verzögerungen blieb das Projekt unter dem Budget.', es: 'A pesar de los retrasos, el proyecto costó menos de lo presupuestado.', fr: 'Malgré les retards, le projet est resté en dessous du budget.', it: 'Nonostante i ritardi, il progetto è rimasto sotto budget.', pt: 'Apesar dos atrasos, o projeto ficou abaixo do orçamento.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['objections', 'setbacks', 'complaints'] },
  { id: 'en4s020', de: 'It is precisely this ambiguity that makes the clause so contentious.', en: 'It is precisely this ambiguity that makes the clause so contentious.', gloss: { de: 'Gerade diese Mehrdeutigkeit macht die Klausel so umstritten.', es: 'Es precisamente esta ambigüedad la que hace tan polémica la cláusula.', fr: 'C’est précisément cette ambiguïté qui rend la clause si controversée.', it: 'È proprio questa ambiguità a rendere la clausola così controversa.', pt: 'É precisamente esta ambiguidade que torna a cláusula tão controversa.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['wording', 'omission', 'vagueness'] },
  { id: 'en4s021', de: 'Should the tenant refuse to pay, the landlord may seek an eviction.', en: 'Should the tenant refuse to pay, the landlord may seek an eviction.', gloss: { de: 'Sollte der Mieter die Zahlung verweigern, kann der Vermieter eine Räumung beantragen.', es: 'Si el inquilino se negara a pagar, el casero podría solicitar el desahucio.', fr: 'Si le locataire refusait de payer, le propriétaire pourrait demander une expulsion.', it: 'Se l’inquilino si rifiutasse di pagare, il padrone di casa potrebbe chiedere lo sfratto.', pt: 'Caso o inquilino se recuse a pagar, o senhorio pode pedir o despejo.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['neglect', 'decline', 'omit'] },
  { id: 'en4s022', de: 'The findings were presented in such a way that no one could object.', en: 'The findings were presented in such a way that no one could object.', gloss: { de: 'Die Ergebnisse wurden so dargestellt, dass niemand widersprechen konnte.', es: 'Los resultados se presentaron de tal manera que nadie pudo objetar.', fr: 'Les résultats ont été présentés de telle façon que personne ne pouvait objecter.', it: 'I risultati sono stati presentati in modo tale che nessuno potesse obiettare.', pt: 'Os resultados foram apresentados de tal forma que ninguém pôde objetar.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['framed', 'arranged', 'summarised'] },
  { id: 'en4s023', de: 'Far from resolving the dispute, the ruling deepened it.', en: 'Far from resolving the dispute, the ruling deepened it.', gloss: { de: 'Weit davon entfernt, den Streit beizulegen, hat das Urteil ihn vertieft.', es: 'Lejos de resolver la disputa, la sentencia la agravó.', fr: 'Loin de régler le litige, la décision l’a aggravé.', it: 'Lungi dal risolvere la controversia, la sentenza l’ha aggravata.', pt: 'Longe de resolver a disputa, a decisão agravou-a.' }, level: 'B2', clozeIndex: 7, clozeDistractors: ['prolonged', 'complicated', 'inflamed'] },
  { id: 'en4s024', de: 'By the time the safeguards were introduced, the data had already been breached.', en: 'By the time the safeguards were introduced, the data had already been breached.', gloss: { de: 'Als die Schutzmaßnahmen eingeführt wurden, waren die Daten bereits kompromittiert.', es: 'Cuando se introdujeron las salvaguardias, los datos ya habían sido vulnerados.', fr: 'Au moment où les garanties ont été mises en place, les données avaient déjà été compromises.', it: 'Quando furono introdotte le salvaguardie, i dati erano già stati violati.', pt: 'Quando as salvaguardas foram introduzidas, os dados já tinham sido violados.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['regulations', 'controls', 'restrictions'] },
  { id: 'en4s025', de: 'Were it not for the scholarship, she would never have finished her degree.', en: 'Were it not for the scholarship, she would never have finished her degree.', gloss: { de: 'Ohne das Stipendium hätte sie ihr Studium nie abgeschlossen.', es: 'Si no fuera por la beca, nunca habría terminado la carrera.', fr: 'Sans la bourse, elle n’aurait jamais terminé ses études.', it: 'Se non fosse stato per la borsa di studio, non si sarebbe mai laureata.', pt: 'Se não fosse a bolsa de estudos, ela nunca teria terminado o curso.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['bursary', 'loan', 'stipend'] },
  { id: 'en4s026', de: 'The critic dismissed the novel as overrated, albeit beautifully written.', en: 'The critic dismissed the novel as overrated, albeit beautifully written.', gloss: { de: 'Der Kritiker tat den Roman als überbewertet ab, wenn auch wunderschön geschrieben.', es: 'El crítico descartó la novela por sobrevalorada, aunque bellamente escrita.', fr: 'Le critique a rejeté le roman comme surestimé, quoique magnifiquement écrit.', it: 'Il critico ha liquidato il romanzo come sopravvalutato, sebbene splendidamente scritto.', pt: 'O crítico rejeitou o romance como superestimado, ainda que lindamente escrito.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['praised', 'defended', 'described'] },
  { id: 'en4s027', de: 'One could argue that the policy has done more harm than good.', en: 'One could argue that the policy has done more harm than good.', gloss: { de: 'Man könnte argumentieren, dass die Maßnahme mehr geschadet als genützt hat.', es: 'Se podría argumentar que la política ha hecho más mal que bien.', fr: 'On pourrait soutenir que cette politique a fait plus de mal que de bien.', it: 'Si potrebbe sostenere che la politica abbia fatto più male che bene.', pt: 'Poder-se-ia argumentar que a política fez mais mal do que bem.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['reform', 'scheme', 'measure'] },
  { id: 'en4s028', de: 'Had the regulator intervened sooner, thousands of savers would have been spared.', en: 'Had the regulator intervened sooner, thousands of savers would have been spared.', gloss: { de: 'Hätte die Aufsichtsbehörde früher eingegriffen, wären Tausenden von Sparern viel erspart geblieben.', es: 'Si el regulador hubiera intervenido antes, miles de ahorradores se habrían librado.', fr: 'Si le régulateur était intervenu plus tôt, des milliers d’épargnants auraient été épargnés.', it: 'Se l’autorità di vigilanza fosse intervenuta prima, migliaia di risparmiatori sarebbero stati risparmiati.', pt: 'Se o regulador tivesse intervindo mais cedo, milhares de aforradores teriam sido poupados.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['responded', 'reported', 'withdrawn'] },
  { id: 'en4s029', de: 'The proposal, though ambitious, is unlikely to gain political support.', en: 'The proposal, though ambitious, is unlikely to gain political support.', gloss: { de: 'Der Vorschlag ist zwar ehrgeizig, wird aber kaum politische Unterstützung finden.', es: 'La propuesta, aunque ambiciosa, difícilmente conseguirá apoyo político.', fr: 'La proposition, bien qu’ambitieuse, a peu de chances d’obtenir un soutien politique.', it: 'La proposta, per quanto ambiziosa, difficilmente otterrà sostegno politico.', pt: 'A proposta, embora ambiciosa, dificilmente vai obter apoio político.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['certain', 'bound', 'due'] },
  { id: 'en4s030', de: 'What the committee failed to consider was the long-term cost.', en: 'What the committee failed to consider was the long-term cost.', gloss: { de: 'Was der Ausschuss nicht bedacht hat, waren die langfristigen Kosten.', es: 'Lo que el comité no tuvo en cuenta fue el coste a largo plazo.', fr: 'Ce que le comité n’a pas pris en compte, c’est le coût à long terme.', it: 'Ciò che la commissione non ha considerato è stato il costo a lungo termine.', pt: 'O que a comissão não considerou foi o custo a longo prazo.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['anticipate', 'address', 'acknowledge'] },
  { id: 'en4s031', de: 'He must have realised by then that the deal would fall through.', en: 'He must have realised by then that the deal would fall through.', gloss: { de: 'Ihm muss damals klar geworden sein, dass der Deal scheitern würde.', es: 'Para entonces debió de darse cuenta de que el acuerdo se vendría abajo.', fr: 'Il avait dû comprendre à ce moment-là que l’accord tomberait à l’eau.', it: 'A quel punto deve aver capito che l’accordo sarebbe andato a monte.', pt: 'A essa altura ele deve ter percebido que o acordo iria por água abaixo.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['suspected', 'accepted', 'forgotten'] },
  { id: 'en4s032', de: 'The exhibition depicts urban life with a nuance the reviews overlooked.', en: 'The exhibition depicts urban life with a nuance the reviews overlooked.', gloss: { de: 'Die Ausstellung stellt das Stadtleben mit einer Nuance dar, die die Kritiken übersehen haben.', es: 'La exposición representa la vida urbana con un matiz que las críticas pasaron por alto.', fr: 'L’exposition dépeint la vie urbaine avec une nuance que les critiques ont ignorée.', it: 'La mostra raffigura la vita urbana con una sfumatura che le recensioni hanno trascurato.', pt: 'A exposição retrata a vida urbana com uma nuance que as críticas ignoraram.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['romanticises', 'ignores', 'celebrates'] },
  { id: 'en4s033', de: 'To some extent, the shortage was brought about by our own decisions.', en: 'To some extent, the shortage was brought about by our own decisions.', gloss: { de: 'Bis zu einem gewissen Grad wurde der Mangel durch unsere eigenen Entscheidungen verursacht.', es: 'Hasta cierto punto, la escasez fue provocada por nuestras propias decisiones.', fr: 'Dans une certaine mesure, la pénurie a été provoquée par nos propres décisions.', it: 'In una certa misura, la carenza è stata provocata dalle nostre stesse decisioni.', pt: 'Até certo ponto, a escassez foi provocada pelas nossas próprias decisões.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['surplus', 'recession', 'delay'] },
  { id: 'en4s034', de: 'Not until the accounts were audited did the discrepancy come to light.', en: 'Not until the accounts were audited did the discrepancy come to light.', gloss: { de: 'Erst als die Konten geprüft wurden, kam die Unstimmigkeit ans Licht.', es: 'Hasta que no se auditaron las cuentas no salió a la luz la discrepancia.', fr: 'Ce n’est qu’une fois les comptes audités que l’écart est apparu.', it: 'Solo quando i conti furono sottoposti a revisione emerse la discrepanza.', pt: 'Só quando as contas foram auditadas é que a discrepância veio à luz.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['published', 'frozen', 'reviewed'] },
  { id: 'en4s035', de: 'The scheme is reported to have cost twice the original estimate.', en: 'The scheme is reported to have cost twice the original estimate.', gloss: { de: 'Das Programm soll doppelt so viel gekostet haben wie ursprünglich veranschlagt.', es: 'Se informa de que el plan costó el doble de la estimación inicial.', fr: 'Le dispositif aurait coûté le double de l’estimation initiale.', it: 'Si riferisce che il piano sia costato il doppio della stima iniziale.', pt: 'Consta que o programa custou o dobro da estimativa inicial.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['exceeded', 'doubled', 'saved'] },
  { id: 'en4s036', de: 'Presumably, the outcome would have been the same either way.', en: 'Presumably, the outcome would have been the same either way.', gloss: { de: 'Vermutlich wäre das Ergebnis so oder so dasselbe gewesen.', es: 'Presumiblemente, el resultado habría sido el mismo de todos modos.', fr: 'Vraisemblablement, le résultat aurait été le même de toute façon.', it: 'Presumibilmente, il risultato sarebbe stato lo stesso in ogni caso.', pt: 'Presumivelmente, o resultado teria sido o mesmo de qualquer forma.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['verdict', 'decision', 'reaction'] },
  { id: 'en4s037', de: 'With all due respect, nobody has explained how the funding will work.', en: 'With all due respect, nobody has explained how the funding will work.', gloss: { de: 'Bei allem Respekt, niemand hat erklärt, wie die Finanzierung funktionieren soll.', es: 'Con todo respeto, nadie ha explicado cómo funcionará la financiación.', fr: 'Avec tout le respect que je vous dois, personne n’a expliqué comment le financement fonctionnera.', it: 'Con tutto il rispetto, nessuno ha spiegato come funzionerà il finanziamento.', pt: 'Com todo o respeito, ninguém explicou como o financiamento vai funcionar.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['clarified', 'specified', 'questioned'] },
  { id: 'en4s038', de: 'Had they consulted the residents, the redevelopment might have been welcomed.', en: 'Had they consulted the residents, the redevelopment might have been welcomed.', gloss: { de: 'Hätten sie die Anwohner befragt, wäre die Sanierung vielleicht begrüßt worden.', es: 'Si hubieran consultado a los vecinos, la remodelación quizá habría sido bien recibida.', fr: 'S’ils avaient consulté les riverains, le réaménagement aurait peut-être été bien accueilli.', it: 'Se avessero consultato i residenti, la riqualificazione sarebbe forse stata accolta bene.', pt: 'Se tivessem consultado os moradores, a requalificação talvez tivesse sido bem recebida.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['notified', 'surveyed', 'ignored'] },
  { id: 'en4s039', de: 'The article was retracted after two of its sources were discredited.', en: 'The article was retracted after two of its sources were discredited.', gloss: { de: 'Der Artikel wurde zurückgezogen, nachdem zwei seiner Quellen diskreditiert worden waren.', es: 'El artículo fue retirado después de que dos de sus fuentes quedaran desacreditadas.', fr: 'L’article a été retiré après que deux de ses sources ont été discréditées.', it: 'L’articolo è stato ritirato dopo che due delle sue fonti sono state screditate.', pt: 'O artigo foi retirado depois de duas das suas fontes terem sido desacreditadas.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['amended', 'republished', 'circulated'] },
  { id: 'en4s040', de: 'It strikes me that we have been asking the wrong question entirely.', en: 'It strikes me that we have been asking the wrong question entirely.', gloss: { de: 'Mir fällt auf, dass wir die ganze Zeit die völlig falsche Frage gestellt haben.', es: 'Me llama la atención que hayamos estado haciendo la pregunta totalmente equivocada.', fr: 'Il me semble que nous posons depuis le début une question totalement erronée.', it: 'Mi colpisce il fatto che ci siamo posti la domanda del tutto sbagliata.', pt: 'Chama-me a atenção que temos feito a pergunta completamente errada.' }, level: 'B2', clozeIndex: 9, clozeDistractors: ['obvious', 'same', 'opposite'] },
  { id: 'en4s041', de: 'Were it up to me, I would rule out the merger altogether.', en: 'Were it up to me, I would rule out the merger altogether.', gloss: { de: 'Wenn es nach mir ginge, würde ich die Fusion völlig ausschließen.', es: 'Si dependiera de mí, descartaría la fusión por completo.', fr: 'Si cela ne tenait qu’à moi, j’exclurais complètement la fusion.', it: 'Se dipendesse da me, escluderei del tutto la fusione.', pt: 'Se dependesse de mim, descartaria a fusão por completo.' }, level: 'B2', clozeIndex: 10, clozeDistractors: ['takeover', 'proposal', 'sale'] },
  { id: 'en4s042', de: 'The lift had been out of order for a fortnight before anyone complained.', en: 'The lift had been out of order for a fortnight before anyone complained.', gloss: { de: 'Der Aufzug war schon zwei Wochen außer Betrieb, bevor sich jemand beschwerte.', es: 'El ascensor llevaba quince días averiado antes de que alguien se quejara.', fr: 'L’ascenseur était en panne depuis quinze jours avant que quelqu’un ne se plaigne.', it: 'L’ascensore era fuori servizio da due settimane prima che qualcuno si lamentasse.', pt: 'O elevador estava avariado havia quinze dias antes de alguém reclamar.' }, level: 'B2', clozeIndex: 9, clozeDistractors: ['month', 'term', 'spell'] },
  { id: 'en4s043', de: 'Little did they know that the queue outside was already two hours long.', en: 'Little did they know that the queue outside was already two hours long.', gloss: { de: 'Sie ahnten nicht, dass die Schlange draußen bereits zwei Stunden lang war.', es: 'No sabían que la cola de fuera ya era de dos horas.', fr: 'Ils ne se doutaient pas que la file dehors durait déjà deux heures.', it: 'Non immaginavano che la fila fuori fosse già di due ore.', pt: 'Mal sabiam eles que a fila lá fora já era de duas horas.' }, level: 'B2', clozeIndex: 9, clozeDistractors: ['barely', 'hardly', 'scarcely'] },
  { id: 'en4s044', de: 'Given the evidence, one can hardly conclude that the risk was negligible.', en: 'Given the evidence, one can hardly conclude that the risk was negligible.', gloss: { de: 'Angesichts der Belege kann man kaum schließen, dass das Risiko vernachlässigbar war.', es: 'Dadas las pruebas, difícilmente se puede concluir que el riesgo fuera insignificante.', fr: 'Compte tenu des preuves, on peut difficilement conclure que le risque était négligeable.', it: 'Date le prove, si può difficilmente concludere che il rischio fosse trascurabile.', pt: 'Dadas as provas, dificilmente se pode concluir que o risco era insignificante.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['argue', 'maintain', 'insist'] },
  { id: 'en4s045', de: 'The underground would have been quicker, had we left ten minutes earlier.', en: 'The underground would have been quicker, had we left ten minutes earlier.', gloss: { de: 'Die U-Bahn wäre schneller gewesen, wenn wir zehn Minuten früher losgegangen wären.', es: 'El metro habría sido más rápido si hubiéramos salido diez minutos antes.', fr: 'Le métro aurait été plus rapide si nous étions partis dix minutes plus tôt.', it: 'La metropolitana sarebbe stata più veloce se fossimo partiti dieci minuti prima.', pt: 'O metro teria sido mais rápido se tivéssemos saído dez minutos mais cedo.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['cheaper', 'safer', 'simpler'] },
  { id: 'en4s046', de: 'Conversely, a weaker currency tends to make exports more competitive.', en: 'Conversely, a weaker currency tends to make exports more competitive.', gloss: { de: 'Umgekehrt macht eine schwächere Währung Exporte tendenziell wettbewerbsfähiger.', es: 'A la inversa, una moneda más débil suele hacer las exportaciones más competitivas.', fr: 'Inversement, une monnaie plus faible tend à rendre les exportations plus compétitives.', it: 'Viceversa, una valuta più debole tende a rendere le esportazioni più competitive.', pt: 'Inversamente, uma moeda mais fraca tende a tornar as exportações mais competitivas.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['economy', 'market', 'demand'] },
  { id: 'en4s047', de: 'The autumn figures suggest that the recession has bottomed out.', en: 'The autumn figures suggest that the recession has bottomed out.', gloss: { de: 'Die Herbstzahlen deuten darauf hin, dass die Rezession die Talsohle erreicht hat.', es: 'Las cifras de otoño sugieren que la recesión ha tocado fondo.', fr: 'Les chiffres de l’automne suggèrent que la récession a atteint son point bas.', it: 'I dati autunnali indicano che la recessione ha toccato il fondo.', pt: 'Os números do outono sugerem que a recessão atingiu o fundo.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['inflation', 'slowdown', 'downturn'] },
  { id: 'en4s048', de: 'Nothing would have been gained by prolonging such a bitter dispute.', en: 'Nothing would have been gained by prolonging such a bitter dispute.', gloss: { de: 'Es wäre nichts gewonnen gewesen, einen so erbitterten Streit zu verlängern.', es: 'No se habría ganado nada prolongando una disputa tan amarga.', fr: 'On n’aurait rien gagné à prolonger un litige aussi âpre.', it: 'Non si sarebbe guadagnato nulla prolungando una disputa così aspra.', pt: 'Nada se teria ganho ao prolongar uma disputa tão amarga.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['reopening', 'publicising', 'escalating'] },
  { id: 'en4s049', de: 'The witness is alleged to have been paid for her testimony.', en: 'The witness is alleged to have been paid for her testimony.', gloss: { de: 'Die Zeugin soll angeblich für ihre Aussage bezahlt worden sein.', es: 'Se alega que la testigo recibió dinero por su testimonio.', fr: 'La témoin aurait été payée pour son témoignage.', it: 'Si sostiene che la testimone sia stata pagata per la sua testimonianza.', pt: 'Alega-se que a testemunha foi paga pelo seu testemunho.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['thought', 'believed', 'rumoured'] },
  { id: 'en4s050', de: 'It was only later that we grasped how thorough the review had been.', en: 'It was only later that we grasped how thorough the review had been.', gloss: { de: 'Erst später begriffen wir, wie gründlich die Prüfung gewesen war.', es: 'Solo más tarde comprendimos lo minuciosa que había sido la revisión.', fr: 'Ce n’est que plus tard que nous avons saisi à quel point l’examen avait été minutieux.', it: 'Solo più tardi abbiamo capito quanto fosse stata accurata la revisione.', pt: 'Só mais tarde é que percebemos quão minuciosa tinha sido a revisão.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['realised', 'discovered', 'understood'] },
  { id: 'en4s051', de: 'Should the negotiations collapse, both sides would bear the brunt.', en: 'Should the negotiations collapse, both sides would bear the brunt.', gloss: { de: 'Sollten die Verhandlungen scheitern, würden beide Seiten die Hauptlast tragen.', es: 'Si las negociaciones se rompieran, ambas partes llevarían la peor parte.', fr: 'Si les négociations échouaient, les deux camps en subiraient le plus gros.', it: 'Se i negoziati fallissero, entrambe le parti ne subirebbero il peso maggiore.', pt: 'Se as negociações fracassassem, ambas as partes levariam a pior parte.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['resume', 'continue', 'succeed'] },
  { id: 'en4s052', de: 'The colour of the packaging, arguably, matters more than the contents.', en: 'The colour of the packaging, arguably, matters more than the contents.', gloss: { de: 'Die Farbe der Verpackung ist wohl wichtiger als der Inhalt.', es: 'El color del envase, posiblemente, importa más que el contenido.', fr: 'La couleur de l’emballage compte sans doute plus que le contenu.', it: 'Il colore della confezione, probabilmente, conta più del contenuto.', pt: 'A cor da embalagem, possivelmente, importa mais do que o conteúdo.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['shape', 'weight', 'price'] },
  { id: 'en4s053', de: 'Had the safeguards not been ignored, the breach would never have occurred.', en: 'Had the safeguards not been ignored, the breach would never have occurred.', gloss: { de: 'Wären die Schutzmaßnahmen nicht ignoriert worden, wäre der Verstoß nie passiert.', es: 'Si no se hubieran ignorado las salvaguardias, la violación nunca habría ocurrido.', fr: 'Si les garanties n’avaient pas été ignorées, la violation n’aurait jamais eu lieu.', it: 'Se le salvaguardie non fossero state ignorate, la violazione non sarebbe mai avvenuta.', pt: 'Se as salvaguardas não tivessem sido ignoradas, a violação nunca teria ocorrido.' }, level: 'B2', clozeIndex: 7, clozeDistractors: ['leak', 'failure', 'scandal'] },
  { id: 'en4s054', de: 'What matters is not the intention but the consequence.', en: 'What matters is not the intention but the consequence.', gloss: { de: 'Was zählt, ist nicht die Absicht, sondern die Folge.', es: 'Lo que importa no es la intención, sino la consecuencia.', fr: 'Ce qui compte, ce n’est pas l’intention mais la conséquence.', it: 'Ciò che conta non è l’intenzione, ma la conseguenza.', pt: 'O que importa não é a intenção, mas a consequência.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['promise', 'apology', 'announcement'] },
  { id: 'en4s055', de: 'Travelling by rail is said to be far less damaging to the climate.', en: 'Travelling by rail is said to be far less damaging to the climate.', gloss: { de: 'Bahnreisen sollen dem Klima weit weniger schaden.', es: 'Se dice que viajar en tren es mucho menos dañino para el clima.', fr: 'On dit que voyager en train est bien moins nocif pour le climat.', it: 'Si dice che viaggiare in treno sia molto meno dannoso per il clima.', pt: 'Diz-se que viajar de comboio é muito menos prejudicial para o clima.' }, level: 'B2', clozeIndex: 9, clozeDistractors: ['costly', 'stressful', 'disruptive'] },
  { id: 'en4s056', de: 'So convincing was her argument that the objections simply melted away.', en: 'So convincing was her argument that the objections simply melted away.', gloss: { de: 'Ihr Argument war so überzeugend, dass die Einwände einfach dahinschmolzen.', es: 'Tan convincente fue su argumento que las objeciones simplemente se desvanecieron.', fr: 'Son argument était si convaincant que les objections se sont tout simplement évanouies.', it: 'Il suo argomento era così convincente che le obiezioni sono semplicemente svanite.', pt: 'O seu argumento foi tão convincente que as objeções simplesmente se desvaneceram.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['passionate', 'detailed', 'concise'] },
  { id: 'en4s057', de: 'The rubbish had not been collected for weeks, hence the complaints.', en: 'The rubbish had not been collected for weeks, hence the complaints.', gloss: { de: 'Der Müll war wochenlang nicht abgeholt worden, daher die Beschwerden.', es: 'La basura llevaba semanas sin recogerse, de ahí las quejas.', fr: 'Les déchets n’avaient pas été ramassés depuis des semaines, d’où les plaintes.', it: 'I rifiuti non venivano raccolti da settimane, di qui le lamentele.', pt: 'O lixo não era recolhido havia semanas, daí as reclamações.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['recycling', 'post', 'washing'] },
  { id: 'en4s058', de: 'It is high time the regulator looked into these practices properly.', en: 'It is high time the regulator looked into these practices properly.', gloss: { de: 'Es wird höchste Zeit, dass die Aufsichtsbehörde diese Praktiken ordentlich untersucht.', es: 'Ya es hora de que el regulador investigue estas prácticas como es debido.', fr: 'Il est grand temps que le régulateur se penche sérieusement sur ces pratiques.', it: 'È ora che l’autorità di vigilanza esamini seriamente queste pratiche.', pt: 'Já é tempo de o regulador investigar estas práticas como deve ser.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['committee', 'minister', 'inspector'] },
  { id: 'en4s059', de: 'Whatever the verdict, the trial has already set a precedent.', en: 'Whatever the verdict, the trial has already set a precedent.', gloss: { de: 'Wie auch immer das Urteil ausfällt, der Prozess hat bereits einen Präzedenzfall geschaffen.', es: 'Sea cual sea el veredicto, el juicio ya ha sentado un precedente.', fr: 'Quel que soit le verdict, le procès a déjà créé un précédent.', it: 'Qualunque sia il verdetto, il processo ha già creato un precedente.', pt: 'Seja qual for o veredicto, o julgamento já abriu um precedente.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['sentence', 'ruling', 'appeal'] },
  { id: 'en4s060', de: 'The flat would have been affordable had the interest rates not risen.', en: 'The flat would have been affordable had the interest rates not risen.', gloss: { de: 'Die Wohnung wäre bezahlbar gewesen, wenn die Zinsen nicht gestiegen wären.', es: 'El piso habría sido asequible si no hubieran subido los tipos de interés.', fr: 'L’appartement aurait été abordable si les taux d’intérêt n’avaient pas augmenté.', it: 'L’appartamento sarebbe stato accessibile se i tassi d’interesse non fossero saliti.', pt: 'O apartamento teria sido acessível se as taxas de juro não tivessem subido.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['empty', 'ideal', 'available'] },
  { id: 'en4s061', de: 'Her mobile had been switched off, which explains the missed calls.', en: 'Her mobile had been switched off, which explains the missed calls.', gloss: { de: 'Ihr Handy war ausgeschaltet, was die verpassten Anrufe erklärt.', es: 'Su móvil estaba apagado, lo que explica las llamadas perdidas.', fr: 'Son portable était éteint, ce qui explique les appels manqués.', it: 'Il suo cellulare era spento, il che spiega le chiamate perse.', pt: 'O telemóvel dela estava desligado, o que explica as chamadas perdidas.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['laptop', 'alarm', 'router'] },
  { id: 'en4s062', de: 'By and large, the reforms have benefited those who needed them least.', en: 'By and large, the reforms have benefited those who needed them least.', gloss: { de: 'Im Großen und Ganzen haben die Reformen denen genützt, die sie am wenigsten brauchten.', es: 'En términos generales, las reformas han beneficiado a quienes menos las necesitaban.', fr: 'Dans l’ensemble, les réformes ont profité à ceux qui en avaient le moins besoin.', it: 'Nel complesso, le riforme hanno favorito chi ne aveva meno bisogno.', pt: 'De um modo geral, as reformas beneficiaram quem menos precisava delas.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['subsidies', 'measures', 'changes'] },
  { id: 'en4s063', de: 'The minister conceded that the targets had been unrealistic from the outset.', en: 'The minister conceded that the targets had been unrealistic from the outset.', gloss: { de: 'Der Minister räumte ein, dass die Ziele von Anfang an unrealistisch gewesen waren.', es: 'El ministro reconoció que los objetivos habían sido poco realistas desde el principio.', fr: 'Le ministre a concédé que les objectifs étaient irréalistes dès le départ.', it: 'Il ministro ha ammesso che gli obiettivi erano irrealistici fin dall’inizio.', pt: 'O ministro admitiu que as metas tinham sido irrealistas desde o início.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['insisted', 'denied', 'announced'] },
  { id: 'en4s064', de: 'Not one of the proposals was deemed feasible by the panel.', en: 'Not one of the proposals was deemed feasible by the panel.', gloss: { de: 'Keiner der Vorschläge wurde vom Gremium für machbar gehalten.', es: 'Ninguna de las propuestas fue considerada viable por el panel.', fr: 'Aucune des propositions n’a été jugée réalisable par le comité.', it: 'Nessuna delle proposte è stata ritenuta fattibile dalla commissione.', pt: 'Nenhuma das propostas foi considerada viável pelo painel.' }, level: 'B2', clozeIndex: 7, clozeDistractors: ['urgent', 'affordable', 'lawful'] },
  { id: 'en4s065', de: 'The scheme might have worked, had it been properly funded from the start.', en: 'The scheme might have worked, had it been properly funded from the start.', gloss: { de: 'Das Programm hätte funktionieren können, wenn es von Anfang an ordentlich finanziert worden wäre.', es: 'El plan podría haber funcionado si se hubiera financiado bien desde el principio.', fr: 'Le dispositif aurait pu marcher s’il avait été correctement financé dès le départ.', it: 'Il piano avrebbe potuto funzionare se fosse stato finanziato bene fin dall’inizio.', pt: 'O programa poderia ter funcionado se tivesse sido bem financiado desde o início.' }, level: 'B2', clozeIndex: 9, clozeDistractors: ['staffed', 'explained', 'managed'] },
  { id: 'en4s066', de: 'Such was the outcry that the council backed down within a week.', en: 'Such was the outcry that the council backed down within a week.', gloss: { de: 'Der Aufschrei war so groß, dass die Stadtverwaltung binnen einer Woche einen Rückzieher machte.', es: 'Tal fue el clamor que el ayuntamiento se echó atrás en una semana.', fr: 'Le tollé fut tel que la mairie a fait marche arrière en une semaine.', it: 'La protesta fu tale che il comune fece marcia indietro nel giro di una settimana.', pt: 'O clamor foi tal que a câmara municipal recuou no espaço de uma semana.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['pressure', 'turnout', 'backlash'] },
  { id: 'en4s067', de: 'The novel is thought to have been written under a pseudonym.', en: 'The novel is thought to have been written under a pseudonym.', gloss: { de: 'Man nimmt an, dass der Roman unter einem Pseudonym geschrieben wurde.', es: 'Se cree que la novela fue escrita bajo seudónimo.', fr: 'On pense que le roman a été écrit sous un pseudonyme.', it: 'Si ritiene che il romanzo sia stato scritto sotto pseudonimo.', pt: 'Pensa-se que o romance foi escrito sob pseudónimo.' }, level: 'B2', clozeIndex: 7, clozeDistractors: ['published', 'completed', 'circulated'] },
  { id: 'en4s068', de: 'Whether or not the data are reliable remains an open question.', en: 'Whether or not the data are reliable remains an open question.', gloss: { de: 'Ob die Daten zuverlässig sind, bleibt eine offene Frage.', es: 'Que los datos sean fiables o no sigue siendo una cuestión abierta.', fr: 'La fiabilité des données reste une question ouverte.', it: 'Se i dati siano affidabili o meno resta una questione aperta.', pt: 'Se os dados são fiáveis ou não continua a ser uma questão em aberto.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['complete', 'accurate', 'representative'] },
  { id: 'en4s069', de: 'One should bear in mind that correlation does not imply causation.', en: 'One should bear in mind that correlation does not imply causation.', gloss: { de: 'Man sollte bedenken, dass Korrelation keine Kausalität bedeutet.', es: 'Hay que tener en cuenta que la correlación no implica causalidad.', fr: 'Il faut garder à l’esprit que la corrélation n’implique pas la causalité.', it: 'Bisogna tenere presente che la correlazione non implica causalità.', pt: 'Deve ter-se em conta que a correlação não implica causalidade.' }, level: 'B2', clozeIndex: 9, clozeDistractors: ['guarantee', 'establish', 'prove'] },
  { id: 'en4s070', de: 'Only by acknowledging the drawbacks can we strike a sensible balance.', en: 'Only by acknowledging the drawbacks can we strike a sensible balance.', gloss: { de: 'Nur wenn wir die Nachteile anerkennen, können wir ein vernünftiges Gleichgewicht finden.', es: 'Solo reconociendo los inconvenientes podemos encontrar un equilibrio sensato.', fr: 'Ce n’est qu’en reconnaissant les inconvénients que nous pouvons trouver un équilibre raisonnable.', it: 'Solo riconoscendo gli svantaggi possiamo trovare un equilibrio ragionevole.', pt: 'Só reconhecendo os inconvenientes podemos encontrar um equilíbrio sensato.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['costs', 'risks', 'limitations'] },
];
