import type { SentenceItem } from '@/content/german/types';

// Italian B1 sentences. `de` holds the Italian text. These are deliberately not
// simple SVO: subordinate clauses, the congiuntivo after verbs of opinion and
// after benché / sebbene / affinché, and opinion framing.
//
// clozeIndex targets the load-bearing word (never an article), and
// clozeDistractors are same-class words — congiuntivo forms against congiuntivo
// forms, connectors against connectors — so the exercise tests meaning rather
// than word shape.
//
// `gloss` carries the non-English UI locales; see b1-vocab.ts for the rule.

export const B1_SENTENCES: SentenceItem[] = [
  { id: 'it3s001', de: 'Penso che sia una decisione sbagliata.', en: 'I think it is a wrong decision.', gloss: { de: 'Ich finde, das ist eine falsche Entscheidung.', es: 'Creo que es una decisión equivocada.', fr: 'Je pense que c’est une mauvaise décision.', pt: 'Acho que é uma decisão errada.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['abbia', 'faccia', 'possa'] },
  { id: 'it3s002', de: 'Benché sia difficile, vale la pena provare.', en: 'Although it is difficult, it is worth trying.', gloss: { de: 'Obwohl es schwierig ist, lohnt es sich, es zu versuchen.', es: 'Aunque sea difícil, vale la pena intentarlo.', fr: 'Bien que ce soit difficile, ça vaut la peine d’essayer.', pt: 'Embora seja difícil, vale a pena tentar.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Perciò', 'Tuttavia', 'Inoltre'] },
  { id: 'it3s003', de: 'Secondo me il governo dovrebbe agire subito.', en: 'In my opinion the government should act immediately.', gloss: { de: 'Meiner Meinung nach sollte die Regierung sofort handeln.', es: 'En mi opinión el gobierno debería actuar de inmediato.', fr: 'À mon avis le gouvernement devrait agir tout de suite.', pt: 'Na minha opinião o governo deveria agir imediatamente.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['giornale', 'dibattito', 'stipendio'] },
  { id: 'it3s004', de: 'Non credo che l’azienda voglia assumere altri dipendenti.', en: 'I don’t think the company wants to hire more employees.', gloss: { de: 'Ich glaube nicht, dass die Firma weitere Mitarbeiter einstellen will.', es: 'No creo que la empresa quiera contratar a más empleados.', fr: 'Je ne crois pas que l’entreprise veuille embaucher d’autres employés.', pt: 'Não acho que a empresa queira contratar mais funcionários.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['possa', 'debba', 'sappia'] },
  { id: 'it3s005', de: 'L’inquinamento è aumentato nonostante le nuove leggi.', en: 'Pollution has increased despite the new laws.', gloss: { de: 'Die Verschmutzung ist trotz der neuen Gesetze gestiegen.', es: 'La contaminación ha aumentado a pesar de las nuevas leyes.', fr: 'La pollution a augmenté malgré les nouvelles lois.', pt: 'A poluição aumentou apesar das novas leis.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['secondo', 'durante', 'oltre'] },
  { id: 'it3s006', de: 'Bisogna ridurre i rifiuti, altrimenti il problema peggiorerà.', en: 'We have to reduce waste, otherwise the problem will get worse.', gloss: { de: 'Man muss den Müll reduzieren, sonst wird das Problem schlimmer.', es: 'Hay que reducir los residuos, si no el problema empeorará.', fr: 'Il faut réduire les déchets, sinon le problème va empirer.', pt: 'É preciso reduzir o lixo, senão o problema vai piorar.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['inoltre', 'tuttavia', 'quindi'] },
  { id: 'it3s007', de: 'Tuttavia non sono del tutto d’accordo con te.', en: 'However, I do not entirely agree with you.', gloss: { de: 'Ich bin jedoch nicht ganz deiner Meinung.', es: 'Sin embargo, no estoy del todo de acuerdo contigo.', fr: 'Cependant, je ne suis pas entièrement d’accord avec toi.', pt: 'No entanto, não concordo totalmente com você.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Inoltre', 'Perciò', 'Quindi'] },
  { id: 'it3s008', de: 'Spero che il colloquio vada bene.', en: 'I hope the job interview goes well.', gloss: { de: 'Ich hoffe, dass das Vorstellungsgespräch gut läuft.', es: 'Espero que la entrevista vaya bien.', fr: 'J’espère que l’entretien se passera bien.', pt: 'Espero que a entrevista corra bem.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['finisca', 'sembri', 'riesca'] },
  { id: 'it3s009', de: 'È importante che i cittadini abbiano fiducia nelle istituzioni.', en: 'It is important that citizens have trust in institutions.', gloss: { de: 'Es ist wichtig, dass die Bürger Vertrauen in die Institutionen haben.', es: 'Es importante que los ciudadanos tengan confianza en las instituciones.', fr: 'Il est important que les citoyens aient confiance dans les institutions.', pt: 'É importante que os cidadãos tenham confiança nas instituições.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['possano', 'sappiano', 'vogliano'] },
  { id: 'it3s010', de: 'Il giornale ha pubblicato un sondaggio molto discutibile.', en: 'The newspaper published a very questionable poll.', gloss: { de: 'Die Zeitung hat eine sehr fragwürdige Umfrage veröffentlicht.', es: 'El periódico publicó una encuesta muy discutible.', fr: 'Le journal a publié un sondage très discutable.', pt: 'O jornal publicou uma pesquisa muito discutível.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['articolo', 'dibattito', 'parere'] },
  { id: 'it3s011', de: 'Sebbene sia giovane, ha molta esperienza.', en: 'Although he is young, he has a lot of experience.', gloss: { de: 'Obwohl er jung ist, hat er viel Erfahrung.', es: 'Aunque es joven, tiene mucha experiencia.', fr: 'Bien qu’il soit jeune, il a beaucoup d’expérience.', pt: 'Embora seja jovem, tem muita experiência.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Perciò', 'Inoltre', 'Quindi'] },
  { id: 'it3s012', de: 'Se avessi più tempo, approfondirei l’argomento.', en: 'If I had more time, I would study the topic in depth.', gloss: { de: 'Wenn ich mehr Zeit hätte, würde ich das Thema vertiefen.', es: 'Si tuviera más tiempo, profundizaría en el tema.', fr: 'Si j’avais plus de temps, j’approfondirais le sujet.', pt: 'Se eu tivesse mais tempo, aprofundaria o assunto.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['potessi', 'sapessi', 'trovassi'] },
  { id: 'it3s013', de: 'Mi rendo conto che la situazione è più complessa di quanto pensassi.', en: 'I realize that the situation is more complex than I thought.', gloss: { de: 'Mir ist klar, dass die Lage komplexer ist, als ich dachte.', es: 'Me doy cuenta de que la situación es más compleja de lo que pensaba.', fr: 'Je me rends compte que la situation est plus complexe que je ne pensais.', pt: 'Me dou conta de que a situação é mais complexa do que eu pensava.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['inevitabile', 'superficiale', 'urgente'] },
  { id: 'it3s014', de: 'Molti giovani rinunciano a un lavoro stabile per viaggiare.', en: 'Many young people give up a stable job in order to travel.', gloss: { de: 'Viele junge Leute verzichten auf einen festen Job, um zu reisen.', es: 'Muchos jóvenes renuncian a un trabajo estable para viajar.', fr: 'Beaucoup de jeunes renoncent à un emploi stable pour voyager.', pt: 'Muitos jovens renunciam a um emprego estável para viajar.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['cercano', 'evitano', 'accettano'] },
  { id: 'it3s015', de: 'Quindi è meglio affrontare il problema adesso.', en: 'So it is better to face the problem now.', gloss: { de: 'Also ist es besser, das Problem jetzt anzugehen.', es: 'Por lo tanto es mejor afrontar el problema ahora.', fr: 'Donc il vaut mieux affronter le problème maintenant.', pt: 'Portanto é melhor enfrentar o problema agora.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['evitare', 'proporre', 'impedire'] },
  { id: 'it3s016', de: 'Nonostante gli sforzi, la povertà continua a crescere.', en: 'Despite the efforts, poverty keeps growing.', gloss: { de: 'Trotz der Bemühungen wächst die Armut weiter.', es: 'A pesar de los esfuerzos, la pobreza sigue creciendo.', fr: 'Malgré les efforts, la pauvreté continue d’augmenter.', pt: 'Apesar dos esforços, a pobreza continua crescendo.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['disoccupazione', 'pubblicità', 'libertà'] },
  { id: 'it3s017', de: 'Bisogna che tutti facciano la propria parte.', en: 'Everyone needs to do their part.', gloss: { de: 'Es ist nötig, dass alle ihren Teil beitragen.', es: 'Hace falta que todos hagan su parte.', fr: 'Il faut que chacun fasse sa part.', pt: 'É preciso que todos façam a sua parte.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['diano', 'sappiano', 'vogliano'] },
  { id: 'it3s018', de: 'L’energia rinnovabile è una scelta sostenibile per il futuro.', en: 'Renewable energy is a sustainable choice for the future.', gloss: { de: 'Erneuerbare Energie ist eine nachhaltige Entscheidung für die Zukunft.', es: 'La energía renovable es una opción sostenible para el futuro.', fr: 'L’énergie renouvelable est un choix durable pour l’avenir.', pt: 'A energia renovável é uma escolha sustentável para o futuro.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['efficace', 'urgente', 'affidabile'] },
  { id: 'it3s019', de: 'Ho l’impressione che nessuno voglia prendersi la responsabilità.', en: 'I have the impression that nobody wants to take responsibility.', gloss: { de: 'Ich habe den Eindruck, dass niemand die Verantwortung übernehmen will.', es: 'Tengo la impresión de que nadie quiere asumir la responsabilidad.', fr: 'J’ai l’impression que personne ne veut prendre la responsabilité.', pt: 'Tenho a impressão de que ninguém quer assumir a responsabilidade.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['qualcuno', 'ognuno', 'chiunque'] },
  { id: 'it3s020', de: 'Affinché il progetto riesca, serve l’impegno di tutti.', en: 'For the project to succeed, everyone’s commitment is needed.', gloss: { de: 'Damit das Projekt gelingt, braucht es das Engagement aller.', es: 'Para que el proyecto tenga éxito, hace falta el compromiso de todos.', fr: 'Pour que le projet réussisse, il faut l’engagement de tous.', pt: 'Para que o projeto tenha sucesso, é preciso o empenho de todos.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['funzioni', 'cresca', 'duri'] },
  { id: 'it3s021', de: 'Credo che la tecnologia cambi il modo di lavorare.', en: 'I believe technology is changing the way we work.', gloss: { de: 'Ich glaube, dass die Technologie die Art zu arbeiten verändert.', es: 'Creo que la tecnología cambia la forma de trabajar.', fr: 'Je crois que la technologie change la façon de travailler.', pt: 'Acredito que a tecnologia muda a forma de trabalhar.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['renda', 'crei', 'migliori'] },
  { id: 'it3s022', de: 'È probabile che l’economia cresca meno del previsto.', en: 'It is likely that the economy will grow less than expected.', gloss: { de: 'Wahrscheinlich wächst die Wirtschaft weniger als erwartet.', es: 'Es probable que la economía crezca menos de lo previsto.', fr: 'Il est probable que l’économie croisse moins que prévu.', pt: 'É provável que a economia cresça menos do que o previsto.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['peggiori', 'rallenti', 'aumenti'] },
  { id: 'it3s023', de: 'Molti sostengono che le tasse siano troppo alte.', en: 'Many maintain that taxes are too high.', gloss: { de: 'Viele behaupten, dass die Steuern zu hoch sind.', es: 'Muchos sostienen que los impuestos son demasiado altos.', fr: 'Beaucoup soutiennent que les impôts sont trop élevés.', pt: 'Muitos sustentam que os impostos são altos demais.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['restino', 'sembrino', 'diventino'] },
  { id: 'it3s024', de: 'Il governo vuole ridurre il debito pubblico.', en: 'The government wants to reduce public debt.', gloss: { de: 'Die Regierung will die Staatsschulden senken.', es: 'El gobierno quiere reducir la deuda pública.', fr: 'Le gouvernement veut réduire la dette publique.', pt: 'O governo quer reduzir a dívida pública.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['aumentare', 'garantire', 'ottenere'] },
  { id: 'it3s025', de: 'Il reddito medio è aumentato solo dell’uno per cento.', en: 'Average income rose by only one per cent.', gloss: { de: 'Das Durchschnittseinkommen ist nur um ein Prozent gestiegen.', es: 'La renta media aumentó solo un uno por ciento.', fr: 'Le revenu moyen n’a augmenté que d’un pour cent.', pt: 'A renda média aumentou apenas um por cento.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['risparmio', 'debito', 'bilancio'] },
  { id: 'it3s026', de: 'Senza risparmio è difficile affrontare un imprevisto.', en: 'Without savings it is hard to face something unexpected.', gloss: { de: 'Ohne Ersparnisse ist es schwer, etwas Unerwartetes zu bewältigen.', es: 'Sin ahorros es difícil afrontar un imprevisto.', fr: 'Sans épargne il est difficile de faire face à un imprévu.', pt: 'Sem poupança é difícil enfrentar um imprevisto.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['sostegno', 'compromesso', 'criterio'] },
  { id: 'it3s027', de: 'L’investimento non ha dato i risultati sperati.', en: 'The investment did not deliver the hoped-for results.', gloss: { de: 'Die Investition hat nicht die erhofften Ergebnisse gebracht.', es: 'La inversión no dio los resultados esperados.', fr: 'L’investissement n’a pas donné les résultats espérés.', pt: 'O investimento não deu os resultados esperados.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['motivi', 'fattori', 'dati'] },
  { id: 'it3s028', de: 'È necessario aggiornare i dati con regolarità.', en: 'It is necessary to update the data regularly.', gloss: { de: 'Es ist nötig, die Daten regelmäßig zu aktualisieren.', es: 'Es necesario actualizar los datos con regularidad.', fr: 'Il est nécessaire de mettre à jour les données régulièrement.', pt: 'É necessário atualizar os dados com regularidade.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['ridurre', 'sostituire', 'coinvolgere'] },
  { id: 'it3s029', de: 'La connessione instabile ha bloccato tutto il sistema.', en: 'The unstable connection blocked the whole system.', gloss: { de: 'Die instabile Verbindung hat das ganze System blockiert.', es: 'La conexión inestable bloqueó todo el sistema.', fr: 'La connexion instable a bloqué tout le système.', pt: 'A conexão instável bloqueou todo o sistema.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['tecnologia', 'innovazione', 'prevenzione'] },
  { id: 'it3s030', de: 'Il progresso tecnologico crea nuove disuguaglianze.', en: 'Technological progress creates new inequalities.', gloss: { de: 'Der technische Fortschritt schafft neue Ungleichheiten.', es: 'El progreso tecnológico crea nuevas desigualdades.', fr: 'Le progrès technologique crée de nouvelles inégalités.', pt: 'O progresso tecnológico cria novas desigualdades.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['dibattito', 'sondaggio', 'malinteso'] },
  { id: 'it3s031', de: 'Non è detto che l’innovazione porti sempre benefici.', en: 'It is not certain that innovation always brings benefits.', gloss: { de: 'Es ist nicht gesagt, dass Innovation immer Vorteile bringt.', es: 'No es seguro que la innovación traiga siempre beneficios.', fr: 'Il n’est pas certain que l’innovation apporte toujours des bénéfices.', pt: 'Não é certo que a inovação traga sempre benefícios.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['crei', 'garantisca', 'riduca'] },
  { id: 'it3s032', de: 'La prevenzione costa meno della cura.', en: 'Prevention costs less than treatment.', gloss: { de: 'Vorbeugung kostet weniger als Behandlung.', es: 'La prevención cuesta menos que el tratamiento.', fr: 'La prévention coûte moins que le traitement.', pt: 'A prevenção custa menos do que o tratamento.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['giustizia', 'tecnologia', 'crescita'] },
  { id: 'it3s033', de: 'Lo stress prolungato danneggia la salute.', en: 'Prolonged stress damages health.', gloss: { de: 'Anhaltender Stress schadet der Gesundheit.', es: 'El estrés prolongado daña la salud.', fr: 'Le stress prolongé nuit à la santé.', pt: 'O estresse prolongado prejudica a saúde.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['dibattito', 'sostegno', 'benessere'] },
  { id: 'it3s034', de: 'Temo che il paziente non guarisca in fretta.', en: 'I fear the patient will not recover quickly.', gloss: { de: 'Ich fürchte, dass der Patient nicht schnell genest.', es: 'Temo que el paciente no se cure rápido.', fr: 'Je crains que le patient ne guérisse pas vite.', pt: 'Receio que o paciente não se cure depressa.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['reagisca', 'migliori', 'resista'] },
  { id: 'it3s035', de: 'Il benessere dei dipendenti dovrebbe essere una priorità.', en: 'Employee wellbeing should be a priority.', gloss: { de: 'Das Wohlbefinden der Mitarbeiter sollte eine Priorität sein.', es: 'El bienestar de los empleados debería ser una prioridad.', fr: 'Le bien-être des employés devrait être une priorité.', pt: 'O bem-estar dos funcionários deveria ser uma prioridade.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['sostegno', 'fatturato', 'criterio'] },
  { id: 'it3s036', de: 'Ho letto un romanzo che parla di libertà e giustizia.', en: 'I read a novel that speaks of freedom and justice.', gloss: { de: 'Ich habe einen Roman über Freiheit und Gerechtigkeit gelesen.', es: 'Leí una novela que habla de libertad y justicia.', fr: 'J’ai lu un roman qui parle de liberté et de justice.', pt: 'Li um romance que fala de liberdade e justiça.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['articolo', 'sondaggio', 'spettacolo'] },
  { id: 'it3s037', de: 'La mostra ha attirato un pubblico numeroso.', en: 'The exhibition attracted a large audience.', gloss: { de: 'Die Ausstellung hat ein zahlreiches Publikum angezogen.', es: 'La exposición atrajo a un público numeroso.', fr: 'L’exposition a attiré un public nombreux.', pt: 'A exposição atraiu um público numeroso.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['trama', 'cultura', 'coppia'] },
  { id: 'it3s038', de: 'Lo spettacolo è stato apprezzato dalla critica.', en: 'The show was appreciated by the critics.', gloss: { de: 'Die Vorstellung wurde von der Kritik gelobt.', es: 'El espectáculo fue apreciado por la crítica.', fr: 'Le spectacle a été apprécié par la critique.', pt: 'O espetáculo foi apreciado pela crítica.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['romanzo', 'regista', 'dibattito'] },
  { id: 'it3s039', de: 'Il regista ha spiegato la trama in poche parole.', en: 'The director explained the plot in a few words.', gloss: { de: 'Der Regisseur hat die Handlung in wenigen Worten erklärt.', es: 'El director explicó la trama en pocas palabras.', fr: 'Le réalisateur a expliqué l’intrigue en quelques mots.', pt: 'O diretor explicou o enredo em poucas palavras.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['giornalista', 'avvocato', 'cittadino'] },
  { id: 'it3s040', de: 'La cultura non dovrebbe dipendere solo dai finanziamenti pubblici.', en: 'Culture should not depend only on public funding.', gloss: { de: 'Kultur sollte nicht nur von öffentlichen Geldern abhängen.', es: 'La cultura no debería depender solo de la financiación pública.', fr: 'La culture ne devrait pas dépendre uniquement des financements publics.', pt: 'A cultura não deveria depender apenas do financiamento público.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['giustizia', 'ricerca', 'società'] },
  { id: 'it3s041', de: 'Il nostro rapporto si basa sulla fiducia reciproca.', en: 'Our relationship is based on mutual trust.', gloss: { de: 'Unsere Beziehung beruht auf gegenseitigem Vertrauen.', es: 'Nuestra relación se basa en la confianza mutua.', fr: 'Notre relation repose sur la confiance mutuelle.', pt: 'A nossa relação baseia-se na confiança mútua.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['sostegno', 'compromesso', 'malinteso'] },
  { id: 'it3s042', de: 'Ogni coppia ha bisogno di un compromesso ragionevole.', en: 'Every couple needs a reasonable compromise.', gloss: { de: 'Jedes Paar braucht einen vernünftigen Kompromiss.', es: 'Toda pareja necesita un acuerdo razonable.', fr: 'Chaque couple a besoin d’un compromis raisonnable.', pt: 'Todo casal precisa de um acordo razoável.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['società', 'carriera', 'ricerca'] },
  { id: 'it3s043', de: 'Il litigio è nato da un semplice malinteso.', en: 'The argument arose from a simple misunderstanding.', gloss: { de: 'Der Streit entstand aus einem einfachen Missverständnis.', es: 'La discusión nació de un simple malentendido.', fr: 'La dispute est née d’un simple malentendu.', pt: 'A briga nasceu de um simples mal-entendido.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['dubbio', 'sostegno', 'criterio'] },
  { id: 'it3s044', de: 'È difficile fidarsi di chi cambia continuamente idea.', en: 'It is hard to trust someone who constantly changes their mind.', gloss: { de: 'Es ist schwer, jemandem zu vertrauen, der ständig seine Meinung ändert.', es: 'Es difícil fiarse de quien cambia continuamente de opinión.', fr: 'Il est difficile de faire confiance à quelqu’un qui change constamment d’avis.', pt: 'É difícil confiar em quem muda de opinião continuamente.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['occuparsi', 'accorgersi', 'stancarsi'] },
  { id: 'it3s045', de: 'Il sostegno dei colleghi è stato determinante.', en: 'The support of colleagues was decisive.', gloss: { de: 'Die Unterstützung der Kollegen war entscheidend.', es: 'El apoyo de los colegas fue decisivo.', fr: 'Le soutien des collègues a été décisif.', pt: 'O apoio dos colegas foi decisivo.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['parere', 'dubbio', 'impegno'] },
  { id: 'it3s046', de: 'L’avvocato sostiene che il suo cliente sia innocente.', en: 'The lawyer maintains that his client is innocent.', gloss: { de: 'Der Anwalt behauptet, dass sein Mandant unschuldig ist.', es: 'El abogado sostiene que su cliente es inocente.', fr: 'L’avocat soutient que son client est innocent.', pt: 'O advogado sustenta que o seu cliente é inocente.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['resti', 'sembri', 'diventi'] },
  { id: 'it3s047', de: 'Il tribunale ha stabilito una multa molto alta.', en: 'The court set a very high fine.', gloss: { de: 'Das Gericht hat eine sehr hohe Geldstrafe festgesetzt.', es: 'El tribunal fijó una multa muy alta.', fr: 'Le tribunal a fixé une amende très élevée.', pt: 'O tribunal fixou uma multa muito alta.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['governo', 'giornale', 'dibattito'] },
  { id: 'it3s048', de: 'La legge vieta di diffondere dati personali.', en: 'The law forbids spreading personal data.', gloss: { de: 'Das Gesetz verbietet die Verbreitung personenbezogener Daten.', es: 'La ley prohíbe difundir datos personales.', fr: 'La loi interdit de diffuser des données personnelles.', pt: 'A lei proíbe difundir dados pessoais.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['permette', 'impedisce', 'garantisce'] },
  { id: 'it3s049', de: 'Chi commette un reato deve risponderne davanti alla giustizia.', en: 'Whoever commits an offence must answer for it before the law.', gloss: { de: 'Wer eine Straftat begeht, muss sich vor der Justiz verantworten.', es: 'Quien comete un delito debe responder ante la justicia.', fr: 'Celui qui commet un délit doit en répondre devant la justice.', pt: 'Quem comete um crime deve responder perante a justiça.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['errore', 'dubbio', 'criterio'] },
  { id: 'it3s050', de: 'Non conosco il motivo di questa decisione.', en: 'I don’t know the reason for this decision.', gloss: { de: 'Ich kenne den Grund für diese Entscheidung nicht.', es: 'No conozco el motivo de esta decisión.', fr: 'Je ne connais pas la raison de cette décision.', pt: 'Não sei o motivo desta decisão.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['criterio', 'fattore', 'vantaggio'] },
  { id: 'it3s051', de: 'La causa principale del problema resta poco chiara.', en: 'The main cause of the problem remains unclear.', gloss: { de: 'Die Hauptursache des Problems bleibt unklar.', es: 'La causa principal del problema sigue poco clara.', fr: 'La cause principale du problème reste peu claire.', pt: 'A causa principal do problema continua pouco clara.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['conseguenza', 'ipotesi', 'prova'] },
  { id: 'it3s052', de: 'Ogni scelta ha una conseguenza che non possiamo ignorare.', en: 'Every choice has a consequence we cannot ignore.', gloss: { de: 'Jede Wahl hat eine Folge, die wir nicht ignorieren können.', es: 'Cada elección tiene una consecuencia que no podemos ignorar.', fr: 'Chaque choix a une conséquence qu’on ne peut pas ignorer.', pt: 'Cada escolha tem uma consequência que não podemos ignorar.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['causa', 'ipotesi', 'speranza'] },
  { id: 'it3s053', de: 'Questa ipotesi non è ancora stata verificata.', en: 'This hypothesis has not been verified yet.', gloss: { de: 'Diese Hypothese wurde noch nicht überprüft.', es: 'Esta hipótesis todavía no ha sido verificada.', fr: 'Cette hypothèse n’a pas encore été vérifiée.', pt: 'Esta hipótese ainda não foi verificada.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['prova', 'notizia', 'competenza'] },
  { id: 'it3s054', de: 'Il prezzo non è l’unico fattore da considerare.', en: 'Price is not the only factor to consider.', gloss: { de: 'Der Preis ist nicht der einzige Faktor, den man beachten muss.', es: 'El precio no es el único factor a considerar.', fr: 'Le prix n’est pas le seul facteur à considérer.', pt: 'O preço não é o único fator a considerar.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['obiettivo', 'vantaggio', 'dubbio'] },
  { id: 'it3s055', de: 'Abbiamo raggiunto l’obiettivo con largo anticipo.', en: 'We reached the target well ahead of time.', gloss: { de: 'Wir haben das Ziel weit im Voraus erreicht.', es: 'Alcanzamos el objetivo con mucha antelación.', fr: 'Nous avons atteint l’objectif bien en avance.', pt: 'Alcançamos o objetivo com bastante antecedência.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['evitato', 'rinviato', 'coinvolto'] },
  { id: 'it3s056', de: 'Il nuovo criterio di valutazione ha convinto pochi.', en: 'The new assessment criterion convinced few people.', gloss: { de: 'Das neue Bewertungskriterium hat wenige überzeugt.', es: 'El nuevo criterio de evaluación convenció a pocos.', fr: 'Le nouveau critère d’évaluation a convaincu peu de gens.', pt: 'O novo critério de avaliação convenceu poucos.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['dubbio', 'motivo', 'fattore'] },
  { id: 'it3s057', de: 'È fondamentale coinvolgere i cittadini nelle decisioni.', en: 'It is essential to involve citizens in decisions.', gloss: { de: 'Es ist entscheidend, die Bürger in die Entscheidungen einzubeziehen.', es: 'Es fundamental involucrar a los ciudadanos en las decisiones.', fr: 'Il est essentiel d’impliquer les citoyens dans les décisions.', pt: 'É fundamental envolver os cidadãos nas decisões.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['garantire', 'sostituire', 'evitare'] },
  { id: 'it3s058', de: 'Questa pratica è ormai molto diffusa tra i giovani.', en: 'This practice is now very widespread among young people.', gloss: { de: 'Diese Praxis ist inzwischen unter jungen Leuten weit verbreitet.', es: 'Esta práctica está ya muy extendida entre los jóvenes.', fr: 'Cette pratique est désormais très répandue chez les jeunes.', pt: 'Essa prática já está muito difundida entre os jovens.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['discutibile', 'superficiale', 'urgente'] },
  { id: 'it3s059', de: 'Le risorse sono scarse e vanno gestite con attenzione.', en: 'Resources are scarce and must be managed carefully.', gloss: { de: 'Die Ressourcen sind knapp und müssen sorgfältig verwaltet werden.', es: 'Los recursos son escasos y deben gestionarse con cuidado.', fr: 'Les ressources sont rares et doivent être gérées avec soin.', pt: 'Os recursos são escassos e devem ser geridos com cuidado.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['diffuse', 'adeguate', 'notevoli'] },
  { id: 'it3s060', de: 'La routine quotidiana può soffocare la creatività.', en: 'Daily routine can stifle creativity.', gloss: { de: 'Die tägliche Routine kann die Kreativität ersticken.', es: 'La rutina cotidiana puede ahogar la creatividad.', fr: 'La routine quotidienne peut étouffer la créativité.', pt: 'A rotina cotidiana pode sufocar a criatividade.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['notevole', 'imprevista', 'scarsa'] },
];
