import type { SentenceItem } from '@/content/german/types';

// French A2 sentences. `de` holds the French text. Where A1 stayed in the
// present tense, A2 lives in the passé composé — which is the whole point of
// the level, and the place French learners actually stumble:
//   · auxiliary choice — avoir for most verbs (j’ai mangé, j’ai payé), être for
//     the movement/state verbs and every reflexive (je suis allé, elle est
//     arrivée, je me suis levé).
//   · agreement — with être the participle agrees with the subject
//     (elle est arrivée, nous sommes allés, ces chaussures sont chères).
// The cloze blanks are placed on those two things wherever possible, and every
// distractor carries the SAME agreement as the answer, so the exercise tests
// meaning rather than letting the learner pattern-match on the ending.
//
// Two French-specific rules the indices respect:
//  · French puts a space before ? ! : ; so "?" is its own whitespace token —
//    the last real word of a question is therefore clean and safe to blank.
//  · Never blank a word carrying trailing punctuation (a final "tôt." would
//    force distractors like "tard."), so sentence-final words are avoided.
//
// `gloss` carries the non-English UI locales; see a2-vocab.ts for the rule.

export const A2_SENTENCES: SentenceItem[] = [
  { id: 'fr2s001', de: 'Hier je me suis levé à sept heures.', en: 'Yesterday I got up at seven o’clock.', gloss: { de: 'Gestern bin ich um sieben Uhr aufgestanden.', es: 'Ayer me levanté a las siete.', it: 'Ieri mi sono alzato alle sette.', pt: 'Ontem eu me levantei às sete.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['couché', 'lavé', 'réveillé'] },
  { id: 'fr2s002', de: 'J’ai pris le train pour Paris.', en: 'I took the train to Paris.', gloss: { de: 'Ich habe den Zug nach Paris genommen.', es: 'Cogí el tren para París.', it: 'Ho preso il treno per Parigi.', pt: 'Peguei o trem para Paris.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['bus', 'métro', 'taxi'] },
  { id: 'fr2s003', de: 'Nous sommes allés à l’hôpital hier soir.', en: 'We went to the hospital last night.', gloss: { de: 'Wir sind gestern Abend ins Krankenhaus gegangen.', es: 'Fuimos al hospital anoche.', it: 'Siamo andati all’ospedale ieri sera.', pt: 'Fomos ao hospital ontem à noite.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['restés', 'venus', 'arrivés'] },
  { id: 'fr2s004', de: 'Elle a oublié son passeport à l’aéroport.', en: 'She forgot her passport at the airport.', gloss: { de: 'Sie hat ihren Reisepass am Flughafen vergessen.', es: 'Ella olvidó su pasaporte en el aeropuerto.', it: 'Ha dimenticato il passaporto all’aeroporto.', pt: 'Ela esqueceu o passaporte no aeroporto.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['trouvé', 'acheté', 'perdu'] },
  { id: 'fr2s005', de: 'J’ai payé avec ma carte bancaire.', en: 'I paid with my bank card.', gloss: { de: 'Ich habe mit meiner Bankkarte bezahlt.', es: 'Pagué con mi tarjeta bancaria.', it: 'Ho pagato con la mia carta bancaria.', pt: 'Paguei com o meu cartão bancário.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['commencé', 'attendu', 'oublié'] },
  { id: 'fr2s006', de: 'Ce matin je me suis douché et je me suis habillé.', en: 'This morning I showered and got dressed.', gloss: { de: 'Heute Morgen habe ich geduscht und mich angezogen.', es: 'Esta mañana me duché y me vestí.', it: 'Stamattina mi sono fatto la doccia e mi sono vestito.', pt: 'Esta manhã tomei banho e me vesti.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['levé', 'couché', 'rasé'] },
  { id: 'fr2s007', de: 'Le médecin m’a dit que j’ai de la fièvre.', en: 'The doctor told me that I have a fever.', gloss: { de: 'Der Arzt hat mir gesagt, dass ich Fieber habe.', es: 'El médico me dijo que tengo fiebre.', it: 'Il medico mi ha detto che ho la febbre.', pt: 'O médico me disse que tenho febre.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['patron', 'collègue', 'voisin'] },
  { id: 'fr2s008', de: 'Nous avons cherché un appartement pendant trois mois.', en: 'We looked for an apartment for three months.', gloss: { de: 'Wir haben drei Monate lang eine Wohnung gesucht.', es: 'Buscamos un apartamento durante tres meses.', it: 'Abbiamo cercato un appartamento per tre mesi.', pt: 'Procuramos um apartamento durante três meses.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['trouvé', 'loué', 'visité'] },
  { id: 'fr2s009', de: 'Est-ce que tu as fini ton travail ?', en: 'Have you finished your work?', gloss: { de: 'Hast du deine Arbeit beendet?', es: '¿Has terminado tu trabajo?', it: 'Hai finito il tuo lavoro?', pt: 'Você terminou o seu trabalho?' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['commencé', 'oublié', 'trouvé'] },
  { id: 'fr2s010', de: 'Le voyage a été plus long que prévu.', en: 'The trip was longer than expected.', gloss: { de: 'Die Reise war länger als erwartet.', es: 'El viaje fue más largo de lo previsto.', it: 'Il viaggio è stato più lungo del previsto.', pt: 'A viagem foi mais longa do que o previsto.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['court', 'cher', 'facile'] },
  { id: 'fr2s011', de: 'Je me suis couché tard parce que j’ai regardé un film.', en: 'I went to bed late because I watched a film.', gloss: { de: 'Ich bin spät ins Bett gegangen, weil ich einen Film gesehen habe.', es: 'Me acosté tarde porque vi una película.', it: 'Sono andato a letto tardi perché ho guardato un film.', pt: 'Fui dormir tarde porque assisti a um filme.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['tôt', 'souvent', 'parfois'] },
  { id: 'fr2s012', de: 'Elle est arrivée au bureau à neuf heures.', en: 'She arrived at the office at nine o’clock.', gloss: { de: 'Sie ist um neun Uhr im Büro angekommen.', es: 'Ella llegó a la oficina a las nueve.', it: 'È arrivata in ufficio alle nove.', pt: 'Ela chegou ao escritório às nove horas.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['partie', 'rentrée', 'venue'] },
  { id: 'fr2s013', de: 'Ces chaussures sont trop chères pour moi.', en: 'These shoes are too expensive for me.', gloss: { de: 'Diese Schuhe sind mir zu teuer.', es: 'Estos zapatos son demasiado caros para mí.', it: 'Queste scarpe sono troppo care per me.', pt: 'Estes sapatos são caros demais para mim.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['grandes', 'petites', 'sales'] },
  { id: 'fr2s014', de: 'Hier soir nous avons dîné dans un très bon restaurant.', en: 'Last night we had dinner in a very good restaurant.', gloss: { de: 'Gestern Abend haben wir in einem sehr guten Restaurant gegessen.', es: 'Anoche cenamos en un restaurante muy bueno.', it: 'Ieri sera abbiamo cenato in un ottimo ristorante.', pt: 'Ontem à noite jantamos num restaurante muito bom.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['mangé', 'travaillé', 'attendu'] },
  { id: 'fr2s015', de: 'Mon frère a trouvé un nouveau travail le mois dernier.', en: 'My brother found a new job last month.', gloss: { de: 'Mein Bruder hat letzten Monat eine neue Arbeit gefunden.', es: 'Mi hermano encontró un nuevo trabajo el mes pasado.', it: 'Mio fratello ha trovato un nuovo lavoro il mese scorso.', pt: 'Meu irmão encontrou um novo emprego no mês passado.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['cherché', 'commencé', 'quitté'] },
  { id: 'fr2s016', de: 'Je n’ai pas encore fait les courses.', en: 'I haven’t done the shopping yet.', gloss: { de: 'Ich habe noch nicht eingekauft.', es: 'Todavía no he hecho la compra.', it: 'Non ho ancora fatto la spesa.', pt: 'Ainda não fiz as compras.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['payé', 'fini', 'oublié'] },
  { id: 'fr2s017', de: 'La chambre d’hôtel était petite mais très propre.', en: 'The hotel room was small but very clean.', gloss: { de: 'Das Hotelzimmer war klein, aber sehr sauber.', es: 'La habitación del hotel era pequeña pero muy limpia.', it: 'La camera d’albergo era piccola ma molto pulita.', pt: 'O quarto do hotel era pequeno mas muito limpo.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['grande', 'chère', 'sombre'] },
  { id: 'fr2s018', de: 'Est-ce que vous avez attendu longtemps ?', en: 'Did you wait a long time?', gloss: { de: 'Haben Sie lange gewartet?', es: '¿Han esperado mucho tiempo?', it: 'Avete aspettato molto?', pt: 'Vocês esperaram muito tempo?' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['travaillé', 'dormi', 'marché'] },
  { id: 'fr2s019', de: 'Je me sens fatigué parce que je me suis levé très tôt.', en: 'I feel tired because I got up very early.', gloss: { de: 'Ich fühle mich müde, weil ich sehr früh aufgestanden bin.', es: 'Me siento cansado porque me levanté muy temprano.', it: 'Mi sento stanco perché mi sono alzato molto presto.', pt: 'Me sinto cansado porque me levantei muito cedo.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['malade', 'heureux', 'occupé'] },
  { id: 'fr2s020', de: 'Nous sommes restés à la maison tout le week-end.', en: 'We stayed at home all weekend.', gloss: { de: 'Wir sind das ganze Wochenende zu Hause geblieben.', es: 'Nos quedamos en casa todo el fin de semana.', it: 'Siamo rimasti a casa tutto il fine settimana.', pt: 'Ficamos em casa o fim de semana inteiro.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['allés', 'arrivés', 'partis'] },
  { id: 'fr2s021', de: 'Le train est parti sans moi ce matin !', en: 'The train left without me this morning!', gloss: { de: 'Der Zug ist heute Morgen ohne mich abgefahren!', es: '¡El tren salió sin mí esta mañana!', it: 'Il treno è partito senza di me stamattina!', pt: 'O trem partiu sem mim esta manhã!' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['arrivé', 'revenu', 'tombé'] },
  { id: 'fr2s022', de: 'J’ai oublié mes clés dans la voiture.', en: 'I left my keys in the car.', gloss: { de: 'Ich habe meine Schlüssel im Auto vergessen.', es: 'Olvidé mis llaves en el coche.', it: 'Ho dimenticato le chiavi in macchina.', pt: 'Esqueci as minhas chaves no carro.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['valises', 'chaussures', 'affaires'] },
];
