import type { SentenceItem } from '@/content/german/types';

// French A2 sentences. `de` holds the French text. Where A1 stayed in the
// present tense, A2 lives in the passé composé — which is the whole point of
// the level, and the place French learners actually stumble:
//   · auxiliary choice — avoir for most verbs (j’ai mangé, j’ai payé), être for
//     the movement/state verbs and every reflexive (je suis allé, elle est
//     arrivée, je me suis levé).
//   · agreement — with être the participle agrees with the subject
//     (elle est arrivée, nous sommes allés, ces chaussures sont chères).
// The cloze blanks are placed on those two things wherever possible, and every
// distractor carries the SAME agreement as the answer, so the exercise tests
// meaning rather than letting the learner pattern-match on the ending.
//
// Two French-specific rules the indices respect:
//  · French puts a space before ? ! : ; so "?" is its own whitespace token —
//    the last real word of a question is therefore clean and safe to blank.
//  · Never blank a word carrying trailing punctuation (a final "tôt." would
//    force distractors like "tard."), so sentence-final words are avoided.
//
// `gloss` carries the non-English UI locales; see a2-vocab.ts for the rule.

export const A2_SENTENCES: SentenceItem[] = [
  { id: 'fr2s001', de: 'Hier je me suis levé à sept heures.', en: 'Yesterday I got up at seven o’clock.', gloss: { de: 'Gestern bin ich um sieben Uhr aufgestanden.', es: 'Ayer me levanté a las siete.', it: 'Ieri mi sono alzato alle sette.', pt: 'Ontem eu me levantei às sete.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['couché', 'lavé', 'réveillé'] },
  { id: 'fr2s002', de: 'J’ai pris le train pour Paris.', en: 'I took the train to Paris.', gloss: { de: 'Ich habe den Zug nach Paris genommen.', es: 'Cogí el tren para París.', it: 'Ho preso il treno per Parigi.', pt: 'Peguei o trem para Paris.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['bus', 'métro', 'taxi'] },
  { id: 'fr2s003', de: 'Nous sommes allés à l’hôpital hier soir.', en: 'We went to the hospital last night.', gloss: { de: 'Wir sind gestern Abend ins Krankenhaus gegangen.', es: 'Fuimos al hospital anoche.', it: 'Siamo andati all’ospedale ieri sera.', pt: 'Fomos ao hospital ontem à noite.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['restés', 'venus', 'arrivés'] },
  { id: 'fr2s004', de: 'Elle a oublié son passeport à l’aéroport.', en: 'She forgot her passport at the airport.', gloss: { de: 'Sie hat ihren Reisepass am Flughafen vergessen.', es: 'Ella olvidó su pasaporte en el aeropuerto.', it: 'Ha dimenticato il passaporto all’aeroporto.', pt: 'Ela esqueceu o passaporte no aeroporto.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['trouvé', 'acheté', 'perdu'] },
  { id: 'fr2s005', de: 'J’ai payé avec ma carte bancaire.', en: 'I paid with my bank card.', gloss: { de: 'Ich habe mit meiner Bankkarte bezahlt.', es: 'Pagué con mi tarjeta bancaria.', it: 'Ho pagato con la mia carta bancaria.', pt: 'Paguei com o meu cartão bancário.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['commencé', 'attendu', 'oublié'] },
  { id: 'fr2s006', de: 'Ce matin je me suis douché et je me suis habillé.', en: 'This morning I showered and got dressed.', gloss: { de: 'Heute Morgen habe ich geduscht und mich angezogen.', es: 'Esta mañana me duché y me vestí.', it: 'Stamattina mi sono fatto la doccia e mi sono vestito.', pt: 'Esta manhã tomei banho e me vesti.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['levé', 'couché', 'rasé'] },
  { id: 'fr2s007', de: 'Le médecin m’a dit que j’ai de la fièvre.', en: 'The doctor told me that I have a fever.', gloss: { de: 'Der Arzt hat mir gesagt, dass ich Fieber habe.', es: 'El médico me dijo que tengo fiebre.', it: 'Il medico mi ha detto che ho la febbre.', pt: 'O médico me disse que tenho febre.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['patron', 'collègue', 'voisin'] },
  { id: 'fr2s008', de: 'Nous avons cherché un appartement pendant trois mois.', en: 'We looked for an apartment for three months.', gloss: { de: 'Wir haben drei Monate lang eine Wohnung gesucht.', es: 'Buscamos un apartamento durante tres meses.', it: 'Abbiamo cercato un appartamento per tre mesi.', pt: 'Procuramos um apartamento durante três meses.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['trouvé', 'loué', 'visité'] },
  { id: 'fr2s009', de: 'Est-ce que tu as fini ton travail ?', en: 'Have you finished your work?', gloss: { de: 'Hast du deine Arbeit beendet?', es: '¿Has terminado tu trabajo?', it: 'Hai finito il tuo lavoro?', pt: 'Você terminou o seu trabalho?' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['commencé', 'oublié', 'trouvé'] },
  { id: 'fr2s010', de: 'Le voyage a été plus long que prévu.', en: 'The trip was longer than expected.', gloss: { de: 'Die Reise war länger als erwartet.', es: 'El viaje fue más largo de lo previsto.', it: 'Il viaggio è stato più lungo del previsto.', pt: 'A viagem foi mais longa do que o previsto.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['court', 'cher', 'facile'] },
  { id: 'fr2s011', de: 'Je me suis couché tard parce que j’ai regardé un film.', en: 'I went to bed late because I watched a film.', gloss: { de: 'Ich bin spät ins Bett gegangen, weil ich einen Film gesehen habe.', es: 'Me acosté tarde porque vi una película.', it: 'Sono andato a letto tardi perché ho guardato un film.', pt: 'Fui dormir tarde porque assisti a um filme.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['tôt', 'souvent', 'parfois'] },
  { id: 'fr2s012', de: 'Elle est arrivée au bureau à neuf heures.', en: 'She arrived at the office at nine o’clock.', gloss: { de: 'Sie ist um neun Uhr im Büro angekommen.', es: 'Ella llegó a la oficina a las nueve.', it: 'È arrivata in ufficio alle nove.', pt: 'Ela chegou ao escritório às nove horas.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['partie', 'rentrée', 'venue'] },
  { id: 'fr2s013', de: 'Ces chaussures sont trop chères pour moi.', en: 'These shoes are too expensive for me.', gloss: { de: 'Diese Schuhe sind mir zu teuer.', es: 'Estos zapatos son demasiado caros para mí.', it: 'Queste scarpe sono troppo care per me.', pt: 'Estes sapatos são caros demais para mim.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['grandes', 'petites', 'sales'] },
  { id: 'fr2s014', de: 'Hier soir nous avons dîné dans un très bon restaurant.', en: 'Last night we had dinner in a very good restaurant.', gloss: { de: 'Gestern Abend haben wir in einem sehr guten Restaurant gegessen.', es: 'Anoche cenamos en un restaurante muy bueno.', it: 'Ieri sera abbiamo cenato in un ottimo ristorante.', pt: 'Ontem à noite jantamos num restaurante muito bom.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['mangé', 'travaillé', 'attendu'] },
  { id: 'fr2s015', de: 'Mon frère a trouvé un nouveau travail le mois dernier.', en: 'My brother found a new job last month.', gloss: { de: 'Mein Bruder hat letzten Monat eine neue Arbeit gefunden.', es: 'Mi hermano encontró un nuevo trabajo el mes pasado.', it: 'Mio fratello ha trovato un nuovo lavoro il mese scorso.', pt: 'Meu irmão encontrou um novo emprego no mês passado.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['cherché', 'commencé', 'quitté'] },
  { id: 'fr2s016', de: 'Je n’ai pas encore fait les courses.', en: 'I haven’t done the shopping yet.', gloss: { de: 'Ich habe noch nicht eingekauft.', es: 'Todavía no he hecho la compra.', it: 'Non ho ancora fatto la spesa.', pt: 'Ainda não fiz as compras.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['payé', 'fini', 'oublié'] },
  { id: 'fr2s017', de: 'La chambre d’hôtel était petite mais très propre.', en: 'The hotel room was small but very clean.', gloss: { de: 'Das Hotelzimmer war klein, aber sehr sauber.', es: 'La habitación del hotel era pequeña pero muy limpia.', it: 'La camera d’albergo era piccola ma molto pulita.', pt: 'O quarto do hotel era pequeno mas muito limpo.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['grande', 'chère', 'sombre'] },
  { id: 'fr2s018', de: 'Est-ce que vous avez attendu longtemps ?', en: 'Did you wait a long time?', gloss: { de: 'Haben Sie lange gewartet?', es: '¿Han esperado mucho tiempo?', it: 'Avete aspettato molto?', pt: 'Vocês esperaram muito tempo?' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['travaillé', 'dormi', 'marché'] },
  { id: 'fr2s019', de: 'Je me sens fatigué parce que je me suis levé très tôt.', en: 'I feel tired because I got up very early.', gloss: { de: 'Ich fühle mich müde, weil ich sehr früh aufgestanden bin.', es: 'Me siento cansado porque me levanté muy temprano.', it: 'Mi sento stanco perché mi sono alzato molto presto.', pt: 'Me sinto cansado porque me levantei muito cedo.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['malade', 'heureux', 'occupé'] },
  { id: 'fr2s020', de: 'Nous sommes restés à la maison tout le week-end.', en: 'We stayed at home all weekend.', gloss: { de: 'Wir sind das ganze Wochenende zu Hause geblieben.', es: 'Nos quedamos en casa todo el fin de semana.', it: 'Siamo rimasti a casa tutto il fine settimana.', pt: 'Ficamos em casa o fim de semana inteiro.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['allés', 'arrivés', 'partis'] },
  { id: 'fr2s021', de: 'Le train est parti sans moi ce matin !', en: 'The train left without me this morning!', gloss: { de: 'Der Zug ist heute Morgen ohne mich abgefahren!', es: '¡El tren salió sin mí esta mañana!', it: 'Il treno è partito senza di me stamattina!', pt: 'O trem partiu sem mim esta manhã!' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['arrivé', 'revenu', 'tombé'] },
  { id: 'fr2s022', de: 'J’ai oublié mes clés dans la voiture.', en: 'I left my keys in the car.', gloss: { de: 'Ich habe meine Schlüssel im Auto vergessen.', es: 'Olvidé mis llaves en el coche.', it: 'Ho dimenticato le chiavi in macchina.', pt: 'Esqueci as minhas chaves no carro.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['valises', 'chaussures', 'affaires'] },
  { id: 'fr2s023', de: 'Nous avons visité le musée le week-end dernier.', en: 'We visited the museum last weekend.', gloss: { de: 'Wir haben letztes Wochenende das Museum besucht.', es: 'Visitamos el museo el fin de semana pasado.', it: 'Abbiamo visitato il museo lo scorso fine settimana.', pt: 'Visitamos o museu no fim de semana passado.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['parc', 'quartier', 'pont'] },
  { id: 'fr2s024', de: 'J’ai retiré de l’argent à la banque.', en: 'I withdrew some money at the bank.', gloss: { de: 'Ich habe bei der Bank Geld abgehoben.', es: 'Saqué dinero en el banco.', it: 'Ho ritirato dei soldi in banca.', pt: 'Retirei dinheiro no banco.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['perdu', 'compté', 'oublié'] },
  { id: 'fr2s025', de: 'Elle est allée à la pharmacie ce matin.', en: 'She went to the pharmacy this morning.', gloss: { de: 'Sie ist heute Morgen in die Apotheke gegangen.', es: 'Ella fue a la farmacia esta mañana.', it: 'È andata in farmacia stamattina.', pt: 'Ela foi à farmácia esta manhã.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['banque', 'poste', 'bibliothèque'] },
  { id: 'fr2s026', de: 'Tournez à droite après le pont.', en: 'Turn right after the bridge.', gloss: { de: 'Biegen Sie nach der Brücke rechts ab.', es: 'Gire a la derecha después del puente.', it: 'Giri a destra dopo il ponte.', pt: 'Vire à direita depois da ponte.' }, level: 'A2', clozeIndex: 0, clozeDistractors: ['Continuez', 'Traversez', 'Montez'] },
  { id: 'fr2s027', de: 'Il a plu pendant tout le week-end.', en: 'It rained all weekend.', gloss: { de: 'Es hat das ganze Wochenende geregnet.', es: 'Llovió durante todo el fin de semana.', it: 'Ha piovuto per tutto il fine settimana.', pt: 'Choveu durante todo o fim de semana.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['neigé', 'duré', 'continué'] },
  { id: 'fr2s028', de: 'La météo a annoncé de la pluie pour demain.', en: 'The forecast has announced rain for tomorrow.', gloss: { de: 'Der Wetterbericht hat für morgen Regen angekündigt.', es: 'El pronóstico ha anunciado lluvia para mañana.', it: 'Le previsioni hanno annunciato pioggia per domani.', pt: 'A previsão anunciou chuva para amanhã.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['prévu', 'confirmé', 'changé'] },
  { id: 'fr2s029', de: 'Hier il a fait très chaud dans le bureau.', en: 'Yesterday it was very hot in the office.', gloss: { de: 'Gestern war es im Büro sehr heiß.', es: 'Ayer hizo mucho calor en la oficina.', it: 'Ieri faceva molto caldo in ufficio.', pt: 'Ontem estava muito quente no escritório.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['froid', 'humide', 'sombre'] },
  { id: 'fr2s030', de: 'Nous avons pris le vélo pour aller au parc.', en: 'We took the bike to go to the park.', gloss: { de: 'Wir haben das Fahrrad genommen, um in den Park zu fahren.', es: 'Cogimos la bicicleta para ir al parque.', it: 'Abbiamo preso la bicicletta per andare al parco.', pt: 'Pegamos a bicicleta para ir ao parque.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['bus', 'métro', 'train'] },
  { id: 'fr2s031', de: 'Mon équipe a gagné le match hier soir.', en: 'My team won the match last night.', gloss: { de: 'Meine Mannschaft hat gestern Abend das Spiel gewonnen.', es: 'Mi equipo ganó el partido anoche.', it: 'La mia squadra ha vinto la partita ieri sera.', pt: 'A minha equipe ganhou a partida ontem à noite.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['perdu', 'joué', 'regardé'] },
  { id: 'fr2s032', de: 'J’ai changé mon mot de passe hier.', en: 'I changed my password yesterday.', gloss: { de: 'Ich habe gestern mein Passwort geändert.', es: 'Cambié mi contraseña ayer.', it: 'Ho cambiato la mia password ieri.', pt: 'Mudei a minha senha ontem.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['choisi', 'noté', 'perdu'] },
  { id: 'fr2s033', de: 'Elle m’a envoyé un message ce matin.', en: 'She sent me a message this morning.', gloss: { de: 'Sie hat mir heute Morgen eine Nachricht geschickt.', es: 'Ella me envió un mensaje esta mañana.', it: 'Mi ha mandato un messaggio stamattina.', pt: 'Ela me enviou uma mensagem esta manhã.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['écrit', 'laissé', 'montré'] },
  { id: 'fr2s034', de: 'J’ai téléchargé une application pour apprendre le français.', en: 'I downloaded an app to learn French.', gloss: { de: 'Ich habe eine App heruntergeladen, um Französisch zu lernen.', es: 'Descargué una aplicación para aprender francés.', it: 'Ho scaricato un’applicazione per imparare il francese.', pt: 'Baixei um aplicativo para aprender francês.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['acheté', 'ouvert', 'fermé'] },
  { id: 'fr2s035', de: 'Mon portable est tombé et l’écran est cassé.', en: 'My phone fell and the screen is broken.', gloss: { de: 'Mein Handy ist heruntergefallen und der Bildschirm ist kaputt.', es: 'Mi móvil se cayó y la pantalla está rota.', it: 'Il mio cellulare è caduto e lo schermo è rotto.', pt: 'O meu celular caiu e a tela está quebrada.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['resté', 'parti', 'arrivé'] },
  { id: 'fr2s036', de: 'Nous avons décidé de partir le week-end prochain.', en: 'We decided to leave next weekend.', gloss: { de: 'Wir haben beschlossen, nächstes Wochenende wegzufahren.', es: 'Decidimos irnos el fin de semana que viene.', it: 'Abbiamo deciso di partire il prossimo fine settimana.', pt: 'Decidimos partir no próximo fim de semana.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['essayé', 'refusé', 'promis'] },
  { id: 'fr2s037', de: 'J’ai un rendez-vous chez le médecin à trois heures.', en: 'I have an appointment at the doctor’s at three o’clock.', gloss: { de: 'Ich habe um drei Uhr einen Termin beim Arzt.', es: 'Tengo una cita con el médico a las tres.', it: 'Ho un appuntamento dal medico alle tre.', pt: 'Tenho uma consulta com o médico às três horas.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['examen', 'entretien', 'problème'] },
  { id: 'fr2s038', de: 'Elle a réservé une chambre pour deux nuits.', en: 'She booked a room for two nights.', gloss: { de: 'Sie hat ein Zimmer für zwei Nächte reserviert.', es: 'Ella reservó una habitación para dos noches.', it: 'Ha prenotato una camera per due notti.', pt: 'Ela reservou um quarto para duas noites.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['cherché', 'payé', 'trouvé'] },
  { id: 'fr2s039', de: 'Nous sommes descendus du train à la gare.', en: 'We got off the train at the station.', gloss: { de: 'Wir sind am Bahnhof aus dem Zug ausgestiegen.', es: 'Bajamos del tren en la estación.', it: 'Siamo scesi dal treno alla stazione.', pt: 'Descemos do trem na estação.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['montés', 'arrivés', 'partis'] },
  { id: 'fr2s040', de: 'La pharmacie est en face de la poste.', en: 'The pharmacy is opposite the post office.', gloss: { de: 'Die Apotheke ist gegenüber der Post.', es: 'La farmacia está enfrente de la oficina de correos.', it: 'La farmacia è di fronte alla posta.', pt: 'A farmácia fica em frente dos correios.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['banque', 'bibliothèque', 'piscine'] },
  { id: 'fr2s041', de: 'Je vais continuer tout droit jusqu’au pont.', en: 'I am going to carry straight on as far as the bridge.', gloss: { de: 'Ich gehe geradeaus weiter bis zur Brücke.', es: 'Voy a seguir todo recto hasta el puente.', it: 'Continuo sempre dritto fino al ponte.', pt: 'Vou continuar sempre em frente até a ponte.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['tourner', 'traverser', 'monter'] },
  { id: 'fr2s042', de: 'Il a traversé la place pour aller à la poste.', en: 'He crossed the square to go to the post office.', gloss: { de: 'Er hat den Platz überquert, um zur Post zu gehen.', es: 'Cruzó la plaza para ir a la oficina de correos.', it: 'Ha attraversato la piazza per andare alla posta.', pt: 'Ele atravessou a praça para ir aos correios.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['quitté', 'regardé', 'cherché'] },
  { id: 'fr2s043', de: 'Le mois prochain je vais commencer un nouveau travail.', en: 'Next month I am going to start a new job.', gloss: { de: 'Nächsten Monat fange ich eine neue Arbeit an.', es: 'El mes que viene voy a empezar un nuevo trabajo.', it: 'Il mese prossimo comincerò un nuovo lavoro.', pt: 'No mês que vem vou começar um novo emprego.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['chercher', 'quitter', 'finir'] },
  { id: 'fr2s044', de: 'Est-ce que tu as déjà réservé le billet ?', en: 'Have you already booked the ticket?', gloss: { de: 'Hast du die Fahrkarte schon reserviert?', es: '¿Ya has reservado el billete?', it: 'Hai già prenotato il biglietto?', pt: 'Você já reservou a passagem?' }, level: 'A2', clozeIndex: 7, clozeDistractors: ['hôtel', 'voyage', 'taxi'] },
  { id: 'fr2s045', de: 'Nous avons nagé dans la piscine pendant une heure.', en: 'We swam in the pool for an hour.', gloss: { de: 'Wir sind eine Stunde lang im Schwimmbad geschwommen.', es: 'Nadamos en la piscina durante una hora.', it: 'Abbiamo nuotato in piscina per un’ora.', pt: 'Nadamos na piscina durante uma hora.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['joué', 'couru', 'marché'] },
  { id: 'fr2s046', de: 'J’ai couru dans le parc ce matin.', en: 'I ran in the park this morning.', gloss: { de: 'Ich bin heute Morgen im Park gelaufen.', es: 'Corrí en el parque esta mañana.', it: 'Ho corso nel parco stamattina.', pt: 'Corri no parque esta manhã.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['marché', 'dormi', 'travaillé'] },
  { id: 'fr2s047', de: 'Le concert a commencé très tard hier soir.', en: 'The concert started very late last night.', gloss: { de: 'Das Konzert hat gestern Abend sehr spät angefangen.', es: 'El concierto empezó muy tarde anoche.', it: 'Il concerto è cominciato molto tardi ieri sera.', pt: 'O concerto começou muito tarde ontem à noite.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['match', 'film', 'voyage'] },
  { id: 'fr2s048', de: 'Nous avons regardé un film sur mon ordinateur.', en: 'We watched a film on my computer.', gloss: { de: 'Wir haben einen Film auf meinem Computer angesehen.', es: 'Vimos una película en mi ordenador.', it: 'Abbiamo guardato un film sul mio computer.', pt: 'Assistimos a um filme no meu computador.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['choisi', 'trouvé', 'acheté'] },
  { id: 'fr2s049', de: 'Elle a préféré rester à la maison ce week-end.', en: 'She preferred to stay at home this weekend.', gloss: { de: 'Sie ist dieses Wochenende lieber zu Hause geblieben.', es: 'Ella prefirió quedarse en casa este fin de semana.', it: 'Ha preferito restare a casa questo fine settimana.', pt: 'Ela preferiu ficar em casa neste fim de semana.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['voulu', 'pu', 'dû'] },
  { id: 'fr2s050', de: 'Je n’ai pas pu venir parce que j’étais malade.', en: 'I could not come because I was ill.', gloss: { de: 'Ich konnte nicht kommen, weil ich krank war.', es: 'No pude venir porque estaba enfermo.', it: 'Non ho potuto venire perché ero malato.', pt: 'Não pude vir porque estava doente.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['voulu', 'su', 'dû'] },
  { id: 'fr2s051', de: 'Je dois envoyer ce message avant la réunion.', en: 'I have to send this message before the meeting.', gloss: { de: 'Ich muss diese Nachricht vor der Besprechung schicken.', es: 'Tengo que enviar este mensaje antes de la reunión.', it: 'Devo inviare questo messaggio prima della riunione.', pt: 'Tenho que enviar esta mensagem antes da reunião.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['écrire', 'finir', 'préparer'] },
  { id: 'fr2s052', de: 'Nous espérons trouver un appartement dans ce quartier.', en: 'We hope to find a flat in this neighbourhood.', gloss: { de: 'Wir hoffen, in diesem Viertel eine Wohnung zu finden.', es: 'Esperamos encontrar un apartamento en este barrio.', it: 'Speriamo di trovare un appartamento in questo quartiere.', pt: 'Esperamos encontrar um apartamento neste bairro.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['voulons', 'pouvons', 'devons'] },
  { id: 'fr2s053', de: 'La bibliothèque est ouverte jusqu’à sept heures.', en: 'The library is open until seven o’clock.', gloss: { de: 'Die Bibliothek ist bis sieben Uhr geöffnet.', es: 'La biblioteca está abierta hasta las siete.', it: 'La biblioteca è aperta fino alle sette.', pt: 'A biblioteca fica aberta até as sete horas.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['banque', 'poste', 'piscine'] },
  { id: 'fr2s054', de: 'Il y a un grand immeuble dans notre quartier.', en: 'There is a big building in our neighbourhood.', gloss: { de: 'In unserem Viertel gibt es ein großes Gebäude.', es: 'Hay un edificio grande en nuestro barrio.', it: 'C’è un grande palazzo nel nostro quartiere.', pt: 'Há um prédio grande no nosso bairro.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['parc', 'musée', 'pont'] },
  { id: 'fr2s055', de: 'Le temps a changé pendant la nuit.', en: 'The weather changed during the night.', gloss: { de: 'Das Wetter hat sich in der Nacht geändert.', es: 'El tiempo cambió durante la noche.', it: 'Il tempo è cambiato durante la notte.', pt: 'O tempo mudou durante a noite.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['duré', 'commencé', 'continué'] },
  { id: 'fr2s056', de: 'Il a neigé sur la montagne cette semaine.', en: 'It snowed on the mountain this week.', gloss: { de: 'Diese Woche hat es auf dem Berg geschneit.', es: 'Esta semana nevó en la montaña.', it: 'Questa settimana ha nevicato sulla montagna.', pt: 'Esta semana nevou na montanha.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['plu', 'duré', 'commencé'] },
  { id: 'fr2s057', de: 'Il y a beaucoup de nuages ce matin.', en: 'There are a lot of clouds this morning.', gloss: { de: 'Heute Morgen gibt es viele Wolken.', es: 'Hay muchas nubes esta mañana.', it: 'Ci sono molte nuvole stamattina.', pt: 'Há muitas nuvens esta manhã.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['vent', 'soleil', 'brouillard'] },
  { id: 'fr2s058', de: 'L’orage a commencé pendant le dîner.', en: 'The storm started during dinner.', gloss: { de: 'Das Gewitter hat während des Abendessens angefangen.', es: 'La tormenta empezó durante la cena.', it: 'Il temporale è cominciato durante la cena.', pt: 'A tempestade começou durante o jantar.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['fini', 'duré', 'continué'] },
  { id: 'fr2s059', de: 'J’ai monté les valises dans la chambre.', en: 'I carried the suitcases up to the room.', gloss: { de: 'Ich habe die Koffer ins Zimmer hinaufgetragen.', es: 'Subí las maletas a la habitación.', it: 'Ho portato su le valigie in camera.', pt: 'Levei as malas para o quarto.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['descendu', 'porté', 'laissé'] },
  { id: 'fr2s060', de: 'Nous avons choisi une date pour la réunion.', en: 'We chose a date for the meeting.', gloss: { de: 'Wir haben ein Datum für die Besprechung gewählt.', es: 'Elegimos una fecha para la reunión.', it: 'Abbiamo scelto una data per la riunione.', pt: 'Escolhemos uma data para a reunião.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['proposé', 'trouvé', 'changé'] },
  { id: 'fr2s061', de: 'Ce projet a duré plus de six mois.', en: 'This project lasted more than six months.', gloss: { de: 'Dieses Projekt hat mehr als sechs Monate gedauert.', es: 'Este proyecto duró más de seis meses.', it: 'Questo progetto è durato più di sei mesi.', pt: 'Este projeto durou mais de seis meses.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['voyage', 'examen', 'entretien'] },
  { id: 'fr2s062', de: 'Le site web ne marche pas depuis hier.', en: 'The website has not been working since yesterday.', gloss: { de: 'Die Webseite funktioniert seit gestern nicht.', es: 'El sitio web no funciona desde ayer.', it: 'Il sito web non funziona da ieri.', pt: 'O site não funciona desde ontem.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['change', 'répond', 'ouvre'] },
];
