import type { SentenceItem } from '@/content/german/types';

// French B1 sentences. `de` holds the French text. Where A2 lived in the passé
// composé of a personal anecdote, B1 is the syntax of argument: subordinate
// clauses, opinion framing, and above all the subjunctive — the level's real
// hurdle, and the reason most of the blanks sit on a conjugated verb:
//   · after bien que / afin que / pour que        → bien qu’il SOIT fatigué
//   · after il faut que / il est important que    → il faut que nous PUISSIONS
//   · after verbs of doubt and wish (douter, vouloir) → je doute qu’elle VEUILLE
// Every distractor on those blanks is the SAME verb in the indicative
// (est / était / sera), so the exercise tests mood rather than vocabulary — the
// learner has to notice the trigger, which is the whole skill.
//
// Two French-specific rules the indices respect:
//  · French puts a space before ? ! : ; so "?" is its own whitespace token —
//    the last real word of a question is therefore clean and safe to blank.
//  · Never blank a word carrying trailing punctuation (a final "possible."
//    would force distractors like "facile."), so sentence-final words are
//    avoided and the target always sits mid-sentence.
//
// `gloss` carries the non-English UI locales; see b1-vocab.ts for the rule.

export const B1_SENTENCES: SentenceItem[] = [
  { id: 'fr3s001', de: 'Bien qu’il soit fatigué, il continue à travailler.', en: 'Although he is tired, he keeps working.', gloss: { de: 'Obwohl er müde ist, arbeitet er weiter.', es: 'Aunque esté cansado, sigue trabajando.', it: 'Benché sia stanco, continua a lavorare.', pt: 'Embora esteja cansado, continua trabalhando.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['est', 'était', 'sera'] },
  { id: 'fr3s002', de: 'À mon avis, il faut que nous changions nos habitudes.', en: 'In my opinion, we need to change our habits.', gloss: { de: 'Meiner Meinung nach müssen wir unsere Gewohnheiten ändern.', es: 'En mi opinión, tenemos que cambiar nuestras costumbres.', it: 'Secondo me, dobbiamo cambiare le nostre abitudini.', pt: 'Na minha opinião, temos que mudar os nossos hábitos.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['changeons', 'changerons', 'changiez'] },
  { id: 'fr3s003', de: 'Le gouvernement a proposé une nouvelle loi contre la pollution.', en: 'The government proposed a new law against pollution.', gloss: { de: 'Die Regierung hat ein neues Gesetz gegen die Verschmutzung vorgeschlagen.', es: 'El gobierno propuso una nueva ley contra la contaminación.', it: 'Il governo ha proposto una nuova legge contro l’inquinamento.', pt: 'O governo propôs uma nova lei contra a poluição.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['voté', 'rejeté', 'annoncé'] },
  { id: 'fr3s004', de: 'Cependant, beaucoup de citoyens doutent de l’efficacité de cette mesure.', en: 'However, many citizens doubt the effectiveness of this measure.', gloss: { de: 'Viele Bürger zweifeln jedoch an der Wirksamkeit dieser Maßnahme.', es: 'Sin embargo, muchos ciudadanos dudan de la eficacia de esta medida.', it: 'Tuttavia, molti cittadini dubitano dell’efficacia di questa misura.', pt: 'No entanto, muitos cidadãos duvidam da eficácia desta medida.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['électeurs', 'habitants', 'employés'] },
  { id: 'fr3s005', de: 'Il est important que chacun fasse un effort pour réduire ses déchets.', en: 'It is important that everyone makes an effort to reduce their waste.', gloss: { de: 'Es ist wichtig, dass jeder sich bemüht, seinen Müll zu reduzieren.', es: 'Es importante que cada uno haga un esfuerzo para reducir sus residuos.', it: 'È importante che ognuno faccia uno sforzo per ridurre i propri rifiuti.', pt: 'É importante que cada um faça um esforço para reduzir os seus resíduos.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['fait', 'fera', 'faisait'] },
  { id: 'fr3s006', de: 'Malgré la crise, l’entreprise a embauché vingt personnes cette année.', en: 'Despite the crisis, the company hired twenty people this year.', gloss: { de: 'Trotz der Krise hat die Firma dieses Jahr zwanzig Leute eingestellt.', es: 'A pesar de la crisis, la empresa contrató a veinte personas este año.', it: 'Nonostante la crisi, l’azienda ha assunto venti persone quest’anno.', pt: 'Apesar da crise, a empresa contratou vinte pessoas este ano.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['licencié', 'formé', 'remplacé'] },
  { id: 'fr3s007', de: 'Je ne suis pas d’accord avec cet article, car les preuves manquent.', en: 'I do not agree with this article, because the evidence is missing.', gloss: { de: 'Ich bin mit diesem Artikel nicht einverstanden, denn die Beweise fehlen.', es: 'No estoy de acuerdo con este artículo, porque faltan las pruebas.', it: 'Non sono d’accordo con questo articolo, perché mancano le prove.', pt: 'Não concordo com este artigo, porque faltam as provas.' }, level: 'B1', clozeIndex: 10, clozeDistractors: ['sources', 'données', 'statistiques'] },
  { id: 'fr3s008', de: 'Les médias diffusent parfois des informations qui ne sont pas vérifiées.', en: 'The media sometimes broadcast information that has not been verified.', gloss: { de: 'Die Medien verbreiten manchmal Informationen, die nicht überprüft sind.', es: 'Los medios difunden a veces informaciones que no están verificadas.', it: 'I media diffondono a volte informazioni che non sono verificate.', pt: 'A mídia às vezes divulga informações que não são verificadas.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['publient', 'relaient', 'répètent'] },
  { id: 'fr3s009', de: 'Bien que le chômage ait baissé, la pauvreté reste un problème grave.', en: 'Although unemployment has fallen, poverty remains a serious problem.', gloss: { de: 'Obwohl die Arbeitslosigkeit gesunken ist, bleibt die Armut ein ernstes Problem.', es: 'Aunque el desempleo haya bajado, la pobreza sigue siendo un problema grave.', it: 'Benché la disoccupazione sia diminuita, la povertà resta un problema grave.', pt: 'Embora o desemprego tenha baixado, a pobreza continua sendo um problema grave.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['a', 'avait', 'aura'] },
  { id: 'fr3s010', de: 'Elle a démissionné pour que sa carrière prenne une autre direction.', en: 'She resigned so that her career would take another direction.', gloss: { de: 'Sie hat gekündigt, damit ihre Karriere eine andere Richtung nimmt.', es: 'Dimitió para que su carrera tomara otra dirección.', it: 'Si è dimessa affinché la sua carriera prendesse un’altra direzione.', pt: 'Ela se demitiu para que a sua carreira tomasse outra direção.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['prend', 'prendra', 'prenait'] },
  { id: 'fr3s011', de: 'Nous devons protéger l’environnement, sinon les générations futures paieront.', en: 'We must protect the environment, otherwise future generations will pay.', gloss: { de: 'Wir müssen die Umwelt schützen, sonst werden künftige Generationen zahlen.', es: 'Debemos proteger el medio ambiente, si no las generaciones futuras pagarán.', it: 'Dobbiamo proteggere l’ambiente, altrimenti le generazioni future pagheranno.', pt: 'Devemos proteger o ambiente, senão as gerações futuras pagarão.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['pourtant', 'donc', 'ainsi'] },
  { id: 'fr3s012', de: 'Le journaliste a soutenu que le sondage n’était pas fiable.', en: 'The journalist maintained that the poll was not reliable.', gloss: { de: 'Der Journalist hat behauptet, dass die Umfrage nicht zuverlässig war.', es: 'El periodista sostuvo que la encuesta no era fiable.', it: 'Il giornalista ha sostenuto che il sondaggio non era affidabile.', pt: 'O jornalista sustentou que a pesquisa não era confiável.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['affirmé', 'reconnu', 'nié'] },
  { id: 'fr3s013', de: 'Il faut que nous puissions débattre sans nous fâcher.', en: 'We need to be able to debate without getting angry.', gloss: { de: 'Wir müssen debattieren können, ohne uns zu ärgern.', es: 'Hace falta que podamos debatir sin enfadarnos.', it: 'Bisogna che possiamo discutere senza arrabbiarci.', pt: 'É preciso que possamos debater sem nos zangarmos.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['pouvons', 'pourrons', 'pouvions'] },
  { id: 'fr3s014', de: 'Beaucoup d’étudiants s’inscrivent à une formation afin d’améliorer leurs compétences.', en: 'Many students enrol in a training course in order to improve their skills.', gloss: { de: 'Viele Studenten schreiben sich für eine Ausbildung ein, um ihre Kompetenzen zu verbessern.', es: 'Muchos estudiantes se matriculan en una formación para mejorar sus competencias.', it: 'Molti studenti si iscrivono a una formazione per migliorare le proprie competenze.', pt: 'Muitos estudantes se inscrevem numa formação a fim de melhorar as suas competências.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['licence', 'bourse', 'recherche'] },
  { id: 'fr3s015', de: 'Penses-tu qu’il soit possible de changer les choses ?', en: 'Do you think it is possible to change things?', gloss: { de: 'Glaubst du, dass es möglich ist, die Dinge zu ändern?', es: '¿Crees que es posible cambiar las cosas?', it: 'Pensi che sia possibile cambiare le cose?', pt: 'Você acha que é possível mudar as coisas?' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['facile', 'utile', 'urgent'] },
  { id: 'fr3s016', de: 'L’égalité entre les citoyens est un droit fondamental, pas un privilège.', en: 'Equality between citizens is a fundamental right, not a privilege.', gloss: { de: 'Die Gleichheit zwischen den Bürgern ist ein Grundrecht, kein Privileg.', es: 'La igualdad entre los ciudadanos es un derecho fundamental, no un privilegio.', it: 'L’uguaglianza tra i cittadini è un diritto fondamentale, non un privilegio.', pt: 'A igualdade entre os cidadãos é um direito fundamental, não um privilégio.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['devoir', 'choix', 'but'] },
  { id: 'fr3s017', de: 'Le recyclage est efficace, mais le gaspillage reste le vrai problème.', en: 'Recycling is effective, but waste is still the real problem.', gloss: { de: 'Recycling ist wirksam, aber die Verschwendung bleibt das eigentliche Problem.', es: 'El reciclaje es eficaz, pero el derroche sigue siendo el verdadero problema.', it: 'Il riciclaggio è efficace, ma lo spreco resta il vero problema.', pt: 'A reciclagem é eficaz, mas o desperdício continua sendo o verdadeiro problema.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['transport', 'emballage', 'plastique'] },
  { id: 'fr3s018', de: 'Malgré son expérience, il n’a pas obtenu le poste qu’il espérait.', en: 'Despite his experience, he did not get the job he was hoping for.', gloss: { de: 'Trotz seiner Erfahrung hat er die Stelle nicht bekommen, die er sich erhofft hatte.', es: 'A pesar de su experiencia, no obtuvo el puesto que esperaba.', it: 'Nonostante la sua esperienza, non ha ottenuto il posto che sperava.', pt: 'Apesar da sua experiência, não obteve o cargo que esperava.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['accepté', 'refusé', 'trouvé'] },
  { id: 'fr3s019', de: 'Cette émission a été diffusée sur toutes les chaînes hier soir.', en: 'This programme was broadcast on all the channels last night.', gloss: { de: 'Diese Sendung wurde gestern Abend auf allen Sendern ausgestrahlt.', es: 'Este programa fue difundido en todos los canales anoche.', it: 'Questa trasmissione è stata diffusa su tutti i canali ieri sera.', pt: 'Este programa foi transmitido em todos os canais ontem à noite.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['annulée', 'enregistrée', 'critiquée'] },
  { id: 'fr3s020', de: 'Je doute qu’elle veuille assumer une telle responsabilité au travail.', en: 'I doubt she wants to take on such a responsibility at work.', gloss: { de: 'Ich bezweifle, dass sie eine solche Verantwortung bei der Arbeit übernehmen will.', es: 'Dudo que quiera asumir tal responsabilidad en el trabajo.', it: 'Dubito che voglia assumersi una simile responsabilità al lavoro.', pt: 'Duvido que ela queira assumir tal responsabilidade no trabalho.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['veut', 'voudra', 'voulait'] },
];
