import type { SentenceItem } from './types';

// B2 sentences: Konjunktiv II, passive, extended attributes and the connectors
// that carry an argument. clozeIndex targets the hinge word — the connector,
// the modal, the nominalisation the whole sentence turns on.

export const B2_SENTENCES: SentenceItem[] = [
  // ── connectors of argument ────────────────────────────────────────────
  { id: 'b2s001', de: 'Der Vorschlag klingt vernünftig, dennoch bleiben erhebliche Zweifel.', en: 'The proposal sounds reasonable; nevertheless, considerable doubts remain.', gloss: { es: 'La propuesta suena razonable; aun así, quedan dudas considerables.', fr: 'La proposition semble raisonnable ; néanmoins, des doutes considérables subsistent.', it: 'La proposta sembra ragionevole; nondimeno restano dubbi considerevoli.', pt: 'A proposta parece razoável; ainda assim, restam dúvidas consideráveis.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['folglich', 'hingegen', 'bekanntlich'] },
  { id: 'b2s002', de: 'Insofern lässt sich die Kritik durchaus nachvollziehen.', en: 'In that respect, the criticism is perfectly understandable.', gloss: { es: 'En ese sentido, la crítica se entiende perfectamente.', fr: 'Dans cette mesure, la critique est tout à fait compréhensible.', it: 'In tal senso, la critica è del tutto comprensibile.', pt: 'Nesse sentido, a crítica é perfeitamente compreensível.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Folglich', 'Dennoch', 'Hingegen'] },
  { id: 'b2s003', de: 'Sofern keine Einwände bestehen, gilt der Termin als bestätigt.', en: 'Provided there are no objections, the appointment counts as confirmed.', gloss: { es: 'Siempre que no haya objeciones, la cita se considera confirmada.', fr: 'À condition qu’il n’y ait pas d’objections, le rendez-vous est considéré comme confirmé.', it: 'Purché non ci siano obiezioni, l’appuntamento si considera confermato.', pt: 'Desde que não haja objeções, o compromisso é considerado confirmado.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Obgleich', 'Zumal', 'Wohingegen'] },
  { id: 'b2s004', de: 'Obgleich die Studie sorgfältig angelegt war, bleiben die Ergebnisse vorläufig.', en: 'Although the study was carefully designed, the results remain provisional.', gloss: { es: 'Si bien el estudio estaba cuidadosamente diseñado, los resultados siguen siendo provisionales.', fr: 'Bien que l’étude ait été soigneusement conçue, les résultats restent provisoires.', it: 'Sebbene lo studio fosse impostato con cura, i risultati restano provvisori.', pt: 'Embora o estudo tenha sido cuidadosamente concebido, os resultados continuam provisórios.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Sofern', 'Zumal', 'Indem'] },
  { id: 'b2s005', de: 'Er kann kaum kochen, geschweige denn ein ganzes Menü planen.', en: 'He can barely cook, let alone plan a whole menu.', gloss: { es: 'Apenas sabe cocinar, y mucho menos planear un menú entero.', fr: 'Il sait à peine cuisiner, et encore moins concevoir un menu entier.', it: 'Sa a malapena cucinare, tanto meno pianificare un menù intero.', pt: 'Ele mal sabe cozinhar, muito menos planejar um cardápio inteiro.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['zumal', 'sofern', 'folglich'] },
  { id: 'b2s006', de: 'Die Entscheidung wurde vertagt, zumal wichtige Unterlagen fehlten.', en: 'The decision was postponed, especially since important documents were missing.', gloss: { es: 'La decisión se aplazó, sobre todo porque faltaban documentos importantes.', fr: 'La décision a été reportée, d’autant plus que des documents importants manquaient.', it: 'La decisione è stata rinviata, tanto più che mancavano documenti importanti.', pt: 'A decisão foi adiada, sobretudo porque faltavam documentos importantes.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['sofern', 'obgleich', 'indem'] },
  { id: 'b2s007', de: 'Die Löhne stiegen leicht, die Mieten hingegen sprunghaft.', en: 'Wages rose slightly; rents, by contrast, jumped sharply.', gloss: { es: 'Los salarios subieron ligeramente; los alquileres, en cambio, se dispararon.', fr: 'Les salaires ont légèrement augmenté ; les loyers, en revanche, ont bondi.', it: 'I salari sono saliti leggermente; gli affitti, invece, sono schizzati.', pt: 'Os salários subiram um pouco; os aluguéis, em contrapartida, dispararam.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['dennoch', 'folglich', 'gewissermaßen'] },
  { id: 'b2s008', de: 'Folglich muss die gesamte Strategie grundlegend überarbeitet werden.', en: 'Consequently, the entire strategy has to be fundamentally revised.', gloss: { es: 'Por consiguiente, toda la estrategia debe revisarse a fondo.', fr: 'Par conséquent, toute la stratégie doit être fondamentalement revue.', it: 'Di conseguenza, l’intera strategia deve essere rivista radicalmente.', pt: 'Por conseguinte, toda a estratégia precisa ser revista a fundo.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Insofern', 'Hingegen', 'Keineswegs'] },
  { id: 'b2s009', de: 'Man verbessert seine Aussprache, indem man täglich laut liest.', en: 'You improve your pronunciation by reading aloud every day.', gloss: { es: 'Uno mejora su pronunciación leyendo en voz alta todos los días.', fr: 'On améliore sa prononciation en lisant à voix haute chaque jour.', it: 'Si migliora la pronuncia leggendo ad alta voce ogni giorno.', pt: 'Melhora-se a pronúncia lendo em voz alta todos os dias.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['sofern', 'zumal', 'obgleich'] },
  { id: 'b2s010', de: 'Die Kosten sinken, wohingegen die Qualität konstant bleibt.', en: 'Costs are falling, whereas quality remains constant.', gloss: { es: 'Los costes bajan, mientras que la calidad se mantiene constante.', fr: 'Les coûts baissent, alors que la qualité reste constante.', it: 'I costi calano, mentre la qualità resta costante.', pt: 'Os custos caem, ao passo que a qualidade permanece constante.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['sofern', 'indem', 'zumal'] },
  { id: 'b2s011', de: 'Angesichts der neuen Zahlen wirkt die Prognose reichlich optimistisch.', en: 'In view of the new figures, the forecast looks rather optimistic.', gloss: { es: 'En vista de las nuevas cifras, la previsión parece bastante optimista.', fr: 'Compte tenu des nouveaux chiffres, la prévision paraît plutôt optimiste.', it: 'Alla luce dei nuovi dati, la previsione appare piuttosto ottimistica.', pt: 'Tendo em vista os novos números, a previsão parece bastante otimista.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Ungeachtet', 'Insofern', 'Folglich'] },
  { id: 'b2s012', de: 'Ungeachtet aller Bedenken wurde das Gesetz schließlich verabschiedet.', en: 'Notwithstanding all the concerns, the law was ultimately passed.', gloss: { es: 'A pesar de todas las reservas, la ley se aprobó finalmente.', fr: 'Malgré toutes les réserves, la loi a finalement été adoptée.', it: 'Nonostante tutte le perplessità, la legge è stata infine approvata.', pt: 'Apesar de todas as ressalvas, a lei acabou sendo aprovada.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Angesichts', 'Insofern', 'Dennoch'] },
  { id: 'b2s013', de: 'Wir bleiben bei dem Plan, es sei denn, es sprechen neue Erkenntnisse dagegen.', en: 'We are sticking with the plan, unless new findings speak against it.', gloss: { es: 'Nos mantenemos en el plan, a menos que nuevos hallazgos lo desaconsejen.', fr: 'Nous maintenons le plan, à moins que de nouvelles données ne s’y opposent.', it: 'Restiamo sul piano, a meno che nuovi dati non lo sconsiglino.', pt: 'Mantemos o plano, a menos que novas descobertas o desaconselhem.' }, level: 'B2', clozeIndex: 11, clozeDistractors: ['Vermutungen', 'Bedingungen', 'Verhandlungen'] },
  { id: 'b2s014', de: 'Das war kein Rückschritt, im Gegenteil, es war ein echter Durchbruch.', en: 'That was not a step backwards; on the contrary, it was a real breakthrough.', gloss: { es: 'No fue un retroceso; al contrario, fue un verdadero avance.', fr: 'Ce n’était pas un recul ; au contraire, c’était une véritable percée.', it: 'Non è stato un passo indietro; al contrario, è stata una vera svolta.', pt: 'Não foi um retrocesso; pelo contrário, foi um verdadeiro avanço.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['Gegensatz', 'Vergleich', 'Ergebnis'] },

  // ── Konjunktiv II, passive & speculation ──────────────────────────────
  { id: 'b2s015', de: 'Hätte man früher reagiert, wäre der Schaden geringer ausgefallen.', en: 'Had people reacted earlier, the damage would have been smaller.', gloss: { es: 'Si se hubiera reaccionado antes, el daño habría sido menor.', fr: 'Si l’on avait réagi plus tôt, les dégâts auraient été moindres.', it: 'Se si fosse reagito prima, il danno sarebbe stato minore.', pt: 'Se tivessem reagido antes, o dano teria sido menor.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Wäre', 'Könnte', 'Sollte'] },
  { id: 'b2s016', de: 'An deiner Stelle würde ich das Angebot schriftlich bestätigen lassen.', en: 'If I were you, I would have the offer confirmed in writing.', gloss: { es: 'Yo en tu lugar haría confirmar la oferta por escrito.', fr: 'À ta place, je ferais confirmer l’offre par écrit.', it: 'Al posto tuo farei confermare l’offerta per iscritto.', pt: 'No seu lugar, eu mandaria confirmar a oferta por escrito.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['könnte', 'müsste', 'dürfte'] },
  { id: 'b2s017', de: 'Wenn ich mehr Zeit hätte, würde ich den Text vollständig überarbeiten.', en: 'If I had more time, I would revise the text completely.', gloss: { es: 'Si tuviera más tiempo, revisaría el texto por completo.', fr: 'Si j’avais plus de temps, je réviserais le texte entièrement.', it: 'Se avessi più tempo, rivedrei il testo completamente.', pt: 'Se eu tivesse mais tempo, revisaria o texto por completo.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['wäre', 'könnte', 'müsste'] },
  { id: 'b2s018', de: 'Die Studie hätte längst veröffentlicht werden müssen.', en: 'The study should have been published long ago.', gloss: { es: 'El estudio debería haberse publicado hace mucho.', fr: 'L’étude aurait dû être publiée depuis longtemps.', it: 'Lo studio avrebbe dovuto essere pubblicato da tempo.', pt: 'O estudo deveria ter sido publicado há muito tempo.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['wäre', 'könnte', 'würde'] },
  { id: 'b2s019', de: 'Ohne diese Förderung wäre das Projekt vermutlich gescheitert.', en: 'Without this funding, the project would presumably have failed.', gloss: { es: 'Sin esta financiación, el proyecto probablemente habría fracasado.', fr: 'Sans cette subvention, le projet aurait vraisemblablement échoué.', it: 'Senza questo finanziamento, il progetto sarebbe presumibilmente fallito.', pt: 'Sem esse financiamento, o projeto presumivelmente teria fracassado.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['angeblich', 'keineswegs', 'bekanntlich'] },
  { id: 'b2s020', de: 'Es wäre ratsam, die Frist noch einmal zu verlängern.', en: 'It would be advisable to extend the deadline once more.', gloss: { es: 'Sería aconsejable prorrogar el plazo una vez más.', fr: 'Il serait judicieux de prolonger le délai encore une fois.', it: 'Sarebbe consigliabile prorogare il termine ancora una volta.', pt: 'Seria aconselhável prorrogar o prazo mais uma vez.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['Bedingung', 'Klage', 'Quelle'] },
  { id: 'b2s021', de: 'Über die Details wird erst nächste Woche entschieden.', en: 'The details will only be decided next week.', gloss: { es: 'Los detalles no se decidirán hasta la semana que viene.', fr: 'Les détails ne seront tranchés que la semaine prochaine.', it: 'I dettagli saranno decisi solo la settimana prossima.', pt: 'Os detalhes só serão decididos na semana que vem.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['ist', 'hat', 'war'] },
  { id: 'b2s022', de: 'Die Daten werden ausschließlich anonymisiert ausgewertet.', en: 'The data are analysed exclusively in anonymised form.', gloss: { es: 'Los datos se analizan exclusivamente de forma anonimizada.', fr: 'Les données sont analysées exclusivement de façon anonymisée.', it: 'I dati vengono analizzati esclusivamente in forma anonimizzata.', pt: 'Os dados são analisados exclusivamente de forma anonimizada.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['grundsätzlich', 'weitgehend', 'überwiegend'] },
  { id: 'b2s023', de: 'Man hätte den Konflikt durch frühe Gespräche vermeiden können.', en: 'The conflict could have been avoided through early talks.', gloss: { es: 'El conflicto se podría haber evitado con conversaciones tempranas.', fr: 'Le conflit aurait pu être évité par des discussions précoces.', it: 'Il conflitto si sarebbe potuto evitare con colloqui tempestivi.', pt: 'O conflito poderia ter sido evitado com conversas precoces.' }, level: 'B2', clozeIndex: 7, clozeDistractors: ['bewältigen', 'begründen', 'durchsetzen'] },
  { id: 'b2s024', de: 'Sollte sich die Lage ändern, informieren wir Sie umgehend.', en: 'Should the situation change, we will inform you immediately.', gloss: { es: 'Si la situación cambiara, le informaremos de inmediato.', fr: 'Si la situation venait à changer, nous vous informerons immédiatement.', it: 'Qualora la situazione cambiasse, la informeremo immediatamente.', pt: 'Caso a situação mude, informaremos o senhor imediatamente.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Hätte', 'Wäre', 'Müsste'] },
  { id: 'b2s025', de: 'Der Vertrag wird derzeit von der Rechtsabteilung geprüft.', en: 'The contract is currently being reviewed by the legal department.', gloss: { es: 'El contrato está siendo revisado actualmente por el departamento jurídico.', fr: 'Le contrat est actuellement examiné par le service juridique.', it: 'Il contratto è attualmente esaminato dall’ufficio legale.', pt: 'O contrato está sendo analisado no momento pelo departamento jurídico.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['ohnehin', 'keineswegs', 'bekanntlich'] },

  // ── work & negotiation ────────────────────────────────────────────────
  { id: 'b2s026', de: 'Beide Seiten mussten erhebliche Zugeständnisse machen.', en: 'Both sides had to make considerable concessions.', gloss: { es: 'Ambas partes tuvieron que hacer concesiones considerables.', fr: 'Les deux parties ont dû faire des concessions considérables.', it: 'Entrambe le parti hanno dovuto fare notevoli concessioni.', pt: 'Ambos os lados tiveram que fazer concessões consideráveis.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['Bedingungen', 'Vorbehalte', 'Verhandlungen'] },
  { id: 'b2s027', de: 'Wir sollten sämtliche Risiken in Ruhe abwägen, bevor wir zusagen.', en: 'We should calmly weigh up all the risks before we agree.', gloss: { es: 'Deberíamos sopesar con calma todos los riesgos antes de aceptar.', fr: 'Nous devrions peser tranquillement tous les risques avant d’accepter.', it: 'Dovremmo soppesare con calma tutti i rischi prima di accettare.', pt: 'Deveríamos ponderar com calma todos os riscos antes de aceitar.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['auswerten', 'durchsetzen', 'bewahren'] },
  { id: 'b2s028', de: 'Erst nach Stunden lenkte die Gegenseite endlich ein.', en: 'Only after hours did the other side finally give in.', gloss: { es: 'Solo después de horas cedió por fin la otra parte.', fr: 'Ce n’est qu’au bout de plusieurs heures que la partie adverse a enfin cédé.', it: 'Solo dopo ore la controparte ha finalmente ceduto.', pt: 'Só depois de horas a outra parte finalmente cedeu.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['scheiterte', 'zögerte', 'schwankte'] },
  { id: 'b2s029', de: 'Die Verhandlung scheiterte an einer einzigen Bedingung.', en: 'The negotiation failed over a single condition.', gloss: { es: 'La negociación fracasó por una sola condición.', fr: 'La négociation a échoué sur une seule condition.', it: 'La trattativa è fallita per una sola condizione.', pt: 'A negociação fracassou por causa de uma única condição.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['zögerte', 'schwankte', 'schrumpfte'] },
  { id: 'b2s030', de: 'Die Frist läuft am Monatsende unwiderruflich ab.', en: 'The deadline expires irrevocably at the end of the month.', gloss: { es: 'El plazo vence irrevocablemente a fin de mes.', fr: 'Le délai expire irrévocablement à la fin du mois.', it: 'Il termine scade irrevocabilmente a fine mese.', pt: 'O prazo vence irrevogavelmente no fim do mês.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Klage', 'Quelle', 'Steuer'] },
  { id: 'b2s031', de: 'Als Gegenleistung erwarten wir vollständige Transparenz.', en: 'In return, we expect complete transparency.', gloss: { es: 'Como contraprestación, esperamos total transparencia.', fr: 'En contrepartie, nous attendons une transparence totale.', it: 'Come corrispettivo, ci aspettiamo piena trasparenza.', pt: 'Como contrapartida, esperamos total transparência.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Bedingung', 'Rendite', 'Haftung'] },
  { id: 'b2s032', de: 'Sie konnte ihren Standpunkt im Gremium erfolgreich durchsetzen.', en: 'She successfully asserted her position in the committee.', gloss: { es: 'Logró imponer con éxito su postura en el comité.', fr: 'Elle a réussi à imposer son point de vue au sein du comité.', it: 'È riuscita a far valere la sua posizione in commissione.', pt: 'Ela conseguiu impor com sucesso seu ponto de vista no comitê.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['mühelos', 'vorsichtig', 'gelassen'] },
  { id: 'b2s033', de: 'Diese Zusage ist rechtlich noch nicht verbindlich.', en: 'This promise is not yet legally binding.', gloss: { es: 'Esta promesa todavía no es jurídicamente vinculante.', fr: 'Cette promesse n’est pas encore juridiquement contraignante.', it: 'Questa promessa non è ancora giuridicamente vincolante.', pt: 'Essa promessa ainda não é juridicamente vinculativa.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['persönlich', 'wirtschaftlich', 'öffentlich'] },
  { id: 'b2s034', de: 'Er kam uns bei den Konditionen deutlich entgegen.', en: 'He met us considerably halfway on the terms.', gloss: { es: 'Nos hizo concesiones notables en las condiciones.', fr: 'Il nous a fait des concessions notables sur les conditions.', it: 'Ci è venuto molto incontro sulle condizioni.', pt: 'Ele nos fez concessões notáveis nas condições.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['spürbar', 'kaum', 'grundsätzlich'] },

  // ── media & information ───────────────────────────────────────────────
  { id: 'b2s035', de: 'Die Berichterstattung war streckenweise auffällig voreingenommen.', en: 'The coverage was conspicuously biased in places.', gloss: { es: 'La cobertura informativa fue notoriamente sesgada en algunos tramos.', fr: 'La couverture médiatique était par endroits nettement partiale.', it: 'La copertura mediatica era a tratti visibilmente di parte.', pt: 'A cobertura jornalística foi, em certos trechos, visivelmente tendenciosa.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Inszenierung', 'Wahrnehmung', 'Forschung'] },
  { id: 'b2s036', de: 'Ohne belastbare Quellen verliert jede Behauptung ihre Glaubwürdigkeit.', en: 'Without solid sources, every claim loses its credibility.', gloss: { es: 'Sin fuentes sólidas, toda afirmación pierde su credibilidad.', fr: 'Sans sources solides, toute affirmation perd sa crédibilité.', it: 'Senza fonti solide, ogni affermazione perde la propria credibilità.', pt: 'Sem fontes sólidas, toda afirmação perde sua credibilidade.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['Schlagzeilen', 'Vorurteile', 'Gewohnheiten'] },
  { id: 'b2s037', de: 'Die Schlagzeile verzerrt den eigentlichen Sachverhalt erheblich.', en: 'The headline considerably distorts the actual facts.', gloss: { es: 'El titular distorsiona considerablemente los hechos reales.', fr: 'Le gros titre déforme considérablement les faits réels.', it: 'Il titolo distorce notevolmente i fatti reali.', pt: 'A manchete distorce consideravelmente os fatos reais.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['bewahrt', 'hinterfragt', 'verbreitet'] },
  { id: 'b2s038', de: 'Gerüchte verbreiten sich online schneller als jede Richtigstellung.', en: 'Rumours spread online faster than any correction.', gloss: { es: 'Los rumores se difunden en internet más rápido que cualquier rectificación.', fr: 'Les rumeurs se répandent en ligne plus vite que toute rectification.', it: 'Le voci si diffondono online più in fretta di qualsiasi rettifica.', pt: 'Os boatos se espalham na internet mais rápido do que qualquer retificação.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['verzerren', 'hinterfragen', 'bewahren'] },
  { id: 'b2s039', de: 'Wir sollten solche Zahlen grundsätzlich kritisch hinterfragen.', en: 'We should always question such figures critically.', gloss: { es: 'Deberíamos cuestionar siempre críticamente esas cifras.', fr: 'Nous devrions toujours remettre ces chiffres en question de manière critique.', it: 'Dovremmo sempre mettere criticamente in discussione tali cifre.', pt: 'Deveríamos sempre questionar criticamente esses números.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['wohlwollend', 'gelassen', 'nüchtern'] },
  { id: 'b2s040', de: 'Sie hat monatelang zu diesem heiklen Thema recherchiert.', en: 'She researched this delicate topic for months.', gloss: { es: 'Investigó durante meses este tema delicado.', fr: 'Elle a enquêté pendant des mois sur ce sujet délicat.', it: 'Ha indagato per mesi su questo tema delicato.', pt: 'Ela apurou durante meses esse tema delicado.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['jahrelang', 'stundenlang', 'wochenlang'] },
  { id: 'b2s041', de: 'Die Meinungsfreiheit gehört zum Kern jeder offenen Gesellschaft.', en: 'Freedom of expression is at the core of any open society.', gloss: { es: 'La libertad de expresión forma parte del núcleo de toda sociedad abierta.', fr: 'La liberté d’expression est au cœur de toute société ouverte.', it: 'La libertà di espressione è al centro di ogni società aperta.', pt: 'A liberdade de expressão faz parte do núcleo de qualquer sociedade aberta.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Privatsphäre', 'Vielfalt', 'Transparenz'] },

  // ── science & environment ─────────────────────────────────────────────
  { id: 'b2s042', de: 'Die Hypothese ließ sich bislang nicht eindeutig nachweisen.', en: 'The hypothesis could not be clearly proven so far.', gloss: { es: 'Hasta ahora la hipótesis no ha podido demostrarse con claridad.', fr: 'Jusqu’à présent, l’hypothèse n’a pas pu être clairement prouvée.', it: 'Finora l’ipotesi non è stata dimostrata in modo chiaro.', pt: 'Até agora a hipótese não pôde ser comprovada de forma clara.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Forschung', 'Wirkung', 'Belastung'] },
  { id: 'b2s043', de: 'Zwischen beiden Phänomenen besteht kein kausaler Zusammenhang.', en: 'There is no causal connection between the two phenomena.', gloss: { es: 'Entre ambos fenómenos no existe ninguna relación causal.', fr: 'Il n’existe aucun lien de causalité entre les deux phénomènes.', it: 'Tra i due fenomeni non sussiste alcun nesso causale.', pt: 'Entre os dois fenômenos não existe nenhuma relação causal.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['zeitlicher', 'sachlicher', 'messbarer'] },
  { id: 'b2s044', de: 'Die Auswirkungen des Eingriffs zeigen sich erst nach Jahren.', en: 'The effects of the intervention only show after years.', gloss: { es: 'Los efectos de la intervención solo se manifiestan al cabo de años.', fr: 'Les répercussions de l’intervention n’apparaissent qu’après des années.', it: 'Le ripercussioni dell’intervento si manifestano solo dopo anni.', pt: 'As repercussões da intervenção só aparecem depois de anos.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Bedingungen', 'Gewohnheiten', 'Zugeständnisse'] },
  { id: 'b2s045', de: 'Die Messwerte schwanken je nach Tageszeit erheblich.', en: 'The readings fluctuate considerably depending on the time of day.', gloss: { es: 'Los valores medidos oscilan considerablemente según la hora del día.', fr: 'Les valeurs mesurées fluctuent considérablement selon l’heure de la journée.', it: 'I valori misurati oscillano notevolmente a seconda dell’ora del giorno.', pt: 'Os valores medidos oscilam consideravelmente conforme a hora do dia.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['schrumpfen', 'scheitern', 'zögern'] },
  { id: 'b2s046', de: 'Das Verfahren setzt eine äußerst sorgfältige Vorbereitung voraus.', en: 'The procedure requires extremely careful preparation.', gloss: { es: 'El procedimiento presupone una preparación sumamente cuidadosa.', fr: 'La procédure présuppose une préparation extrêmement soignée.', it: 'La procedura presuppone una preparazione estremamente accurata.', pt: 'O procedimento pressupõe uma preparação extremamente cuidadosa.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['erlaubt', 'verhindert', 'ersetzt'] },
  { id: 'b2s047', de: 'Der Artenschutz genießt in diesem Gebiet höchste Priorität.', en: 'The conservation of species has the highest priority in this area.', gloss: { es: 'La protección de las especies tiene la máxima prioridad en esta zona.', fr: 'La protection des espèces a la priorité absolue dans cette zone.', it: 'La tutela delle specie ha la massima priorità in questa zona.', pt: 'A proteção das espécies tem prioridade máxima nessa região.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Datenschutz', 'Wohnraum', 'Nahverkehr'] },
  { id: 'b2s048', de: 'Die Wahrscheinlichkeit eines Fehlers liegt bei unter einem Prozent.', en: 'The probability of an error is below one percent.', gloss: { es: 'La probabilidad de un error es inferior al uno por ciento.', fr: 'La probabilité d’une erreur est inférieure à un pour cent.', it: 'La probabilità di un errore è inferiore all’uno per cento.', pt: 'A probabilidade de um erro é inferior a um por cento.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Glaubwürdigkeit', 'Zugehörigkeit', 'Verantwortlichkeit'] },

  // ── law & rights ──────────────────────────────────────────────────────
  { id: 'b2s049', de: 'Das Urteil wurde in zweiter Instanz überraschend aufgehoben.', en: 'The verdict was surprisingly overturned on appeal.', gloss: { es: 'La sentencia fue anulada sorprendentemente en segunda instancia.', fr: 'Le jugement a été annulé de manière surprenante en appel.', it: 'La sentenza è stata sorprendentemente annullata in appello.', pt: 'A sentença foi surpreendentemente anulada em segunda instância.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Verfahren', 'Verhalten', 'Zugeständnis'] },
  { id: 'b2s050', de: 'Wer gegen diese Auflagen verstößt, haftet persönlich.', en: 'Whoever breaches these conditions is personally liable.', gloss: { es: 'Quien infrinja estas condiciones responde personalmente.', fr: 'Quiconque enfreint ces conditions en répond personnellement.', it: 'Chi viola queste condizioni ne risponde personalmente.', pt: 'Quem infringir essas condições responde pessoalmente.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['abwägt', 'zögert', 'einlenkt'] },
  { id: 'b2s051', de: 'Ein Anspruch auf Entschädigung besteht in diesem Fall nicht.', en: 'There is no entitlement to compensation in this case.', gloss: { es: 'En este caso no existe derecho a indemnización.', fr: 'Dans ce cas, il n’existe aucun droit à indemnisation.', it: 'In questo caso non sussiste alcun diritto al risarcimento.', pt: 'Nesse caso não existe direito a indenização.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Vorbehalt', 'Verstoß', 'Nachweis'] },
  { id: 'b2s052', de: 'Die Verarbeitung erfordert die ausdrückliche Einwilligung der Betroffenen.', en: 'The processing requires the explicit consent of the people affected.', gloss: { es: 'El tratamiento requiere el consentimiento expreso de los afectados.', fr: 'Le traitement exige le consentement explicite des personnes concernées.', it: 'Il trattamento richiede il consenso esplicito degli interessati.', pt: 'O tratamento exige o consentimento expresso dos envolvidos.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['Rechenschaft', 'Haftung', 'Klage'] },
  { id: 'b2s053', de: 'Die Behörde muss über ihre Ausgaben Rechenschaft ablegen.', en: 'The authority has to account for its spending.', gloss: { es: 'La administración debe rendir cuentas de sus gastos.', fr: 'L’administration doit rendre des comptes sur ses dépenses.', it: 'L’ente deve rendere conto delle proprie spese.', pt: 'O órgão deve prestar contas de seus gastos.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['Haftung', 'Einwilligung', 'Verfassung'] },
  { id: 'b2s054', de: 'Eine solche Wartezeit ist für Betroffene kaum zumutbar.', en: 'Such a waiting time is hardly reasonable for those affected.', gloss: { es: 'Un tiempo de espera así es apenas exigible a los afectados.', fr: 'Un tel délai d’attente est difficilement exigible des personnes concernées.', it: 'Un simile tempo di attesa è difficilmente esigibile per gli interessati.', pt: 'Um tempo de espera assim é dificilmente exigível dos envolvidos.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['Prägung', 'Klage', 'Gattung'] },

  // ── economics ─────────────────────────────────────────────────────────
  { id: 'b2s055', de: 'Die Nachfrage ist im letzten Quartal spürbar eingebrochen.', en: 'Demand collapsed noticeably in the last quarter.', gloss: { es: 'La demanda se desplomó notablemente en el último trimestre.', fr: 'La demande s’est effondrée sensiblement au dernier trimestre.', it: 'La domanda è crollata sensibilmente nell’ultimo trimestre.', pt: 'A demanda despencou sensivelmente no último trimestre.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Rendite', 'Konkurrenz', 'Investition'] },
  { id: 'b2s056', de: 'Der Umsatz wuchs, die Rendite schrumpfte jedoch deutlich.', en: 'Revenue grew, but the return shrank considerably.', gloss: { es: 'La facturación creció, pero la rentabilidad se redujo notablemente.', fr: 'Le chiffre d’affaires a augmenté, mais le rendement a nettement diminué.', it: 'Il fatturato è cresciuto, ma il rendimento si è ridotto sensibilmente.', pt: 'O faturamento cresceu, mas o rendimento encolheu de forma notável.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['schwankte', 'scheiterte', 'zögerte'] },
  { id: 'b2s057', de: 'Solche Investitionen rentieren sich meist erst nach Jahren.', en: 'Such investments usually only pay off after years.', gloss: { es: 'Tales inversiones suelen ser rentables solo al cabo de años.', fr: 'De tels investissements ne deviennent rentables qu’après des années.', it: 'Tali investimenti diventano redditizi di solito solo dopo anni.', pt: 'Tais investimentos costumam ser rentáveis apenas depois de anos.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Verhandlungen', 'Gewohnheiten', 'Aufführungen'] },
  { id: 'b2s058', de: 'Wegen der hohen Schulden bleibt der finanzielle Spielraum gering.', en: 'Because of the high debts, the financial room for manoeuvre remains small.', gloss: { es: 'Debido a las elevadas deudas, el margen financiero sigue siendo escaso.', fr: 'En raison de l’endettement élevé, la marge de manœuvre financière reste faible.', it: 'A causa dell’elevato indebitamento, il margine finanziario resta ridotto.', pt: 'Por causa das altas dívidas, a margem financeira continua pequena.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['Steuern', 'Gebühren', 'Renditen'] },
  { id: 'b2s059', de: 'Die Konkurrenz reagierte prompt mit deutlich niedrigeren Preisen.', en: 'The competition responded promptly with considerably lower prices.', gloss: { es: 'La competencia reaccionó de inmediato con precios notablemente más bajos.', fr: 'La concurrence a réagi promptement avec des prix nettement plus bas.', it: 'La concorrenza ha reagito prontamente con prezzi decisamente più bassi.', pt: 'A concorrência reagiu prontamente com preços bem mais baixos.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Nachfrage', 'Verfassung', 'Belastung'] },

  // ── psychology ────────────────────────────────────────────────────────
  { id: 'b2s060', de: 'Unsere Wahrnehmung täuscht uns häufiger, als uns lieb ist.', en: 'Our perception deceives us more often than we would like.', gloss: { es: 'Nuestra percepción nos engaña más a menudo de lo que quisiéramos.', fr: 'Notre perception nous trompe plus souvent qu’on ne le voudrait.', it: 'La nostra percezione ci inganna più spesso di quanto vorremmo.', pt: 'Nossa percepção nos engana com mais frequência do que gostaríamos.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Gewohnheit', 'Belastung', 'Herkunft'] },
  { id: 'b2s061', de: 'Alte Gewohnheiten lassen sich nur schwer verdrängen.', en: 'Old habits are hard to push aside.', gloss: { es: 'Los viejos hábitos son difíciles de desplazar.', fr: 'Les vieilles habitudes sont difficiles à évincer.', it: 'Le vecchie abitudini sono difficili da rimuovere.', pt: 'Velhos hábitos são difíceis de reprimir.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Vorurteile', 'Bedingungen', 'Zugeständnisse'] },
  { id: 'b2s062', de: 'Nach dem schwierigen Gespräch wirkte sie erstaunlich gelassen.', en: 'After the difficult conversation, she seemed remarkably composed.', gloss: { es: 'Tras la difícil conversación, parecía asombrosamente serena.', fr: 'Après cette conversation difficile, elle semblait étonnamment sereine.', it: 'Dopo la difficile conversazione, sembrava sorprendentemente serena.', pt: 'Depois da conversa difícil, ela parecia surpreendentemente serena.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['bemerkenswert', 'überraschend', 'ausgesprochen'] },
  { id: 'b2s063', de: 'Sie zögerte lange, bevor sie ihre Zweifel offen äußerte.', en: 'She hesitated for a long time before openly voicing her doubts.', gloss: { es: 'Vaciló mucho tiempo antes de expresar abiertamente sus dudas.', fr: 'Elle a longtemps hésité avant d’exprimer ouvertement ses doutes.', it: 'Ha esitato a lungo prima di esprimere apertamente i suoi dubbi.', pt: 'Ela hesitou muito tempo antes de expressar abertamente suas dúvidas.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['schwankte', 'scheiterte', 'lenkte'] },
  { id: 'b2s064', de: 'Die ständige Belastung fordert irgendwann ihren Tribut.', en: 'The constant strain eventually takes its toll.', gloss: { es: 'La carga constante acaba pasando factura.', fr: 'La charge constante finit par se payer.', it: 'Il carico costante prima o poi presenta il conto.', pt: 'A carga constante mais cedo ou mais tarde cobra seu preço.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['Wahrnehmung', 'Gewohnheit', 'Zugehörigkeit'] },

  // ── technology & ethics ───────────────────────────────────────────────
  { id: 'b2s065', de: 'Der Algorithmus entscheidet, ohne dass die Kriterien nachvollziehbar wären.', en: 'The algorithm decides without the criteria being traceable.', gloss: { es: 'El algoritmo decide sin que los criterios sean rastreables.', fr: 'L’algorithme décide sans que les critères soient traçables.', it: 'L’algoritmo decide senza che i criteri siano tracciabili.', pt: 'O algoritmo decide sem que os critérios sejam rastreáveis.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Datenschutz', 'Nachweis', 'Umsatz'] },
  { id: 'b2s066', de: 'Ob eine solche Überwachung zumutbar ist, bleibt umstritten.', en: 'Whether such surveillance is reasonable remains disputed.', gloss: { es: 'Si tal vigilancia es exigible sigue siendo discutido.', fr: 'La question de savoir si une telle surveillance est acceptable reste contestée.', it: 'Se una tale sorveglianza sia accettabile resta controverso.', pt: 'Se tal vigilância é aceitável continua sendo controverso.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['Automatisierung', 'Privatsphäre', 'Transparenz'] },
  { id: 'b2s067', de: 'Für Schäden durch fehlerhafte Software haftet allein der Anbieter.', en: 'The provider alone is liable for damage caused by faulty software.', gloss: { es: 'De los daños causados por software defectuoso responde únicamente el proveedor.', fr: 'Le fournisseur est seul responsable des dommages causés par un logiciel défectueux.', it: 'Dei danni causati da software difettoso risponde soltanto il fornitore.', pt: 'Pelos danos causados por software defeituoso responde apenas o fornecedor.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['bürgt', 'zögert', 'entscheidet'] },
  { id: 'b2s068', de: 'Solche Systeme sind besonders anfällig für verzerrte Trainingsdaten.', en: 'Such systems are particularly prone to distorted training data.', gloss: { es: 'Tales sistemas son especialmente propensos a datos de entrenamiento sesgados.', fr: 'De tels systèmes sont particulièrement vulnérables aux données d’entraînement biaisées.', it: 'Tali sistemi sono particolarmente vulnerabili a dati di addestramento distorti.', pt: 'Tais sistemas são especialmente propensos a dados de treinamento distorcidos.' }, level: 'B2', clozeIndex: 4, clozeDistractors: ['dankbar', 'zuständig', 'bekannt'] },

  // ── urban life, arts & collocations ───────────────────────────────────
  { id: 'b2s069', de: 'Bezahlbarer Wohnraum ist in vielen Städten praktisch verschwunden.', en: 'Affordable housing has practically disappeared in many cities.', gloss: { es: 'La vivienda asequible ha desaparecido prácticamente en muchas ciudades.', fr: 'Le logement abordable a pratiquement disparu dans de nombreuses villes.', it: 'Gli alloggi accessibili sono praticamente scomparsi in molte città.', pt: 'A moradia acessível praticamente desapareceu em muitas cidades.' }, level: 'B2', clozeIndex: 1, clozeDistractors: ['Nahverkehr', 'Leerstand', 'Beifall'] },
  { id: 'b2s070', de: 'Die Inszenierung war eigenwillig, im Großen und Ganzen aber gelungen.', en: 'The staging was idiosyncratic, but by and large successful.', gloss: { es: 'La puesta en escena era peculiar, pero en términos generales lograda.', fr: 'La mise en scène était singulière, mais dans l’ensemble réussie.', it: 'La messa in scena era originale, ma nel complesso riuscita.', pt: 'A encenação era peculiar, mas de modo geral bem-sucedida.' }, level: 'B2', clozeIndex: 3, clozeDistractors: ['anspruchsvoll', 'nachvollziehbar', 'gelassen'] },
  { id: 'b2s071', de: 'Dass die Kosten steigen würden, lag von Anfang an auf der Hand.', en: 'That the costs would rise was obvious from the start.', gloss: { es: 'Que los costes subirían era evidente desde el principio.', fr: 'Que les coûts augmenteraient allait de soi dès le départ.', it: 'Che i costi sarebbero saliti era lampante fin dall’inizio.', pt: 'Que os custos subiriam era evidente desde o início.' }, level: 'B2', clozeIndex: 5, clozeDistractors: ['blieb', 'kam', 'stand'] },
  { id: 'b2s072', de: 'Dieses Detail fällt bei der Bewertung kaum ins Gewicht.', en: 'This detail hardly carries any weight in the assessment.', gloss: { es: 'Este detalle apenas tiene peso en la valoración.', fr: 'Ce détail ne pèse guère dans l’évaluation.', it: 'Questo dettaglio incide appena nella valutazione.', pt: 'Esse detalhe quase não pesa na avaliação.' }, level: 'B2', clozeIndex: 2, clozeDistractors: ['zählt', 'wirkt', 'gilt'] },
  { id: 'b2s073', de: 'Wirtschaftliches Wachstum und Klimaschutz müssen Hand in Hand gehen.', en: 'Economic growth and climate protection have to go hand in hand.', gloss: { es: 'El crecimiento económico y la protección del clima deben ir de la mano.', fr: 'La croissance économique et la protection du climat doivent aller de pair.', it: 'La crescita economica e la tutela del clima devono andare di pari passo.', pt: 'O crescimento econômico e a proteção do clima precisam andar lado a lado.' }, level: 'B2', clozeIndex: 0, clozeDistractors: ['Nachhaltiges', 'Kulturelles', 'Städtisches'] },
  { id: 'b2s074', de: 'Ich möchte diesen Punkt noch einmal zur Sprache bringen.', en: 'I would like to bring this point up once more.', gloss: { es: 'Quisiera plantear este punto una vez más.', fr: 'Je voudrais aborder ce point encore une fois.', it: 'Vorrei sollevare di nuovo questo punto.', pt: 'Gostaria de trazer esse ponto à tona mais uma vez.' }, level: 'B2', clozeIndex: 7, clozeDistractors: ['Prüfung', 'Bewertung', 'Abstimmung'] },
  { id: 'b2s075', de: 'Nach einem Jahr wollen wir gemeinsam Bilanz ziehen.', en: 'After a year we want to take stock together.', gloss: { es: 'Al cabo de un año queremos hacer balance juntos.', fr: 'Au bout d’un an, nous voulons dresser un bilan ensemble.', it: 'Dopo un anno vogliamo fare un bilancio insieme.', pt: 'Depois de um ano queremos fazer um balanço juntos.' }, level: 'B2', clozeIndex: 6, clozeDistractors: ['Rendite', 'Frist', 'Wirkung'] },
];
