"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.B1_VOCAB = void 0;
// Spanish (Peninsular (Spain)) B1 vocabulary. The `de` field holds the Spanish text
// (see the note in content/german/types.ts). Nouns include the article (el/la).
//
// B1 is where the learner stops labelling the world and starts arguing about
// it: opinions and how to defend them, abstract nouns, work and career, media,
// environment, social issues, and the discourse connectors that hold a real
// paragraph together. Nothing here repeats A1 (greetings, numbers, family,
// basic food, core verbs) or A2 (past tense basics, travel, shopping, health,
// routine, clothing, weather).
//
// `gloss` carries the other UI locales — de / fr / it / pt. English lives in
// `en` and is the guaranteed fallback; Spanish itself is never glossed.
//
// Regionalisms are avoided: where Spain and Latin America split (el enfado /
// el enojo, suspender / reprobar) we teach the form that reads as neutral on
// both sides of the Atlantic.
exports.B1_VOCAB = [
    // ── opinion & argument ────────────────────────────────────────────────
    { id: 'es3v001', de: 'la opinión', en: ['the opinion'], gloss: { de: ['die Meinung'], fr: ['l’opinion'], it: ['l’opinione'], pt: ['a opinião'] }, pos: 'noun', level: 'B1', category: 'opinion' },
    { id: 'es3v002', de: 'el punto de vista', en: ['the point of view'], gloss: { de: ['der Standpunkt'], fr: ['le point de vue'], it: ['il punto di vista'], pt: ['o ponto de vista'] }, pos: 'noun', level: 'B1', category: 'opinion' },
    { id: 'es3v003', de: 'el argumento', en: ['the argument', 'the reasoning'], gloss: { de: ['das Argument'], fr: ['l’argument'], it: ['l’argomento'], pt: ['o argumento'] }, pos: 'noun', level: 'B1', category: 'opinion' },
    { id: 'es3v004', de: 'la ventaja', en: ['the advantage'], gloss: { de: ['der Vorteil'], fr: ['l’avantage'], it: ['il vantaggio'], pt: ['a vantagem'] }, pos: 'noun', level: 'B1', category: 'opinion' },
    { id: 'es3v005', de: 'la desventaja', en: ['the disadvantage', 'the drawback'], gloss: { de: ['der Nachteil'], fr: ['l’inconvénient'], it: ['lo svantaggio'], pt: ['a desvantagem'] }, pos: 'noun', level: 'B1', category: 'opinion' },
    { id: 'es3v006', de: 'estar de acuerdo', en: ['to agree'], gloss: { de: ['einverstanden sein'], fr: ['être d’accord'], it: ['essere d’accordo'], pt: ['concordar'] }, pos: 'phrase', level: 'B1', category: 'opinion' },
    { id: 'es3v007', de: 'convencer', en: ['to convince'], gloss: { de: ['überzeugen'], fr: ['convaincre'], it: ['convincere'], pt: ['convencer'] }, pos: 'verb', level: 'B1', category: 'opinion' },
    { id: 'es3v008', de: 'reconocer', en: ['to admit', 'to acknowledge'], gloss: { de: ['zugeben'], fr: ['reconnaître'], it: ['riconoscere'], pt: ['reconhecer'] }, pos: 'verb', level: 'B1', category: 'opinion' },
    { id: 'es3v009', de: 'en mi opinión', en: ['in my opinion'], gloss: { de: ['meiner Meinung nach'], fr: ['à mon avis'], it: ['secondo me'], pt: ['na minha opinião'] }, pos: 'phrase', level: 'B1', category: 'opinion' },
    { id: 'es3v010', de: 'debatir', en: ['to debate'], gloss: { de: ['debattieren'], fr: ['débattre'], it: ['dibattere'], pt: ['debater'] }, pos: 'verb', level: 'B1', category: 'opinion' },
    // ── work & career ─────────────────────────────────────────────────────
    { id: 'es3v011', de: 'el puesto', en: ['the position', 'the post'], gloss: { de: ['die Stelle'], fr: ['le poste'], it: ['la posizione'], pt: ['o cargo'] }, pos: 'noun', level: 'B1', category: 'work' },
    { id: 'es3v012', de: 'la remuneración', en: ['the remuneration', 'the compensation'], gloss: { de: ['die Vergütung'], fr: ['la rémunération'], it: ['la retribuzione'], pt: ['a remuneração'] }, pos: 'noun', level: 'B1', category: 'work' },
    { id: 'es3v013', de: 'la entrevista de trabajo', en: ['the job interview'], gloss: { de: ['das Vorstellungsgespräch'], fr: ['l’entretien d’embauche'], it: ['il colloquio di lavoro'], pt: ['a entrevista de emprego'] }, pos: 'noun', level: 'B1', category: 'work' },
    { id: 'es3v014', de: 'el contrato', en: ['the contract'], gloss: { de: ['der Vertrag'], fr: ['le contrat'], it: ['il contratto'], pt: ['o contrato'] }, pos: 'noun', level: 'B1', category: 'work' },
    { id: 'es3v015', de: 'el rendimiento', en: ['the performance', 'the output'], gloss: { de: ['die Leistung'], fr: ['la performance'], it: ['il rendimento'], pt: ['o desempenho'] }, pos: 'noun', level: 'B1', category: 'work' },
    { id: 'es3v016', de: 'el ascenso', en: ['the promotion'], gloss: { de: ['die Beförderung'], fr: ['la promotion'], it: ['la promozione'], pt: ['a promoção'] }, pos: 'noun', level: 'B1', category: 'work' },
    { id: 'es3v017', de: 'contratar', en: ['to hire'], gloss: { de: ['einstellen'], fr: ['embaucher'], it: ['assumere'], pt: ['contratar'] }, pos: 'verb', level: 'B1', category: 'work' },
    { id: 'es3v018', de: 'despedir', en: ['to fire', 'to make redundant'], gloss: { de: ['entlassen'], fr: ['licencier'], it: ['licenziare'], pt: ['demitir'] }, pos: 'verb', level: 'B1', category: 'work' },
    { id: 'es3v019', de: 'la carrera', en: ['the career'], gloss: { de: ['die Laufbahn'], fr: ['la carrière'], it: ['la carriera'], pt: ['a carreira'] }, pos: 'noun', level: 'B1', category: 'work' },
    { id: 'es3v020', de: 'el plazo', en: ['the deadline', 'the time limit'], gloss: { de: ['die Frist'], fr: ['le délai'], it: ['la scadenza'], pt: ['o prazo'] }, pos: 'noun', level: 'B1', category: 'work' },
    // ── society & politics ────────────────────────────────────────────────
    { id: 'es3v021', de: 'la sociedad', en: ['the society'], gloss: { de: ['die Gesellschaft'], fr: ['la société'], it: ['la società'], pt: ['a sociedade'] }, pos: 'noun', level: 'B1', category: 'society' },
    { id: 'es3v022', de: 'el gobierno', en: ['the government'], gloss: { de: ['die Regierung'], fr: ['le gouvernement'], it: ['il governo'], pt: ['o governo'] }, pos: 'noun', level: 'B1', category: 'society' },
    { id: 'es3v023', de: 'la ley', en: ['the law'], gloss: { de: ['das Gesetz'], fr: ['la loi'], it: ['la legge'], pt: ['a lei'] }, pos: 'noun', level: 'B1', category: 'society' },
    { id: 'es3v024', de: 'el derecho', en: ['the right'], gloss: { de: ['das Recht'], fr: ['le droit'], it: ['il diritto'], pt: ['o direito'] }, pos: 'noun', level: 'B1', category: 'society' },
    { id: 'es3v025', de: 'la igualdad', en: ['the equality'], gloss: { de: ['die Gleichheit'], fr: ['l’égalité'], it: ['l’uguaglianza'], pt: ['a igualdade'] }, pos: 'noun', level: 'B1', category: 'society' },
    { id: 'es3v026', de: 'la pobreza', en: ['the poverty'], gloss: { de: ['die Armut'], fr: ['la pauvreté'], it: ['la povertà'], pt: ['a pobreza'] }, pos: 'noun', level: 'B1', category: 'society' },
    { id: 'es3v027', de: 'el desempleo', en: ['the unemployment'], gloss: { de: ['die Arbeitslosigkeit'], fr: ['le chômage'], it: ['la disoccupazione'], pt: ['o desemprego'] }, pos: 'noun', level: 'B1', category: 'society' },
    { id: 'es3v028', de: 'la población', en: ['the population'], gloss: { de: ['die Bevölkerung'], fr: ['la population'], it: ['la popolazione'], pt: ['a população'] }, pos: 'noun', level: 'B1', category: 'society' },
    { id: 'es3v029', de: 'el ciudadano', en: ['the citizen'], gloss: { de: ['der Bürger'], fr: ['le citoyen'], it: ['il cittadino'], pt: ['o cidadão'] }, pos: 'noun', level: 'B1', category: 'society' },
    { id: 'es3v030', de: 'votar', en: ['to vote'], gloss: { de: ['wählen'], fr: ['voter'], it: ['votare'], pt: ['votar'] }, pos: 'verb', level: 'B1', category: 'society' },
    // ── media & news ──────────────────────────────────────────────────────
    { id: 'es3v031', de: 'las noticias', en: ['the news'], gloss: { de: ['die Nachrichten'], fr: ['les informations'], it: ['le notizie'], pt: ['as notícias'] }, pos: 'noun', level: 'B1', category: 'media' },
    { id: 'es3v032', de: 'el periódico', en: ['the newspaper'], gloss: { de: ['die Zeitung'], fr: ['le journal'], it: ['il giornale'], pt: ['o jornal'] }, pos: 'noun', level: 'B1', category: 'media' },
    { id: 'es3v033', de: 'el periodista', en: ['the journalist'], gloss: { de: ['der Journalist'], fr: ['le journaliste'], it: ['il giornalista'], pt: ['o jornalista'] }, pos: 'noun', level: 'B1', category: 'media' },
    { id: 'es3v034', de: 'el titular', en: ['the headline'], gloss: { de: ['die Schlagzeile'], fr: ['le titre'], it: ['il titolo'], pt: ['a manchete'] }, pos: 'noun', level: 'B1', category: 'media' },
    { id: 'es3v035', de: 'la publicidad', en: ['the advertising'], gloss: { de: ['die Werbung'], fr: ['la publicité'], it: ['la pubblicità'], pt: ['a publicidade'] }, pos: 'noun', level: 'B1', category: 'media' },
    { id: 'es3v036', de: 'la red social', en: ['the social network'], gloss: { de: ['das soziale Netzwerk'], fr: ['le réseau social'], it: ['il social network'], pt: ['a rede social'] }, pos: 'noun', level: 'B1', category: 'media' },
    { id: 'es3v037', de: 'la fuente', en: ['the source'], gloss: { de: ['die Quelle'], fr: ['la source'], it: ['la fonte'], pt: ['a fonte'] }, pos: 'noun', level: 'B1', category: 'media' },
    { id: 'es3v038', de: 'el rumor', en: ['the rumour'], gloss: { de: ['das Gerücht'], fr: ['la rumeur'], it: ['la diceria'], pt: ['o boato'] }, pos: 'noun', level: 'B1', category: 'media' },
    { id: 'es3v039', de: 'informar', en: ['to report', 'to inform'], gloss: { de: ['berichten'], fr: ['informer'], it: ['informare'], pt: ['informar'] }, pos: 'verb', level: 'B1', category: 'media' },
    { id: 'es3v040', de: 'difundir', en: ['to spread', 'to broadcast'], gloss: { de: ['verbreiten'], fr: ['diffuser'], it: ['diffondere'], pt: ['divulgar'] }, pos: 'verb', level: 'B1', category: 'media' },
    // ── environment ───────────────────────────────────────────────────────
    { id: 'es3v041', de: 'el medio ambiente', en: ['the environment'], gloss: { de: ['die Umwelt'], fr: ['l’environnement'], it: ['l’ambiente'], pt: ['o meio ambiente'] }, pos: 'noun', level: 'B1', category: 'environment' },
    { id: 'es3v042', de: 'el cambio climático', en: ['the climate change'], gloss: { de: ['der Klimawandel'], fr: ['le changement climatique'], it: ['il cambiamento climatico'], pt: ['a mudança climática'] }, pos: 'noun', level: 'B1', category: 'environment' },
    { id: 'es3v043', de: 'la contaminación', en: ['the pollution'], gloss: { de: ['die Verschmutzung'], fr: ['la pollution'], it: ['l’inquinamento'], pt: ['a poluição'] }, pos: 'noun', level: 'B1', category: 'environment' },
    { id: 'es3v044', de: 'los residuos', en: ['the waste'], gloss: { de: ['die Abfälle'], fr: ['les déchets'], it: ['i rifiuti'], pt: ['o lixo'] }, pos: 'noun', level: 'B1', category: 'environment' },
    { id: 'es3v045', de: 'el reciclaje', en: ['the recycling'], gloss: { de: ['das Recycling'], fr: ['le recyclage'], it: ['il riciclaggio'], pt: ['a reciclagem'] }, pos: 'noun', level: 'B1', category: 'environment' },
    { id: 'es3v046', de: 'la sequía', en: ['the drought'], gloss: { de: ['die Dürre'], fr: ['la sécheresse'], it: ['la siccità'], pt: ['a seca'] }, pos: 'noun', level: 'B1', category: 'environment' },
    { id: 'es3v047', de: 'la energía renovable', en: ['the renewable energy'], gloss: { de: ['die erneuerbare Energie'], fr: ['l’énergie renouvelable'], it: ['l’energia rinnovabile'], pt: ['a energia renovável'] }, pos: 'noun', level: 'B1', category: 'environment' },
    { id: 'es3v048', de: 'sostenible', en: ['sustainable'], gloss: { de: ['nachhaltig'], fr: ['durable'], it: ['sostenibile'], pt: ['sustentável'] }, pos: 'adj', level: 'B1', category: 'environment' },
    { id: 'es3v049', de: 'contaminar', en: ['to pollute'], gloss: { de: ['verschmutzen'], fr: ['polluer'], it: ['inquinare'], pt: ['poluir'] }, pos: 'verb', level: 'B1', category: 'environment' },
    { id: 'es3v050', de: 'ahorrar', en: ['to save (resources, money)'], gloss: { de: ['sparen'], fr: ['économiser'], it: ['risparmiare'], pt: ['economizar'] }, pos: 'verb', level: 'B1', category: 'environment' },
    // ── abstract nouns ────────────────────────────────────────────────────
    { id: 'es3v051', de: 'la libertad', en: ['the freedom'], gloss: { de: ['die Freiheit'], fr: ['la liberté'], it: ['la libertà'], pt: ['a liberdade'] }, pos: 'noun', level: 'B1', category: 'abstract' },
    { id: 'es3v052', de: 'el desarrollo', en: ['the development'], gloss: { de: ['die Entwicklung'], fr: ['le développement'], it: ['lo sviluppo'], pt: ['o desenvolvimento'] }, pos: 'noun', level: 'B1', category: 'abstract' },
    { id: 'es3v053', de: 'el compromiso', en: ['the commitment'], gloss: { de: ['die Verpflichtung'], fr: ['l’engagement'], it: ['l’impegno'], pt: ['o compromisso'] }, pos: 'noun', level: 'B1', category: 'abstract' },
    { id: 'es3v054', de: 'el esfuerzo', en: ['the effort'], gloss: { de: ['die Anstrengung'], fr: ['l’effort'], it: ['lo sforzo'], pt: ['o esforço'] }, pos: 'noun', level: 'B1', category: 'abstract' },
    { id: 'es3v055', de: 'la confianza', en: ['the trust', 'the confidence'], gloss: { de: ['das Vertrauen'], fr: ['la confiance'], it: ['la fiducia'], pt: ['a confiança'] }, pos: 'noun', level: 'B1', category: 'abstract' },
    { id: 'es3v056', de: 'el riesgo', en: ['the risk'], gloss: { de: ['das Risiko'], fr: ['le risque'], it: ['il rischio'], pt: ['o risco'] }, pos: 'noun', level: 'B1', category: 'abstract' },
    { id: 'es3v057', de: 'la costumbre', en: ['the habit', 'the custom'], gloss: { de: ['die Gewohnheit'], fr: ['l’habitude'], it: ['l’abitudine'], pt: ['o costume'] }, pos: 'noun', level: 'B1', category: 'abstract' },
    { id: 'es3v058', de: 'el objetivo', en: ['the goal', 'the objective'], gloss: { de: ['das Ziel'], fr: ['l’objectif'], it: ['l’obiettivo'], pt: ['o objetivo'] }, pos: 'noun', level: 'B1', category: 'abstract' },
    { id: 'es3v059', de: 'la realidad', en: ['the reality'], gloss: { de: ['die Wirklichkeit'], fr: ['la réalité'], it: ['la realtà'], pt: ['a realidade'] }, pos: 'noun', level: 'B1', category: 'abstract' },
    { id: 'es3v060', de: 'el sentido', en: ['the meaning', 'the sense'], gloss: { de: ['der Sinn'], fr: ['le sens'], it: ['il senso'], pt: ['o sentido'] }, pos: 'noun', level: 'B1', category: 'abstract' },
    // ── connectors & discourse ────────────────────────────────────────────
    { id: 'es3v061', de: 'sin embargo', en: ['however', 'nevertheless'], gloss: { de: ['jedoch'], fr: ['cependant'], it: ['tuttavia'], pt: ['no entanto'] }, pos: 'adv', level: 'B1', category: 'connectors' },
    { id: 'es3v062', de: 'por lo tanto', en: ['therefore'], gloss: { de: ['folglich'], fr: ['par conséquent'], it: ['pertanto'], pt: ['portanto'] }, pos: 'adv', level: 'B1', category: 'connectors' },
    { id: 'es3v063', de: 'aunque', en: ['although', 'even if'], gloss: { de: ['obwohl'], fr: ['bien que'], it: ['anche se'], pt: ['embora'] }, pos: 'conj', level: 'B1', category: 'connectors' },
    { id: 'es3v064', de: 'a pesar de', en: ['despite', 'in spite of'], gloss: { de: ['trotz'], fr: ['malgré'], it: ['nonostante'], pt: ['apesar de'] }, pos: 'prep', level: 'B1', category: 'connectors' },
    { id: 'es3v065', de: 'además', en: ['besides', 'moreover'], gloss: { de: ['außerdem'], fr: ['de plus'], it: ['inoltre'], pt: ['além disso'] }, pos: 'adv', level: 'B1', category: 'connectors' },
    { id: 'es3v066', de: 'en cambio', en: ['on the other hand', 'whereas'], gloss: { de: ['hingegen'], fr: ['en revanche'], it: ['invece'], pt: ['por outro lado'] }, pos: 'adv', level: 'B1', category: 'connectors' },
    { id: 'es3v067', de: 'es decir', en: ['that is to say', 'in other words'], gloss: { de: ['das heißt'], fr: ['c’est-à-dire'], it: ['cioè'], pt: ['ou seja'] }, pos: 'phrase', level: 'B1', category: 'connectors' },
    { id: 'es3v068', de: 'mientras que', en: ['whereas', 'while'], gloss: { de: ['während'], fr: ['tandis que'], it: ['mentre'], pt: ['enquanto'] }, pos: 'conj', level: 'B1', category: 'connectors' },
    { id: 'es3v069', de: 'siempre que', en: ['as long as', 'provided that'], gloss: { de: ['sofern'], fr: ['pourvu que'], it: ['purché'], pt: ['desde que'] }, pos: 'conj', level: 'B1', category: 'connectors' },
    { id: 'es3v070', de: 'para que', en: ['so that'], gloss: { de: ['damit'], fr: ['pour que'], it: ['affinché'], pt: ['para que'] }, pos: 'conj', level: 'B1', category: 'connectors' },
    // ── emotions & inner life ─────────────────────────────────────────────
    { id: 'es3v071', de: 'el orgullo', en: ['the pride'], gloss: { de: ['der Stolz'], fr: ['la fierté'], it: ['l’orgoglio'], pt: ['o orgulho'] }, pos: 'noun', level: 'B1', category: 'emotions' },
    { id: 'es3v072', de: 'la vergüenza', en: ['the shame', 'the embarrassment'], gloss: { de: ['die Scham'], fr: ['la honte'], it: ['la vergogna'], pt: ['a vergonha'] }, pos: 'noun', level: 'B1', category: 'emotions' },
    { id: 'es3v073', de: 'el enfado', en: ['the anger', 'the annoyance'], gloss: { de: ['der Ärger'], fr: ['la colère'], it: ['la rabbia'], pt: ['a raiva'] }, pos: 'noun', level: 'B1', category: 'emotions' },
    { id: 'es3v074', de: 'la tristeza', en: ['the sadness'], gloss: { de: ['die Traurigkeit'], fr: ['la tristesse'], it: ['la tristezza'], pt: ['a tristeza'] }, pos: 'noun', level: 'B1', category: 'emotions' },
    { id: 'es3v075', de: 'la preocupación', en: ['the worry', 'the concern'], gloss: { de: ['die Sorge'], fr: ['l’inquiétude'], it: ['la preoccupazione'], pt: ['a preocupação'] }, pos: 'noun', level: 'B1', category: 'emotions' },
    { id: 'es3v076', de: 'la sorpresa', en: ['the surprise'], gloss: { de: ['die Überraschung'], fr: ['la surprise'], it: ['la sorpresa'], pt: ['a surpresa'] }, pos: 'noun', level: 'B1', category: 'emotions' },
    { id: 'es3v077', de: 'el temor', en: ['the apprehension', 'the fear'], gloss: { de: ['das Misstrauen'], fr: ['la méfiance'], it: ['la diffidenza'], pt: ['o receio'] }, pos: 'noun', level: 'B1', category: 'emotions' },
    { id: 'es3v078', de: 'atreverse', en: ['to dare'], gloss: { de: ['sich trauen'], fr: ['oser'], it: ['osare'], pt: ['atrever-se'] }, pos: 'verb', level: 'B1', category: 'emotions' },
    { id: 'es3v079', de: 'arrepentirse', en: ['to regret'], gloss: { de: ['bereuen'], fr: ['regretter'], it: ['pentirsi'], pt: ['arrepender-se'] }, pos: 'verb', level: 'B1', category: 'emotions' },
    { id: 'es3v080', de: 'emocionante', en: ['exciting', 'moving'], gloss: { de: ['aufregend'], fr: ['passionnant'], it: ['emozionante'], pt: ['emocionante'] }, pos: 'adj', level: 'B1', category: 'emotions' },
    // ── education & learning ──────────────────────────────────────────────
    { id: 'es3v081', de: 'la formación', en: ['the training', 'the education'], gloss: { de: ['die Ausbildung'], fr: ['la formation'], it: ['la formazione'], pt: ['a formação'] }, pos: 'noun', level: 'B1', category: 'education' },
    { id: 'es3v082', de: 'la carrera universitaria', en: ['the university degree course'], gloss: { de: ['das Studium'], fr: ['les études universitaires'], it: ['il corso di laurea'], pt: ['o curso universitário'] }, pos: 'noun', level: 'B1', category: 'education' },
    { id: 'es3v083', de: 'la beca', en: ['the scholarship', 'the grant'], gloss: { de: ['das Stipendium'], fr: ['la bourse'], it: ['la borsa di studio'], pt: ['a bolsa de estudos'] }, pos: 'noun', level: 'B1', category: 'education' },
    { id: 'es3v084', de: 'el título', en: ['the degree', 'the qualification'], gloss: { de: ['der Abschluss'], fr: ['le diplôme'], it: ['il titolo di studio'], pt: ['o diploma'] }, pos: 'noun', level: 'B1', category: 'education' },
    { id: 'es3v085', de: 'la asignatura', en: ['the subject (school)'], gloss: { de: ['das Fach'], fr: ['la matière'], it: ['la materia'], pt: ['a disciplina'] }, pos: 'noun', level: 'B1', category: 'education' },
    { id: 'es3v086', de: 'el conocimiento', en: ['the knowledge'], gloss: { de: ['das Wissen'], fr: ['la connaissance'], it: ['la conoscenza'], pt: ['o conhecimento'] }, pos: 'noun', level: 'B1', category: 'education' },
    { id: 'es3v087', de: 'el aprendizaje', en: ['the learning'], gloss: { de: ['das Lernen'], fr: ['l’apprentissage'], it: ['l’apprendimento'], pt: ['a aprendizagem'] }, pos: 'noun', level: 'B1', category: 'education' },
    { id: 'es3v088', de: 'aprobar', en: ['to pass (an exam)'], gloss: { de: ['bestehen'], fr: ['réussir'], it: ['superare'], pt: ['ser aprovado'] }, pos: 'verb', level: 'B1', category: 'education' },
    { id: 'es3v089', de: 'suspender', en: ['to fail (an exam)'], gloss: { de: ['durchfallen'], fr: ['échouer'], it: ['essere bocciato'], pt: ['reprovar'] }, pos: 'verb', level: 'B1', category: 'education' },
    { id: 'es3v090', de: 'investigar', en: ['to research', 'to investigate'], gloss: { de: ['erforschen'], fr: ['faire des recherches'], it: ['fare ricerca'], pt: ['pesquisar'] }, pos: 'verb', level: 'B1', category: 'education' },
    // ── adjectives ────────────────────────────────────────────────────────
    { id: 'es3v091', de: 'imprescindible', en: ['essential', 'indispensable'], gloss: { de: ['unverzichtbar'], fr: ['indispensable'], it: ['indispensabile'], pt: ['imprescindível'] }, pos: 'adj', level: 'B1', category: 'adjectives' },
    { id: 'es3v092', de: 'capaz', en: ['capable', 'able'], gloss: { de: ['fähig'], fr: ['capable'], it: ['capace'], pt: ['capaz'] }, pos: 'adj', level: 'B1', category: 'adjectives' },
    { id: 'es3v093', de: 'eficaz', en: ['effective'], gloss: { de: ['wirksam'], fr: ['efficace'], it: ['efficace'], pt: ['eficaz'] }, pos: 'adj', level: 'B1', category: 'adjectives' },
    { id: 'es3v094', de: 'injusto', en: ['unfair', 'unjust'], gloss: { de: ['ungerecht'], fr: ['injuste'], it: ['ingiusto'], pt: ['injusto'] }, pos: 'adj', level: 'B1', category: 'adjectives' },
    { id: 'es3v095', de: 'exigente', en: ['demanding'], gloss: { de: ['anspruchsvoll'], fr: ['exigeant'], it: ['esigente'], pt: ['exigente'] }, pos: 'adj', level: 'B1', category: 'adjectives' },
    { id: 'es3v096', de: 'dispuesto', en: ['willing', 'ready'], gloss: { de: ['bereit'], fr: ['prêt'], it: ['disposto'], pt: ['disposto'] }, pos: 'adj', level: 'B1', category: 'adjectives' },
    { id: 'es3v097', de: 'sorprendente', en: ['surprising'], gloss: { de: ['überraschend'], fr: ['surprenant'], it: ['sorprendente'], pt: ['surpreendente'] }, pos: 'adj', level: 'B1', category: 'adjectives' },
    { id: 'es3v098', de: 'escaso', en: ['scarce', 'limited'], gloss: { de: ['knapp'], fr: ['rare'], it: ['scarso'], pt: ['escasso'] }, pos: 'adj', level: 'B1', category: 'adjectives' },
    { id: 'es3v099', de: 'cotidiano', en: ['everyday', 'daily'], gloss: { de: ['alltäglich'], fr: ['quotidien'], it: ['quotidiano'], pt: ['cotidiano'] }, pos: 'adj', level: 'B1', category: 'adjectives' },
    { id: 'es3v100', de: 'arriesgado', en: ['risky'], gloss: { de: ['riskant'], fr: ['risqué'], it: ['rischioso'], pt: ['arriscado'] }, pos: 'adj', level: 'B1', category: 'adjectives' },
    // ── economy & money ───────────────────────────────────────────────────
    { id: 'es3v101', de: 'la economía', en: ['the economy'], gloss: { de: ['die Wirtschaft'], fr: ['l’économie'], it: ['l’economia'], pt: ['a economia'] }, pos: 'noun', level: 'B1', category: 'economy' },
    { id: 'es3v102', de: 'la crisis', en: ['the crisis'], gloss: { de: ['die Krise'], fr: ['la crise'], it: ['la crisi'], pt: ['a crise'] }, pos: 'noun', level: 'B1', category: 'economy' },
    { id: 'es3v103', de: 'el impuesto', en: ['the tax'], gloss: { de: ['die Steuer'], fr: ['l’impôt'], it: ['l’imposta'], pt: ['o imposto'] }, pos: 'noun', level: 'B1', category: 'economy' },
    { id: 'es3v104', de: 'el préstamo', en: ['the loan'], gloss: { de: ['der Kredit'], fr: ['le prêt'], it: ['il prestito'], pt: ['o empréstimo'] }, pos: 'noun', level: 'B1', category: 'economy' },
    { id: 'es3v105', de: 'la inversión', en: ['the investment'], gloss: { de: ['die Investition'], fr: ['l’investissement'], it: ['l’investimento'], pt: ['o investimento'] }, pos: 'noun', level: 'B1', category: 'economy' },
    { id: 'es3v106', de: 'el alquiler', en: ['the rent'], gloss: { de: ['die Miete'], fr: ['le loyer'], it: ['l’affitto'], pt: ['o aluguel'] }, pos: 'noun', level: 'B1', category: 'economy' },
    { id: 'es3v107', de: 'la deuda', en: ['the debt'], gloss: { de: ['die Schulden'], fr: ['la dette'], it: ['il debito'], pt: ['a dívida'] }, pos: 'noun', level: 'B1', category: 'economy' },
    { id: 'es3v108', de: 'el consumo', en: ['the consumption'], gloss: { de: ['der Konsum'], fr: ['la consommation'], it: ['il consumo'], pt: ['o consumo'] }, pos: 'noun', level: 'B1', category: 'economy' },
    { id: 'es3v109', de: 'invertir', en: ['to invest'], gloss: { de: ['investieren'], fr: ['investir'], it: ['investire'], pt: ['investir'] }, pos: 'verb', level: 'B1', category: 'economy' },
    { id: 'es3v110', de: 'gastar', en: ['to spend'], gloss: { de: ['ausgeben'], fr: ['dépenser'], it: ['spendere'], pt: ['gastar'] }, pos: 'verb', level: 'B1', category: 'economy' },
    // ── health & wellbeing ────────────────────────────────────────────────
    { id: 'es3v111', de: 'la salud', en: ['the health'], gloss: { de: ['die Gesundheit'], fr: ['la santé'], it: ['la salute'], pt: ['a saúde'] }, pos: 'noun', level: 'B1', category: 'wellbeing' },
    { id: 'es3v112', de: 'el tratamiento', en: ['the treatment'], gloss: { de: ['die Behandlung'], fr: ['le traitement'], it: ['il trattamento'], pt: ['o tratamento'] }, pos: 'noun', level: 'B1', category: 'wellbeing' },
    { id: 'es3v113', de: 'la enfermedad', en: ['the illness', 'the disease'], gloss: { de: ['die Krankheit'], fr: ['la maladie'], it: ['la malattia'], pt: ['a doença'] }, pos: 'noun', level: 'B1', category: 'wellbeing' },
    { id: 'es3v114', de: 'el estrés', en: ['the stress'], gloss: { de: ['der Stress'], fr: ['le stress'], it: ['lo stress'], pt: ['o estresse'] }, pos: 'noun', level: 'B1', category: 'wellbeing' },
    { id: 'es3v115', de: 'el sueño', en: ['the sleep'], gloss: { de: ['der Schlaf'], fr: ['le sommeil'], it: ['il sonno'], pt: ['o sono'] }, pos: 'noun', level: 'B1', category: 'wellbeing' },
    { id: 'es3v116', de: 'la alimentación', en: ['the diet', 'the nutrition'], gloss: { de: ['die Ernährung'], fr: ['l’alimentation'], it: ['l’alimentazione'], pt: ['a alimentação'] }, pos: 'noun', level: 'B1', category: 'wellbeing' },
    { id: 'es3v117', de: 'el bienestar', en: ['the wellbeing'], gloss: { de: ['das Wohlbefinden'], fr: ['le bien-être'], it: ['il benessere'], pt: ['o bem-estar'] }, pos: 'noun', level: 'B1', category: 'wellbeing' },
    { id: 'es3v118', de: 'prevenir', en: ['to prevent'], gloss: { de: ['vorbeugen'], fr: ['prévenir'], it: ['prevenire'], pt: ['prevenir'] }, pos: 'verb', level: 'B1', category: 'wellbeing' },
    { id: 'es3v119', de: 'padecer', en: ['to suffer from'], gloss: { de: ['leiden an'], fr: ['souffrir de'], it: ['soffrire di'], pt: ['sofrer de'] }, pos: 'verb', level: 'B1', category: 'wellbeing' },
    { id: 'es3v120', de: 'sano', en: ['healthy'], gloss: { de: ['gesund'], fr: ['sain'], it: ['sano'], pt: ['saudável'] }, pos: 'adj', level: 'B1', category: 'wellbeing' },
    // ── technology & science ──────────────────────────────────────────────
    { id: 'es3v121', de: 'la investigación', en: ['the research'], gloss: { de: ['die Forschung'], fr: ['la recherche'], it: ['la ricerca'], pt: ['a pesquisa'] }, pos: 'noun', level: 'B1', category: 'technology' },
    { id: 'es3v122', de: 'el avance', en: ['the advance', 'the breakthrough'], gloss: { de: ['der Fortschritt'], fr: ['l’avancée'], it: ['il progresso'], pt: ['o avanço'] }, pos: 'noun', level: 'B1', category: 'technology' },
    { id: 'es3v123', de: 'la herramienta', en: ['the tool'], gloss: { de: ['das Werkzeug'], fr: ['l’outil'], it: ['lo strumento'], pt: ['a ferramenta'] }, pos: 'noun', level: 'B1', category: 'technology' },
    { id: 'es3v124', de: 'el dato', en: ['the piece of data'], gloss: { de: ['die Angabe'], fr: ['la donnée'], it: ['il dato'], pt: ['o dado'] }, pos: 'noun', level: 'B1', category: 'technology' },
    { id: 'es3v125', de: 'la privacidad', en: ['the privacy'], gloss: { de: ['die Privatsphäre'], fr: ['la vie privée'], it: ['la riservatezza'], pt: ['a privacidade'] }, pos: 'noun', level: 'B1', category: 'technology' },
    { id: 'es3v126', de: 'la inteligencia artificial', en: ['the artificial intelligence'], gloss: { de: ['die künstliche Intelligenz'], fr: ['l’intelligence artificielle'], it: ['l’intelligenza artificiale'], pt: ['a inteligência artificial'] }, pos: 'noun', level: 'B1', category: 'technology' },
    { id: 'es3v127', de: 'el usuario', en: ['the user'], gloss: { de: ['der Nutzer'], fr: ['l’utilisateur'], it: ['l’utente'], pt: ['o usuário'] }, pos: 'noun', level: 'B1', category: 'technology' },
    { id: 'es3v128', de: 'el dispositivo', en: ['the device'], gloss: { de: ['das Gerät'], fr: ['l’appareil'], it: ['il dispositivo'], pt: ['o dispositivo'] }, pos: 'noun', level: 'B1', category: 'technology' },
    { id: 'es3v129', de: 'desarrollar', en: ['to develop'], gloss: { de: ['entwickeln'], fr: ['développer'], it: ['sviluppare'], pt: ['desenvolver'] }, pos: 'verb', level: 'B1', category: 'technology' },
    { id: 'es3v130', de: 'sustituir', en: ['to replace'], gloss: { de: ['ersetzen'], fr: ['remplacer'], it: ['sostituire'], pt: ['substituir'] }, pos: 'verb', level: 'B1', category: 'technology' },
    // ── culture & the arts ────────────────────────────────────────────────
    { id: 'es3v131', de: 'la obra', en: ['the work (of art)'], gloss: { de: ['das Werk'], fr: ['l’œuvre'], it: ['l’opera'], pt: ['a obra'] }, pos: 'noun', level: 'B1', category: 'culture' },
    { id: 'es3v132', de: 'el escritor', en: ['the writer'], gloss: { de: ['der Schriftsteller'], fr: ['l’écrivain'], it: ['lo scrittore'], pt: ['o escritor'] }, pos: 'noun', level: 'B1', category: 'culture' },
    { id: 'es3v133', de: 'la novela', en: ['the novel'], gloss: { de: ['der Roman'], fr: ['le roman'], it: ['il romanzo'], pt: ['o romance'] }, pos: 'noun', level: 'B1', category: 'culture' },
    { id: 'es3v134', de: 'el guion', en: ['the screenplay', 'the script'], gloss: { de: ['das Drehbuch'], fr: ['le scénario'], it: ['la sceneggiatura'], pt: ['o roteiro'] }, pos: 'noun', level: 'B1', category: 'culture' },
    { id: 'es3v135', de: 'el público', en: ['the audience'], gloss: { de: ['das Publikum'], fr: ['le public'], it: ['il pubblico'], pt: ['o público'] }, pos: 'noun', level: 'B1', category: 'culture' },
    { id: 'es3v136', de: 'la exposición', en: ['the exhibition'], gloss: { de: ['die Ausstellung'], fr: ['l’exposition'], it: ['la mostra'], pt: ['a exposição'] }, pos: 'noun', level: 'B1', category: 'culture' },
    { id: 'es3v137', de: 'el patrimonio', en: ['the heritage'], gloss: { de: ['das Erbe'], fr: ['le patrimoine'], it: ['il patrimonio'], pt: ['o patrimônio'] }, pos: 'noun', level: 'B1', category: 'culture' },
    { id: 'es3v138', de: 'la crítica', en: ['the review', 'the criticism'], gloss: { de: ['die Kritik'], fr: ['la critique'], it: ['la critica'], pt: ['a crítica'] }, pos: 'noun', level: 'B1', category: 'culture' },
    { id: 'es3v139', de: 'estrenar', en: ['to premiere', 'to release'], gloss: { de: ['uraufführen'], fr: ['sortir'], it: ['presentare in anteprima'], pt: ['estrear'] }, pos: 'verb', level: 'B1', category: 'culture' },
    { id: 'es3v140', de: 'interpretar', en: ['to interpret', 'to perform'], gloss: { de: ['interpretieren'], fr: ['interpréter'], it: ['interpretare'], pt: ['interpretar'] }, pos: 'verb', level: 'B1', category: 'culture' },
    // ── verbs for argument & change ───────────────────────────────────────
    { id: 'es3v141', de: 'suponer', en: ['to assume', 'to suppose'], gloss: { de: ['annehmen'], fr: ['supposer'], it: ['supporre'], pt: ['supor'] }, pos: 'verb', level: 'B1', category: 'verbs' },
    { id: 'es3v142', de: 'plantear', en: ['to raise (an issue)', 'to put forward'], gloss: { de: ['aufwerfen'], fr: ['soulever'], it: ['porre'], pt: ['levantar'] }, pos: 'verb', level: 'B1', category: 'verbs' },
    { id: 'es3v143', de: 'lograr', en: ['to achieve', 'to manage to'], gloss: { de: ['erreichen'], fr: ['réussir'], it: ['riuscire'], pt: ['conseguir'] }, pos: 'verb', level: 'B1', category: 'verbs' },
    { id: 'es3v144', de: 'exigir', en: ['to demand'], gloss: { de: ['fordern'], fr: ['exiger'], it: ['esigere'], pt: ['exigir'] }, pos: 'verb', level: 'B1', category: 'verbs' },
    { id: 'es3v145', de: 'impedir', en: ['to prevent', 'to stop'], gloss: { de: ['verhindern'], fr: ['empêcher'], it: ['impedire'], pt: ['impedir'] }, pos: 'verb', level: 'B1', category: 'verbs' },
    { id: 'es3v146', de: 'fomentar', en: ['to promote', 'to encourage'], gloss: { de: ['fördern'], fr: ['encourager'], it: ['promuovere'], pt: ['fomentar'] }, pos: 'verb', level: 'B1', category: 'verbs' },
    { id: 'es3v147', de: 'destacar', en: ['to highlight', 'to stand out'], gloss: { de: ['hervorheben'], fr: ['souligner'], it: ['sottolineare'], pt: ['destacar'] }, pos: 'verb', level: 'B1', category: 'verbs' },
    { id: 'es3v148', de: 'surgir', en: ['to arise', 'to emerge'], gloss: { de: ['entstehen'], fr: ['surgir'], it: ['sorgere'], pt: ['surgir'] }, pos: 'verb', level: 'B1', category: 'verbs' },
    { id: 'es3v149', de: 'rechazar', en: ['to reject', 'to turn down'], gloss: { de: ['ablehnen'], fr: ['refuser'], it: ['rifiutare'], pt: ['rejeitar'] }, pos: 'verb', level: 'B1', category: 'verbs' },
    { id: 'es3v150', de: 'apoyar', en: ['to support'], gloss: { de: ['unterstützen'], fr: ['soutenir'], it: ['sostenere'], pt: ['apoiar'] }, pos: 'verb', level: 'B1', category: 'verbs' },
    // ── nuance & discourse markers ────────────────────────────────────────
    { id: 'es3v151', de: 'por cierto', en: ['by the way'], gloss: { de: ['übrigens'], fr: ['au fait'], it: ['a proposito'], pt: ['a propósito'] }, pos: 'phrase', level: 'B1', category: 'nuance' },
    { id: 'es3v152', de: 'en realidad', en: ['actually', 'in fact'], gloss: { de: ['eigentlich'], fr: ['en réalité'], it: ['in realtà'], pt: ['na verdade'] }, pos: 'phrase', level: 'B1', category: 'nuance' },
    { id: 'es3v153', de: 'de hecho', en: ['in fact', 'indeed'], gloss: { de: ['tatsächlich'], fr: ['en fait'], it: ['in effetti'], pt: ['de fato'] }, pos: 'phrase', level: 'B1', category: 'nuance' },
    { id: 'es3v154', de: 'por supuesto', en: ['of course'], gloss: { de: ['selbstverständlich'], fr: ['bien sûr'], it: ['certamente'], pt: ['com certeza'] }, pos: 'phrase', level: 'B1', category: 'nuance' },
    { id: 'es3v155', de: 'al fin y al cabo', en: ['after all'], gloss: { de: ['letzten Endes'], fr: ['après tout'], it: ['in fin dei conti'], pt: ['afinal de contas'] }, pos: 'phrase', level: 'B1', category: 'nuance' },
    { id: 'es3v156', de: 'de todos modos', en: ['anyway', 'in any case'], gloss: { de: ['jedenfalls'], fr: ['de toute façon'], it: ['comunque'], pt: ['de qualquer forma'] }, pos: 'phrase', level: 'B1', category: 'nuance' },
    { id: 'es3v157', de: 'a menos que', en: ['unless'], gloss: { de: ['es sei denn'], fr: ['à moins que'], it: ['a meno che'], pt: ['a menos que'] }, pos: 'conj', level: 'B1', category: 'nuance' },
    { id: 'es3v158', de: 'en cuanto', en: ['as soon as'], gloss: { de: ['sobald'], fr: ['dès que'], it: ['non appena'], pt: ['assim que'] }, pos: 'conj', level: 'B1', category: 'nuance' },
    { id: 'es3v159', de: 'puesto que', en: ['since', 'given that'], gloss: { de: ['da'], fr: ['puisque'], it: ['poiché'], pt: ['uma vez que'] }, pos: 'conj', level: 'B1', category: 'nuance' },
    { id: 'es3v160', de: 'ni siquiera', en: ['not even'], gloss: { de: ['nicht einmal'], fr: ['même pas'], it: ['nemmeno'], pt: ['nem sequer'] }, pos: 'adv', level: 'B1', category: 'nuance' },
];
