import { LegalShell } from '../legal';

export const metadata = {
  title: 'Terms of Use',
  description: 'LangToll terms: a language-learning app that gates distracting apps behind practice. Subscriptions, app-blocking, AI content, and acceptable use.',
  alternates: { canonical: '/terms' },
};

// LangToll terms of use — language-learning positioning, Screen Time/app-blocking
// disclaimer, AI-content limitations, subscriptions (what free and Plus each include,
// kept in step with lib/plans.ts in the app), acceptable use.
export default function TermsOfUsePage() {
  return (
    <LegalShell title="Terms of Use" updated="September 7, 2026">
      <h2>1. What LangToll is</h2>
      <p>
        LangToll is a language-learning app. It uses Apple’s Screen Time (Family Controls) framework to
        shield the distracting apps you choose until you complete short practice sessions, which unlock
        a window of phone time before the shield returns. LangToll is an independent product and is not
        affiliated with, endorsed by, or sponsored by Apple.
      </p>

      <h2>2. App blocking is best-effort — don’t rely on it for anything critical</h2>
      <p>
        To lock apps, LangToll needs your permission to use Screen Time, which you grant on your device
        and can withdraw at any time in iOS Settings. You choose which apps to shield, and you can
        change or clear that selection whenever you like. Shielding is a productivity aid provided “as
        is”: it depends on iOS behaving as expected and may be bypassed, delayed, or interrupted.
      </p>
      <ul>
        <li>Do not shield apps you may need for safety, health, work, or emergencies.</li>
        <li>LangToll never blocks phone calls, Messages, or your ability to reach emergency services.</li>
        <li>You are responsible for the apps you choose to lock and for unlocking them when you need them.</li>
      </ul>

      <h2>3. AI-generated content</h2>
      <p>
        Optional topic packs are generated by artificial intelligence from the topic you enter. AI
        output can contain errors, awkward phrasing, or inaccurate translations, and is not a substitute
        for a qualified teacher or authoritative reference. Use your judgment, especially before relying
        on any phrase in a real-world situation.
      </p>

      <h2>4. Subscriptions &amp; auto-renewal</h2>
      <p>
        The lock and the complete A1 course of every language are free, with one app behind the gate,
        multiple-choice practice, and the pass countdown on your Lock Screen. LangToll also offers an
        optional auto-renewing subscription, <strong>LangToll Plus</strong>, available as a weekly,
        monthly or yearly plan. Plus adds the A2 to B2 levels, vocabulary on the Dynamic Island and
        translations on the Lock Screen, unlimited apps and whole categories behind the gate, any fare,
        strict mode, the spoken voice, the full set of exercise types, and AI topic packs. The exact
        title, length, and price of each plan — in your local currency — and whether it includes a free
        trial are shown in the app before you purchase.
      </p>
      <p>
        Payment will be charged to your Apple ID account at confirmation of purchase. The subscription
        automatically renews unless auto-renew is turned off at least 24 hours before the end of the
        current period. Your account will be charged for renewal — at the price of the plan you
        selected — within 24 hours before the end of the current period. You can manage your
        subscription and turn off auto-renewal in your App Store account settings at any time after
        purchase, and you can restore a previous purchase from the in-app paywall. Any unused portion of
        a free trial period, if offered, is forfeited when you purchase a subscription to that product,
        where applicable. When a subscription ends, features that belong to Plus return to the free
        tier; your progress, your wallet and your settings are kept, and come back in full if you
        resubscribe. Subscriptions are sold by Apple and managed for us by RevenueCat.
      </p>

      <h2>5. Acceptable use</h2>
      <p>
        The AI generation feature is provided solely for creating language-learning content. Attempting
        to misuse it for unrelated purposes, to extract harmful content, or to disrupt or overload the
        service may result in limits or termination of access to AI features.
      </p>

      <h2>6. Your data</h2>
      <p>
        Your learning data lives on your device and is yours. See the <a href="/privacy">Privacy Policy</a>{' '}
        for exactly what is and isn’t processed by our systems. You are responsible for backups of your
        device; deleting the app deletes your data.
      </p>

      <h2>7. Intellectual property</h2>
      <p>
        The app, its design, its character, and its bundled learning content and audio are provided for
        your personal, non-commercial use within the app experience.
      </p>

      <h2>8. Changes, termination &amp; governing law</h2>
      <p>
        We may update these terms; material changes will be shown in the app before they take effect.
        Continued use after changes means acceptance. These terms are governed by the laws of Germany,
        without prejudice to any mandatory consumer-protection rights you have where you live. If any
        provision is found unenforceable, the remainder stays in effect. LangToll is operated from
        Germany. Contact: <a href="mailto:support@langtoll.app">support@langtoll.app</a>.
      </p>
    </LegalShell>
  );
}
