import type { SentenceItem } from '@/content/german/types';

// Brazilian Portuguese A2 sentences. `de` holds the Portuguese text. clozeIndex
// targets the load-bearing word (never the article), and clozeDistractors are
// same-class words that would be grammatical but wrong — so the exercise tests
// meaning, not pattern-matching on word shape.
//
// A2 leans on the pretérito perfeito (peguei, acordei, perdeu, começou) and on
// slightly longer clauses than A1's present-tense one-liners.
//
// `gloss` carries the non-English UI locales; see a2-vocab.ts for the rule.

export const A2_SENTENCES: SentenceItem[] = [
  { id: 'pt2s001', de: 'Ontem eu peguei o ônibus para o trabalho.', en: 'Yesterday I took the bus to work.', gloss: { de: 'Gestern habe ich den Bus zur Arbeit genommen.', es: 'Ayer tomé el autobús al trabajo.', fr: 'Hier j’ai pris le bus pour aller au travail.', it: 'Ieri ho preso l’autobus per andare al lavoro.' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['perdi', 'comprei', 'encontrei'] },
  { id: 'pt2s002', de: 'Eu acordei muito cedo hoje de manhã.', en: 'I woke up very early this morning.', gloss: { de: 'Ich bin heute Morgen sehr früh aufgewacht.', es: 'Me desperté muy temprano esta mañana.', fr: 'Je me suis réveillé très tôt ce matin.', it: 'Mi sono svegliato molto presto stamattina.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['tarde', 'nunca', 'sempre'] },
  { id: 'pt2s003', de: 'Nós tomamos café da manhã no hotel.', en: 'We had breakfast at the hotel.', gloss: { de: 'Wir haben im Hotel gefrühstückt.', es: 'Desayunamos en el hotel.', fr: 'Nous avons pris le petit-déjeuner à l’hôtel.', it: 'Abbiamo fatto colazione in hotel.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['comemos', 'fizemos', 'pedimos'] },
  { id: 'pt2s004', de: 'Ela perdeu a passagem de avião.', en: 'She lost the plane ticket.', gloss: { de: 'Sie hat das Flugticket verloren.', es: 'Ella perdió el billete de avión.', fr: 'Elle a perdu le billet d’avion.', it: 'Ha perso il biglietto aereo.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['mala', 'sacola', 'viagem'] },
  { id: 'pt2s005', de: 'Quanto você pagou por esse celular?', en: 'How much did you pay for that cell phone?', gloss: { de: 'Wie viel hast du für dieses Handy bezahlt?', es: '¿Cuánto pagaste por ese móvil?', fr: 'Combien as-tu payé ce téléphone ?', it: 'Quanto hai pagato quel cellulare?' }, level: 'A2', clozeIndex: 2, clozeDistractors: ['comprou', 'vendeu', 'gastou'] },
  { id: 'pt2s006', de: 'Ontem eu fui ao supermercado e comprei frango.', en: 'Yesterday I went to the supermarket and bought chicken.', gloss: { de: 'Gestern bin ich in den Supermarkt gegangen und habe Hähnchen gekauft.', es: 'Ayer fui al supermercado y compré pollo.', fr: 'Hier je suis allé au supermarché et j’ai acheté du poulet.', it: 'Ieri sono andato al supermercato e ho comprato del pollo.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['escritório', 'aeroporto', 'hotel'] },
  { id: 'pt2s007', de: 'O garçom trouxe o cardápio para a mesa.', en: 'The waiter brought the menu to the table.', gloss: { de: 'Der Kellner brachte die Speisekarte an den Tisch.', es: 'El camarero trajo la carta a la mesa.', fr: 'Le serveur a apporté le menu à la table.', it: 'Il cameriere ha portato il menù al tavolo.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['prato', 'suco', 'troco'] },
  { id: 'pt2s008', de: 'Eu esqueci o meu celular no escritório.', en: 'I forgot my cell phone at the office.', gloss: { de: 'Ich habe mein Handy im Büro vergessen.', es: 'Olvidé mi móvil en la oficina.', fr: 'J’ai oublié mon téléphone au bureau.', it: 'Ho dimenticato il cellulare in ufficio.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['perdi', 'deixei', 'encontrei'] },
  { id: 'pt2s009', de: 'A reunião com o chefe começou tarde.', en: 'The meeting with the boss started late.', gloss: { de: 'Die Besprechung mit dem Chef hat spät angefangen.', es: 'La reunión con el jefe empezó tarde.', fr: 'La réunion avec le chef a commencé tard.', it: 'La riunione con il capo è cominciata tardi.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['terminou', 'mudou', 'ajudou'] },
  { id: 'pt2s010', de: 'Ele trabalha numa empresa grande há dois anos.', en: 'He has worked at a big company for two years.', gloss: { de: 'Er arbeitet seit zwei Jahren in einer großen Firma.', es: 'Trabaja en una empresa grande desde hace dos años.', fr: 'Il travaille dans une grande entreprise depuis deux ans.', it: 'Lavora in una grande azienda da due anni.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['faculdade', 'escola', 'loja'] },
  { id: 'pt2s011', de: 'Eu estudei para a prova o fim de semana inteiro.', en: 'I studied for the exam all weekend.', gloss: { de: 'Ich habe das ganze Wochenende für die Prüfung gelernt.', es: 'Estudié para el examen todo el fin de semana.', fr: 'J’ai étudié pour l’examen tout le week-end.', it: 'Ho studiato per l’esame tutto il fine settimana.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['reunião', 'faculdade', 'viagem'] },
  { id: 'pt2s012', de: 'Minha cabeça está doendo desde ontem.', en: 'My head has been hurting since yesterday.', gloss: { de: 'Mein Kopf tut seit gestern weh.', es: 'Me duele la cabeza desde ayer.', fr: 'J’ai mal à la tête depuis hier.', it: 'Mi fa male la testa da ieri.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['perna', 'mão', 'garganta'] },
  { id: 'pt2s013', de: 'Ontem eu fui ao médico porque estava doente.', en: 'Yesterday I went to the doctor because I was sick.', gloss: { de: 'Gestern bin ich zum Arzt gegangen, weil ich krank war.', es: 'Ayer fui al médico porque estaba enfermo.', fr: 'Hier je suis allé chez le médecin parce que j’étais malade.', it: 'Ieri sono andato dal medico perché ero malato.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['hospital', 'dentista', 'mercado'] },
  { id: 'pt2s014', de: 'Eu preciso comprar um remédio na farmácia.', en: 'I need to buy medicine at the pharmacy.', gloss: { de: 'Ich muss ein Medikament in der Apotheke kaufen.', es: 'Necesito comprar un medicamento en la farmacia.', fr: 'Je dois acheter un médicament à la pharmacie.', it: 'Devo comprare una medicina in farmacia.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['suco', 'cardápio', 'prato'] },
  { id: 'pt2s015', de: 'Ela ficou muito nervosa antes da viagem.', en: 'She got very nervous before the trip.', gloss: { de: 'Sie wurde vor der Reise sehr nervös.', es: 'Se puso muy nerviosa antes del viaje.', fr: 'Elle est devenue très nerveuse avant le voyage.', it: 'È diventata molto nervosa prima del viaggio.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['triste', 'animada', 'calma'] },
  { id: 'pt2s016', de: 'Eu estou com saudade dos meus amigos.', en: 'I miss my friends.', gloss: { de: 'Ich vermisse meine Freunde.', es: 'Echo de menos a mis amigos.', fr: 'Mes amis me manquent.', it: 'Mi mancano i miei amici.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['medo', 'raiva', 'pressa'] },
  { id: 'pt2s017', de: 'Nós compramos um sofá novo para a sala.', en: 'We bought a new sofa for the living room.', gloss: { de: 'Wir haben ein neues Sofa für das Wohnzimmer gekauft.', es: 'Compramos un sofá nuevo para el salón.', fr: 'Nous avons acheté un nouveau canapé pour le salon.', it: 'Abbiamo comprato un divano nuovo per il soggiorno.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['cama', 'cadeira', 'chuveiro'] },
  { id: 'pt2s018', de: 'A cozinha do apartamento é pequena mas limpa.', en: 'The apartment’s kitchen is small but clean.', gloss: { de: 'Die Küche der Wohnung ist klein, aber sauber.', es: 'La cocina del apartamento es pequeña pero limpia.', fr: 'La cuisine de l’appartement est petite mais propre.', it: 'La cucina dell’appartamento è piccola ma pulita.' }, level: 'A2', clozeIndex: 1, clozeDistractors: ['sala', 'janela', 'geladeira'] },
  { id: 'pt2s019', de: 'Este trem é mais rápido do que o ônibus.', en: 'This train is faster than the bus.', gloss: { de: 'Dieser Zug ist schneller als der Bus.', es: 'Este tren es más rápido que el autobús.', fr: 'Ce train est plus rapide que le bus.', it: 'Questo treno è più veloce dell’autobus.' }, level: 'A2', clozeIndex: 4, clozeDistractors: ['lento', 'velho', 'sujo'] },
  { id: 'pt2s020', de: 'O preço do hotel está melhor este ano.', en: 'The hotel price is better this year.', gloss: { de: 'Der Hotelpreis ist dieses Jahr besser.', es: 'El precio del hotel está mejor este año.', fr: 'Le prix de l’hôtel est meilleur cette année.', it: 'Il prezzo dell’hotel è migliore quest’anno.' }, level: 'A2', clozeIndex: 5, clozeDistractors: ['pior', 'alto', 'difícil'] },
  { id: 'pt2s021', de: 'Você pode me ajudar com as malas?', en: 'Can you help me with the suitcases?', gloss: { de: 'Kannst du mir mit den Koffern helfen?', es: '¿Puedes ayudarme con las maletas?', fr: 'Peux-tu m’aider avec les valises ?', it: 'Puoi aiutarmi con le valigie?' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['esperar', 'pagar', 'levar'] },
  { id: 'pt2s022', de: 'Às vezes eu durmo no ônibus depois do trabalho.', en: 'Sometimes I sleep on the bus after work.', gloss: { de: 'Manchmal schlafe ich nach der Arbeit im Bus.', es: 'A veces duermo en el autobús después del trabajo.', fr: 'Parfois je dors dans le bus après le travail.', it: 'A volte dormo in autobus dopo il lavoro.' }, level: 'A2', clozeIndex: 3, clozeDistractors: ['estudo', 'descanso', 'converso'] },
];
