import type { SentenceItem } from '@/content/german/types';

// Brazilian Portuguese B1 sentences. `de` holds the Portuguese text.
//
// B1 register means these are not simple SVO: subordinate clauses, present and
// imperfect subjunctive, the future subjunctive after `quando`/`caso`, and
// opinion framing (`acho que…`, `na minha opinião…`). clozeIndex targets the
// load-bearing word — usually the connector or the conjugated verb carrying the
// mood — never an article. Distractors are same-class forms that are
// grammatical-looking but wrong, so the exercise tests the grammar, not shape.
//
// `gloss` carries the non-English UI locales; see b1-vocab.ts for the rule.

export const B1_SENTENCES: SentenceItem[] = [
  { id: 'pt3s001', de: 'Embora seja difícil, acho que vale a pena tentar.', en: 'Although it is difficult, I think it is worth trying.', gloss: { de: 'Auch wenn es schwierig ist, finde ich, dass es sich lohnt, es zu versuchen.', es: 'Aunque sea difícil, creo que vale la pena intentarlo.', fr: 'Bien que ce soit difficile, je pense que ça vaut la peine d’essayer.', it: 'Benché sia difficile, penso che valga la pena provarci.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Portanto', 'Porque', 'Assim'] },
  { id: 'pt3s002', de: 'Na minha opinião, o governo deveria investir mais em educação.', en: 'In my opinion, the government should invest more in education.', gloss: { de: 'Meiner Meinung nach sollte die Regierung mehr in Bildung investieren.', es: 'En mi opinión, el gobierno debería invertir más en educación.', fr: 'À mon avis, le gouvernement devrait investir davantage dans l’éducation.', it: 'Secondo me, il governo dovrebbe investire di più nell’istruzione.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['gastar', 'cortar', 'exigir'] },
  { id: 'pt3s003', de: 'Apesar de trabalhar muito, ele nunca conseguiu uma promoção.', en: 'Despite working a lot, he never got a promotion.', gloss: { de: 'Obwohl er viel arbeitet, hat er nie eine Beförderung bekommen.', es: 'A pesar de trabajar mucho, nunca consiguió un ascenso.', fr: 'Bien qu’il travaille beaucoup, il n’a jamais obtenu de promotion.', it: 'Nonostante lavori molto, non ha mai ottenuto una promozione.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['pediu', 'recusou', 'perdeu'] },
  { id: 'pt3s004', de: 'É importante que todos tenham acesso à informação de qualidade.', en: 'It is important that everyone has access to quality information.', gloss: { de: 'Es ist wichtig, dass alle Zugang zu guten Informationen haben.', es: 'Es importante que todos tengan acceso a información de calidad.', fr: 'Il est important que tout le monde ait accès à une information de qualité.', it: 'È importante che tutti abbiano accesso a un’informazione di qualità.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['têm', 'tenha', 'teriam'] },
  { id: 'pt3s005', de: 'No entanto, poucos jornais verificam as fontes antes de publicar.', en: 'However, few newspapers check their sources before publishing.', gloss: { de: 'Jedoch prüfen nur wenige Zeitungen die Quellen, bevor sie etwas veröffentlichen.', es: 'Sin embargo, pocos periódicos verifican las fuentes antes de publicar.', fr: 'Cependant, peu de journaux vérifient les sources avant de publier.', it: 'Tuttavia, pochi giornali verificano le fonti prima di pubblicare.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['manchetes', 'entrevistas', 'reportagens'] },
  { id: 'pt3s006', de: 'Se eu tivesse mais tempo, faria um curso de fotografia.', en: 'If I had more time, I would take a photography course.', gloss: { de: 'Wenn ich mehr Zeit hätte, würde ich einen Fotokurs machen.', es: 'Si tuviera más tiempo, haría un curso de fotografía.', fr: 'Si j’avais plus de temps, je suivrais un cours de photographie.', it: 'Se avessi più tempo, farei un corso di fotografia.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['tenho', 'tinha', 'tiver'] },
  { id: 'pt3s007', de: 'A poluição do ar piorou muito nos últimos dez anos.', en: 'Air pollution has got much worse in the last ten years.', gloss: { de: 'Die Luftverschmutzung hat sich in den letzten zehn Jahren stark verschlechtert.', es: 'La contaminación del aire ha empeorado mucho en los últimos diez años.', fr: 'La pollution de l’air s’est beaucoup aggravée ces dix dernières années.', it: 'L’inquinamento dell’aria è peggiorato molto negli ultimi dieci anni.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['melhorou', 'diminuiu', 'parou'] },
  { id: 'pt3s008', de: 'Talvez a gente consiga resolver isso sem brigar.', en: 'Maybe we can sort this out without fighting.', gloss: { de: 'Vielleicht schaffen wir es, das ohne Streit zu klären.', es: 'Quizás podamos resolver esto sin pelear.', fr: 'On arrivera peut-être à régler ça sans se disputer.', it: 'Forse riusciamo a risolvere questa cosa senza litigare.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['consegue', 'conseguiu', 'conseguir'] },
  { id: 'pt3s009', de: 'Portanto, é preciso reconhecer que o problema é mais complexo.', en: 'Therefore, we have to acknowledge that the problem is more complex.', gloss: { de: 'Deshalb muss man anerkennen, dass das Problem komplexer ist.', es: 'Por lo tanto, hay que reconocer que el problema es más complejo.', fr: 'Il faut donc reconnaître que le problème est plus complexe.', it: 'Perciò bisogna riconoscere che il problema è più complesso.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['esquecer', 'negar', 'repetir'] },
  { id: 'pt3s010', de: 'Ela me disse que estava cansada de tantas reuniões inúteis.', en: 'She told me she was tired of so many useless meetings.', gloss: { de: 'Sie sagte mir, dass sie so viele nutzlose Besprechungen satt habe.', es: 'Me dijo que estaba cansada de tantas reuniones inútiles.', fr: 'Elle m’a dit qu’elle en avait assez de toutes ces réunions inutiles.', it: 'Mi ha detto che era stanca di tante riunioni inutili.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['entrevistas', 'notícias', 'desculpas'] },
  { id: 'pt3s011', de: 'Embora o salário seja bom, o prazo é impossível de cumprir.', en: 'Although the pay is good, the deadline is impossible to meet.', gloss: { de: 'Auch wenn das Gehalt gut ist, ist die Frist unmöglich einzuhalten.', es: 'Aunque el sueldo sea bueno, el plazo es imposible de cumplir.', fr: 'Même si le salaire est bon, le délai est impossible à respecter.', it: 'Anche se lo stipendio è buono, la scadenza è impossibile da rispettare.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['cargo', 'currículo', 'imposto'] },
  { id: 'pt3s012', de: 'Muita gente compartilha notícias sem verificar se são verdadeiras.', en: 'A lot of people share news without checking whether it is true.', gloss: { de: 'Viele Leute teilen Nachrichten, ohne zu prüfen, ob sie stimmen.', es: 'Mucha gente comparte noticias sin comprobar si son verdaderas.', fr: 'Beaucoup de gens partagent des nouvelles sans vérifier si elles sont vraies.', it: 'Molta gente condivide notizie senza verificare se siano vere.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['escreve', 'publica', 'apaga'] },
  { id: 'pt3s013', de: 'Quando eu terminar o relatório, aviso você.', en: 'When I finish the report, I will let you know.', gloss: { de: 'Wenn ich den Bericht fertig habe, sage ich dir Bescheid.', es: 'Cuando termine el informe, te aviso.', fr: 'Quand j’aurai fini le rapport, je te préviens.', it: 'Quando finirò il rapporto, ti avviso.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['terminei', 'termino', 'terminaria'] },
  { id: 'pt3s014', de: 'Não acho que essa lei resolva o problema da desigualdade.', en: 'I do not think this law solves the problem of inequality.', gloss: { de: 'Ich glaube nicht, dass dieses Gesetz das Problem der Ungleichheit löst.', es: 'No creo que esta ley resuelva el problema de la desigualdad.', fr: 'Je ne pense pas que cette loi résolve le problème des inégalités.', it: 'Non credo che questa legge risolva il problema della disuguaglianza.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['resolve', 'resolveu', 'resolveria'] },
  { id: 'pt3s015', de: 'Além disso, precisamos reduzir o lixo que produzimos todos os dias.', en: 'Besides, we need to reduce the waste we produce every day.', gloss: { de: 'Außerdem müssen wir den Müll reduzieren, den wir jeden Tag produzieren.', es: 'Además, tenemos que reducir la basura que producimos cada día.', fr: 'De plus, nous devons réduire les déchets que nous produisons chaque jour.', it: 'Inoltre, dobbiamo ridurre i rifiuti che produciamo ogni giorno.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['consumo', 'plástico', 'desperdício'] },
  { id: 'pt3s016', de: 'Ele se arrependeu de ter aceitado aquele cargo.', en: 'He regretted having accepted that position.', gloss: { de: 'Er hat es bereut, diese Stelle angenommen zu haben.', es: 'Se arrepintió de haber aceptado ese puesto.', fr: 'Il a regretté d’avoir accepté ce poste.', it: 'Si è pentito di aver accettato quella posizione.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['esqueceu', 'queixou', 'lembrou'] },
  { id: 'pt3s017', de: 'Caso você mude de ideia, me avise até sexta.', en: 'In case you change your mind, let me know by Friday.', gloss: { de: 'Falls du es dir anders überlegst, sag mir bis Freitag Bescheid.', es: 'Por si cambias de idea, avísame antes del viernes.', fr: 'Au cas où tu changerais d’avis, préviens-moi avant vendredi.', it: 'Nel caso in cui cambiassi idea, fammelo sapere entro venerdì.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['muda', 'mudou', 'mudaria'] },
  { id: 'pt3s018', de: 'A empresa contratou dez pessoas, mas demitiu vinte no mês passado.', en: 'The company hired ten people but laid off twenty last month.', gloss: { de: 'Die Firma hat zehn Leute eingestellt, aber letzten Monat zwanzig entlassen.', es: 'La empresa contrató a diez personas, pero despidió a veinte el mes pasado.', fr: 'L’entreprise a embauché dix personnes, mais en a licencié vingt le mois dernier.', it: 'L’azienda ha assunto dieci persone, ma ne ha licenziate venti il mese scorso.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['promoveu', 'treinou', 'entrevistou'] },
  { id: 'pt3s019', de: 'Sinto muita saudade de morar perto do mar.', en: 'I really miss living near the sea.', gloss: { de: 'Ich vermisse es sehr, in Meeresnähe zu wohnen.', es: 'Echo mucho de menos vivir cerca del mar.', fr: 'Ça me manque beaucoup d’habiter près de la mer.', it: 'Mi manca molto vivere vicino al mare.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['vergonha', 'raiva', 'pressa'] },
  { id: 'pt3s020', de: 'Desde que haja transparência, a maioria aceita pagar mais impostos.', en: 'As long as there is transparency, most people accept paying more taxes.', gloss: { de: 'Solange es Transparenz gibt, akzeptieren die meisten, mehr Steuern zu zahlen.', es: 'Siempre que haya transparencia, la mayoría acepta pagar más impuestos.', fr: 'Tant qu’il y a de la transparence, la plupart des gens acceptent de payer plus d’impôts.', it: 'Purché ci sia trasparenza, la maggior parte accetta di pagare più tasse.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['há', 'houve', 'havia'] },
];
