import type { SentenceItem } from '@/content/german/types';

// Brazilian Portuguese B1 sentences. `de` holds the Portuguese text.
//
// B1 register means these are not simple SVO: subordinate clauses, present and
// imperfect subjunctive, the future subjunctive after `quando`/`caso`, and
// opinion framing (`acho que…`, `na minha opinião…`). clozeIndex targets the
// load-bearing word — usually the connector or the conjugated verb carrying the
// mood — never an article. Distractors are same-class forms that are
// grammatical-looking but wrong, so the exercise tests the grammar, not shape.
//
// `gloss` carries the non-English UI locales; see b1-vocab.ts for the rule.

export const B1_SENTENCES: SentenceItem[] = [
  { id: 'pt3s001', de: 'Embora seja difícil, acho que vale a pena tentar.', en: 'Although it is difficult, I think it is worth trying.', gloss: { de: 'Auch wenn es schwierig ist, finde ich, dass es sich lohnt, es zu versuchen.', es: 'Aunque sea difícil, creo que vale la pena intentarlo.', fr: 'Bien que ce soit difficile, je pense que ça vaut la peine d’essayer.', it: 'Benché sia difficile, penso che valga la pena provarci.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Portanto', 'Porque', 'Assim'] },
  { id: 'pt3s002', de: 'Na minha opinião, o governo deveria investir mais em educação.', en: 'In my opinion, the government should invest more in education.', gloss: { de: 'Meiner Meinung nach sollte die Regierung mehr in Bildung investieren.', es: 'En mi opinión, el gobierno debería invertir más en educación.', fr: 'À mon avis, le gouvernement devrait investir davantage dans l’éducation.', it: 'Secondo me, il governo dovrebbe investire di più nell’istruzione.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['gastar', 'cortar', 'exigir'] },
  { id: 'pt3s003', de: 'Apesar de trabalhar muito, ele nunca conseguiu uma promoção.', en: 'Despite working a lot, he never got a promotion.', gloss: { de: 'Obwohl er viel arbeitet, hat er nie eine Beförderung bekommen.', es: 'A pesar de trabajar mucho, nunca consiguió un ascenso.', fr: 'Bien qu’il travaille beaucoup, il n’a jamais obtenu de promotion.', it: 'Nonostante lavori molto, non ha mai ottenuto una promozione.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['pediu', 'recusou', 'perdeu'] },
  { id: 'pt3s004', de: 'É importante que todos tenham acesso à informação de qualidade.', en: 'It is important that everyone has access to quality information.', gloss: { de: 'Es ist wichtig, dass alle Zugang zu guten Informationen haben.', es: 'Es importante que todos tengan acceso a información de calidad.', fr: 'Il est important que tout le monde ait accès à une information de qualité.', it: 'È importante che tutti abbiano accesso a un’informazione di qualità.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['têm', 'tenha', 'teriam'] },
  { id: 'pt3s005', de: 'No entanto, poucos jornais verificam as fontes antes de publicar.', en: 'However, few newspapers check their sources before publishing.', gloss: { de: 'Jedoch prüfen nur wenige Zeitungen die Quellen, bevor sie etwas veröffentlichen.', es: 'Sin embargo, pocos periódicos verifican las fuentes antes de publicar.', fr: 'Cependant, peu de journaux vérifient les sources avant de publier.', it: 'Tuttavia, pochi giornali verificano le fonti prima di pubblicare.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['manchetes', 'entrevistas', 'reportagens'] },
  { id: 'pt3s006', de: 'Se eu tivesse mais tempo, faria um curso de fotografia.', en: 'If I had more time, I would take a photography course.', gloss: { de: 'Wenn ich mehr Zeit hätte, würde ich einen Fotokurs machen.', es: 'Si tuviera más tiempo, haría un curso de fotografía.', fr: 'Si j’avais plus de temps, je suivrais un cours de photographie.', it: 'Se avessi più tempo, farei un corso di fotografia.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['tenho', 'tinha', 'tiver'] },
  { id: 'pt3s007', de: 'A poluição do ar piorou muito nos últimos dez anos.', en: 'Air pollution has got much worse in the last ten years.', gloss: { de: 'Die Luftverschmutzung hat sich in den letzten zehn Jahren stark verschlechtert.', es: 'La contaminación del aire ha empeorado mucho en los últimos diez años.', fr: 'La pollution de l’air s’est beaucoup aggravée ces dix dernières années.', it: 'L’inquinamento dell’aria è peggiorato molto negli ultimi dieci anni.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['melhorou', 'diminuiu', 'parou'] },
  { id: 'pt3s008', de: 'Talvez a gente consiga resolver isso sem brigar.', en: 'Maybe we can sort this out without fighting.', gloss: { de: 'Vielleicht schaffen wir es, das ohne Streit zu klären.', es: 'Quizás podamos resolver esto sin pelear.', fr: 'On arrivera peut-être à régler ça sans se disputer.', it: 'Forse riusciamo a risolvere questa cosa senza litigare.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['consegue', 'conseguiu', 'conseguir'] },
  { id: 'pt3s009', de: 'Portanto, é preciso reconhecer que o problema é mais complexo.', en: 'Therefore, we have to acknowledge that the problem is more complex.', gloss: { de: 'Deshalb muss man anerkennen, dass das Problem komplexer ist.', es: 'Por lo tanto, hay que reconocer que el problema es más complejo.', fr: 'Il faut donc reconnaître que le problème est plus complexe.', it: 'Perciò bisogna riconoscere che il problema è più complesso.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['esquecer', 'negar', 'repetir'] },
  { id: 'pt3s010', de: 'Ela me disse que estava cansada de tantas reuniões inúteis.', en: 'She told me she was tired of so many useless meetings.', gloss: { de: 'Sie sagte mir, dass sie so viele nutzlose Besprechungen satt habe.', es: 'Me dijo que estaba cansada de tantas reuniones inútiles.', fr: 'Elle m’a dit qu’elle en avait assez de toutes ces réunions inutiles.', it: 'Mi ha detto che era stanca di tante riunioni inutili.' }, level: 'B1', clozeIndex: 8, clozeDistractors: ['entrevistas', 'notícias', 'desculpas'] },
  { id: 'pt3s011', de: 'Embora o salário seja bom, o prazo é impossível de cumprir.', en: 'Although the pay is good, the deadline is impossible to meet.', gloss: { de: 'Auch wenn das Gehalt gut ist, ist die Frist unmöglich einzuhalten.', es: 'Aunque el sueldo sea bueno, el plazo es imposible de cumplir.', fr: 'Même si le salaire est bon, le délai est impossible à respecter.', it: 'Anche se lo stipendio è buono, la scadenza è impossibile da rispettare.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['cargo', 'currículo', 'imposto'] },
  { id: 'pt3s012', de: 'Muita gente compartilha notícias sem verificar se são verdadeiras.', en: 'A lot of people share news without checking whether it is true.', gloss: { de: 'Viele Leute teilen Nachrichten, ohne zu prüfen, ob sie stimmen.', es: 'Mucha gente comparte noticias sin comprobar si son verdaderas.', fr: 'Beaucoup de gens partagent des nouvelles sans vérifier si elles sont vraies.', it: 'Molta gente condivide notizie senza verificare se siano vere.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['escreve', 'publica', 'apaga'] },
  { id: 'pt3s013', de: 'Quando eu terminar o relatório, aviso você.', en: 'When I finish the report, I will let you know.', gloss: { de: 'Wenn ich den Bericht fertig habe, sage ich dir Bescheid.', es: 'Cuando termine el informe, te aviso.', fr: 'Quand j’aurai fini le rapport, je te préviens.', it: 'Quando finirò il rapporto, ti avviso.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['terminei', 'termino', 'terminaria'] },
  { id: 'pt3s014', de: 'Não acho que essa lei resolva o problema da desigualdade.', en: 'I do not think this law solves the problem of inequality.', gloss: { de: 'Ich glaube nicht, dass dieses Gesetz das Problem der Ungleichheit löst.', es: 'No creo que esta ley resuelva el problema de la desigualdad.', fr: 'Je ne pense pas que cette loi résolve le problème des inégalités.', it: 'Non credo che questa legge risolva il problema della disuguaglianza.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['resolve', 'resolveu', 'resolveria'] },
  { id: 'pt3s015', de: 'Além disso, precisamos reduzir o lixo que produzimos todos os dias.', en: 'Besides, we need to reduce the waste we produce every day.', gloss: { de: 'Außerdem müssen wir den Müll reduzieren, den wir jeden Tag produzieren.', es: 'Además, tenemos que reducir la basura que producimos cada día.', fr: 'De plus, nous devons réduire les déchets que nous produisons chaque jour.', it: 'Inoltre, dobbiamo ridurre i rifiuti che produciamo ogni giorno.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['consumo', 'plástico', 'desperdício'] },
  { id: 'pt3s016', de: 'Ele se arrependeu de ter aceitado aquele cargo.', en: 'He regretted having accepted that position.', gloss: { de: 'Er hat es bereut, diese Stelle angenommen zu haben.', es: 'Se arrepintió de haber aceptado ese puesto.', fr: 'Il a regretté d’avoir accepté ce poste.', it: 'Si è pentito di aver accettato quella posizione.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['esqueceu', 'queixou', 'lembrou'] },
  { id: 'pt3s017', de: 'Caso você mude de ideia, me avise até sexta.', en: 'In case you change your mind, let me know by Friday.', gloss: { de: 'Falls du es dir anders überlegst, sag mir bis Freitag Bescheid.', es: 'Por si cambias de idea, avísame antes del viernes.', fr: 'Au cas où tu changerais d’avis, préviens-moi avant vendredi.', it: 'Nel caso in cui cambiassi idea, fammelo sapere entro venerdì.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['muda', 'mudou', 'mudaria'] },
  { id: 'pt3s018', de: 'A empresa contratou dez pessoas, mas demitiu vinte no mês passado.', en: 'The company hired ten people but laid off twenty last month.', gloss: { de: 'Die Firma hat zehn Leute eingestellt, aber letzten Monat zwanzig entlassen.', es: 'La empresa contrató a diez personas, pero despidió a veinte el mes pasado.', fr: 'L’entreprise a embauché dix personnes, mais en a licencié vingt le mois dernier.', it: 'L’azienda ha assunto dieci persone, ma ne ha licenziate venti il mese scorso.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['promoveu', 'treinou', 'entrevistou'] },
  { id: 'pt3s019', de: 'Sinto muita saudade de morar perto do mar.', en: 'I really miss living near the sea.', gloss: { de: 'Ich vermisse es sehr, in Meeresnähe zu wohnen.', es: 'Echo mucho de menos vivir cerca del mar.', fr: 'Ça me manque beaucoup d’habiter près de la mer.', it: 'Mi manca molto vivere vicino al mare.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['vergonha', 'raiva', 'pressa'] },
  { id: 'pt3s020', de: 'Desde que haja transparência, a maioria aceita pagar mais impostos.', en: 'As long as there is transparency, most people accept paying more taxes.', gloss: { de: 'Solange es Transparenz gibt, akzeptieren die meisten, mehr Steuern zu zahlen.', es: 'Siempre que haya transparencia, la mayoría acepta pagar más impuestos.', fr: 'Tant qu’il y a de la transparence, la plupart des gens acceptent de payer plus d’impôts.', it: 'Purché ci sia trasparenza, la maggior parte accetta di pagare più tasse.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['há', 'houve', 'havia'] },
  { id: 'pt3s021', de: 'É provável que a inflação suba de novo no próximo ano.', en: 'Inflation is likely to rise again next year.', gloss: { de: 'Wahrscheinlich steigt die Inflation nächstes Jahr wieder.', es: 'Es probable que la inflación suba otra vez el año que viene.', fr: 'Il est probable que l’inflation augmente à nouveau l’an prochain.', it: 'È probabile che l’inflazione salga di nuovo l’anno prossimo.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['sobe', 'subiu', 'subiria'] },
  { id: 'pt3s022', de: 'Espero que o tratamento faça efeito rapidamente.', en: 'I hope the treatment works quickly.', gloss: { de: 'Ich hoffe, dass die Behandlung schnell wirkt.', es: 'Espero que el tratamiento haga efecto rápidamente.', fr: 'J’espère que le traitement fasse effet rapidement.', it: 'Spero che il trattamento faccia effetto in fretta.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['faz', 'fez', 'faria'] },
  { id: 'pt3s023', de: 'Ainda que os dados sejam públicos, poucos sabem interpretá-los.', en: 'Even though the data is public, few people know how to interpret it.', gloss: { de: 'Auch wenn die Daten öffentlich sind, können sie nur wenige deuten.', es: 'Aunque los datos sean públicos, pocos saben interpretarlos.', fr: 'Même si les données sont publiques, peu de gens savent les interpréter.', it: 'Anche se i dati sono pubblici, pochi sanno interpretarli.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['são', 'foram', 'seriam'] },
  { id: 'pt3s024', de: 'Na minha opinião, a tecnologia não substitui o contato humano.', en: 'In my opinion, technology does not replace human contact.', gloss: { de: 'Meiner Meinung nach ersetzt Technik den menschlichen Kontakt nicht.', es: 'En mi opinión, la tecnología no sustituye el contacto humano.', fr: 'À mon avis, la technologie ne remplace pas le contact humain.', it: 'Secondo me, la tecnologia non sostituisce il contatto umano.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['aumenta', 'garante', 'defende'] },
  { id: 'pt3s025', de: 'Se o governo reduzisse os impostos, o consumo aumentaria.', en: 'If the government cut taxes, consumption would go up.', gloss: { de: 'Wenn die Regierung die Steuern senken würde, würde der Konsum steigen.', es: 'Si el gobierno redujera los impuestos, el consumo aumentaría.', fr: 'Si le gouvernement réduisait les impôts, la consommation augmenterait.', it: 'Se il governo riducesse le tasse, i consumi aumenterebbero.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['reduz', 'reduziu', 'reduzir'] },
  { id: 'pt3s026', de: 'É essencial que os alunos aprendam a questionar as fontes.', en: 'It is essential that students learn to question their sources.', gloss: { de: 'Es ist entscheidend, dass Schüler lernen, Quellen zu hinterfragen.', es: 'Es esencial que los alumnos aprendan a cuestionar las fuentes.', fr: 'Il est essentiel que les élèves apprennent à remettre en question les sources.', it: 'È essenziale che gli studenti imparino a mettere in discussione le fonti.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['aprendem', 'aprenderam', 'aprenderiam'] },
  { id: 'pt3s027', de: 'Ele admitiu que o orçamento estava errado desde o começo.', en: 'He admitted the budget had been wrong from the start.', gloss: { de: 'Er hat zugegeben, dass das Budget von Anfang an falsch war.', es: 'Admitió que el presupuesto estaba mal desde el principio.', fr: 'Il a admis que le budget était faux depuis le début.', it: 'Ha ammesso che il bilancio era sbagliato fin dall’inizio.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['negou', 'garantiu', 'sugeriu'] },
  { id: 'pt3s028', de: 'Quando eu tiver mais renda, vou investir em um curso.', en: 'When I have more income, I will invest in a course.', gloss: { de: 'Wenn ich mehr Einkommen habe, investiere ich in einen Kurs.', es: 'Cuando tenga más ingresos, voy a invertir en un curso.', fr: 'Quand j’aurai plus de revenus, j’investirai dans un cours.', it: 'Quando avrò più reddito, investirò in un corso.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['tenho', 'tinha', 'tivesse'] },
  { id: 'pt3s029', de: 'Muitos jovens preferem que o ensino seja mais prático.', en: 'Many young people would rather education were more practical.', gloss: { de: 'Viele junge Leute wünschen sich einen praxisnäheren Unterricht.', es: 'Muchos jóvenes prefieren que la enseñanza sea más práctica.', fr: 'Beaucoup de jeunes préfèrent que l’enseignement soit plus pratique.', it: 'Molti giovani preferiscono che l’insegnamento sia più pratico.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['é', 'foi', 'seria'] },
  { id: 'pt3s030', de: 'Duvido que essa ferramenta resolva o problema da privacidade.', en: 'I doubt this tool solves the privacy problem.', gloss: { de: 'Ich bezweifle, dass dieses Werkzeug das Datenschutzproblem löst.', es: 'Dudo que esta herramienta resuelva el problema de la privacidad.', fr: 'Je doute que cet outil résolve le problème de la vie privée.', it: 'Dubito che questo strumento risolva il problema della privacy.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['tecnologia', 'pesquisa', 'inovação'] },
  { id: 'pt3s031', de: 'Analisando os dados, percebemos que a dívida cresceu muito.', en: 'Analysing the data, we realised the debt had grown a lot.', gloss: { de: 'Bei der Analyse der Daten merkten wir, dass die Schulden stark gewachsen sind.', es: 'Analizando los datos, nos dimos cuenta de que la deuda creció mucho.', fr: 'En analysant les données, nous avons constaté que la dette avait beaucoup augmenté.', it: 'Analizzando i dati, ci siamo accorti che il debito è cresciuto molto.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['renda', 'economia', 'inflação'] },
  { id: 'pt3s032', de: 'Por mais que ele se esforce, o prazo continua irreal.', en: 'However hard he tries, the deadline is still unrealistic.', gloss: { de: 'So sehr er sich auch anstrengt, die Frist bleibt unrealistisch.', es: 'Por mucho que se esfuerce, el plazo sigue siendo irreal.', fr: 'Il a beau faire des efforts, le délai reste irréaliste.', it: 'Per quanto si sforzi, la scadenza resta irrealistica.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['esforça', 'esforçou', 'esforçaria'] },
  { id: 'pt3s033', de: 'Ela sugeriu que a gente comparasse os dois orçamentos.', en: 'She suggested we compare the two budgets.', gloss: { de: 'Sie schlug vor, dass wir die beiden Budgets vergleichen.', es: 'Sugirió que comparáramos los dos presupuestos.', fr: 'Elle a suggéré que nous comparions les deux budgets.', it: 'Ha suggerito di confrontare i due bilanci.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['compara', 'comparou', 'compararia'] },
  { id: 'pt3s034', de: 'A saúde mental ainda é um tema pouco discutido no trabalho.', en: 'Mental health is still rarely discussed at work.', gloss: { de: 'Über psychische Gesundheit wird bei der Arbeit noch wenig gesprochen.', es: 'La salud mental todavía es un tema poco discutido en el trabajo.', fr: 'La santé mentale reste un sujet peu abordé au travail.', it: 'La salute mentale è ancora un tema poco discusso al lavoro.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['economia', 'tradição', 'paisagem'] },
  { id: 'pt3s035', de: 'Caso o sintoma persista, procure um especialista.', en: 'If the symptom persists, see a specialist.', gloss: { de: 'Falls das Symptom anhält, suchen Sie einen Facharzt auf.', es: 'En caso de que el síntoma persista, consulte a un especialista.', fr: 'Si le symptôme persiste, consultez un spécialiste.', it: 'Nel caso in cui il sintomo persista, si rivolga a uno specialista.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['persiste', 'persistiu', 'persistiria'] },
  { id: 'pt3s036', de: 'Não é verdade que a inovação sempre gere desemprego.', en: 'It is not true that innovation always creates unemployment.', gloss: { de: 'Es stimmt nicht, dass Innovation immer Arbeitslosigkeit erzeugt.', es: 'No es cierto que la innovación siempre genere desempleo.', fr: 'Il n’est pas vrai que l’innovation crée toujours du chômage.', it: 'Non è vero che l’innovazione generi sempre disoccupazione.' }, level: 'B1', clozeIndex: 7, clozeDistractors: ['gera', 'gerou', 'geraria'] },
  { id: 'pt3s037', de: 'Ele garantiu que o diagnóstico estava correto.', en: 'He assured us the diagnosis was correct.', gloss: { de: 'Er versicherte, dass die Diagnose richtig war.', es: 'Garantizó que el diagnóstico estaba correcto.', fr: 'Il a assuré que le diagnostic était correct.', it: 'Ha assicurato che la diagnosi era corretta.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['duvidou', 'negou', 'questionou'] },
  { id: 'pt3s038', de: 'Antes que você decida, leia o contrato com atenção.', en: 'Before you decide, read the contract carefully.', gloss: { de: 'Bevor du dich entscheidest, lies den Vertrag aufmerksam.', es: 'Antes de que decidas, lee el contrato con atención.', fr: 'Avant que tu ne décides, lis le contrat attentivement.', it: 'Prima che tu decida, leggi il contratto con attenzione.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['decide', 'decidiu', 'decidiria'] },
  { id: 'pt3s039', de: 'O intercâmbio me ajudou a entender outros costumes.', en: 'The exchange programme helped me understand other customs.', gloss: { de: 'Der Austausch hat mir geholfen, andere Sitten zu verstehen.', es: 'El intercambio me ayudó a entender otras costumbres.', fr: 'L’échange m’a aidé à comprendre d’autres coutumes.', it: 'Lo scambio mi ha aiutato a capire altre usanze.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['curso', 'turismo', 'destino'] },
  { id: 'pt3s040', de: 'Talvez o custo do projeto seja maior do que imaginamos.', en: 'Maybe the cost of the project is higher than we imagine.', gloss: { de: 'Vielleicht sind die Kosten des Projekts höher, als wir denken.', es: 'Quizás el coste del proyecto sea mayor de lo que imaginamos.', fr: 'Le coût du projet est peut-être plus élevé qu’on ne l’imagine.', it: 'Forse il costo del progetto è più alto di quanto immaginiamo.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['lucro', 'prazo', 'orçamento'] },
  { id: 'pt3s041', de: 'Ela se adaptou rapidamente à paisagem e ao clima do sul.', en: 'She quickly adapted to the landscape and the climate of the south.', gloss: { de: 'Sie hat sich schnell an die Landschaft und das Klima des Südens gewöhnt.', es: 'Se adaptó rápidamente al paisaje y al clima del sur.', fr: 'Elle s’est vite adaptée au paysage et au climat du sud.', it: 'Si è adattata in fretta al paesaggio e al clima del sud.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['queixou', 'esqueceu', 'aproximou'] },
  { id: 'pt3s042', de: 'É difícil que uma lei sozinha mude os costumes de um país.', en: 'It is unlikely that a law alone changes a country’s customs.', gloss: { de: 'Ein Gesetz allein ändert kaum die Sitten eines Landes.', es: 'Es difícil que una ley sola cambie las costumbres de un país.', fr: 'Il est difficile qu’une loi seule change les coutumes d’un pays.', it: 'È difficile che una legge da sola cambi le usanze di un paese.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['muda', 'mudou', 'mudaria'] },
  { id: 'pt3s043', de: 'Os pesquisadores destacaram a importância da prevenção.', en: 'The researchers highlighted the importance of prevention.', gloss: { de: 'Die Forscher betonten die Bedeutung der Vorbeugung.', es: 'Los investigadores destacaron la importancia de la prevención.', fr: 'Les chercheurs ont souligné l’importance de la prévention.', it: 'I ricercatori hanno evidenziato l’importanza della prevenzione.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['negaram', 'duvidaram', 'esqueceram'] },
  { id: 'pt3s044', de: 'Enquanto uns defendem o algoritmo, outros questionam seus efeitos.', en: 'While some defend the algorithm, others question its effects.', gloss: { de: 'Während die einen den Algorithmus verteidigen, hinterfragen andere seine Wirkung.', es: 'Mientras unos defienden el algoritmo, otros cuestionan sus efectos.', fr: 'Alors que certains défendent l’algorithme, d’autres en questionnent les effets.', it: 'Mentre alcuni difendono l’algoritmo, altri ne mettono in discussione gli effetti.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['duvidam', 'discordam', 'reclamam'] },
  { id: 'pt3s045', de: 'Supondo que a economia melhore, o desemprego deve cair.', en: 'Assuming the economy improves, unemployment should fall.', gloss: { de: 'Angenommen, die Wirtschaft erholt sich, dürfte die Arbeitslosigkeit sinken.', es: 'Suponiendo que la economía mejore, el desempleo debería bajar.', fr: 'À supposer que l’économie s’améliore, le chômage devrait baisser.', it: 'Supponendo che l’economia migliori, la disoccupazione dovrebbe calare.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['melhora', 'melhorou', 'melhoraria'] },
  { id: 'pt3s046', de: 'Poupar sem um orçamento claro é praticamente impossível.', en: 'Saving without a clear budget is practically impossible.', gloss: { de: 'Ohne klares Budget zu sparen ist praktisch unmöglich.', es: 'Ahorrar sin un presupuesto claro es prácticamente imposible.', fr: 'Épargner sans budget clair est pratiquement impossible.', it: 'Risparmiare senza un bilancio chiaro è praticamente impossibile.' }, level: 'B1', clozeIndex: 0, clozeDistractors: ['Gastar', 'Investir', 'Comparar'] },
  { id: 'pt3s047', de: 'O idioma deixou de ser uma barreira para ela.', en: 'The language stopped being a barrier for her.', gloss: { de: 'Die Sprache war für sie kein Hindernis mehr.', es: 'El idioma dejó de ser una barrera para ella.', fr: 'La langue a cessé d’être une barrière pour elle.', it: 'La lingua ha smesso di essere una barriera per lei.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['costume', 'destino', 'turismo'] },
  { id: 'pt3s048', de: 'É lamentável que tantos pacientes esperem meses por uma consulta.', en: 'It is regrettable that so many patients wait months for an appointment.', gloss: { de: 'Es ist bedauerlich, dass so viele Patienten Monate auf einen Termin warten.', es: 'Es lamentable que tantos pacientes esperen meses por una cita.', fr: 'Il est regrettable que tant de patients attendent des mois un rendez-vous.', it: 'È deplorevole che tanti pazienti aspettino mesi per una visita.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['esperam', 'esperaram', 'esperariam'] },
  { id: 'pt3s049', de: 'A formação técnica costuma abrir mais portas do que se imagina.', en: 'Technical training usually opens more doors than people think.', gloss: { de: 'Eine technische Ausbildung öffnet meist mehr Türen als gedacht.', es: 'La formación técnica suele abrir más puertas de lo que se imagina.', fr: 'La formation technique ouvre souvent plus de portes qu’on ne le croit.', it: 'La formazione tecnica apre di solito più porte di quanto si immagini.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['pesquisa', 'matrícula', 'habilidade'] },
  { id: 'pt3s050', de: 'Sem que ninguém percebesse, o custo do projeto dobrou.', en: 'Without anyone noticing, the cost of the project doubled.', gloss: { de: 'Ohne dass es jemand merkte, verdoppelten sich die Projektkosten.', es: 'Sin que nadie se diera cuenta, el coste del proyecto se duplicó.', fr: 'Sans que personne ne s’en rende compte, le coût du projet a doublé.', it: 'Senza che nessuno se ne accorgesse, il costo del progetto è raddoppiato.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['percebe', 'percebeu', 'perceberia'] },
  { id: 'pt3s051', de: 'Ele resumiu a pesquisa em três páginas muito claras.', en: 'He summarised the research in three very clear pages.', gloss: { de: 'Er hat die Forschung auf drei sehr klaren Seiten zusammengefasst.', es: 'Resumió la investigación en tres páginas muy claras.', fr: 'Il a résumé la recherche en trois pages très claires.', it: 'Ha riassunto la ricerca in tre pagine molto chiare.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['destacou', 'questionou', 'defendeu'] },
  { id: 'pt3s052', de: 'Cabe ao usuário proteger os próprios dados.', en: 'It is up to the user to protect their own data.', gloss: { de: 'Es liegt am Nutzer, die eigenen Daten zu schützen.', es: 'Le corresponde al usuario proteger sus propios datos.', fr: 'C’est à l’utilisateur de protéger ses propres données.', it: 'Spetta all’utente proteggere i propri dati.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['governo', 'jornal', 'diploma'] },
  { id: 'pt3s053', de: 'Prevenir uma doença sai muito mais barato do que tratá-la.', en: 'Preventing an illness is far cheaper than treating it.', gloss: { de: 'Eine Krankheit vorzubeugen ist viel billiger, als sie zu behandeln.', es: 'Prevenir una enfermedad sale mucho más barato que tratarla.', fr: 'Prévenir une maladie coûte bien moins cher que la soigner.', it: 'Prevenire una malattia costa molto meno che curarla.' }, level: 'B1', clozeIndex: 2, clozeDistractors: ['dívida', 'fronteira', 'habilidade'] },
  { id: 'pt3s054', de: 'Assim que eu terminar o curso, vou procurar outro emprego.', en: 'As soon as I finish the course, I will look for another job.', gloss: { de: 'Sobald ich den Kurs beende, suche ich eine andere Stelle.', es: 'En cuanto termine el curso, voy a buscar otro empleo.', fr: 'Dès que j’aurai fini le cours, je chercherai un autre emploi.', it: 'Appena finirò il corso, cercherò un altro lavoro.' }, level: 'B1', clozeIndex: 3, clozeDistractors: ['termino', 'terminei', 'terminaria'] },
  { id: 'pt3s055', de: 'O estresse no trabalho afeta o bem-estar de toda a equipe.', en: 'Stress at work affects the wellbeing of the whole team.', gloss: { de: 'Stress bei der Arbeit beeinträchtigt das Wohlbefinden des ganzen Teams.', es: 'El estrés en el trabajo afecta el bienestar de todo el equipo.', fr: 'Le stress au travail affecte le bien-être de toute l’équipe.', it: 'Lo stress al lavoro incide sul benessere di tutta la squadra.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['lucro', 'orçamento', 'turismo'] },
  { id: 'pt3s056', de: 'Ainda que a fronteira esteja aberta, poucos decidem atravessá-la.', en: 'Even though the border is open, few decide to cross it.', gloss: { de: 'Auch wenn die Grenze offen ist, entscheiden sich wenige, sie zu überqueren.', es: 'Aunque la frontera esté abierta, pocos deciden cruzarla.', fr: 'Même si la frontière est ouverte, peu décident de la traverser.', it: 'Anche se la frontiera è aperta, in pochi decidono di attraversarla.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['está', 'estava', 'estaria'] },
  { id: 'pt3s057', de: 'Comparar salários entre países exige cuidado com o custo de vida.', en: 'Comparing salaries across countries requires care with the cost of living.', gloss: { de: 'Gehälter zwischen Ländern zu vergleichen erfordert Vorsicht bei den Lebenshaltungskosten.', es: 'Comparar salarios entre países exige cuidado con el coste de vida.', fr: 'Comparer les salaires entre pays exige de la prudence avec le coût de la vie.', it: 'Confrontare gli stipendi tra paesi richiede attenzione al costo della vita.' }, level: 'B1', clozeIndex: 4, clozeDistractors: ['evita', 'permite', 'impede'] },
  { id: 'pt3s058', de: 'A tradição da família se perdeu com o tempo.', en: 'The family tradition was lost over time.', gloss: { de: 'Die Familientradition ging mit der Zeit verloren.', es: 'La tradición de la familia se perdió con el tiempo.', fr: 'La tradition familiale s’est perdue avec le temps.', it: 'La tradizione di famiglia si è persa col tempo.' }, level: 'B1', clozeIndex: 1, clozeDistractors: ['paisagem', 'fronteira', 'habilidade'] },
  { id: 'pt3s059', de: 'É provável que o lucro caia caso os custos continuem subindo.', en: 'Profit is likely to fall if costs keep rising.', gloss: { de: 'Der Gewinn dürfte sinken, falls die Kosten weiter steigen.', es: 'Es probable que el beneficio caiga si los costes siguen subiendo.', fr: 'Il est probable que le bénéfice baisse si les coûts continuent d’augmenter.', it: 'È probabile che il profitto cali se i costi continuano a salire.' }, level: 'B1', clozeIndex: 5, clozeDistractors: ['cai', 'caiu', 'cairia'] },
  { id: 'pt3s060', de: 'Aprofundar o debate exige que todos ouçam antes de responder.', en: 'Deepening the debate requires everyone to listen before answering.', gloss: { de: 'Die Debatte zu vertiefen verlangt, dass alle zuhören, bevor sie antworten.', es: 'Profundizar el debate exige que todos escuchen antes de responder.', fr: 'Approfondir le débat exige que chacun écoute avant de répondre.', it: 'Approfondire il dibattito richiede che tutti ascoltino prima di rispondere.' }, level: 'B1', clozeIndex: 6, clozeDistractors: ['ouvem', 'ouviram', 'ouviriam'] },
];
